
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Controls;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.Geometry;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ESRI.ArcGIS.DataSourcesFile;
using Yutai.Pipeline.Analysis.Classes;
using Yutai.Pipeline.Analysis.Helpers;
using Yutai.Plugins.Interfaces;

namespace Yutai.Pipeline.Analysis.Forms
{
	    partial class GForm0
    {
		protected override void Dispose(bool disposing)
		{
			if ((!disposing ? false : this.icontainer_0 != null))
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

	
		private void InitializeComponent()
		{
			this.icontainer_0 = new System.ComponentModel.Container();
			DataGridViewCellStyle dataGridViewCellStyle = new DataGridViewCellStyle();
			DataGridViewCellStyle control = new DataGridViewCellStyle();
			DataGridViewCellStyle window = new DataGridViewCellStyle();
			DataGridViewCellStyle font = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
			DataGridViewCellStyle controlText = new DataGridViewCellStyle();
			DataGridViewCellStyle windowText = new DataGridViewCellStyle();
			DataGridViewCellStyle white = new DataGridViewCellStyle();
			DataGridViewCellStyle highlight = new DataGridViewCellStyle();
			DataGridViewCellStyle highlightText = new DataGridViewCellStyle();
			DataGridViewCellStyle control1 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle5 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle6 = new DataGridViewCellStyle();
			this.groupBox1 = new GroupBox();
			this.tbBufferRadius = new TextBox();
			this.label1 = new Label();
			this.btClose = new Button();
			this.btAnalyse = new Button();
			this.btnClear = new Button();
			this.textBoxLoadCADName = new TextBox();
			this.button_0 = new Button();
			this.groupBox2 = new GroupBox();
			this.QfyEqiOwEk = new TabControl();
			this.tabPageApprove = new TabPage();
			this.dataGridViewSelectItem = new DataGridView();
			this.ColumnIndex = new DataGridViewTextBoxColumn();
			this.FeatueName = new DataGridViewTextBoxColumn();
			this.krepayTghI = new DataGridViewTextBoxColumn();
			this.editHeightStartPoint = new DataGridViewTextBoxColumn();
			this.editHeightEndPoint = new DataGridViewTextBoxColumn();
			this.comboLineType = new DataGridViewComboBoxColumn();
			this.tabPageHor = new TabPage();
			this.dataGridViewHor = new DataGridView();
			this.dataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn3 = new DataGridViewTextBoxColumn();
			this.hrzDist = new DataGridViewTextBoxColumn();
			this.UwxEkbyfru = new DataGridViewTextBoxColumn();
			this.ejsEghpDqe = new TabPage();
			this.dataGridViewVer = new DataGridView();
			this.序号 = new DataGridViewTextBoxColumn();
			this.PipeDataset = new DataGridViewTextBoxColumn();
			this.FID = new DataGridViewTextBoxColumn();
			this.verDist = new DataGridViewTextBoxColumn();
			this.stanDist = new DataGridViewTextBoxColumn();
			this.tabPageRollCenter = new TabPage();
			this.dataGridViewCenterLine = new DataGridView();
			this.dataGridViewTextBoxColumn5 = new DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn6 = new DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn7 = new DataGridViewTextBoxColumn();
			this.dataGridViewTextBoxColumn8 = new DataGridViewTextBoxColumn();
			this.timer_0 = new Timer(this.icontainer_0);
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.QfyEqiOwEk.SuspendLayout();
			this.tabPageApprove.SuspendLayout();
			((ISupportInitialize)this.dataGridViewSelectItem).BeginInit();
			this.tabPageHor.SuspendLayout();
			((ISupportInitialize)this.dataGridViewHor).BeginInit();
			this.ejsEghpDqe.SuspendLayout();
			((ISupportInitialize)this.dataGridViewVer).BeginInit();
			this.tabPageRollCenter.SuspendLayout();
			((ISupportInitialize)this.dataGridViewCenterLine).BeginInit();
			base.SuspendLayout();
			this.groupBox1.Controls.Add(this.tbBufferRadius);
			this.groupBox1.Controls.Add(this.label1);
			this.groupBox1.Controls.Add(this.btClose);
			this.groupBox1.Controls.Add(this.btAnalyse);
			this.groupBox1.Controls.Add(this.btnClear);
			this.groupBox1.Controls.Add(this.textBoxLoadCADName);
			this.groupBox1.Controls.Add(this.button_0);
			this.groupBox1.Dock = DockStyle.Top;
			this.groupBox1.Location = new System.Drawing.Point(0, 0);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(553, 87);
			this.groupBox1.TabIndex = 2;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "报批数据";
			this.tbBufferRadius.Location = new System.Drawing.Point(105, 51);
			this.tbBufferRadius.Name = "tbBufferRadius";
			this.tbBufferRadius.Size = new System.Drawing.Size(99, 21);
			this.tbBufferRadius.TabIndex = 29;
			this.tbBufferRadius.Text = "20";
			this.tbBufferRadius.WordWrap = false;
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(10, 56);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(89, 12);
			this.label1.TabIndex = 28;
			this.label1.Text = "分析半径(米)：";
			this.btClose.Location = new System.Drawing.Point(469, 49);
			this.btClose.Name = "btClose";
			this.btClose.Size = new System.Drawing.Size(75, 23);
			this.btClose.TabIndex = 27;
			this.btClose.Text = "关闭(&C)";
			this.btClose.UseVisualStyleBackColor = true;
			this.btClose.Click += new EventHandler(this.btClose_Click);
			this.btAnalyse.Enabled = false;
			this.btAnalyse.Location = new System.Drawing.Point(210, 49);
			this.btAnalyse.Name = "btAnalyse";
			this.btAnalyse.Size = new System.Drawing.Size(75, 23);
			this.btAnalyse.TabIndex = 26;
			this.btAnalyse.Text = "分析(&A)";
			this.btAnalyse.UseVisualStyleBackColor = true;
			this.btAnalyse.Click += new EventHandler(this.btAnalyse_Click);
			this.btnClear.Location = new System.Drawing.Point(388, 49);
			this.btnClear.Name = "btnClear";
			this.btnClear.Size = new System.Drawing.Size(75, 23);
			this.btnClear.TabIndex = 2;
			this.btnClear.Text = "清除";
			this.btnClear.UseVisualStyleBackColor = true;
			this.btnClear.Click += new EventHandler(this.btnClear_Click);
			this.textBoxLoadCADName.AcceptsReturn = true;
			this.textBoxLoadCADName.Location = new System.Drawing.Point(12, 22);
			this.textBoxLoadCADName.Name = "textBoxLoadCADName";
			this.textBoxLoadCADName.ReadOnly = true;
			this.textBoxLoadCADName.Size = new System.Drawing.Size(532, 21);
			this.textBoxLoadCADName.TabIndex = 1;
			this.button_0.Location = new System.Drawing.Point(291, 49);
			this.button_0.Name = "btnLoadCAD";
			this.button_0.Size = new System.Drawing.Size(91, 23);
			this.button_0.TabIndex = 0;
			this.button_0.Text = "导入报批数据";
			this.button_0.UseVisualStyleBackColor = true;
			this.button_0.Click += new EventHandler(this.qsTayfWbAn);
			this.groupBox2.Controls.Add(this.QfyEqiOwEk);
			this.groupBox2.Dock = DockStyle.Bottom;
			this.groupBox2.Location = new System.Drawing.Point(0, 93);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new System.Drawing.Size(553, 302);
			this.groupBox2.TabIndex = 4;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "分析结果";
			this.QfyEqiOwEk.Controls.Add(this.tabPageApprove);
			this.QfyEqiOwEk.Controls.Add(this.tabPageHor);
			this.QfyEqiOwEk.Controls.Add(this.ejsEghpDqe);
			this.QfyEqiOwEk.Controls.Add(this.tabPageRollCenter);
			this.QfyEqiOwEk.Dock = DockStyle.Fill;
			this.QfyEqiOwEk.Location = new System.Drawing.Point(3, 17);
			this.QfyEqiOwEk.Name = "tabControl1";
			this.QfyEqiOwEk.SelectedIndex = 0;
			this.QfyEqiOwEk.Size = new System.Drawing.Size(547, 282);
			this.QfyEqiOwEk.TabIndex = 0;
			this.tabPageApprove.Controls.Add(this.dataGridViewSelectItem);
			this.tabPageApprove.Location = new System.Drawing.Point(4, 22);
			this.tabPageApprove.Name = "tabPageApprove";
			this.tabPageApprove.Size = new System.Drawing.Size(539, 256);
			this.tabPageApprove.TabIndex = 3;
			this.tabPageApprove.Text = "导入管线";
			this.tabPageApprove.UseVisualStyleBackColor = true;
			this.dataGridViewSelectItem.AllowUserToAddRows = false;
			this.dataGridViewSelectItem.AllowUserToDeleteRows = false;
			this.dataGridViewSelectItem.AllowUserToResizeRows = false;
			this.dataGridViewSelectItem.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			dataGridViewCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle.BackColor = SystemColors.Control;
			dataGridViewCellStyle.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			dataGridViewCellStyle.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = DataGridViewTriState.True;
			this.dataGridViewSelectItem.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.dataGridViewSelectItem.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.dataGridViewSelectItem.Columns.AddRange(new DataGridViewColumn[] { this.ColumnIndex, this.FeatueName, this.krepayTghI, this.editHeightStartPoint, this.editHeightEndPoint, this.comboLineType });
			
			this.dataGridViewSelectItem.Dock = DockStyle.Fill;
			this.dataGridViewSelectItem.Location = new System.Drawing.Point(0, 0);
			this.dataGridViewSelectItem.MultiSelect = false;
			this.dataGridViewSelectItem.Name = "dataGridViewSelectItem";
			this.dataGridViewSelectItem.RowHeadersVisible = false;
			this.dataGridViewSelectItem.RowTemplate.Height = 23;
			this.dataGridViewSelectItem.SelectionMode = DataGridViewSelectionMode.CellSelect;
			this.dataGridViewSelectItem.Size = new System.Drawing.Size(539, 256);
			this.dataGridViewSelectItem.TabIndex = 7;
			this.dataGridViewSelectItem.CellClick += new DataGridViewCellEventHandler(this.dataGridViewSelectItem_CellClick);
			this.dataGridViewSelectItem.CellEndEdit += new DataGridViewCellEventHandler(this.dataGridViewSelectItem_CellEndEdit);
			this.ColumnIndex.HeaderText = "序号";
			this.ColumnIndex.Name = "ColumnIndex";
			this.FeatueName.HeaderText = "元素类";
			this.FeatueName.Name = "FeatueName";
			this.krepayTghI.HeaderText = "编号";
			this.krepayTghI.Name = "OID";
			this.editHeightStartPoint.AutoSizeMode = DataGridViewAutoSizeColumnMode.ColumnHeader;
			this.editHeightStartPoint.HeaderText = "起点高程(可编辑)";
			this.editHeightStartPoint.Name = "editHeightStartPoint";
			this.editHeightStartPoint.Width = 126;
			this.editHeightEndPoint.AutoSizeMode = DataGridViewAutoSizeColumnMode.ColumnHeader;
			this.editHeightEndPoint.HeaderText = "终点高程(可编辑)";
			this.editHeightEndPoint.Name = "editHeightEndPoint";
			this.editHeightEndPoint.Width = 126;
			this.comboLineType.HeaderText = "管线类型";
			this.comboLineType.Name = "comboLineType";
			this.comboLineType.Resizable = DataGridViewTriState.True;
			this.comboLineType.SortMode = DataGridViewColumnSortMode.Automatic;
			this.tabPageHor.Controls.Add(this.dataGridViewHor);
			this.tabPageHor.Location = new System.Drawing.Point(4, 22);
			this.tabPageHor.Name = "tabPageHor";
			this.tabPageHor.Padding = new System.Windows.Forms.Padding(3);
			this.tabPageHor.Size = new System.Drawing.Size(539, 256);
			this.tabPageHor.TabIndex = 0;
			this.tabPageHor.Text = "水平净距";
			this.tabPageHor.UseVisualStyleBackColor = true;
			this.dataGridViewHor.AllowUserToAddRows = false;
			this.dataGridViewHor.AllowUserToDeleteRows = false;
			this.dataGridViewHor.AllowUserToResizeRows = false;
			this.dataGridViewHor.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			control.Alignment = DataGridViewContentAlignment.MiddleCenter;
			control.BackColor = SystemColors.Control;
			control.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			control.ForeColor = SystemColors.WindowText;
			control.SelectionBackColor = SystemColors.Highlight;
			control.SelectionForeColor = SystemColors.HighlightText;
			control.WrapMode = DataGridViewTriState.True;
			this.dataGridViewHor.ColumnHeadersDefaultCellStyle = control;
			this.dataGridViewHor.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dataGridViewHor.Columns.AddRange(new DataGridViewColumn[] { this.dataGridViewTextBoxColumn1, this.dataGridViewTextBoxColumn2, this.dataGridViewTextBoxColumn3, this.hrzDist, this.UwxEkbyfru });
			
			window.Alignment = DataGridViewContentAlignment.MiddleCenter;
			window.BackColor = SystemColors.Window;
			window.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			window.ForeColor = SystemColors.ControlText;
			window.SelectionBackColor = SystemColors.Highlight;
			window.SelectionForeColor = SystemColors.HighlightText;
			window.WrapMode = DataGridViewTriState.False;
			this.dataGridViewHor.DefaultCellStyle = window;
			this.dataGridViewHor.Dock = DockStyle.Fill;
			this.dataGridViewHor.Location = new System.Drawing.Point(3, 3);
			this.dataGridViewHor.MultiSelect = false;
			this.dataGridViewHor.Name = "dataGridViewHor";
			this.dataGridViewHor.ReadOnly = true;
			font.Alignment = DataGridViewContentAlignment.MiddleCenter;
			font.BackColor = SystemColors.Control;
			font.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			font.ForeColor = SystemColors.WindowText;
			font.SelectionBackColor = SystemColors.Highlight;
			font.SelectionForeColor = SystemColors.HighlightText;
			font.WrapMode = DataGridViewTriState.True;
			this.dataGridViewHor.RowHeadersDefaultCellStyle = font;
			this.dataGridViewHor.RowHeadersVisible = false;
			this.dataGridViewHor.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dataGridViewHor.RowTemplate.Height = 20;
			this.dataGridViewHor.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			this.dataGridViewHor.Size = new System.Drawing.Size(533, 250);
			this.dataGridViewHor.TabIndex = 27;
			this.dataGridViewHor.CellClick += new DataGridViewCellEventHandler(this.dataGridViewHor_CellClick);
			this.dataGridViewTextBoxColumn1.HeaderText = "序号";
			this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
			this.dataGridViewTextBoxColumn1.ReadOnly = true;
			dataGridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridViewTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle1;
			this.dataGridViewTextBoxColumn2.HeaderText = "管线性质";
			this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
			this.dataGridViewTextBoxColumn2.ReadOnly = true;
			dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridViewTextBoxColumn3.DefaultCellStyle = dataGridViewCellStyle2;
			this.dataGridViewTextBoxColumn3.HeaderText = "编号";
			this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
			this.dataGridViewTextBoxColumn3.ReadOnly = true;
			dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.hrzDist.DefaultCellStyle = dataGridViewCellStyle3;
			this.hrzDist.HeaderText = "水平净距(米)";
			this.hrzDist.Name = "hrzDist";
			this.hrzDist.ReadOnly = true;
			controlText.Alignment = DataGridViewContentAlignment.MiddleCenter;
			controlText.BackColor = SystemColors.Window;
			controlText.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			controlText.ForeColor = SystemColors.ControlText;
			controlText.SelectionBackColor = SystemColors.Highlight;
			controlText.SelectionForeColor = SystemColors.HighlightText;
			controlText.WrapMode = DataGridViewTriState.False;
			this.UwxEkbyfru.DefaultCellStyle = controlText;
			this.UwxEkbyfru.HeaderText = "标准";
			this.UwxEkbyfru.Name = "dataGridViewTextBoxColumn4";
			this.UwxEkbyfru.ReadOnly = true;
			this.ejsEghpDqe.Controls.Add(this.dataGridViewVer);
			this.ejsEghpDqe.Location = new System.Drawing.Point(4, 22);
			this.ejsEghpDqe.Name = "tabPageVer";
			this.ejsEghpDqe.Padding = new System.Windows.Forms.Padding(3);
			this.ejsEghpDqe.Size = new System.Drawing.Size(539, 256);
			this.ejsEghpDqe.TabIndex = 1;
			this.ejsEghpDqe.Text = "垂直净距";
			this.ejsEghpDqe.UseVisualStyleBackColor = true;
			this.dataGridViewVer.AllowUserToAddRows = false;
			this.dataGridViewVer.AllowUserToDeleteRows = false;
			this.dataGridViewVer.AllowUserToResizeRows = false;
			this.dataGridViewVer.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			windowText.Alignment = DataGridViewContentAlignment.MiddleCenter;
			windowText.BackColor = SystemColors.Control;
			windowText.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			windowText.ForeColor = SystemColors.WindowText;
			windowText.SelectionBackColor = SystemColors.Highlight;
			windowText.SelectionForeColor = SystemColors.HighlightText;
			windowText.WrapMode = DataGridViewTriState.True;
			this.dataGridViewVer.ColumnHeadersDefaultCellStyle = windowText;
			this.dataGridViewVer.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dataGridViewVer.Columns.AddRange(new DataGridViewColumn[] { this.序号, this.PipeDataset, this.FID, this.verDist, this.stanDist });
			
			this.dataGridViewVer.Dock = DockStyle.Fill;
			this.dataGridViewVer.Location = new System.Drawing.Point(3, 3);
			this.dataGridViewVer.MultiSelect = false;
			this.dataGridViewVer.Name = "dataGridViewVer";
			this.dataGridViewVer.ReadOnly = true;
			this.dataGridViewVer.RowHeadersVisible = false;
			this.dataGridViewVer.RowTemplate.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridViewVer.RowTemplate.Height = 20;
			this.dataGridViewVer.Size = new System.Drawing.Size(533, 250);
			this.dataGridViewVer.TabIndex = 6;
			this.dataGridViewVer.CellClick += new DataGridViewCellEventHandler(this.dataGridViewVer_CellClick);
			this.序号.HeaderText = "序号";
			this.序号.Name = "序号";
			this.序号.ReadOnly = true;
			this.PipeDataset.HeaderText = "管线性质";
			this.PipeDataset.Name = "PipeDataset";
			this.PipeDataset.ReadOnly = true;
			this.FID.HeaderText = "编号";
			this.FID.Name = "FID";
			this.FID.ReadOnly = true;
			this.verDist.HeaderText = "垂直净距(米)";
			this.verDist.Name = "verDist";
			this.verDist.ReadOnly = true;
			white.Alignment = DataGridViewContentAlignment.MiddleCenter;
			white.BackColor = Color.White;
			white.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			white.ForeColor = SystemColors.WindowText;
			white.SelectionBackColor = SystemColors.Highlight;
			white.SelectionForeColor = SystemColors.HighlightText;
			white.WrapMode = DataGridViewTriState.True;
			this.stanDist.DefaultCellStyle = white;
			this.stanDist.HeaderText = "标准";
			this.stanDist.Name = "stanDist";
			this.stanDist.ReadOnly = true;
			this.tabPageRollCenter.Controls.Add(this.dataGridViewCenterLine);
			this.tabPageRollCenter.Location = new System.Drawing.Point(4, 22);
			this.tabPageRollCenter.Name = "tabPageRollCenter";
			this.tabPageRollCenter.Size = new System.Drawing.Size(539, 256);
			this.tabPageRollCenter.TabIndex = 2;
			this.tabPageRollCenter.Text = "道路中心线";
			this.tabPageRollCenter.UseVisualStyleBackColor = true;
			this.dataGridViewCenterLine.AllowUserToAddRows = false;
			this.dataGridViewCenterLine.AllowUserToDeleteRows = false;
			this.dataGridViewCenterLine.AllowUserToResizeRows = false;
			this.dataGridViewCenterLine.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			highlight.Alignment = DataGridViewContentAlignment.MiddleCenter;
			highlight.BackColor = SystemColors.Control;
			highlight.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			highlight.ForeColor = SystemColors.WindowText;
			highlight.SelectionBackColor = SystemColors.Highlight;
			highlight.SelectionForeColor = SystemColors.HighlightText;
			highlight.WrapMode = DataGridViewTriState.True;
			this.dataGridViewCenterLine.ColumnHeadersDefaultCellStyle = highlight;
			this.dataGridViewCenterLine.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dataGridViewCenterLine.Columns.AddRange(new DataGridViewColumn[] { this.dataGridViewTextBoxColumn5, this.dataGridViewTextBoxColumn6, this.dataGridViewTextBoxColumn7, this.dataGridViewTextBoxColumn8 });
			
			highlightText.Alignment = DataGridViewContentAlignment.MiddleCenter;
			highlightText.BackColor = SystemColors.Window;
			highlightText.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			highlightText.ForeColor = SystemColors.ControlText;
			highlightText.SelectionBackColor = SystemColors.Highlight;
			highlightText.SelectionForeColor = SystemColors.HighlightText;
			highlightText.WrapMode = DataGridViewTriState.False;
			this.dataGridViewCenterLine.DefaultCellStyle = highlightText;
			this.dataGridViewCenterLine.Dock = DockStyle.Fill;
			this.dataGridViewCenterLine.Location = new System.Drawing.Point(0, 0);
			this.dataGridViewCenterLine.MultiSelect = false;
			this.dataGridViewCenterLine.Name = "dataGridViewCenterLine";
			this.dataGridViewCenterLine.ReadOnly = true;
			control1.Alignment = DataGridViewContentAlignment.MiddleCenter;
			control1.BackColor = SystemColors.Control;
			control1.Font = new System.Drawing.Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
			control1.ForeColor = SystemColors.WindowText;
			control1.SelectionBackColor = SystemColors.Highlight;
			control1.SelectionForeColor = SystemColors.HighlightText;
			control1.WrapMode = DataGridViewTriState.True;
			this.dataGridViewCenterLine.RowHeadersDefaultCellStyle = control1;
			this.dataGridViewCenterLine.RowHeadersVisible = false;
			this.dataGridViewCenterLine.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dataGridViewCenterLine.RowTemplate.Height = 20;
			this.dataGridViewCenterLine.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			this.dataGridViewCenterLine.Size = new System.Drawing.Size(539, 256);
			this.dataGridViewCenterLine.TabIndex = 28;
			this.dataGridViewCenterLine.CellClick += new DataGridViewCellEventHandler(this.dataGridViewCenterLine_CellClick);
			this.dataGridViewTextBoxColumn5.HeaderText = "序号";
			this.dataGridViewTextBoxColumn5.Name = "dataGridViewTextBoxColumn5";
			this.dataGridViewTextBoxColumn5.ReadOnly = true;
			dataGridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridViewTextBoxColumn6.DefaultCellStyle = dataGridViewCellStyle4;
			this.dataGridViewTextBoxColumn6.HeaderText = "道路名称";
			this.dataGridViewTextBoxColumn6.Name = "dataGridViewTextBoxColumn6";
			this.dataGridViewTextBoxColumn6.ReadOnly = true;
			dataGridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridViewTextBoxColumn7.DefaultCellStyle = dataGridViewCellStyle5;
			this.dataGridViewTextBoxColumn7.HeaderText = "编号";
			this.dataGridViewTextBoxColumn7.Name = "dataGridViewTextBoxColumn7";
			this.dataGridViewTextBoxColumn7.ReadOnly = true;
			dataGridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleCenter;
			this.dataGridViewTextBoxColumn8.DefaultCellStyle = dataGridViewCellStyle6;
			this.dataGridViewTextBoxColumn8.HeaderText = "水平净距(米)";
			this.dataGridViewTextBoxColumn8.Name = "dataGridViewTextBoxColumn8";
			this.dataGridViewTextBoxColumn8.ReadOnly = true;
			this.timer_0.Interval = 500;
			this.timer_0.Tick += new EventHandler(this.timer_0_Tick);
			base.AutoScaleDimensions = new SizeF(6f, 12f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new System.Drawing.Size(553, 395);
			base.Controls.Add(this.groupBox2);
			base.Controls.Add(this.groupBox1);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "FormApproveFromCAD";
			base.ShowIcon = false;
			base.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
			this.Text = "审批辅助分析";
			base.FormClosing += new FormClosingEventHandler(this.GForm0_FormClosing);
			base.FormClosed += new FormClosedEventHandler(this.GForm0_FormClosed);
			base.Load += new EventHandler(this.GForm0_Load);
			base.HelpRequested += new HelpEventHandler(this.GForm0_HelpRequested);
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.groupBox2.ResumeLayout(false);
			this.QfyEqiOwEk.ResumeLayout(false);
			this.tabPageApprove.ResumeLayout(false);
			((ISupportInitialize)this.dataGridViewSelectItem).EndInit();
			this.tabPageHor.ResumeLayout(false);
			((ISupportInitialize)this.dataGridViewHor).EndInit();
			this.ejsEghpDqe.ResumeLayout(false);
			((ISupportInitialize)this.dataGridViewVer).EndInit();
			this.tabPageRollCenter.ResumeLayout(false);
			((ISupportInitialize)this.dataGridViewCenterLine).EndInit();
			base.ResumeLayout(false);
		}

	
		private TabControl QfyEqiOwEk;
		private IPolyline ipolyline_0;
		private IPolyline ipolyline_1;
		private IFeatureClass ifeatureClass_0;
		private IFeature ifeature_0;
		private double double_0;
		private double double_1;
		private int int_0;
		private IFeatureClass ifeatureClass_1;
		private int int_1;
		private int int_2;
		private GroupBox groupBox1;
		private Button btnClear;
		private TextBox textBoxLoadCADName;
		private Button button_0;
		private TextBox tbBufferRadius;
		private Label label1;
		private Button btClose;
		private Button btAnalyse;
		private GroupBox groupBox2;
		private TabPage tabPageHor;
		private TabPage ejsEghpDqe;
		private TabPage tabPageRollCenter;
		private TabPage tabPageApprove;
		private DataGridView dataGridViewSelectItem;
		private Timer timer_0;
		private DataGridView dataGridViewVer;
		private DataGridViewTextBoxColumn 序号;
		private DataGridViewTextBoxColumn PipeDataset;
		private DataGridViewTextBoxColumn FID;
		private DataGridViewTextBoxColumn verDist;
		private DataGridViewTextBoxColumn stanDist;
		private DataGridView dataGridViewHor;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn3;
		private DataGridViewTextBoxColumn hrzDist;
		private DataGridViewTextBoxColumn UwxEkbyfru;
		private DataGridView dataGridViewCenterLine;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn5;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn6;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn7;
		private DataGridViewTextBoxColumn dataGridViewTextBoxColumn8;
		private DataGridViewTextBoxColumn ColumnIndex;
		private DataGridViewTextBoxColumn FeatueName;
		private DataGridViewTextBoxColumn krepayTghI;
		private DataGridViewTextBoxColumn editHeightStartPoint;
		private DataGridViewTextBoxColumn editHeightEndPoint;
		private DataGridViewComboBoxColumn comboLineType;
		private DataGridViewComboBoxCell dataGridViewComboBoxCell_0;
    }
}