using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using ESRI.ArcGIS.ADF.Connection.Local;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common.SymbolLib;

namespace Yutai.ArcGIS.Controls.SymbolLib
{
    partial class GeometricEffectFillPage
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.components = new Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(GeometricEffectFillPage));
            this.label1 = new Label();
            this.panel1 = new Panel();
            this.symbolItem1 = new SymbolItem();
            this.label3 = new Label();
            this.btnChangeEffic = new Button();
            this.imageList1 = new ImageList(this.components);
            this.panel2 = new Panel();
            this.btnAddGemoetricEffic = new Button();
            this.panel3 = new Panel();
            this.comboBox2 = new ComboBox();
            this.comboBox1 = new ComboBox();
            this.label13 = new Label();
            this.label14 = new Label();
            this.txtAngleGrad = new TextBox();
            this.label10 = new Label();
            this.txtPercent = new TextBox();
            this.label11 = new Label();
            this.txtInterval = new TextBox();
            this.label12 = new Label();
            this.symbolItemColor2 = new SymbolItem();
            this.label9 = new Label();
            this.symbolItemColor1 = new SymbolItem();
            this.label2 = new Label();
            this.panel4 = new Panel();
            this.txtOffset = new TextBox();
            this.label8 = new Label();
            this.txtStep = new TextBox();
            this.label7 = new Label();
            this.txtAngle = new TextBox();
            this.label6 = new Label();
            this.txtWidth = new TextBox();
            this.label5 = new Label();
            this.HatchsymbolItem = new SymbolItem();
            this.label4 = new Label();
            this.contextMenuStrip1 = new ContextMenuStrip(this.components);
            this.solidColorToolStripMenuItem = new ToolStripMenuItem();
            this.hatchToolStripMenuItem = new ToolStripMenuItem();
            this.gradientToolStripMenuItem = new ToolStripMenuItem();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel4.SuspendLayout();
            this.contextMenuStrip1.SuspendLayout();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.ForeColor = SystemColors.ActiveCaptionText;
            this.label1.Location = new Point(3, 4);
            this.label1.Name = "label1";
            this.label1.Size = new Size(17, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "面";
            this.panel1.BackColor = SystemColors.Window;
            this.panel1.Controls.Add(this.symbolItem1);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Location = new Point(0, 33);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(212, 44);
            this.panel1.TabIndex = 1;
            this.symbolItem1.BackColor = SystemColors.ActiveCaptionText;
            this.symbolItem1.Location = new Point(66, 9);
            this.symbolItem1.Name = "symbolItem1";
            this.symbolItem1.Size = new Size(122, 30);
            this.symbolItem1.Symbol = null;
            this.symbolItem1.TabIndex = 11;
            this.symbolItem1.Click += new EventHandler(this.symbolItem1_Click);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(6, 16);
            this.label3.Name = "label3";
            this.label3.Size = new Size(35, 12);
            this.label3.TabIndex = 7;
            this.label3.Text = "颜色:";
            this.btnChangeEffic.ImageIndex = 0;
            this.btnChangeEffic.ImageList = this.imageList1;
            this.btnChangeEffic.Location = new Point(193, 0);
            this.btnChangeEffic.Name = "btnChangeEffic";
            this.btnChangeEffic.RightToLeft = RightToLeft.Yes;
            this.btnChangeEffic.Size = new Size(16, 16);
            this.btnChangeEffic.TabIndex = 2;
            this.btnChangeEffic.UseVisualStyleBackColor = true;
            this.btnChangeEffic.Click += new EventHandler(this.btnChangeEffic_Click);
            this.imageList1.ImageStream = (ImageListStreamer) resources.GetObject("imageList1.ImageStream");
            this.imageList1.TransparentColor = Color.White;
            this.imageList1.Images.SetKeyName(0, "Bitmap4.bmp");
            this.imageList1.Images.SetKeyName(1, "Bitmap5.bmp");
            this.panel2.BackColor = SystemColors.ControlDark;
            this.panel2.Controls.Add(this.label1);
            this.panel2.Controls.Add(this.btnChangeEffic);
            this.panel2.Location = new Point(3, 16);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(209, 16);
            this.panel2.TabIndex = 3;
            this.btnAddGemoetricEffic.ImageIndex = 1;
            this.btnAddGemoetricEffic.ImageList = this.imageList1;
            this.btnAddGemoetricEffic.Location = new Point(196, 0);
            this.btnAddGemoetricEffic.Name = "btnAddGemoetricEffic";
            this.btnAddGemoetricEffic.RightToLeft = RightToLeft.Yes;
            this.btnAddGemoetricEffic.Size = new Size(16, 16);
            this.btnAddGemoetricEffic.TabIndex = 4;
            this.btnAddGemoetricEffic.UseVisualStyleBackColor = true;
            this.btnAddGemoetricEffic.Click += new EventHandler(this.btnAddGemoetricEffic_Click);
            this.panel3.BackColor = SystemColors.Window;
            this.panel3.Controls.Add(this.comboBox2);
            this.panel3.Controls.Add(this.comboBox1);
            this.panel3.Controls.Add(this.label13);
            this.panel3.Controls.Add(this.label14);
            this.panel3.Controls.Add(this.txtAngleGrad);
            this.panel3.Controls.Add(this.label10);
            this.panel3.Controls.Add(this.txtPercent);
            this.panel3.Controls.Add(this.label11);
            this.panel3.Controls.Add(this.txtInterval);
            this.panel3.Controls.Add(this.label12);
            this.panel3.Controls.Add(this.symbolItemColor2);
            this.panel3.Controls.Add(this.label9);
            this.panel3.Controls.Add(this.symbolItemColor1);
            this.panel3.Controls.Add(this.label2);
            this.panel3.Location = new Point(0, 33);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(212, 200);
            this.panel3.TabIndex = 12;
            this.panel3.Visible = false;
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Items.AddRange(new object[] { "Linear", "Rectangle", "Circle", "Buffer" });
            this.comboBox2.Location = new Point(81, 86);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new Size(119, 20);
            this.comboBox2.TabIndex = 29;
            this.comboBox2.SelectedIndexChanged += new EventHandler(this.comboBox2_SelectedIndexChanged);
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] { "HSV", "CIE Lab", "LabLCH" });
            this.comboBox1.Location = new Point(81, 61);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(119, 20);
            this.comboBox1.TabIndex = 28;
            this.comboBox1.SelectedIndexChanged += new EventHandler(this.comboBox1_SelectedIndexChanged);
            this.label13.AutoSize = true;
            this.label13.Location = new Point(6, 89);
            this.label13.Name = "label13";
            this.label13.Size = new Size(35, 12);
            this.label13.TabIndex = 27;
            this.label13.Text = "样式:";
            this.label14.AutoSize = true;
            this.label14.Location = new Point(6, 64);
            this.label14.Name = "label14";
            this.label14.Size = new Size(35, 12);
            this.label14.TabIndex = 26;
            this.label14.Text = "算法:";
            this.txtAngleGrad.Location = new Point(81, 163);
            this.txtAngleGrad.Name = "txtAngleGrad";
            this.txtAngleGrad.Size = new Size(119, 21);
            this.txtAngleGrad.TabIndex = 25;
            this.txtAngleGrad.Text = "0";
            this.txtAngleGrad.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label10.AutoSize = true;
            this.label10.Location = new Point(3, 166);
            this.label10.Name = "label10";
            this.label10.Size = new Size(35, 12);
            this.label10.TabIndex = 24;
            this.label10.Text = "角度:";
            this.txtPercent.Location = new Point(81, 137);
            this.txtPercent.Name = "txtPercent";
            this.txtPercent.Size = new Size(119, 21);
            this.txtPercent.TabIndex = 23;
            this.txtPercent.Text = "0";
            this.txtPercent.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label11.AutoSize = true;
            this.label11.Location = new Point(3, 140);
            this.label11.Name = "label11";
            this.label11.Size = new Size(47, 12);
            this.label11.TabIndex = 22;
            this.label11.Text = "百分比:";
            this.txtInterval.Location = new Point(81, 111);
            this.txtInterval.Name = "txtInterval";
            this.txtInterval.Size = new Size(119, 21);
            this.txtInterval.TabIndex = 21;
            this.txtInterval.Text = "0";
            this.txtInterval.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label12.AutoSize = true;
            this.label12.Location = new Point(3, 114);
            this.label12.Name = "label12";
            this.label12.Size = new Size(35, 12);
            this.label12.TabIndex = 20;
            this.label12.Text = "间隔:";
            this.symbolItemColor2.BackColor = SystemColors.ActiveCaptionText;
            this.symbolItemColor2.Location = new Point(81, 37);
            this.symbolItemColor2.Name = "symbolItemColor2";
            this.symbolItemColor2.Size = new Size(119, 19);
            this.symbolItemColor2.Symbol = null;
            this.symbolItemColor2.TabIndex = 13;
            this.symbolItemColor2.Click += new EventHandler(this.symbolItemColor2_Click);
            this.label9.AutoSize = true;
            this.label9.Location = new Point(6, 37);
            this.label9.Name = "label9";
            this.label9.Size = new Size(41, 12);
            this.label9.TabIndex = 12;
            this.label9.Text = "颜色2:";
            this.symbolItemColor1.BackColor = SystemColors.ActiveCaptionText;
            this.symbolItemColor1.Location = new Point(79, 9);
            this.symbolItemColor1.Name = "symbolItemColor1";
            this.symbolItemColor1.Size = new Size(119, 19);
            this.symbolItemColor1.Symbol = null;
            this.symbolItemColor1.TabIndex = 11;
            this.symbolItemColor1.Click += new EventHandler(this.symbolItemColor1_Click);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(6, 16);
            this.label2.Name = "label2";
            this.label2.Size = new Size(41, 12);
            this.label2.TabIndex = 7;
            this.label2.Text = "颜色1:";
            this.panel4.BackColor = SystemColors.Window;
            this.panel4.Controls.Add(this.txtOffset);
            this.panel4.Controls.Add(this.label8);
            this.panel4.Controls.Add(this.txtStep);
            this.panel4.Controls.Add(this.label7);
            this.panel4.Controls.Add(this.txtAngle);
            this.panel4.Controls.Add(this.label6);
            this.panel4.Controls.Add(this.txtWidth);
            this.panel4.Controls.Add(this.label5);
            this.panel4.Controls.Add(this.HatchsymbolItem);
            this.panel4.Controls.Add(this.label4);
            this.panel4.Location = new Point(0, 33);
            this.panel4.Name = "panel4";
            this.panel4.Size = new Size(212, 152);
            this.panel4.TabIndex = 13;
            this.panel4.Visible = false;
            this.txtOffset.Location = new Point(81, 128);
            this.txtOffset.Name = "txtOffset";
            this.txtOffset.Size = new Size(119, 21);
            this.txtOffset.TabIndex = 19;
            this.txtOffset.Text = "0";
            this.txtOffset.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(1, 131);
            this.label8.Name = "label8";
            this.label8.Size = new Size(35, 12);
            this.label8.TabIndex = 18;
            this.label8.Text = "偏移:";
            this.txtStep.Location = new Point(81, 105);
            this.txtStep.Name = "txtStep";
            this.txtStep.Size = new Size(119, 21);
            this.txtStep.TabIndex = 17;
            this.txtStep.Text = "0";
            this.txtStep.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(3, 108);
            this.label7.Name = "label7";
            this.label7.Size = new Size(35, 12);
            this.label7.TabIndex = 16;
            this.label7.Text = "步长:";
            this.txtAngle.Location = new Point(81, 77);
            this.txtAngle.Name = "txtAngle";
            this.txtAngle.Size = new Size(119, 21);
            this.txtAngle.TabIndex = 15;
            this.txtAngle.Text = "0";
            this.txtAngle.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(3, 80);
            this.label6.Name = "label6";
            this.label6.Size = new Size(35, 12);
            this.label6.TabIndex = 14;
            this.label6.Text = "角度:";
            this.txtWidth.Location = new Point(81, 50);
            this.txtWidth.Name = "txtWidth";
            this.txtWidth.Size = new Size(119, 21);
            this.txtWidth.TabIndex = 13;
            this.txtWidth.Text = "0";
            this.txtWidth.Leave += new EventHandler(this.txtAngleGrad_Leave);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(3, 53);
            this.label5.Name = "label5";
            this.label5.Size = new Size(35, 12);
            this.label5.TabIndex = 12;
            this.label5.Text = "宽度:";
            this.HatchsymbolItem.BackColor = SystemColors.ActiveCaptionText;
            this.HatchsymbolItem.Location = new Point(79, 14);
            this.HatchsymbolItem.Name = "HatchsymbolItem";
            this.HatchsymbolItem.Size = new Size(119, 30);
            this.HatchsymbolItem.Symbol = null;
            this.HatchsymbolItem.TabIndex = 11;
            this.HatchsymbolItem.Load += new EventHandler(this.HatchsymbolItem_Load);
            this.HatchsymbolItem.Click += new EventHandler(this.HatchsymbolItem_Click);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(6, 16);
            this.label4.Name = "label4";
            this.label4.Size = new Size(35, 12);
            this.label4.TabIndex = 7;
            this.label4.Text = "颜色:";
            this.contextMenuStrip1.Items.AddRange(new ToolStripItem[] { this.solidColorToolStripMenuItem, this.hatchToolStripMenuItem, this.gradientToolStripMenuItem });
            this.contextMenuStrip1.Name = "contextMenuStrip1";
            this.contextMenuStrip1.Size = new Size(125, 70);
            this.solidColorToolStripMenuItem.Name = "solidColorToolStripMenuItem";
            this.solidColorToolStripMenuItem.Size = new Size(124, 22);
            this.solidColorToolStripMenuItem.Text = "Solid Color";
            this.solidColorToolStripMenuItem.Click += new EventHandler(this.solidColorToolStripMenuItem_Click);
            this.hatchToolStripMenuItem.Name = "hatchToolStripMenuItem";
            this.hatchToolStripMenuItem.Size = new Size(124, 22);
            this.hatchToolStripMenuItem.Text = "Hatch";
            this.hatchToolStripMenuItem.Click += new EventHandler(this.hatchToolStripMenuItem_Click);
            this.gradientToolStripMenuItem.Name = "gradientToolStripMenuItem";
            this.gradientToolStripMenuItem.Size = new Size(124, 22);
            this.gradientToolStripMenuItem.Text = "Gradient";
            this.gradientToolStripMenuItem.Click += new EventHandler(this.gradientToolStripMenuItem_Click);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = SystemColors.Control;
            base.Controls.Add(this.panel4);
            base.Controls.Add(this.panel3);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.btnAddGemoetricEffic);
            base.Controls.Add(this.panel1);
            base.Name = "GeometricEffectFillPage";
            base.Size = new Size(212, 232);
            base.Load += new EventHandler(this.GeometricEffectFillPage_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.contextMenuStrip1.ResumeLayout(false);
            base.ResumeLayout(false);
        }

       
        private IContainer components = null;
        private Button btnAddGemoetricEffic;
        private Button btnChangeEffic;
        private ComboBox comboBox1;
        private ComboBox comboBox2;
        private ContextMenuStrip contextMenuStrip1;
        private ToolStripMenuItem gradientToolStripMenuItem;
        private SymbolItem HatchsymbolItem;
        private ToolStripMenuItem hatchToolStripMenuItem;
        private ImageList imageList1;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private Panel panel4;
        private ToolStripMenuItem solidColorToolStripMenuItem;
        private SymbolItem symbolItem1;
        private SymbolItem symbolItemColor1;
        private SymbolItem symbolItemColor2;
        private TextBox txtAngle;
        private TextBox txtAngleGrad;
        private TextBox txtInterval;
        private TextBox txtOffset;
        private TextBox txtPercent;
        private TextBox txtStep;
        private TextBox txtWidth;
    }
}