using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Yutai.ArcGIS.Carto.DesignLib
{
    public class LegendInfoPage : UserControl
    {
        private Button btnDele;
        private Button btnDeleteAll;
        private Button btnMoveDown;
        private Button btnMoveUp;
        private Button butNewRow;
        private CheckBox chkHasBorder;
        private CheckBox chkItemHasBorder;
        private ColumnHeader columnHeader_0;
        private ColumnHeader columnHeader_1;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private IContainer icontainer_0 = null;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label labPoint;
        private RenderInfoListView renderInfoListView1;
        private TextBox txtColumnNum;
        private TextBox txtColumnSpace;
        private TextBox txtHeight;
        private TextBox txtLabelSpace;
        private TextBox txtLegend;
        private TextBox txtRowSpace;
        private TextBox txtWidth;

        public LegendInfoPage()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool bool_0)
        {
            if (bool_0 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_0);
        }

        private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LegendInfoPage));
            this.groupBox1 = new GroupBox();
            this.label11 = new Label();
            this.label10 = new Label();
            this.txtColumnSpace = new TextBox();
            this.label9 = new Label();
            this.chkHasBorder = new CheckBox();
            this.txtRowSpace = new TextBox();
            this.label2 = new Label();
            this.groupBox2 = new GroupBox();
            this.btnDeleteAll = new Button();
            this.btnMoveDown = new Button();
            this.btnMoveUp = new Button();
            this.chkItemHasBorder = new CheckBox();
            this.label8 = new Label();
            this.txtLabelSpace = new TextBox();
            this.label7 = new Label();
            this.label6 = new Label();
            this.label5 = new Label();
            this.txtHeight = new TextBox();
            this.label4 = new Label();
            this.txtWidth = new TextBox();
            this.label3 = new Label();
            this.renderInfoListView1 = new RenderInfoListView();
            this.columnHeader_0 = new ColumnHeader();
            this.columnHeader_1 = new ColumnHeader();
            this.butNewRow = new Button();
            this.btnDele = new Button();
            this.txtColumnNum = new TextBox();
            this.label1 = new Label();
            this.txtLegend = new TextBox();
            this.labPoint = new Label();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.label11);
            this.groupBox1.Controls.Add(this.label10);
            this.groupBox1.Controls.Add(this.txtColumnSpace);
            this.groupBox1.Controls.Add(this.label9);
            this.groupBox1.Controls.Add(this.chkHasBorder);
            this.groupBox1.Controls.Add(this.txtRowSpace);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Controls.Add(this.txtColumnNum);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.txtLegend);
            this.groupBox1.Controls.Add(this.labPoint);
            this.groupBox1.Location = new Point(13, 13);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x188, 0x166);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "图例配置";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(0x160, 0x5c);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x1d, 12);
            this.label11.TabIndex = 0x55;
            this.label11.Text = "厘米";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(0xa8, 0x5c);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x1d, 12);
            this.label10.TabIndex = 0x54;
            this.label10.Text = "厘米";
            this.txtColumnSpace.Location = new Point(0x10f, 0x59);
            this.txtColumnSpace.Name = "txtColumnSpace";
            this.txtColumnSpace.Size = new Size(0x4b, 0x15);
            this.txtColumnSpace.TabIndex = 80;
            this.label9.AutoSize = true;
            this.label9.Location = new Point(0xd3, 0x5c);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x2f, 12);
            this.label9.TabIndex = 0x51;
            this.label9.Text = "列间距:";
            this.chkHasBorder.AutoSize = true;
            this.chkHasBorder.Location = new Point(0x105, 0x40);
            this.chkHasBorder.Name = "chkHasBorder";
            this.chkHasBorder.Size = new Size(120, 0x10);
            this.chkHasBorder.TabIndex = 0x4f;
            this.chkHasBorder.Text = "图例是否添加边框";
            this.chkHasBorder.UseVisualStyleBackColor = true;
            this.txtRowSpace.Location = new Point(80, 0x59);
            this.txtRowSpace.Name = "txtRowSpace";
            this.txtRowSpace.Size = new Size(0x54, 0x15);
            this.txtRowSpace.TabIndex = 0x4d;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(20, 0x5c);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x2f, 12);
            this.label2.TabIndex = 0x4e;
            this.label2.Text = "行间距:";
            this.groupBox2.Controls.Add(this.btnDeleteAll);
            this.groupBox2.Controls.Add(this.btnMoveDown);
            this.groupBox2.Controls.Add(this.btnMoveUp);
            this.groupBox2.Controls.Add(this.chkItemHasBorder);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.txtLabelSpace);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.txtHeight);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.txtWidth);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.renderInfoListView1);
            this.groupBox2.Controls.Add(this.butNewRow);
            this.groupBox2.Controls.Add(this.btnDele);
            this.groupBox2.Location = new Point(6, 0x74);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x167, 230);
            this.groupBox2.TabIndex = 0x4c;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "图例项信息";
            this.btnDeleteAll.Location = new Point(0xdb, 0xc3);
            this.btnDeleteAll.Name = "btnDeleteAll";
            this.btnDeleteAll.Size = new Size(80, 0x18);
            this.btnDeleteAll.TabIndex = 0x42;
            this.btnDeleteAll.Text = "删除全部";
            this.btnMoveDown.Enabled = false;
            this.btnMoveDown.Image = (Image) resources.GetObject("btnMoveDown.Image");
            this.btnMoveDown.Location = new Point(0x131, 0x76);
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.Size = new Size(0x18, 0x18);
            this.btnMoveDown.TabIndex = 0x41;
            this.btnMoveUp.Enabled = false;
            this.btnMoveUp.Image = (Image) resources.GetObject("btnMoveUp.Image");
            this.btnMoveUp.Location = new Point(0x131, 0x4e);
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.Size = new Size(0x18, 0x18);
            this.btnMoveUp.TabIndex = 0x40;
            this.btnMoveUp.Text = "z";
            this.chkItemHasBorder.AutoSize = true;
            this.chkItemHasBorder.Location = new Point(0xe4, 0x30);
            this.chkItemHasBorder.Name = "chkItemHasBorder";
            this.chkItemHasBorder.Size = new Size(0x60, 0x10);
            this.chkItemHasBorder.TabIndex = 0x3f;
            this.chkItemHasBorder.Text = "是否添加边框";
            this.chkItemHasBorder.UseVisualStyleBackColor = true;
            this.label8.AutoSize = true;
            this.label8.Location = new Point(0xbd, 0x31);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x1d, 12);
            this.label8.TabIndex = 0x3e;
            this.label8.Text = "厘米";
            this.txtLabelSpace.Location = new Point(0x63, 0x2e);
            this.txtLabelSpace.Name = "txtLabelSpace";
            this.txtLabelSpace.Size = new Size(0x54, 0x15);
            this.txtLabelSpace.TabIndex = 60;
            this.label7.AutoSize = true;
            this.label7.Location = new Point(6, 0x31);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x59, 12);
            this.label7.TabIndex = 0x3d;
            this.label7.Text = "符号与说明间距";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(0x13e, 0x11);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x1d, 12);
            this.label6.TabIndex = 0x3b;
            this.label6.Text = "厘米";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(0x7d, 0x11);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x1d, 12);
            this.label5.TabIndex = 0x3a;
            this.label5.Text = "厘米";
            this.txtHeight.Location = new Point(0xe4, 14);
            this.txtHeight.Name = "txtHeight";
            this.txtHeight.Size = new Size(0x54, 0x15);
            this.txtHeight.TabIndex = 0x38;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(0xc3, 0x11);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x17, 12);
            this.label4.TabIndex = 0x39;
            this.label4.Text = "高:";
            this.txtWidth.Location = new Point(0x23, 14);
            this.txtWidth.Name = "txtWidth";
            this.txtWidth.Size = new Size(0x54, 0x15);
            this.txtWidth.TabIndex = 0x36;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(6, 0x11);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x17, 12);
            this.label3.TabIndex = 0x37;
            this.label3.Text = "宽:";
            this.renderInfoListView1.Columns.AddRange(new ColumnHeader[] { this.columnHeader_0, this.columnHeader_1 });
            this.renderInfoListView1.FullRowSelect = true;
            this.renderInfoListView1.Location = new Point(7, 0x4e);
            this.renderInfoListView1.Name = "renderInfoListView1";
            this.renderInfoListView1.Size = new Size(0x124, 0x6f);
            this.renderInfoListView1.TabIndex = 0x30;
            this.renderInfoListView1.UseCompatibleStateImageBehavior = false;
            this.renderInfoListView1.View = View.Details;
            this.columnHeader_0.Text = "图例项符号";
            this.columnHeader_0.Width = 110;
            this.columnHeader_1.Text = "图例项说明";
            this.columnHeader_1.Width = 0x84;
            this.butNewRow.Location = new Point(0x3a, 0xc3);
            this.butNewRow.Name = "butNewRow";
            this.butNewRow.Size = new Size(70, 0x17);
            this.butNewRow.TabIndex = 0x2c;
            this.butNewRow.Text = "添加";
            this.butNewRow.UseVisualStyleBackColor = true;
            this.btnDele.Location = new Point(0x8f, 0xc3);
            this.btnDele.Name = "btnDele";
            this.btnDele.Size = new Size(70, 0x17);
            this.btnDele.TabIndex = 0x2b;
            this.btnDele.Text = "删除";
            this.btnDele.UseVisualStyleBackColor = true;
            this.txtColumnNum.Location = new Point(80, 0x3b);
            this.txtColumnNum.Name = "txtColumnNum";
            this.txtColumnNum.Size = new Size(0x75, 0x15);
            this.txtColumnNum.TabIndex = 0x4a;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(20, 0x3e);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x3b, 12);
            this.label1.TabIndex = 0x4b;
            this.label1.Text = "图例列数:";
            this.txtLegend.Location = new Point(80, 0x17);
            this.txtLegend.Name = "txtLegend";
            this.txtLegend.Size = new Size(0x12d, 0x15);
            this.txtLegend.TabIndex = 0x48;
            this.labPoint.AutoSize = true;
            this.labPoint.Location = new Point(20, 0x1a);
            this.labPoint.Name = "labPoint";
            this.labPoint.Size = new Size(0x3b, 12);
            this.labPoint.TabIndex = 0x49;
            this.labPoint.Text = "图例标题:";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.Controls.Add(this.groupBox1);
            base.Name = "LegendInfoPage";
            base.Size = new Size(0x1a7, 0x185);
            base.Load += new EventHandler(this.LegendInfoPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            base.ResumeLayout(false);
        }

        private void LegendInfoPage_Load(object sender, EventArgs e)
        {
        }
    }
}

