using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using System.Xml;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.DesignLib
{
    partial class StarndFenFuMapTemplatePage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
 private void InitializeComponent()
        {
            this.groupSR = new GroupBox();
            this.cboDataum = new ComboBox();
            this.txtYOffset = new TextBox();
            this.rdo6 = new RadioButton();
            this.rdo3 = new RadioButton();
            this.label4 = new Label();
            this.label3 = new Label();
            this.groupBox4 = new GroupBox();
            this.rdoFill = new RadioButton();
            this.rdoLine = new RadioButton();
            this.label18 = new Label();
            this.txtOutBorderWidth = new TextBox();
            this.label20 = new Label();
            this.label16 = new Label();
            this.styleButton1 = new StyleButton();
            this.label17 = new Label();
            this.textBox2 = new TextBox();
            this.label19 = new Label();
            this.groupBox3 = new GroupBox();
            this.label11 = new Label();
            this.label10 = new Label();
            this.txtXInterval = new TextBox();
            this.txtYInterval = new TextBox();
            this.label1 = new Label();
            this.label2 = new Label();
            this.btnClear = new Button();
            this.button1 = new Button();
            this.txtLegendInfo = new TextBox();
            this.label15 = new Label();
            this.txtName = new TextBox();
            this.label14 = new Label();
            this.groupBox2 = new GroupBox();
            this.label13 = new Label();
            this.label5 = new Label();
            this.txtStartY = new TextBox();
            this.txtStartX = new TextBox();
            this.label6 = new Label();
            this.label7 = new Label();
            this.groupSR.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            base.SuspendLayout();
            this.groupSR.Controls.Add(this.cboDataum);
            this.groupSR.Controls.Add(this.txtYOffset);
            this.groupSR.Controls.Add(this.rdo6);
            this.groupSR.Controls.Add(this.rdo3);
            this.groupSR.Controls.Add(this.label4);
            this.groupSR.Controls.Add(this.label3);
            this.groupSR.Location = new Point(8, 39);
            this.groupSR.Name = "groupSR";
            this.groupSR.Size = new Size(155, 138);
            this.groupSR.TabIndex = 23;
            this.groupSR.TabStop = false;
            this.groupSR.Text = "投影坐标系统参数";
            this.cboDataum.FormattingEnabled = true;
            this.cboDataum.Items.AddRange(new object[] { "北京54", "西安80" });
            this.cboDataum.Location = new Point(72, 29);
            this.cboDataum.Name = "cboDataum";
            this.cboDataum.Size = new Size(78, 20);
            this.cboDataum.TabIndex = 5;
            this.cboDataum.Text = "西安80";
            this.cboDataum.SelectedIndexChanged += new EventHandler(this.cboDataum_SelectedIndexChanged);
            this.txtYOffset.Location = new Point(72, 55);
            this.txtYOffset.Name = "txtYOffset";
            this.txtYOffset.Size = new Size(78, 21);
            this.txtYOffset.TabIndex = 4;
            this.txtYOffset.Visible = false;
            this.txtYOffset.TextChanged += new EventHandler(this.txtYOffset_TextChanged);
            this.rdo6.AutoSize = true;
            this.rdo6.Location = new Point(77, 97);
            this.rdo6.Name = "rdo6";
            this.rdo6.Size = new Size(65, 16);
            this.rdo6.TabIndex = 3;
            this.rdo6.Text = "6度分带";
            this.rdo6.UseVisualStyleBackColor = true;
            this.rdo6.CheckedChanged += new EventHandler(this.rdo6_CheckedChanged);
            this.rdo3.AutoSize = true;
            this.rdo3.Checked = true;
            this.rdo3.Location = new Point(13, 97);
            this.rdo3.Name = "rdo3";
            this.rdo3.Size = new Size(65, 16);
            this.rdo3.TabIndex = 2;
            this.rdo3.TabStop = true;
            this.rdo3.Text = "3度分带";
            this.rdo3.UseVisualStyleBackColor = true;
            this.rdo3.CheckedChanged += new EventHandler(this.rdo3_CheckedChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(9, 61);
            this.label4.Name = "label4";
            this.label4.Size = new Size(59, 12);
            this.label4.TabIndex = 1;
            this.label4.Text = "坐标偏移:";
            this.label4.Visible = false;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(9, 32);
            this.label3.Name = "label3";
            this.label3.Size = new Size(59, 12);
            this.label3.TabIndex = 0;
            this.label3.Text = "参考椭球:";
            this.groupBox4.Controls.Add(this.rdoFill);
            this.groupBox4.Controls.Add(this.rdoLine);
            this.groupBox4.Controls.Add(this.label18);
            this.groupBox4.Controls.Add(this.txtOutBorderWidth);
            this.groupBox4.Controls.Add(this.label20);
            this.groupBox4.Controls.Add(this.label16);
            this.groupBox4.Controls.Add(this.styleButton1);
            this.groupBox4.Controls.Add(this.label17);
            this.groupBox4.Controls.Add(this.textBox2);
            this.groupBox4.Controls.Add(this.label19);
            this.groupBox4.Location = new Point(169, 48);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(175, 131);
            this.groupBox4.TabIndex = 89;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "边框设置";
            this.rdoFill.AutoSize = true;
            this.rdoFill.Location = new Point(77, 75);
            this.rdoFill.Name = "rdoFill";
            this.rdoFill.Size = new Size(35, 16);
            this.rdoFill.TabIndex = 22;
            this.rdoFill.Text = "面";
            this.rdoFill.UseVisualStyleBackColor = true;
            this.rdoFill.CheckedChanged += new EventHandler(this.rdoFill_CheckedChanged);
            this.rdoLine.AutoSize = true;
            this.rdoLine.Checked = true;
            this.rdoLine.Location = new Point(19, 75);
            this.rdoLine.Name = "rdoLine";
            this.rdoLine.Size = new Size(35, 16);
            this.rdoLine.TabIndex = 21;
            this.rdoLine.TabStop = true;
            this.rdoLine.Text = "线";
            this.rdoLine.UseVisualStyleBackColor = true;
            this.rdoLine.CheckedChanged += new EventHandler(this.rdoLine_CheckedChanged);
            this.label18.AutoSize = true;
            this.label18.Location = new Point(123, 51);
            this.label18.Name = "label18";
            this.label18.Size = new Size(29, 12);
            this.label18.TabIndex = 20;
            this.label18.Text = "厘米";
            this.txtOutBorderWidth.Location = new Point(77, 48);
            this.txtOutBorderWidth.Name = "txtOutBorderWidth";
            this.txtOutBorderWidth.Size = new Size(43, 21);
            this.txtOutBorderWidth.TabIndex = 19;
            this.txtOutBorderWidth.Text = "1";
            this.txtOutBorderWidth.TextChanged += new EventHandler(this.txtOutBorderWidth_TextChanged);
            this.label20.AutoSize = true;
            this.label20.Location = new Point(6, 51);
            this.label20.Name = "label20";
            this.label20.Size = new Size(41, 12);
            this.label20.TabIndex = 18;
            this.label20.Text = "外框宽";
            this.label16.AutoSize = true;
            this.label16.Location = new Point(12, 104);
            this.label16.Name = "label16";
            this.label16.Size = new Size(29, 12);
            this.label16.TabIndex = 10;
            this.label16.Text = "符号";
            this.styleButton1.Location = new Point(59, 94);
            this.styleButton1.Name = "styleButton1";
            this.styleButton1.Size = new Size(96, 31);
            this.styleButton1.Style = null;
            this.styleButton1.TabIndex = 9;
            this.styleButton1.Click += new EventHandler(this.styleButton1_Click);
            this.label17.AutoSize = true;
            this.label17.Location = new Point(123, 23);
            this.label17.Name = "label17";
            this.label17.Size = new Size(29, 12);
            this.label17.TabIndex = 8;
            this.label17.Text = "厘米";
            this.textBox2.Location = new Point(77, 20);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(43, 21);
            this.textBox2.TabIndex = 2;
            this.textBox2.Text = "1";
            this.textBox2.TextChanged += new EventHandler(this.textBox2_TextChanged);
            this.label19.AutoSize = true;
            this.label19.Location = new Point(6, 23);
            this.label19.Name = "label19";
            this.label19.Size = new Size(65, 12);
            this.label19.TabIndex = 0;
            this.label19.Text = "与内框间隔";
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.txtXInterval);
            this.groupBox3.Controls.Add(this.txtYInterval);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Controls.Add(this.label2);
            this.groupBox3.Location = new Point(169, 181);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(175, 92);
            this.groupBox3.TabIndex = 90;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "坐标轴间隔";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(120, 55);
            this.label11.Name = "label11";
            this.label11.Size = new Size(29, 12);
            this.label11.TabIndex = 6;
            this.label11.Text = "厘米";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(120, 27);
            this.label10.Name = "label10";
            this.label10.Size = new Size(29, 12);
            this.label10.TabIndex = 5;
            this.label10.Text = "厘米";
            this.txtXInterval.Location = new Point(62, 52);
            this.txtXInterval.Name = "txtXInterval";
            this.txtXInterval.Size = new Size(52, 21);
            this.txtXInterval.TabIndex = 3;
            this.txtXInterval.Text = "10";
            this.txtXInterval.TextChanged += new EventHandler(this.txtXInterval_TextChanged);
            this.txtYInterval.Location = new Point(62, 24);
            this.txtYInterval.Name = "txtYInterval";
            this.txtYInterval.Size = new Size(52, 21);
            this.txtYInterval.TabIndex = 2;
            this.txtYInterval.Text = "10";
            this.txtYInterval.TextChanged += new EventHandler(this.txtYInterval_TextChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(15, 55);
            this.label1.Name = "label1";
            this.label1.Size = new Size(41, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "横坐标";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(15, 27);
            this.label2.Name = "label2";
            this.label2.Size = new Size(41, 12);
            this.label2.TabIndex = 0;
            this.label2.Text = "纵坐标";
            this.btnClear.Location = new Point(299, 296);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new Size(45, 19);
            this.btnClear.TabIndex = 96;
            this.btnClear.Text = "清除";
            this.btnClear.UseVisualStyleBackColor = true;
            this.btnClear.Visible = false;
            this.button1.Location = new Point(259, 296);
            this.button1.Name = "button1";
            this.button1.Size = new Size(34, 19);
            this.button1.TabIndex = 95;
            this.button1.Text = "...";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Visible = false;
            this.txtLegendInfo.Location = new Point(92, 296);
            this.txtLegendInfo.Name = "txtLegendInfo";
            this.txtLegendInfo.ReadOnly = true;
            this.txtLegendInfo.Size = new Size(154, 21);
            this.txtLegendInfo.TabIndex = 94;
            this.txtLegendInfo.Visible = false;
            this.label15.AutoSize = true;
            this.label15.Location = new Point(9, 299);
            this.label15.Name = "label15";
            this.label15.Size = new Size(77, 12);
            this.label15.TabIndex = 93;
            this.label15.Text = "图例配置文件";
            this.label15.Visible = false;
            this.txtName.Location = new Point(49, 9);
            this.txtName.Name = "txtName";
            this.txtName.Size = new Size(248, 21);
            this.txtName.TabIndex = 98;
            this.txtName.Text = "模板";
            this.txtName.TextChanged += new EventHandler(this.txtName_TextChanged);
            this.label14.AutoSize = true;
            this.label14.Location = new Point(8, 12);
            this.label14.Name = "label14";
            this.label14.Size = new Size(29, 12);
            this.label14.TabIndex = 97;
            this.label14.Text = "名称";
            this.groupBox2.Controls.Add(this.label13);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.txtStartY);
            this.groupBox2.Controls.Add(this.txtStartX);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Location = new Point(10, 181);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(155, 92);
            this.groupBox2.TabIndex = 99;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "左小角坐标基数";
            this.label13.AutoSize = true;
            this.label13.Location = new Point(132, 55);
            this.label13.Name = "label13";
            this.label13.Size = new Size(17, 12);
            this.label13.TabIndex = 7;
            this.label13.Text = "米";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(131, 27);
            this.label5.Name = "label5";
            this.label5.Size = new Size(17, 12);
            this.label5.TabIndex = 6;
            this.label5.Text = "米";
            this.txtStartY.Location = new Point(62, 52);
            this.txtStartY.Name = "txtStartY";
            this.txtStartY.Size = new Size(64, 21);
            this.txtStartY.TabIndex = 3;
            this.txtStartY.Text = "0";
            this.txtStartY.TextChanged += new EventHandler(this.txtStartY_TextChanged);
            this.txtStartX.Location = new Point(62, 24);
            this.txtStartX.Name = "txtStartX";
            this.txtStartX.Size = new Size(64, 21);
            this.txtStartX.TabIndex = 2;
            this.txtStartX.Text = "0";
            this.txtStartX.TextChanged += new EventHandler(this.txtStartX_TextChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(15, 55);
            this.label6.Name = "label6";
            this.label6.Size = new Size(41, 12);
            this.label6.TabIndex = 1;
            this.label6.Text = "横坐标";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(15, 27);
            this.label7.Name = "label7";
            this.label7.Size = new Size(41, 12);
            this.label7.TabIndex = 0;
            this.label7.Text = "纵坐标";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.txtName);
            base.Controls.Add(this.label14);
            base.Controls.Add(this.btnClear);
            base.Controls.Add(this.button1);
            base.Controls.Add(this.txtLegendInfo);
            base.Controls.Add(this.label15);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.groupSR);
            base.Name = "StarndFenFuMapTemplatePage";
            base.Size = new Size(353, 328);
            base.Load += new EventHandler(this.StarndFenFuMapTemplatePage_Load);
            this.groupSR.ResumeLayout(false);
            this.groupSR.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private Button btnClear;
        private Button button1;
        private ComboBox cboDataum;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private GroupBox groupSR;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label18;
        private Label label19;
        private Label label2;
        private Label label20;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private RadioButton rdo3;
        private RadioButton rdo6;
        private RadioButton rdoFill;
        private RadioButton rdoLine;
        private StyleButton styleButton1;
        private TextBox textBox2;
        private TextBox txtLegendInfo;
        private TextBox txtName;
        private TextBox txtOutBorderWidth;
        private TextBox txtStartX;
        private TextBox txtStartY;
        private TextBox txtXInterval;
        private TextBox txtYInterval;
        private TextBox txtYOffset;
    }
}