using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.DataSourcesFile;
using ESRI.ArcGIS.esriSystem;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class CADTransformationPropertyPage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
 private void InitializeComponent()
        {
            this.checkEdit1 = new CheckEdit();
            this.groupBox1 = new GroupBox();
            this.radioGroup1 = new RadioGroup();
            this.panel1 = new Panel();
            this.btnOpenWFName = new SimpleButton();
            this.txtWordFileName = new TextEdit();
            this.label1 = new Label();
            this.panel2 = new Panel();
            this.label2 = new Label();
            this.label3 = new Label();
            this.label4 = new Label();
            this.txtFromXCoord1 = new TextEdit();
            this.txtToXCoord1 = new TextEdit();
            this.label5 = new Label();
            this.txtFromYCoord1 = new TextEdit();
            this.label6 = new Label();
            this.txtToYCoord1 = new TextEdit();
            this.label7 = new Label();
            this.panel3 = new Panel();
            this.txtToYCoord2 = new TextEdit();
            this.label8 = new Label();
            this.txtFromYCoord2 = new TextEdit();
            this.label9 = new Label();
            this.txtToXCoord2 = new TextEdit();
            this.label10 = new Label();
            this.txtFromXCoord2 = new TextEdit();
            this.label11 = new Label();
            this.panel4 = new Panel();
            this.txtScale = new TextEdit();
            this.label15 = new Label();
            this.label14 = new Label();
            this.txtRotate = new TextEdit();
            this.checkEdit1.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.radioGroup1.Properties.BeginInit();
            this.panel1.SuspendLayout();
            this.txtWordFileName.Properties.BeginInit();
            this.panel2.SuspendLayout();
            this.txtFromXCoord1.Properties.BeginInit();
            this.txtToXCoord1.Properties.BeginInit();
            this.txtFromYCoord1.Properties.BeginInit();
            this.txtToYCoord1.Properties.BeginInit();
            this.panel3.SuspendLayout();
            this.txtToYCoord2.Properties.BeginInit();
            this.txtFromYCoord2.Properties.BeginInit();
            this.txtToXCoord2.Properties.BeginInit();
            this.txtFromXCoord2.Properties.BeginInit();
            this.panel4.SuspendLayout();
            this.txtScale.Properties.BeginInit();
            this.txtRotate.Properties.BeginInit();
            base.SuspendLayout();
            this.checkEdit1.Location = new Point(8, 8);
            this.checkEdit1.Name = "checkEdit1";
            this.checkEdit1.Properties.Caption = "启用变换";
            this.checkEdit1.Size = new Size(88, 19);
            this.checkEdit1.TabIndex = 0;
            this.checkEdit1.CheckedChanged += new EventHandler(this.checkEdit1_CheckedChanged);
            this.groupBox1.Controls.Add(this.radioGroup1);
            this.groupBox1.Location = new Point(16, 80);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(128, 120);
            this.groupBox1.TabIndex = 4;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "变换方式";
            this.radioGroup1.Location = new Point(8, 16);
            this.radioGroup1.Name = "radioGroup1";
            this.radioGroup1.Properties.Appearance.BackColor = SystemColors.Control;
            this.radioGroup1.Properties.Appearance.Options.UseBackColor = true;
            this.radioGroup1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.radioGroup1.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "Word File文件"), new RadioGroupItem(null, "坐标"), new RadioGroupItem(null, "旋转,缩放,平移") });
            this.radioGroup1.Size = new Size(112, 88);
            this.radioGroup1.TabIndex = 0;
            this.radioGroup1.SelectedIndexChanged += new EventHandler(this.radioGroup1_SelectedIndexChanged);
            this.panel1.Controls.Add(this.btnOpenWFName);
            this.panel1.Controls.Add(this.txtWordFileName);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Location = new Point(8, 32);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(360, 40);
            this.panel1.TabIndex = 5;
            this.btnOpenWFName.Location = new Point(304, 8);
            this.btnOpenWFName.Name = "btnOpenWFName";
            this.btnOpenWFName.Size = new Size(48, 24);
            this.btnOpenWFName.TabIndex = 6;
            this.btnOpenWFName.Text = "浏览...";
            this.btnOpenWFName.Click += new EventHandler(this.btnOpenWFName_Click);
            this.txtWordFileName.EditValue = "";
            this.txtWordFileName.Location = new Point(120, 8);
            this.txtWordFileName.Name = "txtWordFileName";
            this.txtWordFileName.Properties.ReadOnly = true;
            this.txtWordFileName.Size = new Size(176, 23);
            this.txtWordFileName.TabIndex = 5;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 16);
            this.label1.Name = "label1";
            this.label1.Size = new Size(103, 17);
            this.label1.TabIndex = 4;
            this.label1.Text = "World File文件名";
            this.panel2.Controls.Add(this.panel4);
            this.panel2.Controls.Add(this.panel3);
            this.panel2.Controls.Add(this.txtToYCoord1);
            this.panel2.Controls.Add(this.label7);
            this.panel2.Controls.Add(this.txtFromYCoord1);
            this.panel2.Controls.Add(this.label6);
            this.panel2.Controls.Add(this.txtToXCoord1);
            this.panel2.Controls.Add(this.label5);
            this.panel2.Controls.Add(this.txtFromXCoord1);
            this.panel2.Controls.Add(this.label4);
            this.panel2.Controls.Add(this.label3);
            this.panel2.Controls.Add(this.label2);
            this.panel2.Location = new Point(144, 80);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(336, 192);
            this.panel2.TabIndex = 6;
            this.panel2.Visible = false;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 16);
            this.label2.Name = "label2";
            this.label2.Size = new Size(17, 17);
            this.label2.TabIndex = 0;
            this.label2.Text = "源";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(104, 16);
            this.label3.Name = "label3";
            this.label3.Size = new Size(29, 17);
            this.label3.TabIndex = 1;
            this.label3.Text = "目的";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(8, 40);
            this.label4.Name = "label4";
            this.label4.Size = new Size(11, 17);
            this.label4.TabIndex = 5;
            this.label4.Text = "x";
            this.txtFromXCoord1.EditValue = "";
            this.txtFromXCoord1.Location = new Point(24, 40);
            this.txtFromXCoord1.Name = "txtFromXCoord1";
            this.txtFromXCoord1.Properties.ReadOnly = true;
            this.txtFromXCoord1.Size = new Size(72, 23);
            this.txtFromXCoord1.TabIndex = 6;
            this.txtFromXCoord1.EditValueChanged += new EventHandler(this.txtFromXCoord1_EditValueChanged);
            this.txtToXCoord1.EditValue = "";
            this.txtToXCoord1.Location = new Point(120, 40);
            this.txtToXCoord1.Name = "txtToXCoord1";
            this.txtToXCoord1.Properties.ReadOnly = true;
            this.txtToXCoord1.Size = new Size(72, 23);
            this.txtToXCoord1.TabIndex = 8;
            this.txtToXCoord1.EditValueChanged += new EventHandler(this.txtToXCoord1_EditValueChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(104, 40);
            this.label5.Name = "label5";
            this.label5.Size = new Size(11, 17);
            this.label5.TabIndex = 7;
            this.label5.Text = "x";
            this.txtFromYCoord1.EditValue = "";
            this.txtFromYCoord1.Location = new Point(24, 72);
            this.txtFromYCoord1.Name = "txtFromYCoord1";
            this.txtFromYCoord1.Properties.ReadOnly = true;
            this.txtFromYCoord1.Size = new Size(72, 23);
            this.txtFromYCoord1.TabIndex = 10;
            this.txtFromYCoord1.EditValueChanged += new EventHandler(this.txtFromYCoord1_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(8, 72);
            this.label6.Name = "label6";
            this.label6.Size = new Size(11, 17);
            this.label6.TabIndex = 9;
            this.label6.Text = "y";
            this.txtToYCoord1.EditValue = "";
            this.txtToYCoord1.Location = new Point(120, 72);
            this.txtToYCoord1.Name = "txtToYCoord1";
            this.txtToYCoord1.Properties.ReadOnly = true;
            this.txtToYCoord1.Size = new Size(72, 23);
            this.txtToYCoord1.TabIndex = 12;
            this.txtToYCoord1.EditValueChanged += new EventHandler(this.txtToYCoord1_EditValueChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(104, 72);
            this.label7.Name = "label7";
            this.label7.Size = new Size(11, 17);
            this.label7.TabIndex = 11;
            this.label7.Text = "y";
            this.panel3.Controls.Add(this.txtToYCoord2);
            this.panel3.Controls.Add(this.label8);
            this.panel3.Controls.Add(this.txtFromYCoord2);
            this.panel3.Controls.Add(this.label9);
            this.panel3.Controls.Add(this.txtToXCoord2);
            this.panel3.Controls.Add(this.label10);
            this.panel3.Controls.Add(this.txtFromXCoord2);
            this.panel3.Controls.Add(this.label11);
            this.panel3.Location = new Point(0, 104);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(200, 80);
            this.panel3.TabIndex = 25;
            this.txtToYCoord2.EditValue = "";
            this.txtToYCoord2.Location = new Point(120, 40);
            this.txtToYCoord2.Name = "txtToYCoord2";
            this.txtToYCoord2.Properties.ReadOnly = true;
            this.txtToYCoord2.Size = new Size(72, 23);
            this.txtToYCoord2.TabIndex = 28;
            this.txtToYCoord2.EditValueChanged += new EventHandler(this.txtToYCoord2_EditValueChanged);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(104, 40);
            this.label8.Name = "label8";
            this.label8.Size = new Size(11, 17);
            this.label8.TabIndex = 27;
            this.label8.Text = "y";
            this.txtFromYCoord2.EditValue = "";
            this.txtFromYCoord2.Location = new Point(24, 40);
            this.txtFromYCoord2.Name = "txtFromYCoord2";
            this.txtFromYCoord2.Properties.ReadOnly = true;
            this.txtFromYCoord2.Size = new Size(72, 23);
            this.txtFromYCoord2.TabIndex = 26;
            this.txtFromYCoord2.EditValueChanged += new EventHandler(this.txtFromYCoord2_EditValueChanged);
            this.label9.AutoSize = true;
            this.label9.Location = new Point(8, 40);
            this.label9.Name = "label9";
            this.label9.Size = new Size(11, 17);
            this.label9.TabIndex = 25;
            this.label9.Text = "y";
            this.txtToXCoord2.EditValue = "";
            this.txtToXCoord2.Location = new Point(120, 8);
            this.txtToXCoord2.Name = "txtToXCoord2";
            this.txtToXCoord2.Properties.ReadOnly = true;
            this.txtToXCoord2.Size = new Size(72, 23);
            this.txtToXCoord2.TabIndex = 24;
            this.txtToXCoord2.EditValueChanged += new EventHandler(this.txtToXCoord2_EditValueChanged);
            this.label10.AutoSize = true;
            this.label10.Location = new Point(104, 8);
            this.label10.Name = "label10";
            this.label10.Size = new Size(11, 17);
            this.label10.TabIndex = 23;
            this.label10.Text = "x";
            this.txtFromXCoord2.EditValue = "";
            this.txtFromXCoord2.Location = new Point(24, 8);
            this.txtFromXCoord2.Name = "txtFromXCoord2";
            this.txtFromXCoord2.Properties.ReadOnly = true;
            this.txtFromXCoord2.Size = new Size(72, 23);
            this.txtFromXCoord2.TabIndex = 22;
            this.txtFromXCoord2.EditValueChanged += new EventHandler(this.txtFromXCoord2_EditValueChanged);
            this.label11.AutoSize = true;
            this.label11.Location = new Point(8, 8);
            this.label11.Name = "label11";
            this.label11.Size = new Size(11, 17);
            this.label11.TabIndex = 21;
            this.label11.Text = "x";
            this.panel4.Controls.Add(this.txtScale);
            this.panel4.Controls.Add(this.label14);
            this.panel4.Controls.Add(this.txtRotate);
            this.panel4.Controls.Add(this.label15);
            this.panel4.Location = new Point(200, 32);
            this.panel4.Name = "panel4";
            this.panel4.Size = new Size(136, 80);
            this.panel4.TabIndex = 26;
            this.txtScale.EditValue = "";
            this.txtScale.Location = new Point(56, 40);
            this.txtScale.Name = "txtScale";
            this.txtScale.Properties.ReadOnly = true;
            this.txtScale.Size = new Size(72, 23);
            this.txtScale.TabIndex = 28;
            this.txtScale.EditValueChanged += new EventHandler(this.txtScale_EditValueChanged);
            this.label15.AutoSize = true;
            this.label15.Location = new Point(8, 8);
            this.label15.Name = "label15";
            this.label15.Size = new Size(42, 17);
            this.label15.TabIndex = 25;
            this.label15.Text = "旋转角";
            this.label14.AutoSize = true;
            this.label14.Location = new Point(8, 40);
            this.label14.Name = "label14";
            this.label14.Size = new Size(29, 17);
            this.label14.TabIndex = 27;
            this.label14.Text = "缩放";
            this.txtRotate.EditValue = "";
            this.txtRotate.Location = new Point(56, 8);
            this.txtRotate.Name = "txtRotate";
            this.txtRotate.Properties.ReadOnly = true;
            this.txtRotate.Size = new Size(72, 23);
            this.txtRotate.TabIndex = 26;
            this.txtRotate.EditValueChanged += new EventHandler(this.txtRotate_EditValueChanged);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.checkEdit1);
            base.Name = "CADTransformationPropertyPage";
            base.Size = new Size(488, 288);
            base.Load += new EventHandler(this.CADTransformationPropertyPage_Load);
            this.checkEdit1.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.radioGroup1.Properties.EndInit();
            this.panel1.ResumeLayout(false);
            this.txtWordFileName.Properties.EndInit();
            this.panel2.ResumeLayout(false);
            this.txtFromXCoord1.Properties.EndInit();
            this.txtToXCoord1.Properties.EndInit();
            this.txtFromYCoord1.Properties.EndInit();
            this.txtToYCoord1.Properties.EndInit();
            this.panel3.ResumeLayout(false);
            this.txtToYCoord2.Properties.EndInit();
            this.txtFromYCoord2.Properties.EndInit();
            this.txtToXCoord2.Properties.EndInit();
            this.txtFromXCoord2.Properties.EndInit();
            this.panel4.ResumeLayout(false);
            this.txtScale.Properties.EndInit();
            this.txtRotate.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnOpenWFName;
        private CheckEdit checkEdit1;
        private GroupBox groupBox1;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label14;
        private Label label15;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private Panel panel4;
        private RadioGroup radioGroup1;
        private TextEdit txtFromXCoord1;
        private TextEdit txtFromXCoord2;
        private TextEdit txtFromYCoord1;
        private TextEdit txtFromYCoord2;
        private TextEdit txtRotate;
        private TextEdit txtScale;
        private TextEdit txtToXCoord1;
        private TextEdit txtToXCoord2;
        private TextEdit txtToYCoord1;
        private TextEdit txtToYCoord2;
        private TextEdit txtWordFileName;
    }
}