using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geodatabase;
using Yutai.ArcGIS.Common.Symbol;
using Yutai.ArcGIS.Common.SymbolLib;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class DotDensityRendererCtrl
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DotDensityRendererCtrl));
            this.label4 = new Label();
            this.colorRampComboBox1 = new ColorRampComboBox();
            this.label3 = new Label();
            this.btnStyle = new StyleButton();
            this.groupBox1 = new GroupBox();
            this.btnMoveDown = new SimpleButton();
            this.btnMoveUp = new SimpleButton();
            this.SelectFieldslistView = new RenderInfoListView();
            this.columnHeader_1 = new ColumnHeader();
            this.columnHeader_0 = new ColumnHeader();
            this.btnUnSelectAll = new SimpleButton();
            this.btnUnSelect = new SimpleButton();
            this.btnSelect = new SimpleButton();
            this.FieldsListBoxCtrl = new ListBoxControl();
            this.groupBox2 = new GroupBox();
            this.txtPointValue = new TextEdit();
            this.label2 = new Label();
            this.groupBox4 = new GroupBox();
            this.MinsymbolItem = new SymbolItem();
            this.groupBox5 = new GroupBox();
            this.MaxsymbolItem = new SymbolItem();
            this.txtSize = new TextEdit();
            this.label1 = new Label();
            this.groupBox3 = new GroupBox();
            this.MeansymbolItem = new SymbolItem();
            this.groupBox1.SuspendLayout();
            ((ISupportInitialize) this.FieldsListBoxCtrl).BeginInit();
            this.groupBox2.SuspendLayout();
            this.txtPointValue.Properties.BeginInit();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.txtSize.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            base.SuspendLayout();
            this.label4.AutoSize = true;
            this.label4.Location = new Point(136, 0);
            this.label4.Name = "label4";
            this.label4.Size = new Size(29, 17);
            this.label4.TabIndex = 37;
            this.label4.Text = "背景";
            this.label4.Visible = false;
            this.colorRampComboBox1.DrawMode = DrawMode.OwnerDrawVariable;
            this.colorRampComboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.colorRampComboBox1.Location = new Point(304, 160);
            this.colorRampComboBox1.Name = "colorRampComboBox1";
            this.colorRampComboBox1.Size = new Size(136, 22);
            this.colorRampComboBox1.TabIndex = 36;
            this.colorRampComboBox1.SelectedIndexChanged += new EventHandler(this.colorRampComboBox1_SelectedIndexChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(304, 144);
            this.label3.Name = "label3";
            this.label3.Size = new Size(54, 17);
            this.label3.TabIndex = 35;
            this.label3.Text = "颜色模型";
            this.btnStyle.Location = new Point(176, -8);
            this.btnStyle.Name = "btnStyle";
            this.btnStyle.Size = new Size(72, 24);
            this.btnStyle.Style = null;
            this.btnStyle.TabIndex = 41;
            this.btnStyle.Visible = false;
            this.groupBox1.Controls.Add(this.btnMoveDown);
            this.groupBox1.Controls.Add(this.btnMoveUp);
            this.groupBox1.Controls.Add(this.SelectFieldslistView);
            this.groupBox1.Controls.Add(this.btnUnSelectAll);
            this.groupBox1.Controls.Add(this.btnUnSelect);
            this.groupBox1.Controls.Add(this.btnSelect);
            this.groupBox1.Controls.Add(this.FieldsListBoxCtrl);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.btnStyle);
            this.groupBox1.Location = new Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(440, 136);
            this.groupBox1.TabIndex = 40;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "字段集";
            this.btnMoveDown.Enabled = false;
            this.btnMoveDown.Image = (System.Drawing.Image)resources.GetObject("btnMoveDown.Image");
            this.btnMoveDown.Location = new Point(408, 72);
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.Size = new Size(24, 24);
            this.btnMoveDown.TabIndex = 6;
            this.btnMoveDown.Click += new EventHandler(this.btnMoveDown_Click);
            this.btnMoveUp.Enabled = false;
            this.btnMoveUp.Image = (System.Drawing.Image)resources.GetObject("btnMoveUp.Image");
            this.btnMoveUp.Location = new Point(408, 40);
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.Size = new Size(24, 24);
            this.btnMoveUp.TabIndex = 5;
            this.btnMoveUp.Click += new EventHandler(this.btnMoveUp_Click);
            this.SelectFieldslistView.Columns.AddRange(new ColumnHeader[] { this.columnHeader_1, this.columnHeader_0 });
            this.SelectFieldslistView.FullRowSelect = true;
            this.SelectFieldslistView.Location = new Point(184, 32);
            this.SelectFieldslistView.Name = "SelectFieldslistView";
            this.SelectFieldslistView.Size = new Size(216, 96);
            this.SelectFieldslistView.TabIndex = 4;
            this.SelectFieldslistView.View = View.Details;
            this.SelectFieldslistView.SelectedIndexChanged += new EventHandler(this.SelectFieldslistView_SelectedIndexChanged);
            this.columnHeader_1.Text = "符号";
            this.columnHeader_0.Text = "字段";
            this.columnHeader_0.Width = 95;
            this.btnUnSelectAll.Enabled = false;
            this.btnUnSelectAll.Location = new Point(128, 104);
            this.btnUnSelectAll.Name = "btnUnSelectAll";
            this.btnUnSelectAll.Size = new Size(32, 24);
            this.btnUnSelectAll.TabIndex = 3;
            this.btnUnSelectAll.Text = "<<";
            this.btnUnSelectAll.Click += new EventHandler(this.btnUnSelectAll_Click);
            this.btnUnSelect.Enabled = false;
            this.btnUnSelect.Location = new Point(128, 72);
            this.btnUnSelect.Name = "btnUnSelect";
            this.btnUnSelect.Size = new Size(32, 24);
            this.btnUnSelect.TabIndex = 2;
            this.btnUnSelect.Text = "<";
            this.btnUnSelect.Click += new EventHandler(this.btnUnSelect_Click);
            this.btnSelect.Enabled = false;
            this.btnSelect.Location = new Point(128, 40);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new Size(32, 24);
            this.btnSelect.TabIndex = 1;
            this.btnSelect.Text = ">";
            this.btnSelect.Click += new EventHandler(this.btnSelect_Click);
            this.FieldsListBoxCtrl.ItemHeight = 17;
            this.FieldsListBoxCtrl.Location = new Point(8, 24);
            this.FieldsListBoxCtrl.Name = "FieldsListBoxCtrl";
            this.FieldsListBoxCtrl.SelectionMode = SelectionMode.MultiExtended;
            this.FieldsListBoxCtrl.Size = new Size(112, 104);
            this.FieldsListBoxCtrl.TabIndex = 0;
            this.FieldsListBoxCtrl.SelectedIndexChanged += new EventHandler(this.FieldsListBoxCtrl_SelectedIndexChanged);
            this.groupBox2.Controls.Add(this.txtPointValue);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.groupBox4);
            this.groupBox2.Controls.Add(this.groupBox5);
            this.groupBox2.Controls.Add(this.txtSize);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.groupBox3);
            this.groupBox2.Location = new Point(8, 136);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(288, 120);
            this.groupBox2.TabIndex = 41;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "密度";
            this.txtPointValue.EditValue = "0";
            this.txtPointValue.Location = new Point(112, 88);
            this.txtPointValue.Name = "txtPointValue";
            this.txtPointValue.Size = new Size(96, 23);
            this.txtPointValue.TabIndex = 6;
            this.txtPointValue.EditValueChanged += new EventHandler(this.txtPointValue_EditValueChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(64, 89);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 17);
            this.label2.TabIndex = 5;
            this.label2.Text = "点值";
            this.groupBox4.Controls.Add(this.MinsymbolItem);
            this.groupBox4.Location = new Point(64, 16);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(67, 67);
            this.groupBox4.TabIndex = 4;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "最小值";
            this.MinsymbolItem.BackColor = SystemColors.ControlLight;
            this.MinsymbolItem.Location = new Point(7, 18);
            this.MinsymbolItem.Name = "MinsymbolItem";
            this.MinsymbolItem.Size = new Size(56, 46);
            this.MinsymbolItem.Symbol = null;
            this.MinsymbolItem.TabIndex = 0;
            this.groupBox5.Controls.Add(this.MaxsymbolItem);
            this.groupBox5.Location = new Point(208, 16);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(67, 67);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "最大值";
            this.MaxsymbolItem.BackColor = SystemColors.ControlLight;
            this.MaxsymbolItem.Location = new Point(8, 18);
            this.MaxsymbolItem.Name = "MaxsymbolItem";
            this.MaxsymbolItem.Size = new Size(56, 46);
            this.MaxsymbolItem.Symbol = null;
            this.MaxsymbolItem.TabIndex = 0;
            this.txtSize.EditValue = "2";
            this.txtSize.Location = new Point(8, 48);
            this.txtSize.Name = "txtSize";
            this.txtSize.Size = new Size(48, 23);
            this.txtSize.TabIndex = 1;
            this.txtSize.EditValueChanged += new EventHandler(this.txtSize_EditValueChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 24);
            this.label1.Name = "label1";
            this.label1.Size = new Size(42, 17);
            this.label1.TabIndex = 0;
            this.label1.Text = "点大小";
            this.groupBox3.Controls.Add(this.MeansymbolItem);
            this.groupBox3.Location = new Point(136, 16);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(67, 67);
            this.groupBox3.TabIndex = 3;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "平均值";
            this.MeansymbolItem.BackColor = SystemColors.ControlLight;
            this.MeansymbolItem.Location = new Point(8, 18);
            this.MeansymbolItem.Name = "MeansymbolItem";
            this.MeansymbolItem.Size = new Size(56, 46);
            this.MeansymbolItem.Symbol = null;
            this.MeansymbolItem.TabIndex = 0;
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.colorRampComboBox1);
            base.Controls.Add(this.label3);
            base.Name = "DotDensityRendererCtrl";
            base.Size = new Size(448, 264);
            base.Load += new EventHandler(this.DotDensityRendererCtrl_Load);
            this.groupBox1.ResumeLayout(false);
            ((ISupportInitialize) this.FieldsListBoxCtrl).EndInit();
            this.groupBox2.ResumeLayout(false);
            this.txtPointValue.Properties.EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.txtSize.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnMoveDown;
        private SimpleButton btnMoveUp;
        private SimpleButton btnSelect;
        private StyleButton btnStyle;
        private SimpleButton btnUnSelect;
        private SimpleButton btnUnSelectAll;
        private ColorRampComboBox colorRampComboBox1;
        private ColumnHeader columnHeader_0;
        private ColumnHeader columnHeader_1;
        private ListBoxControl FieldsListBoxCtrl;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private GroupBox groupBox5;
        private IDotDensityRenderer idotDensityRenderer_0;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private SymbolItem MaxsymbolItem;
        private SymbolItem MeansymbolItem;
        private SymbolItem MinsymbolItem;
        private RenderInfoListView SelectFieldslistView;
        private TextEdit txtPointValue;
        private TextEdit txtSize;
    }
}