using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.Symbol;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class FrameProprtyPage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
        private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrameProprtyPage));
            this.groupBox1 = new GroupBox();
            this.txtBorderCornerRounding = new SpinEdit();
            this.label5 = new Label();
            this.txtBorderGapy = new SpinEdit();
            this.label4 = new Label();
            this.label3 = new Label();
            this.txtBorderGapx = new SpinEdit();
            this.label2 = new Label();
            this.label1 = new Label();
            this.colorBorder = new ColorEdit();
            this.btnBorderInfo = new SimpleButton();
            this.imageList_0 = new ImageList(this.icontainer_0);
            this.btnBorderSelector = new SimpleButton();
            this.cboBorder = new StyleComboBox(this.icontainer_0);
            this.groupBox2 = new GroupBox();
            this.txtBackgroundCornerRounding = new SpinEdit();
            this.label6 = new Label();
            this.txtBackgroundGapy = new SpinEdit();
            this.label7 = new Label();
            this.label8 = new Label();
            this.txtBackgroundGapx = new SpinEdit();
            this.label9 = new Label();
            this.label10 = new Label();
            this.colorBackground = new ColorEdit();
            this.btnBackgroundInfo = new SimpleButton();
            this.btnBackgroundSelector = new SimpleButton();
            this.cboBackground = new StyleComboBox(this.icontainer_0);
            this.groupBox3 = new GroupBox();
            this.txtShadowCornerRounding = new SpinEdit();
            this.label11 = new Label();
            this.txtShadowGapy = new SpinEdit();
            this.label12 = new Label();
            this.label13 = new Label();
            this.txtShadowGapx = new SpinEdit();
            this.label14 = new Label();
            this.label15 = new Label();
            this.colorShadow = new ColorEdit();
            this.btnshadowInfo = new SimpleButton();
            this.btnShadowSelector = new SimpleButton();
            this.cboShadow = new StyleComboBox(this.icontainer_0);
            this.groupBox1.SuspendLayout();
            this.txtBorderCornerRounding.Properties.BeginInit();
            this.txtBorderGapy.Properties.BeginInit();
            this.txtBorderGapx.Properties.BeginInit();
            this.colorBorder.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.txtBackgroundCornerRounding.Properties.BeginInit();
            this.txtBackgroundGapy.Properties.BeginInit();
            this.txtBackgroundGapx.Properties.BeginInit();
            this.colorBackground.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.txtShadowCornerRounding.Properties.BeginInit();
            this.txtShadowGapy.Properties.BeginInit();
            this.txtShadowGapx.Properties.BeginInit();
            this.colorShadow.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.txtBorderCornerRounding);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.txtBorderGapy);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.txtBorderGapx);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.colorBorder);
            this.groupBox1.Controls.Add(this.btnBorderInfo);
            this.groupBox1.Controls.Add(this.btnBorderSelector);
            this.groupBox1.Controls.Add(this.cboBorder);
            this.groupBox1.Location = new Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(384, 104);
            this.groupBox1.TabIndex = 10;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "边框";
            int[] bits = new int[4];
            this.txtBorderCornerRounding.EditValue = new decimal(bits);
            this.txtBorderCornerRounding.Location = new Point(280, 72);
            this.txtBorderCornerRounding.Name = "txtBorderCornerRounding";
            this.txtBorderCornerRounding.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBorderCornerRounding.Properties.UseCtrlIncrement = false;
            this.txtBorderCornerRounding.Size = new Size(48, 23);
            this.txtBorderCornerRounding.TabIndex = 21;
            this.txtBorderCornerRounding.EditValueChanged += new EventHandler(this.txtBorderCornerRounding_EditValueChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(240, 72);
            this.label5.Name = "label5";
            this.label5.Size = new Size(35, 17);
            this.label5.TabIndex = 20;
            this.label5.Text = "圆角:";
            int[] bits2 = new int[4];
            this.txtBorderGapy.EditValue = new decimal(bits2);
            this.txtBorderGapy.Location = new Point(152, 72);
            this.txtBorderGapy.Name = "txtBorderGapy";
            this.txtBorderGapy.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBorderGapy.Properties.UseCtrlIncrement = false;
            this.txtBorderGapy.Size = new Size(48, 23);
            this.txtBorderGapy.TabIndex = 19;
            this.txtBorderGapy.EditValueChanged += new EventHandler(this.txtBorderGapy_EditValueChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(128, 72);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 17);
            this.label4.TabIndex = 18;
            this.label4.Text = "Y:";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(48, 72);
            this.label3.Name = "label3";
            this.label3.Size = new Size(17, 17);
            this.label3.TabIndex = 17;
            this.label3.Text = "X:";
            int[] bits3 = new int[4];
            this.txtBorderGapx.EditValue = new decimal(bits3);
            this.txtBorderGapx.Location = new Point(72, 72);
            this.txtBorderGapx.Name = "txtBorderGapx";
            this.txtBorderGapx.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBorderGapx.Properties.UseCtrlIncrement = false;
            this.txtBorderGapx.Size = new Size(48, 23);
            this.txtBorderGapx.TabIndex = 16;
            this.txtBorderGapx.EditValueChanged += new EventHandler(this.txtBorderGapx_EditValueChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 72);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 17);
            this.label2.TabIndex = 15;
            this.label2.Text = "间隔:";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(280, 32);
            this.label1.Name = "label1";
            this.label1.Size = new Size(35, 17);
            this.label1.TabIndex = 14;
            this.label1.Text = "颜色:";
            this.colorBorder.EditValue = Color.Empty;
            this.colorBorder.Location = new Point(320, 32);
            this.colorBorder.Name = "colorBorder";
            this.colorBorder.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorBorder.Size = new Size(48, 23);
            this.colorBorder.TabIndex = 13;
            this.colorBorder.EditValueChanged += new EventHandler(this.colorBorder_EditValueChanged);
            this.btnBorderInfo.Appearance.BackColor = SystemColors.Window;
            this.btnBorderInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBorderInfo.Appearance.Options.UseBackColor = true;
            this.btnBorderInfo.Appearance.Options.UseForeColor = true;
            this.btnBorderInfo.ButtonStyle = BorderStyles.Simple;
            this.btnBorderInfo.ImageIndex = 1;
            this.btnBorderInfo.ImageList = this.imageList_0;
            this.btnBorderInfo.Location = new Point(256, 39);
            this.btnBorderInfo.Name = "btnBorderInfo";
            this.btnBorderInfo.Size = new Size(16, 16);
            this.btnBorderInfo.TabIndex = 12;
            this.btnBorderInfo.Click += new EventHandler(this.btnBorderInfo_Click);
            this.imageList_0.ImageSize = new Size(10, 10);
            this.imageList_0.ImageStream = (ImageListStreamer)resources.GetObject("imageList1.ImageStream");
            this.imageList_0.TransparentColor = Color.Transparent;
            this.btnBorderSelector.Appearance.BackColor = SystemColors.Window;
            this.btnBorderSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBorderSelector.Appearance.Options.UseBackColor = true;
            this.btnBorderSelector.Appearance.Options.UseForeColor = true;
            this.btnBorderSelector.ButtonStyle = BorderStyles.Simple;
            this.btnBorderSelector.ImageIndex = 0;
            this.btnBorderSelector.ImageList = this.imageList_0;
            this.btnBorderSelector.Location = new Point(256, 24);
            this.btnBorderSelector.Name = "btnBorderSelector";
            this.btnBorderSelector.Size = new Size(16, 16);
            this.btnBorderSelector.TabIndex = 11;
            this.btnBorderSelector.Click += new EventHandler(this.btnBorderSelector_Click);
            this.cboBorder.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboBorder.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboBorder.DropDownWidth = 160;
            this.cboBorder.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboBorder.Location = new Point(16, 24);
            this.cboBorder.Name = "cboBorder";
            this.cboBorder.Size = new Size(240, 31);
            this.cboBorder.TabIndex = 10;
            this.cboBorder.SelectedIndexChanged += new EventHandler(this.cboBorder_SelectedIndexChanged);
            this.groupBox2.Controls.Add(this.txtBackgroundCornerRounding);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.txtBackgroundGapy);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.txtBackgroundGapx);
            this.groupBox2.Controls.Add(this.label9);
            this.groupBox2.Controls.Add(this.label10);
            this.groupBox2.Controls.Add(this.colorBackground);
            this.groupBox2.Controls.Add(this.btnBackgroundInfo);
            this.groupBox2.Controls.Add(this.btnBackgroundSelector);
            this.groupBox2.Controls.Add(this.cboBackground);
            this.groupBox2.Location = new Point(8, 120);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(384, 104);
            this.groupBox2.TabIndex = 11;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "背景";
            int[] bits4 = new int[4];
            this.txtBackgroundCornerRounding.EditValue = new decimal(bits4);
            this.txtBackgroundCornerRounding.Location = new Point(280, 72);
            this.txtBackgroundCornerRounding.Name = "txtBackgroundCornerRounding";
            this.txtBackgroundCornerRounding.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBackgroundCornerRounding.Properties.UseCtrlIncrement = false;
            this.txtBackgroundCornerRounding.Size = new Size(48, 23);
            this.txtBackgroundCornerRounding.TabIndex = 21;
            this.txtBackgroundCornerRounding.EditValueChanged += new EventHandler(this.txtBackgroundCornerRounding_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(240, 72);
            this.label6.Name = "label6";
            this.label6.Size = new Size(35, 17);
            this.label6.TabIndex = 20;
            this.label6.Text = "圆角:";
            int[] bits5 = new int[4];
            this.txtBackgroundGapy.EditValue = new decimal(bits5);
            this.txtBackgroundGapy.Location = new Point(152, 72);
            this.txtBackgroundGapy.Name = "txtBackgroundGapy";
            this.txtBackgroundGapy.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBackgroundGapy.Properties.UseCtrlIncrement = false;
            this.txtBackgroundGapy.Size = new Size(48, 23);
            this.txtBackgroundGapy.TabIndex = 19;
            this.txtBackgroundGapy.EditValueChanged += new EventHandler(this.txtBackgroundGapy_EditValueChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(128, 72);
            this.label7.Name = "label7";
            this.label7.Size = new Size(17, 17);
            this.label7.TabIndex = 18;
            this.label7.Text = "Y:";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(48, 72);
            this.label8.Name = "label8";
            this.label8.Size = new Size(17, 17);
            this.label8.TabIndex = 17;
            this.label8.Text = "X:";
            int[] bits6 = new int[4];
            this.txtBackgroundGapx.EditValue = new decimal(bits6);
            this.txtBackgroundGapx.Location = new Point(72, 72);
            this.txtBackgroundGapx.Name = "txtBackgroundGapx";
            this.txtBackgroundGapx.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBackgroundGapx.Properties.UseCtrlIncrement = false;
            this.txtBackgroundGapx.Size = new Size(48, 23);
            this.txtBackgroundGapx.TabIndex = 16;
            this.txtBackgroundGapx.EditValueChanged += new EventHandler(this.txtBackgroundGapx_EditValueChanged);
            this.label9.AutoSize = true;
            this.label9.Location = new Point(8, 72);
            this.label9.Name = "label9";
            this.label9.Size = new Size(35, 17);
            this.label9.TabIndex = 15;
            this.label9.Text = "间隔:";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(280, 32);
            this.label10.Name = "label10";
            this.label10.Size = new Size(35, 17);
            this.label10.TabIndex = 14;
            this.label10.Text = "颜色:";
            this.colorBackground.EditValue = Color.Empty;
            this.colorBackground.Location = new Point(320, 32);
            this.colorBackground.Name = "colorBackground";
            this.colorBackground.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorBackground.Size = new Size(48, 23);
            this.colorBackground.TabIndex = 13;
            this.colorBackground.EditValueChanged += new EventHandler(this.colorBackground_EditValueChanged);
            this.btnBackgroundInfo.Appearance.BackColor = SystemColors.Window;
            this.btnBackgroundInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBackgroundInfo.Appearance.Options.UseBackColor = true;
            this.btnBackgroundInfo.Appearance.Options.UseForeColor = true;
            this.btnBackgroundInfo.ButtonStyle = BorderStyles.Simple;
            this.btnBackgroundInfo.ImageIndex = 1;
            this.btnBackgroundInfo.ImageList = this.imageList_0;
            this.btnBackgroundInfo.Location = new Point(256, 39);
            this.btnBackgroundInfo.Name = "btnBackgroundInfo";
            this.btnBackgroundInfo.Size = new Size(16, 16);
            this.btnBackgroundInfo.TabIndex = 12;
            this.btnBackgroundInfo.Click += new EventHandler(this.btnBackgroundInfo_Click);
            this.btnBackgroundSelector.Appearance.BackColor = SystemColors.Window;
            this.btnBackgroundSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBackgroundSelector.Appearance.Options.UseBackColor = true;
            this.btnBackgroundSelector.Appearance.Options.UseForeColor = true;
            this.btnBackgroundSelector.ButtonStyle = BorderStyles.Simple;
            this.btnBackgroundSelector.ImageIndex = 0;
            this.btnBackgroundSelector.ImageList = this.imageList_0;
            this.btnBackgroundSelector.Location = new Point(256, 24);
            this.btnBackgroundSelector.Name = "btnBackgroundSelector";
            this.btnBackgroundSelector.Size = new Size(16, 16);
            this.btnBackgroundSelector.TabIndex = 11;
            this.btnBackgroundSelector.Click += new EventHandler(this.btnBackgroundSelector_Click);
            this.cboBackground.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboBackground.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboBackground.DropDownWidth = 160;
            this.cboBackground.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboBackground.Location = new Point(16, 24);
            this.cboBackground.Name = "cboBackground";
            this.cboBackground.Size = new Size(240, 31);
            this.cboBackground.TabIndex = 10;
            this.cboBackground.SelectedIndexChanged += new EventHandler(this.cboBackground_SelectedIndexChanged);
            this.groupBox3.Controls.Add(this.txtShadowCornerRounding);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.txtShadowGapy);
            this.groupBox3.Controls.Add(this.label12);
            this.groupBox3.Controls.Add(this.label13);
            this.groupBox3.Controls.Add(this.txtShadowGapx);
            this.groupBox3.Controls.Add(this.label14);
            this.groupBox3.Controls.Add(this.label15);
            this.groupBox3.Controls.Add(this.colorShadow);
            this.groupBox3.Controls.Add(this.btnshadowInfo);
            this.groupBox3.Controls.Add(this.btnShadowSelector);
            this.groupBox3.Controls.Add(this.cboShadow);
            this.groupBox3.Location = new Point(8, 232);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(384, 104);
            this.groupBox3.TabIndex = 12;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "阴影";
            int[] bits7 = new int[4];
            this.txtShadowCornerRounding.EditValue = new decimal(bits7);
            this.txtShadowCornerRounding.Location = new Point(280, 72);
            this.txtShadowCornerRounding.Name = "txtShadowCornerRounding";
            this.txtShadowCornerRounding.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtShadowCornerRounding.Properties.UseCtrlIncrement = false;
            this.txtShadowCornerRounding.Size = new Size(48, 23);
            this.txtShadowCornerRounding.TabIndex = 21;
            this.txtShadowCornerRounding.EditValueChanged += new EventHandler(this.txtShadowCornerRounding_EditValueChanged);
            this.label11.AutoSize = true;
            this.label11.Location = new Point(240, 72);
            this.label11.Name = "label11";
            this.label11.Size = new Size(35, 17);
            this.label11.TabIndex = 20;
            this.label11.Text = "圆角:";
            int[] bits8 = new int[4];
            this.txtShadowGapy.EditValue = new decimal(bits8);
            this.txtShadowGapy.Location = new Point(152, 72);
            this.txtShadowGapy.Name = "txtShadowGapy";
            this.txtShadowGapy.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtShadowGapy.Properties.UseCtrlIncrement = false;
            this.txtShadowGapy.Size = new Size(48, 23);
            this.txtShadowGapy.TabIndex = 19;
            this.txtShadowGapy.EditValueChanged += new EventHandler(this.txtShadowGapy_EditValueChanged);
            this.label12.AutoSize = true;
            this.label12.Location = new Point(128, 72);
            this.label12.Name = "label12";
            this.label12.Size = new Size(17, 17);
            this.label12.TabIndex = 18;
            this.label12.Text = "Y:";
            this.label13.AutoSize = true;
            this.label13.Location = new Point(48, 72);
            this.label13.Name = "label13";
            this.label13.Size = new Size(17, 17);
            this.label13.TabIndex = 17;
            this.label13.Text = "X:";
            int[] bits9 = new int[4];
            this.txtShadowGapx.EditValue = new decimal(bits9);
            this.txtShadowGapx.Location = new Point(72, 72);
            this.txtShadowGapx.Name = "txtShadowGapx";
            this.txtShadowGapx.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtShadowGapx.Properties.UseCtrlIncrement = false;
            this.txtShadowGapx.Size = new Size(48, 23);
            this.txtShadowGapx.TabIndex = 16;
            this.txtShadowGapx.EditValueChanged += new EventHandler(this.txtShadowGapx_EditValueChanged);
            this.label14.AutoSize = true;
            this.label14.Location = new Point(8, 72);
            this.label14.Name = "label14";
            this.label14.Size = new Size(35, 17);
            this.label14.TabIndex = 15;
            this.label14.Text = "间隔:";
            this.label15.AutoSize = true;
            this.label15.Location = new Point(280, 32);
            this.label15.Name = "label15";
            this.label15.Size = new Size(35, 17);
            this.label15.TabIndex = 14;
            this.label15.Text = "颜色:";
            this.colorShadow.EditValue = Color.Empty;
            this.colorShadow.Location = new Point(320, 32);
            this.colorShadow.Name = "colorShadow";
            this.colorShadow.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorShadow.Size = new Size(48, 23);
            this.colorShadow.TabIndex = 13;
            this.colorShadow.EditValueChanged += new EventHandler(this.colorShadow_EditValueChanged);
            this.btnshadowInfo.Appearance.BackColor = SystemColors.Window;
            this.btnshadowInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnshadowInfo.Appearance.Options.UseBackColor = true;
            this.btnshadowInfo.Appearance.Options.UseForeColor = true;
            this.btnshadowInfo.ButtonStyle = BorderStyles.Simple;
            this.btnshadowInfo.ImageIndex = 1;
            this.btnshadowInfo.ImageList = this.imageList_0;
            this.btnshadowInfo.Location = new Point(256, 39);
            this.btnshadowInfo.Name = "btnshadowInfo";
            this.btnshadowInfo.Size = new Size(16, 16);
            this.btnshadowInfo.TabIndex = 12;
            this.btnshadowInfo.Click += new EventHandler(this.btnshadowInfo_Click);
            this.btnShadowSelector.Appearance.BackColor = SystemColors.Window;
            this.btnShadowSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnShadowSelector.Appearance.Options.UseBackColor = true;
            this.btnShadowSelector.Appearance.Options.UseForeColor = true;
            this.btnShadowSelector.ButtonStyle = BorderStyles.Simple;
            this.btnShadowSelector.ImageIndex = 0;
            this.btnShadowSelector.ImageList = this.imageList_0;
            this.btnShadowSelector.Location = new Point(256, 24);
            this.btnShadowSelector.Name = "btnShadowSelector";
            this.btnShadowSelector.Size = new Size(16, 16);
            this.btnShadowSelector.TabIndex = 11;
            this.btnShadowSelector.Click += new EventHandler(this.btnShadowSelector_Click);
            this.cboShadow.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboShadow.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboShadow.DropDownWidth = 160;
            this.cboShadow.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboShadow.Location = new Point(16, 24);
            this.cboShadow.Name = "cboShadow";
            this.cboShadow.Size = new Size(240, 31);
            this.cboShadow.TabIndex = 10;
            this.cboShadow.SelectedIndexChanged += new EventHandler(this.cboShadow_SelectedIndexChanged);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "FrameProprtyPage";
            base.Size = new Size(408, 352);
            base.Load += new EventHandler(this.FrameProprtyPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.txtBorderCornerRounding.Properties.EndInit();
            this.txtBorderGapy.Properties.EndInit();
            this.txtBorderGapx.Properties.EndInit();
            this.colorBorder.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.txtBackgroundCornerRounding.Properties.EndInit();
            this.txtBackgroundGapy.Properties.EndInit();
            this.txtBackgroundGapx.Properties.EndInit();
            this.colorBackground.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.txtShadowCornerRounding.Properties.EndInit();
            this.txtShadowGapy.Properties.EndInit();
            this.txtShadowGapx.Properties.EndInit();
            this.colorShadow.Properties.EndInit();
            base.ResumeLayout(false);
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private SimpleButton btnBackgroundInfo;
        private SimpleButton btnBackgroundSelector;
        private SimpleButton btnBorderInfo;
        private SimpleButton btnBorderSelector;
        private SimpleButton btnshadowInfo;
        private SimpleButton btnShadowSelector;
        private StyleComboBox cboBackground;
        private StyleComboBox cboBorder;
        private StyleComboBox cboShadow;
        private ColorEdit colorBackground;
        private ColorEdit colorBorder;
        private ColorEdit colorShadow;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private IContainer icontainer_0;
        private ImageList imageList_0;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private SpinEdit txtBackgroundCornerRounding;
        private SpinEdit txtBackgroundGapx;
        private SpinEdit txtBackgroundGapy;
        private SpinEdit txtBorderCornerRounding;
        private SpinEdit txtBorderGapx;
        private SpinEdit txtBorderGapy;
        private SpinEdit txtShadowCornerRounding;
        private SpinEdit txtShadowGapx;
        private SpinEdit txtShadowGapy;
    }
}