using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Geodatabase;
using Yutai.Shared;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class frmExpressionBuild
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmExpressionBuild));
            this.label2 = new Label();
            this.btnIs = new SimpleButton();
            this.btnNot = new SimpleButton();
            this.btnBracket = new SimpleButton();
            this.btnOr = new SimpleButton();
            this.btnLittleEqual = new SimpleButton();
            this.btnLittle = new SimpleButton();
            this.btnAnd = new SimpleButton();
            this.btnLike = new SimpleButton();
            this.btnGreat = new SimpleButton();
            this.btnNotEqual = new SimpleButton();
            this.btnGreatEqual = new SimpleButton();
            this.btnEqual = new SimpleButton();
            this.btnClose = new SimpleButton();
            this.btnApply = new SimpleButton();
            this.memEditWhereCaluse = new MemoEdit();
            this.Fieldlist = new ListBoxControl();
            this.lbl = new Label();
            this.lstFunction = new ListBoxControl();
            this.btnClear = new SimpleButton();
            this.btnValidate = new SimpleButton();
            this.label1 = new Label();
            this.simpleButton1 = new SimpleButton();
            this.simpleButton2 = new SimpleButton();
            this.simpleButton3 = new SimpleButton();
            this.simpleButton4 = new SimpleButton();
            this.memEditWhereCaluse.Properties.BeginInit();
            ((ISupportInitialize) this.Fieldlist).BeginInit();
            ((ISupportInitialize) this.lstFunction).BeginInit();
            base.SuspendLayout();
            this.label2.Location = new Point(16, 8);
            this.label2.Name = "label2";
            this.label2.Size = new Size(48, 16);
            this.label2.TabIndex = 43;
            this.label2.Text = "字段";
            this.btnIs.Location = new Point(233, 295);
            this.btnIs.Name = "btnIs";
            this.btnIs.Size = new Size(32, 24);
            this.btnIs.TabIndex = 41;
            this.btnIs.Text = "0";
            this.btnIs.Click += new EventHandler(this.simpleButton4_Click);
            this.btnNot.Location = new Point(275, 295);
            this.btnNot.Name = "btnNot";
            this.btnNot.Size = new Size(32, 24);
            this.btnNot.TabIndex = 40;
            this.btnNot.Text = ".";
            this.btnNot.Click += new EventHandler(this.simpleButton4_Click);
            this.btnBracket.Location = new Point(195, 295);
            this.btnBracket.Name = "btnBracket";
            this.btnBracket.Size = new Size(32, 24);
            this.btnBracket.TabIndex = 39;
            this.btnBracket.Text = "(  )";
            this.btnBracket.Click += new EventHandler(this.simpleButton4_Click);
            this.btnOr.Location = new Point(275, 265);
            this.btnOr.Name = "btnOr";
            this.btnOr.Size = new Size(32, 24);
            this.btnOr.TabIndex = 37;
            this.btnOr.Text = "3";
            this.btnOr.Click += new EventHandler(this.simpleButton4_Click);
            this.btnLittleEqual.Location = new Point(235, 265);
            this.btnLittleEqual.Name = "btnLittleEqual";
            this.btnLittleEqual.Size = new Size(32, 24);
            this.btnLittleEqual.TabIndex = 36;
            this.btnLittleEqual.Text = "2";
            this.btnLittleEqual.Click += new EventHandler(this.simpleButton4_Click);
            this.btnLittle.Location = new Point(195, 265);
            this.btnLittle.Name = "btnLittle";
            this.btnLittle.Size = new Size(32, 24);
            this.btnLittle.TabIndex = 35;
            this.btnLittle.Text = "1";
            this.btnLittle.Click += new EventHandler(this.simpleButton4_Click);
            this.btnAnd.Location = new Point(275, 233);
            this.btnAnd.Name = "btnAnd";
            this.btnAnd.Size = new Size(32, 24);
            this.btnAnd.TabIndex = 34;
            this.btnAnd.Text = "6";
            this.btnAnd.Click += new EventHandler(this.simpleButton4_Click);
            this.btnLike.Location = new Point(275, 201);
            this.btnLike.Name = "btnLike";
            this.btnLike.Size = new Size(32, 24);
            this.btnLike.TabIndex = 33;
            this.btnLike.Text = "9";
            this.btnLike.Click += new EventHandler(this.simpleButton4_Click);
            this.btnGreat.Location = new Point(195, 233);
            this.btnGreat.Name = "btnGreat";
            this.btnGreat.Size = new Size(32, 24);
            this.btnGreat.TabIndex = 32;
            this.btnGreat.Text = "4";
            this.btnGreat.Click += new EventHandler(this.simpleButton4_Click);
            this.btnNotEqual.Location = new Point(235, 201);
            this.btnNotEqual.Name = "btnNotEqual";
            this.btnNotEqual.Size = new Size(32, 24);
            this.btnNotEqual.TabIndex = 31;
            this.btnNotEqual.Text = "8";
            this.btnNotEqual.Click += new EventHandler(this.simpleButton4_Click);
            this.btnGreatEqual.Location = new Point(235, 233);
            this.btnGreatEqual.Name = "btnGreatEqual";
            this.btnGreatEqual.Size = new Size(32, 24);
            this.btnGreatEqual.TabIndex = 30;
            this.btnGreatEqual.Text = "5";
            this.btnGreatEqual.Click += new EventHandler(this.simpleButton4_Click);
            this.btnEqual.Location = new Point(195, 201);
            this.btnEqual.Name = "btnEqual";
            this.btnEqual.Size = new Size(32, 24);
            this.btnEqual.TabIndex = 29;
            this.btnEqual.Text = "7";
            this.btnEqual.Click += new EventHandler(this.simpleButton4_Click);
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnClose.Location = new Point(289, 337);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new Size(56, 24);
            this.btnClose.TabIndex = 28;
            this.btnClose.Text = "取消";
            this.btnApply.Location = new Point(209, 337);
            this.btnApply.Name = "btnApply";
            this.btnApply.Size = new Size(56, 24);
            this.btnApply.TabIndex = 27;
            this.btnApply.Text = "确定";
            this.btnApply.Click += new EventHandler(this.btnApply_Click);
            this.memEditWhereCaluse.EditValue = "";
            this.memEditWhereCaluse.Location = new Point(18, 201);
            this.memEditWhereCaluse.Name = "memEditWhereCaluse";
            this.memEditWhereCaluse.Size = new Size(159, 118);
            this.memEditWhereCaluse.TabIndex = 26;
            this.Fieldlist.ItemHeight = 17;
            this.Fieldlist.Location = new Point(16, 24);
            this.Fieldlist.Name = "Fieldlist";
            this.Fieldlist.Size = new Size(161, 147);
            this.Fieldlist.TabIndex = 24;
            this.Fieldlist.DoubleClick += new EventHandler(this.Fieldlist_DoubleClick);
            this.Fieldlist.SelectedIndexChanged += new EventHandler(this.Fieldlist_SelectedIndexChanged);
            this.lbl.AutoSize = true;
            this.lbl.Location = new Point(181, 8);
            this.lbl.Name = "lbl";
            this.lbl.Size = new Size(29, 12);
            this.lbl.TabIndex = 48;
            this.lbl.Text = "函数";
            this.lstFunction.Enabled = false;
            this.lstFunction.ItemHeight = 17;
            this.lstFunction.Items.AddRange(new object[] { "Abs (  )", "Atn (  )", "Cos (  )", "Exp (  )", " Fix (  )", "Int (  )", "Log (  ) ", "Sin (  )", "Sqr (  )", "Tan (  )" });
            this.lstFunction.Location = new Point(183, 24);
            this.lstFunction.Name = "lstFunction";
            this.lstFunction.Size = new Size(162, 147);
            this.lstFunction.TabIndex = 47;
            this.lstFunction.DoubleClick += new EventHandler(this.lstFunction_DoubleClick);
            this.btnClear.Location = new Point(18, 347);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new Size(56, 24);
            this.btnClear.TabIndex = 50;
            this.btnClear.Text = "清除";
            this.btnClear.Visible = false;
            this.btnValidate.Location = new Point(82, 347);
            this.btnValidate.Name = "btnValidate";
            this.btnValidate.Size = new Size(56, 24);
            this.btnValidate.TabIndex = 51;
            this.btnValidate.Text = "验证";
            this.btnValidate.Visible = false;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(18, 182);
            this.label1.Name = "label1";
            this.label1.Size = new Size(41, 12);
            this.label1.TabIndex = 52;
            this.label1.Text = "表达式";
            this.simpleButton1.Location = new Point(313, 295);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new Size(32, 24);
            this.simpleButton1.TabIndex = 56;
            this.simpleButton1.Text = "+";
            this.simpleButton1.Click += new EventHandler(this.simpleButton4_Click);
            this.simpleButton2.Location = new Point(313, 265);
            this.simpleButton2.Name = "simpleButton2";
            this.simpleButton2.Size = new Size(32, 24);
            this.simpleButton2.TabIndex = 55;
            this.simpleButton2.Text = "-";
            this.simpleButton2.Click += new EventHandler(this.simpleButton4_Click);
            this.simpleButton3.Location = new Point(313, 233);
            this.simpleButton3.Name = "simpleButton3";
            this.simpleButton3.Size = new Size(32, 24);
            this.simpleButton3.TabIndex = 54;
            this.simpleButton3.Text = "/";
            this.simpleButton3.Click += new EventHandler(this.simpleButton4_Click);
            this.simpleButton4.Location = new Point(313, 201);
            this.simpleButton4.Name = "simpleButton4";
            this.simpleButton4.Size = new Size(32, 24);
            this.simpleButton4.TabIndex = 53;
            this.simpleButton4.Text = "*";
            this.simpleButton4.Click += new EventHandler(this.simpleButton4_Click);
            base.ClientSize = new Size(355, 376);
            base.Controls.Add(this.simpleButton1);
            base.Controls.Add(this.simpleButton2);
            base.Controls.Add(this.simpleButton3);
            base.Controls.Add(this.simpleButton4);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.btnValidate);
            base.Controls.Add(this.btnClear);
            base.Controls.Add(this.lbl);
            base.Controls.Add(this.lstFunction);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.btnIs);
            base.Controls.Add(this.btnNot);
            base.Controls.Add(this.btnBracket);
            base.Controls.Add(this.btnOr);
            base.Controls.Add(this.btnLittleEqual);
            base.Controls.Add(this.btnLittle);
            base.Controls.Add(this.btnAnd);
            base.Controls.Add(this.btnLike);
            base.Controls.Add(this.btnGreat);
            base.Controls.Add(this.btnNotEqual);
            base.Controls.Add(this.btnGreatEqual);
            base.Controls.Add(this.btnEqual);
            base.Controls.Add(this.btnClose);
            base.Controls.Add(this.btnApply);
            base.Controls.Add(this.memEditWhereCaluse);
            base.Controls.Add(this.Fieldlist);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmExpressionBuild";
            this.Text = "表达式构造器";
            base.Load += new EventHandler(this.frmExpressionBuild_Load);
            this.memEditWhereCaluse.Properties.EndInit();
            ((ISupportInitialize) this.Fieldlist).EndInit();
            ((ISupportInitialize) this.lstFunction).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private SimpleButton btnAnd;
        private SimpleButton btnApply;
        private SimpleButton btnBracket;
        private SimpleButton btnClear;
        private SimpleButton btnClose;
        private SimpleButton btnEqual;
        private SimpleButton btnGreat;
        private SimpleButton btnGreatEqual;
        private SimpleButton btnIs;
        private SimpleButton btnLike;
        private SimpleButton btnLittle;
        private SimpleButton btnLittleEqual;
        private SimpleButton btnNot;
        private SimpleButton btnNotEqual;
        private SimpleButton btnOr;
        private SimpleButton btnValidate;
        private ListBoxControl Fieldlist;
        private Label label1;
        private Label label2;
        private Label lbl;
        private ListBoxControl lstFunction;
        private MemoEdit memEditWhereCaluse;
        private SimpleButton simpleButton1;
        private SimpleButton simpleButton2;
        private SimpleButton simpleButton3;
        private SimpleButton simpleButton4;
    }
}