using System;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Windows.Forms;
using ESRI.ArcGIS.ADF;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.Geometry;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class frmExtendSet
    {
        protected override void Dispose(bool bool_0)
        {
            if (bool_0 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_0);
        }

       
        private void InitializeComponent()
        {
            this.rdoCurrentMapExtend = new RadioButton();
            this.rdoLayerExtend = new RadioButton();
            this.rdoGraphicsExtend = new RadioButton();
            this.rdoCustomExtend = new RadioButton();
            this.panelExtend = new Panel();
            this.txtRight = new TextBox();
            this.label5 = new Label();
            this.txtLeft = new TextBox();
            this.label4 = new Label();
            this.txtBottom = new TextBox();
            this.label3 = new Label();
            this.txtTop = new TextBox();
            this.label2 = new Label();
            this.panelLayer = new Panel();
            this.label6 = new Label();
            this.cboFeatures = new ComboBox();
            this.cboLayers = new ComboBox();
            this.label1 = new Label();
            this.btnOK = new Button();
            this.btnCancel = new Button();
            this.panelExtend.SuspendLayout();
            this.panelLayer.SuspendLayout();
            base.SuspendLayout();
            this.rdoCurrentMapExtend.AutoSize = true;
            this.rdoCurrentMapExtend.Checked = true;
            this.rdoCurrentMapExtend.Location = new System.Drawing.Point(13, 13);
            this.rdoCurrentMapExtend.Name = "rdoCurrentMapExtend";
            this.rdoCurrentMapExtend.Size = new Size(95, 16);
            this.rdoCurrentMapExtend.TabIndex = 0;
            this.rdoCurrentMapExtend.TabStop = true;
            this.rdoCurrentMapExtend.Text = "当前可见范围";
            this.rdoCurrentMapExtend.UseVisualStyleBackColor = true;
            this.rdoLayerExtend.AutoSize = true;
            this.rdoLayerExtend.Location = new System.Drawing.Point(13, 46);
            this.rdoLayerExtend.Name = "rdoLayerExtend";
            this.rdoLayerExtend.Size = new Size(83, 16);
            this.rdoLayerExtend.TabIndex = 1;
            this.rdoLayerExtend.Text = "要素的轮廓";
            this.rdoLayerExtend.UseVisualStyleBackColor = true;
            this.rdoLayerExtend.CheckedChanged += new EventHandler(this.rdoLayerExtend_CheckedChanged);
            this.rdoGraphicsExtend.AutoSize = true;
            this.rdoGraphicsExtend.Location = new System.Drawing.Point(12, 139);
            this.rdoGraphicsExtend.Name = "rdoGraphicsExtend";
            this.rdoGraphicsExtend.Size = new Size(107, 16);
            this.rdoGraphicsExtend.TabIndex = 2;
            this.rdoGraphicsExtend.Text = "所选图形的轮廓";
            this.rdoGraphicsExtend.UseVisualStyleBackColor = true;
            this.rdoCustomExtend.AutoSize = true;
            this.rdoCustomExtend.Location = new System.Drawing.Point(13, 161);
            this.rdoCustomExtend.Name = "rdoCustomExtend";
            this.rdoCustomExtend.Size = new Size(107, 16);
            this.rdoCustomExtend.TabIndex = 3;
            this.rdoCustomExtend.Text = "自定义数据范围";
            this.rdoCustomExtend.UseVisualStyleBackColor = true;
            this.rdoCustomExtend.CheckedChanged += new EventHandler(this.rdoCustomExtend_CheckedChanged);
            this.panelExtend.Controls.Add(this.txtRight);
            this.panelExtend.Controls.Add(this.label5);
            this.panelExtend.Controls.Add(this.txtLeft);
            this.panelExtend.Controls.Add(this.label4);
            this.panelExtend.Controls.Add(this.txtBottom);
            this.panelExtend.Controls.Add(this.label3);
            this.panelExtend.Controls.Add(this.txtTop);
            this.panelExtend.Controls.Add(this.label2);
            this.panelExtend.Enabled = false;
            this.panelExtend.Location = new System.Drawing.Point(24, 195);
            this.panelExtend.Name = "panelExtend";
            this.panelExtend.Size = new Size(356, 83);
            this.panelExtend.TabIndex = 4;
            this.txtRight.Location = new System.Drawing.Point(205, 32);
            this.txtRight.Name = "txtRight";
            this.txtRight.Size = new Size(117, 21);
            this.txtRight.TabIndex = 8;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(182, 35);
            this.label5.Name = "label5";
            this.label5.Size = new Size(17, 12);
            this.label5.TabIndex = 7;
            this.label5.Text = "右";
            this.txtLeft.Location = new System.Drawing.Point(44, 32);
            this.txtLeft.Name = "txtLeft";
            this.txtLeft.Size = new Size(129, 21);
            this.txtLeft.TabIndex = 6;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(21, 35);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 12);
            this.label4.TabIndex = 5;
            this.label4.Text = "左";
            this.txtBottom.Location = new System.Drawing.Point(126, 59);
            this.txtBottom.Name = "txtBottom";
            this.txtBottom.Size = new Size(100, 21);
            this.txtBottom.TabIndex = 4;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(103, 62);
            this.label3.Name = "label3";
            this.label3.Size = new Size(17, 12);
            this.label3.TabIndex = 3;
            this.label3.Text = "下";
            this.txtTop.Location = new System.Drawing.Point(126, 3);
            this.txtTop.Name = "txtTop";
            this.txtTop.Size = new Size(100, 21);
            this.txtTop.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(103, 6);
            this.label2.Name = "label2";
            this.label2.Size = new Size(17, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "上";
            this.panelLayer.Controls.Add(this.label6);
            this.panelLayer.Controls.Add(this.cboFeatures);
            this.panelLayer.Controls.Add(this.cboLayers);
            this.panelLayer.Controls.Add(this.label1);
            this.panelLayer.Enabled = false;
            this.panelLayer.Location = new System.Drawing.Point(24, 69);
            this.panelLayer.Name = "panelLayer";
            this.panelLayer.Size = new Size(384, 55);
            this.panelLayer.TabIndex = 5;
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(236, 4);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 12);
            this.label6.TabIndex = 3;
            this.label6.Text = "要素";
            this.cboFeatures.FormattingEnabled = true;
            this.cboFeatures.Items.AddRange(new object[] { "全部", "可见" });
            this.cboFeatures.Location = new System.Drawing.Point(238, 23);
            this.cboFeatures.Name = "cboFeatures";
            this.cboFeatures.Size = new Size(130, 20);
            this.cboFeatures.TabIndex = 2;
            this.cboLayers.FormattingEnabled = true;
            this.cboLayers.Location = new System.Drawing.Point(11, 23);
            this.cboLayers.Name = "cboLayers";
            this.cboLayers.Size = new Size(198, 20);
            this.cboLayers.TabIndex = 1;
            this.cboLayers.SelectedIndexChanged += new EventHandler(this.cboLayers_SelectedIndexChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(9, 4);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "图层";
            this.btnOK.Location = new System.Drawing.Point(229, 302);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(75, 23);
            this.btnOK.TabIndex = 6;
            this.btnOK.Text = "确定";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.Location = new System.Drawing.Point(317, 302);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(75, 23);
            this.btnCancel.TabIndex = 7;
            this.btnCancel.Text = "取消";
            this.btnCancel.UseVisualStyleBackColor = true;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(419, 344);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.panelLayer);
            base.Controls.Add(this.panelExtend);
            base.Controls.Add(this.rdoCustomExtend);
            base.Controls.Add(this.rdoGraphicsExtend);
            base.Controls.Add(this.rdoLayerExtend);
            base.Controls.Add(this.rdoCurrentMapExtend);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmExtendSet";
            base.Load += new EventHandler(this.frmExtendSet_Load);
            this.panelExtend.ResumeLayout(false);
            this.panelExtend.PerformLayout();
            this.panelLayer.ResumeLayout(false);
            this.panelLayer.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private Button btnCancel;
        private Button btnOK;
        private ComboBox cboFeatures;
        private ComboBox cboLayers;
        private ExtendSetType extendSetType_0;
        private IBasicMap ibasicMap_0;
        private IEnvelope ienvelope_0;
        private IGeometry igeometry_0;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Panel panelExtend;
        private Panel panelLayer;
        private RadioButton rdoCurrentMapExtend;
        private RadioButton rdoCustomExtend;
        private RadioButton rdoGraphicsExtend;
        private RadioButton rdoLayerExtend;
        private TextBox txtBottom;
        private TextBox txtLeft;
        private TextBox txtRight;
        private TextBox txtTop;
    }
}