using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.Carto;
using Yutai.ArcGIS.Common.Symbol;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using Yutai.Shared;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class frmOutline
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmOutline));
            this.groupBox1 = new GroupBox();
            this.rdoPlacePageMargine = new RadioButton();
            this.rdoPlaceAllElement = new RadioButton();
            this.rdoPlaceSelectElement = new RadioButton();
            this.txtRound = new SpinEdit();
            this.txtGap = new SpinEdit();
            this.label2 = new Label();
            this.label1 = new Label();
            this.chkGroup = new CheckEdit();
            this.chkNewFrameElement = new CheckEdit();
            this.imageList_0 = new ImageList(this.icontainer_0);
            this.groupBox2 = new GroupBox();
            this.btnBorderInfo = new SimpleButton();
            this.btnBorderSelector = new SimpleButton();
            this.cboBorder = new StyleComboBox(this.icontainer_0);
            this.groupBox3 = new GroupBox();
            this.btnBackgroundInfo = new SimpleButton();
            this.btnBackgroundSelector = new SimpleButton();
            this.cboBackground = new StyleComboBox(this.icontainer_0);
            this.groupBox4 = new GroupBox();
            this.btnshadowInfo = new SimpleButton();
            this.btnShadowSelector = new SimpleButton();
            this.cboShadow = new StyleComboBox(this.icontainer_0);
            this.btnOK = new SimpleButton();
            this.btnCancel = new SimpleButton();
            this.groupBox1.SuspendLayout();
            this.txtRound.Properties.BeginInit();
            this.txtGap.Properties.BeginInit();
            this.chkGroup.Properties.BeginInit();
            this.chkNewFrameElement.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.rdoPlacePageMargine);
            this.groupBox1.Controls.Add(this.rdoPlaceAllElement);
            this.groupBox1.Controls.Add(this.rdoPlaceSelectElement);
            this.groupBox1.Controls.Add(this.txtRound);
            this.groupBox1.Controls.Add(this.txtGap);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.chkGroup);
            this.groupBox1.Controls.Add(this.chkNewFrameElement);
            this.groupBox1.Location = new System.Drawing.Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(200, 200);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "放置";
            this.rdoPlacePageMargine.Location = new System.Drawing.Point(8, 64);
            this.rdoPlacePageMargine.Name = "rdoPlacePageMargine";
            this.rdoPlacePageMargine.Size = new Size(112, 24);
            this.rdoPlacePageMargine.TabIndex = 49;
            this.rdoPlacePageMargine.Text = "放在页边距内";
            this.rdoPlacePageMargine.CheckedChanged += new EventHandler(this.rdoPlacePageMargine_CheckedChanged);
            this.rdoPlaceAllElement.Location = new System.Drawing.Point(8, 40);
            this.rdoPlaceAllElement.Name = "rdoPlaceAllElement";
            this.rdoPlaceAllElement.Size = new Size(168, 24);
            this.rdoPlaceAllElement.TabIndex = 48;
            this.rdoPlaceAllElement.Text = "沿所有元素的周边放置";
            this.rdoPlaceAllElement.CheckedChanged += new EventHandler(this.rdoPlaceAllElement_CheckedChanged);
            this.rdoPlaceSelectElement.Location = new System.Drawing.Point(8, 16);
            this.rdoPlaceSelectElement.Name = "rdoPlaceSelectElement";
            this.rdoPlaceSelectElement.Size = new Size(160, 24);
            this.rdoPlaceSelectElement.TabIndex = 46;
            this.rdoPlaceSelectElement.Text = "沿选中元素周边放置";
            this.rdoPlaceSelectElement.CheckedChanged += new EventHandler(this.rdoPlaceSelectElement_CheckedChanged);
            int[] bits = new int[4];
            this.txtRound.EditValue = new decimal(bits);
            this.txtRound.Location = new System.Drawing.Point(112, 167);
            this.txtRound.Name = "txtRound";
            this.txtRound.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtRound.Size = new Size(48, 21);
            this.txtRound.TabIndex = 6;
            int[] bits2 = new int[4];
            bits2[0] = 10;
            this.txtGap.EditValue = new decimal(bits2);
            this.txtGap.Location = new System.Drawing.Point(16, 167);
            this.txtGap.Name = "txtGap";
            this.txtGap.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtGap.Size = new Size(48, 21);
            this.txtGap.TabIndex = 5;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(112, 145);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 12);
            this.label2.TabIndex = 4;
            this.label2.Text = "圆角";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(16, 145);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 12);
            this.label1.TabIndex = 3;
            this.label1.Text = "间隔";
            this.chkGroup.Location = new System.Drawing.Point(8, 112);
            this.chkGroup.Name = "chkGroup";
            this.chkGroup.Properties.Caption = "将边框和元素合并";
            this.chkGroup.Size = new Size(152, 19);
            this.chkGroup.TabIndex = 2;
            this.chkNewFrameElement.Location = new System.Drawing.Point(8, 88);
            this.chkNewFrameElement.Name = "chkNewFrameElement";
            this.chkNewFrameElement.Properties.Caption = "创建单独的边框元素";
            this.chkNewFrameElement.Size = new Size(144, 19);
            this.chkNewFrameElement.TabIndex = 1;
            this.chkNewFrameElement.CheckedChanged += new EventHandler(this.chkNewFrameElement_CheckedChanged);
            this.imageList_0.ImageStream = (ImageListStreamer)resources.GetObject("imageList1.ImageStream");
            this.imageList_0.TransparentColor = Color.Transparent;
            this.imageList_0.Images.SetKeyName(0, "");
            this.imageList_0.Images.SetKeyName(1, "");
            this.groupBox2.Controls.Add(this.btnBorderInfo);
            this.groupBox2.Controls.Add(this.btnBorderSelector);
            this.groupBox2.Controls.Add(this.cboBorder);
            this.groupBox2.Location = new System.Drawing.Point(216, 8);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(280, 60);
            this.groupBox2.TabIndex = 40;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "边框";
            this.btnBorderInfo.Appearance.BackColor = SystemColors.Window;
            this.btnBorderInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBorderInfo.Appearance.Options.UseBackColor = true;
            this.btnBorderInfo.Appearance.Options.UseForeColor = true;
            this.btnBorderInfo.ButtonStyle = BorderStyles.Simple;
            this.btnBorderInfo.ImageIndex = 1;
            this.btnBorderInfo.ImageList = this.imageList_0;
            this.btnBorderInfo.Location = new System.Drawing.Point(252, 36);
            this.btnBorderInfo.Name = "btnBorderInfo";
            this.btnBorderInfo.Size = new Size(16, 16);
            this.btnBorderInfo.TabIndex = 33;
            this.btnBorderInfo.Click += new EventHandler(this.btnBorderInfo_Click);
            this.btnBorderSelector.Appearance.BackColor = SystemColors.Window;
            this.btnBorderSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBorderSelector.Appearance.Options.UseBackColor = true;
            this.btnBorderSelector.Appearance.Options.UseForeColor = true;
            this.btnBorderSelector.ButtonStyle = BorderStyles.Simple;
            this.btnBorderSelector.ImageIndex = 0;
            this.btnBorderSelector.ImageList = this.imageList_0;
            this.btnBorderSelector.Location = new System.Drawing.Point(252, 20);
            this.btnBorderSelector.Name = "btnBorderSelector";
            this.btnBorderSelector.Size = new Size(16, 16);
            this.btnBorderSelector.TabIndex = 32;
            this.btnBorderSelector.Click += new EventHandler(this.btnBorderSelector_Click);
            this.cboBorder.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboBorder.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboBorder.DropDownWidth = 160;
            this.cboBorder.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboBorder.Location = new System.Drawing.Point(12, 20);
            this.cboBorder.Name = "cboBorder";
            this.cboBorder.Size = new Size(240, 31);
            this.cboBorder.TabIndex = 31;
            this.groupBox3.Controls.Add(this.btnBackgroundInfo);
            this.groupBox3.Controls.Add(this.btnBackgroundSelector);
            this.groupBox3.Controls.Add(this.cboBackground);
            this.groupBox3.Location = new System.Drawing.Point(216, 78);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(280, 60);
            this.groupBox3.TabIndex = 41;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "背景";
            this.btnBackgroundInfo.Appearance.BackColor = SystemColors.Window;
            this.btnBackgroundInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBackgroundInfo.Appearance.Options.UseBackColor = true;
            this.btnBackgroundInfo.Appearance.Options.UseForeColor = true;
            this.btnBackgroundInfo.ButtonStyle = BorderStyles.Simple;
            this.btnBackgroundInfo.ImageIndex = 1;
            this.btnBackgroundInfo.ImageList = this.imageList_0;
            this.btnBackgroundInfo.Location = new System.Drawing.Point(252, 34);
            this.btnBackgroundInfo.Name = "btnBackgroundInfo";
            this.btnBackgroundInfo.Size = new Size(16, 16);
            this.btnBackgroundInfo.TabIndex = 39;
            this.btnBackgroundInfo.Click += new EventHandler(this.btnBackgroundInfo_Click);
            this.btnBackgroundSelector.Appearance.BackColor = SystemColors.Window;
            this.btnBackgroundSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBackgroundSelector.Appearance.Options.UseBackColor = true;
            this.btnBackgroundSelector.Appearance.Options.UseForeColor = true;
            this.btnBackgroundSelector.ButtonStyle = BorderStyles.Simple;
            this.btnBackgroundSelector.ImageIndex = 0;
            this.btnBackgroundSelector.ImageList = this.imageList_0;
            this.btnBackgroundSelector.Location = new System.Drawing.Point(252, 18);
            this.btnBackgroundSelector.Name = "btnBackgroundSelector";
            this.btnBackgroundSelector.Size = new Size(16, 16);
            this.btnBackgroundSelector.TabIndex = 38;
            this.btnBackgroundSelector.Click += new EventHandler(this.btnBackgroundSelector_Click);
            this.cboBackground.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboBackground.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboBackground.DropDownWidth = 160;
            this.cboBackground.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboBackground.Location = new System.Drawing.Point(12, 18);
            this.cboBackground.Name = "cboBackground";
            this.cboBackground.Size = new Size(240, 31);
            this.cboBackground.TabIndex = 37;
            this.groupBox4.Controls.Add(this.btnshadowInfo);
            this.groupBox4.Controls.Add(this.btnShadowSelector);
            this.groupBox4.Controls.Add(this.cboShadow);
            this.groupBox4.Location = new System.Drawing.Point(216, 148);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(280, 60);
            this.groupBox4.TabIndex = 42;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "阴影";
            this.btnshadowInfo.Appearance.BackColor = SystemColors.Window;
            this.btnshadowInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnshadowInfo.Appearance.Options.UseBackColor = true;
            this.btnshadowInfo.Appearance.Options.UseForeColor = true;
            this.btnshadowInfo.ButtonStyle = BorderStyles.Simple;
            this.btnshadowInfo.ImageIndex = 1;
            this.btnshadowInfo.ImageList = this.imageList_0;
            this.btnshadowInfo.Location = new System.Drawing.Point(252, 32);
            this.btnshadowInfo.Name = "btnshadowInfo";
            this.btnshadowInfo.Size = new Size(16, 16);
            this.btnshadowInfo.TabIndex = 42;
            this.btnshadowInfo.Click += new EventHandler(this.btnshadowInfo_Click);
            this.btnShadowSelector.Appearance.BackColor = SystemColors.Window;
            this.btnShadowSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnShadowSelector.Appearance.Options.UseBackColor = true;
            this.btnShadowSelector.Appearance.Options.UseForeColor = true;
            this.btnShadowSelector.ButtonStyle = BorderStyles.Simple;
            this.btnShadowSelector.ImageIndex = 0;
            this.btnShadowSelector.ImageList = this.imageList_0;
            this.btnShadowSelector.Location = new System.Drawing.Point(252, 16);
            this.btnShadowSelector.Name = "btnShadowSelector";
            this.btnShadowSelector.Size = new Size(16, 16);
            this.btnShadowSelector.TabIndex = 41;
            this.btnShadowSelector.Click += new EventHandler(this.btnShadowSelector_Click);
            this.cboShadow.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboShadow.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboShadow.DropDownWidth = 160;
            this.cboShadow.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboShadow.Location = new System.Drawing.Point(12, 16);
            this.cboShadow.Name = "cboShadow";
            this.cboShadow.Size = new Size(240, 31);
            this.cboShadow.TabIndex = 40;
            this.btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnOK.Location = new System.Drawing.Point(352, 216);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(56, 24);
            this.btnOK.TabIndex = 43;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new System.Drawing.Point(424, 216);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(56, 24);
            this.btnCancel.TabIndex = 44;
            this.btnCancel.Text = "取消";
            this.AutoScaleBaseSize = new Size(6, 14);
            base.ClientSize = new Size(504, 261);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            
            base.Name = "frmOutline";
            this.Text = "轮廓线";
            base.Load += new EventHandler(this.frmOutline_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.txtRound.Properties.EndInit();
            this.txtGap.Properties.EndInit();
            this.chkGroup.Properties.EndInit();
            this.chkNewFrameElement.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnBackgroundInfo;
        private SimpleButton btnBackgroundSelector;
        private SimpleButton btnBorderInfo;
        private SimpleButton btnBorderSelector;
        private SimpleButton btnCancel;
        private SimpleButton btnOK;
        private SimpleButton btnshadowInfo;
        private SimpleButton btnShadowSelector;
        private StyleComboBox cboBackground;
        private StyleComboBox cboBorder;
        private StyleComboBox cboShadow;
        private CheckEdit chkGroup;
        private CheckEdit chkNewFrameElement;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private IContainer icontainer_0;
        private ImageList imageList_0;
        private Label label1;
        private Label label2;
        private RadioButton rdoPlaceAllElement;
        private RadioButton rdoPlacePageMargine;
        private RadioButton rdoPlaceSelectElement;
        private SpinEdit txtGap;
        private SpinEdit txtRound;
    }
}