using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Output;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class frmPageAndPrinterSetup
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPageAndPrinterSetup));
            this.panel1 = new Panel();
            this.groupBox1 = new GroupBox();
            this.checkBox_usePrinterPageSize = new CheckBox();
            this.groupBox2 = new GroupBox();
            this.label11 = new Label();
            this.optLandscape = new RadioButton();
            this.optPortrait = new RadioButton();
            this.lblInfo = new Label();
            this.label10 = new Label();
            this.label9 = new Label();
            this.txtPageHeight = new TextBox();
            this.label7 = new Label();
            this.txtPageWidth = new TextBox();
            this.label4 = new Label();
            this.cboPageSize = new ComboBox();
            this.fraPrinter = new GroupBox();
            this.button_printerAttribute = new Button();
            this.comboBox_printer = new ComboBox();
            this.lblPrinterOrientation = new Label();
            this.lblPrinterName = new Label();
            this.lblPrinterSize = new Label();
            this.frmPaper = new GroupBox();
            this.cboPaperTrays = new ComboBox();
            this.label12 = new Label();
            this.optPaperLandscape = new RadioButton();
            this.label13 = new Label();
            this.optPaperPortrait = new RadioButton();
            this.cboPrinterPageSize = new ComboBox();
            this.label3 = new Label();
            this.printDialog_0 = new PrintDialog();
            this.cmdPrint = new Button();
            this.cmdCancel = new Button();
            this.cboPageToPrinterMapping = new ComboBox();
            this.Label8 = new Label();
            this.panel1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.fraPrinter.SuspendLayout();
            this.frmPaper.SuspendLayout();
            base.SuspendLayout();
            this.panel1.Controls.Add(this.groupBox1);
            this.panel1.Controls.Add(this.fraPrinter);
            this.panel1.Controls.Add(this.frmPaper);
            this.panel1.Location = new Point(5, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(438, 445);
            this.panel1.TabIndex = 23;
            this.groupBox1.Controls.Add(this.cboPageToPrinterMapping);
            this.groupBox1.Controls.Add(this.Label8);
            this.groupBox1.Controls.Add(this.checkBox_usePrinterPageSize);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Location = new Point(10, 253);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(417, 189);
            this.groupBox1.TabIndex = 26;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "地图页面设置";
            this.checkBox_usePrinterPageSize.Checked = true;
            this.checkBox_usePrinterPageSize.CheckState = CheckState.Checked;
            this.checkBox_usePrinterPageSize.Location = new Point(12, 25);
            this.checkBox_usePrinterPageSize.Name = "checkBox_usePrinterPageSize";
            this.checkBox_usePrinterPageSize.Size = new Size(137, 19);
            this.checkBox_usePrinterPageSize.TabIndex = 28;
            this.checkBox_usePrinterPageSize.Text = "使用打印机纸张设置";
            this.checkBox_usePrinterPageSize.Click += new EventHandler(this.checkBox_usePrinterPageSize_Click);
            this.checkBox_usePrinterPageSize.CheckedChanged += new EventHandler(this.checkBox_usePrinterPageSize_CheckedChanged);
            this.groupBox2.Controls.Add(this.label11);
            this.groupBox2.Controls.Add(this.optLandscape);
            this.groupBox2.Controls.Add(this.optPortrait);
            this.groupBox2.Controls.Add(this.lblInfo);
            this.groupBox2.Controls.Add(this.label10);
            this.groupBox2.Controls.Add(this.label9);
            this.groupBox2.Controls.Add(this.txtPageHeight);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.txtPageWidth);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.cboPageSize);
            this.groupBox2.Location = new Point(10, 51);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(386, 128);
            this.groupBox2.TabIndex = 0;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "页面";
            this.label11.AutoSize = true;
            this.label11.BackColor = SystemColors.Control;
            this.label11.Cursor = Cursors.Default;
            this.label11.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label11.ForeColor = SystemColors.ControlText;
            this.label11.Location = new Point(10, 106);
            this.label11.Name = "label11";
            this.label11.RightToLeft = RightToLeft.No;
            this.label11.Size = new Size(34, 14);
            this.label11.TabIndex = 41;
            this.label11.Text = "方向:";
            this.optLandscape.BackColor = SystemColors.Control;
            this.optLandscape.Cursor = Cursors.Default;
            this.optLandscape.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.optLandscape.ForeColor = SystemColors.ControlText;
            this.optLandscape.Location = new Point(155, 102);
            this.optLandscape.Name = "optLandscape";
            this.optLandscape.RightToLeft = RightToLeft.No;
            this.optLandscape.Size = new Size(50, 23);
            this.optLandscape.TabIndex = 40;
            this.optLandscape.TabStop = true;
            this.optLandscape.Text = "垂直";
            this.optLandscape.UseVisualStyleBackColor = false;
            this.optLandscape.Click += new EventHandler(this.optLandscape_Click);
            this.optPortrait.BackColor = SystemColors.Control;
            this.optPortrait.Cursor = Cursors.Default;
            this.optPortrait.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.optPortrait.ForeColor = SystemColors.ControlText;
            this.optPortrait.Location = new Point(79, 102);
            this.optPortrait.Name = "optPortrait";
            this.optPortrait.RightToLeft = RightToLeft.No;
            this.optPortrait.Size = new Size(50, 23);
            this.optPortrait.TabIndex = 39;
            this.optPortrait.TabStop = true;
            this.optPortrait.Text = "水平";
            this.optPortrait.UseVisualStyleBackColor = false;
            this.optPortrait.Click += new EventHandler(this.optPortrait_Click);
            this.lblInfo.AutoSize = true;
            this.lblInfo.BackColor = SystemColors.Control;
            this.lblInfo.Cursor = Cursors.Default;
            this.lblInfo.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblInfo.ForeColor = SystemColors.ControlText;
            this.lblInfo.Location = new Point(11, 21);
            this.lblInfo.Name = "lblInfo";
            this.lblInfo.RightToLeft = RightToLeft.No;
            this.lblInfo.Size = new Size(58, 14);
            this.lblInfo.TabIndex = 38;
            this.lblInfo.Text = "标准尺寸:";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(212, 47);
            this.label10.Name = "label10";
            this.label10.Size = new Size(29, 12);
            this.label10.TabIndex = 37;
            this.label10.Text = "厘米";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(212, 74);
            this.label9.Name = "label9";
            this.label9.Size = new Size(29, 12);
            this.label9.TabIndex = 36;
            this.label9.Text = "厘米";
            this.txtPageHeight.Location = new Point(73, 71);
            this.txtPageHeight.Name = "txtPageHeight";
            this.txtPageHeight.Size = new Size(135, 21);
            this.txtPageHeight.TabIndex = 35;
            this.txtPageHeight.TextChanged += new EventHandler(this.txtPageHeight_TextChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(11, 74);
            this.label7.Name = "label7";
            this.label7.Size = new Size(23, 12);
            this.label7.TabIndex = 34;
            this.label7.Text = "高:";
            this.txtPageWidth.Location = new Point(73, 45);
            this.txtPageWidth.Name = "txtPageWidth";
            this.txtPageWidth.Size = new Size(135, 21);
            this.txtPageWidth.TabIndex = 33;
            this.txtPageWidth.TextChanged += new EventHandler(this.txtPageWidth_TextChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(11, 47);
            this.label4.Name = "label4";
            this.label4.Size = new Size(23, 12);
            this.label4.TabIndex = 32;
            this.label4.Text = "宽:";
            this.cboPageSize.BackColor = SystemColors.Window;
            this.cboPageSize.Cursor = Cursors.Default;
            this.cboPageSize.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboPageSize.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cboPageSize.ForeColor = SystemColors.WindowText;
            this.cboPageSize.Location = new Point(73, 17);
            this.cboPageSize.Name = "cboPageSize";
            this.cboPageSize.RightToLeft = RightToLeft.No;
            this.cboPageSize.Size = new Size(169, 22);
            this.cboPageSize.TabIndex = 31;
            this.cboPageSize.SelectedIndexChanged += new EventHandler(this.cboPageSize_SelectedIndexChanged);
            this.fraPrinter.BackColor = SystemColors.Control;
            this.fraPrinter.Controls.Add(this.button_printerAttribute);
            this.fraPrinter.Controls.Add(this.comboBox_printer);
            this.fraPrinter.Controls.Add(this.lblPrinterOrientation);
            this.fraPrinter.Controls.Add(this.lblPrinterName);
            this.fraPrinter.Controls.Add(this.lblPrinterSize);
            this.fraPrinter.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.fraPrinter.ForeColor = SystemColors.ControlText;
            this.fraPrinter.Location = new Point(10, 12);
            this.fraPrinter.Name = "fraPrinter";
            this.fraPrinter.RightToLeft = RightToLeft.No;
            this.fraPrinter.Size = new Size(417, 132);
            this.fraPrinter.TabIndex = 23;
            this.fraPrinter.TabStop = false;
            this.fraPrinter.Text = "打印机信息：";
            this.button_printerAttribute.Location = new Point(345, 21);
            this.button_printerAttribute.Name = "button_printerAttribute";
            this.button_printerAttribute.Size = new Size(52, 23);
            this.button_printerAttribute.TabIndex = 26;
            this.button_printerAttribute.Text = "属性";
            this.button_printerAttribute.Click += new EventHandler(this.button_printerAttribute_Click);
            this.comboBox_printer.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox_printer.Location = new Point(71, 22);
            this.comboBox_printer.Name = "comboBox_printer";
            this.comboBox_printer.Size = new Size(268, 22);
            this.comboBox_printer.TabIndex = 25;
            this.comboBox_printer.SelectedIndexChanged += new EventHandler(this.comboBox_printer_SelectedIndexChanged);
            this.lblPrinterOrientation.BackColor = SystemColors.Control;
            this.lblPrinterOrientation.Cursor = Cursors.Default;
            this.lblPrinterOrientation.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPrinterOrientation.ForeColor = SystemColors.ControlText;
            this.lblPrinterOrientation.Location = new Point(10, 81);
            this.lblPrinterOrientation.Name = "lblPrinterOrientation";
            this.lblPrinterOrientation.RightToLeft = RightToLeft.No;
            this.lblPrinterOrientation.Size = new Size(216, 19);
            this.lblPrinterOrientation.TabIndex = 24;
            this.lblPrinterOrientation.Text = "纸张方向：";
            this.lblPrinterName.AutoSize = true;
            this.lblPrinterName.BackColor = SystemColors.Control;
            this.lblPrinterName.Cursor = Cursors.Default;
            this.lblPrinterName.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPrinterName.ForeColor = SystemColors.ControlText;
            this.lblPrinterName.Location = new Point(10, 26);
            this.lblPrinterName.Name = "lblPrinterName";
            this.lblPrinterName.RightToLeft = RightToLeft.No;
            this.lblPrinterName.Size = new Size(64, 14);
            this.lblPrinterName.TabIndex = 3;
            this.lblPrinterName.Text = "名       称：";
            this.lblPrinterSize.BackColor = SystemColors.Control;
            this.lblPrinterSize.Cursor = Cursors.Default;
            this.lblPrinterSize.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPrinterSize.ForeColor = SystemColors.ControlText;
            this.lblPrinterSize.Location = new Point(8, 55);
            this.lblPrinterSize.Name = "lblPrinterSize";
            this.lblPrinterSize.RightToLeft = RightToLeft.No;
            this.lblPrinterSize.Size = new Size(216, 18);
            this.lblPrinterSize.TabIndex = 1;
            this.lblPrinterSize.Text = "纸张大小：";
            this.frmPaper.BackColor = SystemColors.Control;
            this.frmPaper.Controls.Add(this.cboPaperTrays);
            this.frmPaper.Controls.Add(this.label12);
            this.frmPaper.Controls.Add(this.optPaperLandscape);
            this.frmPaper.Controls.Add(this.label13);
            this.frmPaper.Controls.Add(this.optPaperPortrait);
            this.frmPaper.Controls.Add(this.cboPrinterPageSize);
            this.frmPaper.Controls.Add(this.label3);
            this.frmPaper.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.frmPaper.ForeColor = SystemColors.ControlText;
            this.frmPaper.Location = new Point(10, 149);
            this.frmPaper.Name = "frmPaper";
            this.frmPaper.RightToLeft = RightToLeft.No;
            this.frmPaper.Size = new Size(417, 97);
            this.frmPaper.TabIndex = 22;
            this.frmPaper.TabStop = false;
            this.frmPaper.Text = "纸张";
            this.cboPaperTrays.BackColor = SystemColors.Window;
            this.cboPaperTrays.Cursor = Cursors.Default;
            this.cboPaperTrays.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboPaperTrays.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cboPaperTrays.ForeColor = SystemColors.WindowText;
            this.cboPaperTrays.Location = new Point(74, 42);
            this.cboPaperTrays.Name = "cboPaperTrays";
            this.cboPaperTrays.RightToLeft = RightToLeft.No;
            this.cboPaperTrays.Size = new Size(178, 22);
            this.cboPaperTrays.TabIndex = 43;
            this.cboPaperTrays.SelectedIndexChanged += new EventHandler(this.cboPaperTrays_SelectedIndexChanged);
            this.label12.AutoSize = true;
            this.label12.BackColor = SystemColors.Control;
            this.label12.Cursor = Cursors.Default;
            this.label12.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label12.ForeColor = SystemColors.ControlText;
            this.label12.Location = new Point(10, 72);
            this.label12.Name = "label12";
            this.label12.RightToLeft = RightToLeft.No;
            this.label12.Size = new Size(34, 14);
            this.label12.TabIndex = 46;
            this.label12.Text = "方向:";
            this.optPaperLandscape.BackColor = SystemColors.Control;
            this.optPaperLandscape.Cursor = Cursors.Default;
            this.optPaperLandscape.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.optPaperLandscape.ForeColor = SystemColors.ControlText;
            this.optPaperLandscape.Location = new Point(153, 68);
            this.optPaperLandscape.Name = "optPaperLandscape";
            this.optPaperLandscape.RightToLeft = RightToLeft.No;
            this.optPaperLandscape.Size = new Size(50, 23);
            this.optPaperLandscape.TabIndex = 45;
            this.optPaperLandscape.TabStop = true;
            this.optPaperLandscape.Text = "垂直";
            this.optPaperLandscape.UseVisualStyleBackColor = false;
            this.optPaperLandscape.Click += new EventHandler(this.optPaperLandscape_Click);
            this.label13.AutoSize = true;
            this.label13.BackColor = SystemColors.Control;
            this.label13.Cursor = Cursors.Default;
            this.label13.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label13.ForeColor = SystemColors.ControlText;
            this.label13.Location = new Point(10, 42);
            this.label13.Name = "label13";
            this.label13.RightToLeft = RightToLeft.No;
            this.label13.Size = new Size(58, 14);
            this.label13.TabIndex = 42;
            this.label13.Text = "纸张来源:";
            this.optPaperPortrait.BackColor = SystemColors.Control;
            this.optPaperPortrait.Cursor = Cursors.Default;
            this.optPaperPortrait.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.optPaperPortrait.ForeColor = SystemColors.ControlText;
            this.optPaperPortrait.Location = new Point(75, 68);
            this.optPaperPortrait.Name = "optPaperPortrait";
            this.optPaperPortrait.RightToLeft = RightToLeft.No;
            this.optPaperPortrait.Size = new Size(50, 23);
            this.optPaperPortrait.TabIndex = 44;
            this.optPaperPortrait.TabStop = true;
            this.optPaperPortrait.Text = "水平";
            this.optPaperPortrait.UseVisualStyleBackColor = false;
            this.optPaperPortrait.Click += new EventHandler(this.optPaperPortrait_Click);
            this.cboPrinterPageSize.BackColor = SystemColors.Window;
            this.cboPrinterPageSize.Cursor = Cursors.Default;
            this.cboPrinterPageSize.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboPrinterPageSize.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cboPrinterPageSize.ForeColor = SystemColors.WindowText;
            this.cboPrinterPageSize.Location = new Point(74, 16);
            this.cboPrinterPageSize.Name = "cboPrinterPageSize";
            this.cboPrinterPageSize.RightToLeft = RightToLeft.No;
            this.cboPrinterPageSize.Size = new Size(178, 22);
            this.cboPrinterPageSize.TabIndex = 24;
            this.cboPrinterPageSize.SelectedIndexChanged += new EventHandler(this.cboPrinterPageSize_SelectedIndexChanged);
            this.label3.AutoSize = true;
            this.label3.BackColor = SystemColors.Control;
            this.label3.Cursor = Cursors.Default;
            this.label3.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label3.ForeColor = SystemColors.ControlText;
            this.label3.Location = new Point(10, 18);
            this.label3.Name = "label3";
            this.label3.RightToLeft = RightToLeft.No;
            this.label3.Size = new Size(34, 14);
            this.label3.TabIndex = 23;
            this.label3.Text = "纸型:";
            this.cmdPrint.BackColor = SystemColors.Control;
            this.cmdPrint.Cursor = Cursors.Default;
            this.cmdPrint.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cmdPrint.ForeColor = SystemColors.ControlText;
            this.cmdPrint.Location = new Point(279, 451);
            this.cmdPrint.Name = "cmdPrint";
            this.cmdPrint.RightToLeft = RightToLeft.No;
            this.cmdPrint.Size = new Size(75, 23);
            this.cmdPrint.TabIndex = 24;
            this.cmdPrint.Text = "确定";
            this.cmdPrint.UseVisualStyleBackColor = false;
            this.cmdPrint.Click += new EventHandler(this.cmdPrint_Click);
            this.cmdCancel.Location = new Point(357, 451);
            this.cmdCancel.Name = "cmdCancel";
            this.cmdCancel.Size = new Size(75, 23);
            this.cmdCancel.TabIndex = 25;
            this.cmdCancel.Text = "取消";
            this.cmdCancel.Click += new EventHandler(this.cmdCancel_Click);
            this.cboPageToPrinterMapping.BackColor = SystemColors.Window;
            this.cboPageToPrinterMapping.Cursor = Cursors.Default;
            this.cboPageToPrinterMapping.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboPageToPrinterMapping.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cboPageToPrinterMapping.ForeColor = SystemColors.WindowText;
            this.cboPageToPrinterMapping.Location = new Point(284, 23);
            this.cboPageToPrinterMapping.Name = "cboPageToPrinterMapping";
            this.cboPageToPrinterMapping.RightToLeft = RightToLeft.No;
            this.cboPageToPrinterMapping.Size = new Size(113, 22);
            this.cboPageToPrinterMapping.TabIndex = 32;
            this.cboPageToPrinterMapping.SelectedIndexChanged += new EventHandler(this.cboPageToPrinterMapping_SelectedIndexChanged);
            this.Label8.AutoSize = true;
            this.Label8.BackColor = SystemColors.Control;
            this.Label8.Cursor = Cursors.Default;
            this.Label8.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Label8.ForeColor = SystemColors.ControlText;
            this.Label8.Location = new Point(162, 25);
            this.Label8.Name = "Label8";
            this.Label8.RightToLeft = RightToLeft.No;
            this.Label8.Size = new Size(118, 14);
            this.Label8.TabIndex = 31;
            this.Label8.Text = "页面到纸张映射模式:";
            this.AutoScaleBaseSize = new Size(6, 14);
            base.ClientSize = new Size(454, 486);
            base.Controls.Add(this.cmdCancel);
            base.Controls.Add(this.cmdPrint);
            base.Controls.Add(this.panel1);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Icon = (Icon)resources.GetObject("$this.Icon");
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmPageAndPrinterSetup";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "打印设置窗口";
            base.Load += new EventHandler(this.frmPageAndPrinterSetup_Load);
            this.panel1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.fraPrinter.ResumeLayout(false);
            this.fraPrinter.PerformLayout();
            this.frmPaper.ResumeLayout(false);
            this.frmPaper.PerformLayout();
            base.ResumeLayout(false);
        }

       
        private Button button_printerAttribute;
        private ComboBox cboPageSize;
        private ComboBox cboPageToPrinterMapping;
        private ComboBox cboPaperTrays;
        private ComboBox cboPrinterPageSize;
        private CheckBox checkBox_usePrinterPageSize;
        private Button cmdCancel;
        private Button cmdPrint;
        private ComboBox comboBox_printer;
        private GroupBox fraPrinter;
        private GroupBox frmPaper;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private IPageLayout2 ipageLayout2_0;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label3;
        private Label label4;
        private Label label7;
        private Label Label8;
        private Label label9;
        private Label lblInfo;
        private Label lblPrinterName;
        private Label lblPrinterOrientation;
        private Label lblPrinterSize;
        private RadioButton optLandscape;
        private RadioButton optPaperLandscape;
        private RadioButton optPaperPortrait;
        private RadioButton optPortrait;
        private Panel panel1;
        private PrintDialog printDialog_0;
        private PrinterSettings printerSettings_0;
        private TextBox txtPageHeight;
        private TextBox txtPageWidth;
            private System.Drawing.Printing.PaperSize paperSize_0;
            private int int_0;
            private string string_0;
        
    }
}