using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Printing;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Controls;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geometry;
using ESRI.ArcGIS.Output;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class frmPrint
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.fraPrinter = new GroupBox();
            this.lblPrinterName = new Label();
            this.btnprinterAttribute = new Button();
            this.lblPrinterOrientation = new Label();
            this.lblPrinterName2 = new Label();
            this.lblPrinterSize = new Label();
            this.label1 = new Label();
            this.comboBox_printer = new ComboBox();
            this.frmPaper = new GroupBox();
            this.txtQulity = new TextBox();
            this.label4 = new Label();
            this.label2 = new Label();
            this.trackBar1 = new TrackBar();
            this.label13 = new Label();
            this.label3 = new Label();
            this.fraPrint = new GroupBox();
            this.panel1 = new Panel();
            this.txbEndPage = new NumericUpDown();
            this.label8 = new Label();
            this.rdoSpecify = new RadioButton();
            this.txbOverlap = new TextBox();
            this.rdoAll = new RadioButton();
            this.label5 = new Label();
            this.txbStartPage = new NumericUpDown();
            this.lblPageCount = new Label();
            this.radioButton1 = new RadioButton();
            this.rdoTitle = new RadioButton();
            this.textBox_copied = new TextBox();
            this.label_copied = new Label();
            this.printDialog_0 = new PrintDialog();
            this.cmdCancel = new Button();
            this.cmdPrint = new Button();
            this.fraPrinter.SuspendLayout();
            this.frmPaper.SuspendLayout();
            this.trackBar1.BeginInit();
            this.fraPrint.SuspendLayout();
            this.panel1.SuspendLayout();
            this.txbEndPage.BeginInit();
            this.txbStartPage.BeginInit();
            base.SuspendLayout();
            this.fraPrinter.BackColor = SystemColors.Control;
            this.fraPrinter.Controls.Add(this.lblPrinterName);
            this.fraPrinter.Controls.Add(this.btnprinterAttribute);
            this.fraPrinter.Controls.Add(this.lblPrinterOrientation);
            this.fraPrinter.Controls.Add(this.lblPrinterName2);
            this.fraPrinter.Controls.Add(this.lblPrinterSize);
            this.fraPrinter.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.fraPrinter.ForeColor = SystemColors.ControlText;
            this.fraPrinter.Location = new System.Drawing.Point(8, 8);
            this.fraPrinter.Name = "fraPrinter";
            this.fraPrinter.RightToLeft = RightToLeft.No;
            this.fraPrinter.Size = new Size(499, 112);
            this.fraPrinter.TabIndex = 24;
            this.fraPrinter.TabStop = false;
            this.fraPrinter.Text = "打印机信息：";
            this.lblPrinterName.Location = new System.Drawing.Point(72, 24);
            this.lblPrinterName.Name = "lblPrinterName";
            this.lblPrinterName.Size = new Size(304, 24);
            this.lblPrinterName.TabIndex = 27;
            this.btnprinterAttribute.Location = new System.Drawing.Point(424, 21);
            this.btnprinterAttribute.Name = "btnprinterAttribute";
            this.btnprinterAttribute.Size = new Size(67, 23);
            this.btnprinterAttribute.TabIndex = 26;
            this.btnprinterAttribute.Text = "属性";
            this.btnprinterAttribute.Click += new EventHandler(this.btnprinterAttribute_Click);
            this.lblPrinterOrientation.BackColor = SystemColors.Control;
            this.lblPrinterOrientation.Cursor = Cursors.Default;
            this.lblPrinterOrientation.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPrinterOrientation.ForeColor = SystemColors.ControlText;
            this.lblPrinterOrientation.Location = new System.Drawing.Point(10, 81);
            this.lblPrinterOrientation.Name = "lblPrinterOrientation";
            this.lblPrinterOrientation.RightToLeft = RightToLeft.No;
            this.lblPrinterOrientation.Size = new Size(216, 19);
            this.lblPrinterOrientation.TabIndex = 24;
            this.lblPrinterOrientation.Text = "纸张方向：";
            this.lblPrinterName2.AutoSize = true;
            this.lblPrinterName2.BackColor = SystemColors.Control;
            this.lblPrinterName2.Cursor = Cursors.Default;
            this.lblPrinterName2.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPrinterName2.ForeColor = SystemColors.ControlText;
            this.lblPrinterName2.Location = new System.Drawing.Point(10, 26);
            this.lblPrinterName2.Name = "lblPrinterName2";
            this.lblPrinterName2.RightToLeft = RightToLeft.No;
            this.lblPrinterName2.Size = new Size(64, 14);
            this.lblPrinterName2.TabIndex = 3;
            this.lblPrinterName2.Text = "名       称：";
            this.lblPrinterSize.BackColor = SystemColors.Control;
            this.lblPrinterSize.Cursor = Cursors.Default;
            this.lblPrinterSize.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPrinterSize.ForeColor = SystemColors.ControlText;
            this.lblPrinterSize.Location = new System.Drawing.Point(8, 55);
            this.lblPrinterSize.Name = "lblPrinterSize";
            this.lblPrinterSize.RightToLeft = RightToLeft.No;
            this.lblPrinterSize.Size = new Size(216, 18);
            this.lblPrinterSize.TabIndex = 1;
            this.lblPrinterSize.Text = "纸张大小：";
            this.label1.AutoSize = true;
            this.label1.BackColor = SystemColors.Control;
            this.label1.Cursor = Cursors.Default;
            this.label1.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label1.ForeColor = SystemColors.ControlText;
            this.label1.Location = new System.Drawing.Point(16, 133);
            this.label1.Name = "label1";
            this.label1.RightToLeft = RightToLeft.No;
            this.label1.Size = new Size(46, 14);
            this.label1.TabIndex = 25;
            this.label1.Text = "打印机:";
            this.comboBox_printer.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox_printer.Items.AddRange(new object[] { "Windows打印机", "PostScript打印机" });
            this.comboBox_printer.Location = new System.Drawing.Point(68, 131);
            this.comboBox_printer.Name = "comboBox_printer";
            this.comboBox_printer.Size = new Size(154, 20);
            this.comboBox_printer.TabIndex = 26;
            this.comboBox_printer.SelectedIndexChanged += new EventHandler(this.comboBox_printer_SelectedIndexChanged);
            this.frmPaper.BackColor = SystemColors.Control;
            this.frmPaper.Controls.Add(this.txtQulity);
            this.frmPaper.Controls.Add(this.label4);
            this.frmPaper.Controls.Add(this.label2);
            this.frmPaper.Controls.Add(this.trackBar1);
            this.frmPaper.Controls.Add(this.label13);
            this.frmPaper.Controls.Add(this.label3);
            this.frmPaper.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.frmPaper.ForeColor = SystemColors.ControlText;
            this.frmPaper.Location = new System.Drawing.Point(21, 157);
            this.frmPaper.Name = "frmPaper";
            this.frmPaper.RightToLeft = RightToLeft.No;
            this.frmPaper.Size = new Size(220, 126);
            this.frmPaper.TabIndex = 27;
            this.frmPaper.TabStop = false;
            this.frmPaper.Text = "输出影像品质";
            this.txtQulity.Location = new System.Drawing.Point(76, 93);
            this.txtQulity.Name = "txtQulity";
            this.txtQulity.Size = new Size(62, 20);
            this.txtQulity.TabIndex = 46;
            this.txtQulity.Text = "1";
            this.txtQulity.Leave += new EventHandler(this.txtQulity_Leave);
            this.txtQulity.TextChanged += new EventHandler(this.txtQulity_TextChanged);
            this.label4.AutoSize = true;
            this.label4.BackColor = SystemColors.Control;
            this.label4.Cursor = Cursors.Default;
            this.label4.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label4.ForeColor = SystemColors.ControlText;
            this.label4.Location = new System.Drawing.Point(169, 68);
            this.label4.Name = "label4";
            this.label4.RightToLeft = RightToLeft.No;
            this.label4.Size = new Size(19, 14);
            this.label4.TabIndex = 45;
            this.label4.Text = "差";
            this.label2.AutoSize = true;
            this.label2.BackColor = SystemColors.Control;
            this.label2.Cursor = Cursors.Default;
            this.label2.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label2.ForeColor = SystemColors.ControlText;
            this.label2.Location = new System.Drawing.Point(97, 68);
            this.label2.Name = "label2";
            this.label2.RightToLeft = RightToLeft.No;
            this.label2.Size = new Size(31, 14);
            this.label2.TabIndex = 44;
            this.label2.Text = "正常";
            this.trackBar1.Location = new System.Drawing.Point(29, 23);
            this.trackBar1.Maximum = 5;
            this.trackBar1.Minimum = 1;
            this.trackBar1.Name = "trackBar1";
            this.trackBar1.Size = new Size(171, 42);
            this.trackBar1.TabIndex = 43;
            this.trackBar1.Value = 1;
            this.trackBar1.Scroll += new EventHandler(this.trackBar1_Scroll);
            this.label13.AutoSize = true;
            this.label13.BackColor = SystemColors.Control;
            this.label13.Cursor = Cursors.Default;
            this.label13.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label13.ForeColor = SystemColors.ControlText;
            this.label13.Location = new System.Drawing.Point(6, 93);
            this.label13.Name = "label13";
            this.label13.RightToLeft = RightToLeft.No;
            this.label13.Size = new Size(55, 14);
            this.label13.TabIndex = 42;
            this.label13.Text = "比率:    1:";
            this.label3.AutoSize = true;
            this.label3.BackColor = SystemColors.Control;
            this.label3.Cursor = Cursors.Default;
            this.label3.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label3.ForeColor = SystemColors.ControlText;
            this.label3.Location = new System.Drawing.Point(33, 68);
            this.label3.Name = "label3";
            this.label3.RightToLeft = RightToLeft.No;
            this.label3.Size = new Size(19, 14);
            this.label3.TabIndex = 23;
            this.label3.Text = "好";
            this.fraPrint.BackColor = SystemColors.Control;
            this.fraPrint.Controls.Add(this.panel1);
            this.fraPrint.Controls.Add(this.radioButton1);
            this.fraPrint.Controls.Add(this.rdoTitle);
            this.fraPrint.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.fraPrint.ForeColor = SystemColors.ControlText;
            this.fraPrint.Location = new System.Drawing.Point(256, 133);
            this.fraPrint.Name = "fraPrint";
            this.fraPrint.RightToLeft = RightToLeft.No;
            this.fraPrint.Size = new Size(251, 150);
            this.fraPrint.TabIndex = 28;
            this.fraPrint.TabStop = false;
            this.fraPrint.Text = "打印页设置";
            this.panel1.Controls.Add(this.txbEndPage);
            this.panel1.Controls.Add(this.label8);
            this.panel1.Controls.Add(this.rdoSpecify);
            this.panel1.Controls.Add(this.txbOverlap);
            this.panel1.Controls.Add(this.rdoAll);
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.txbStartPage);
            this.panel1.Controls.Add(this.lblPageCount);
            this.panel1.Location = new System.Drawing.Point(27, 31);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(216, 79);
            this.panel1.TabIndex = 29;
            this.txbEndPage.Enabled = false;
            this.txbEndPage.Location = new System.Drawing.Point(167, 26);
            int[] bits = new int[4];
            bits[0] = 1;
            this.txbEndPage.Minimum = new decimal(bits);
            this.txbEndPage.Name = "txbEndPage";
            this.txbEndPage.Size = new Size(46, 20);
            this.txbEndPage.TabIndex = 30;
            int[] bits2 = new int[4];
            bits2[0] = 1;
            this.txbEndPage.Value = new decimal(bits2);
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(147, 30);
            this.label8.Name = "label8";
            this.label8.Size = new Size(19, 14);
            this.label8.TabIndex = 30;
            this.label8.Text = "到";
            this.rdoSpecify.AutoSize = true;
            this.rdoSpecify.Location = new System.Drawing.Point(8, 28);
            this.rdoSpecify.Name = "rdoSpecify";
            this.rdoSpecify.Size = new Size(85, 18);
            this.rdoSpecify.TabIndex = 26;
            this.rdoSpecify.Text = "指定页，从";
            this.rdoSpecify.UseVisualStyleBackColor = true;
            this.rdoSpecify.CheckedChanged += new EventHandler(this.rdoSpecify_CheckedChanged);
            this.txbOverlap.AcceptsReturn = true;
            this.txbOverlap.BackColor = SystemColors.Window;
            this.txbOverlap.Cursor = Cursors.IBeam;
            this.txbOverlap.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txbOverlap.ForeColor = SystemColors.WindowText;
            this.txbOverlap.Location = new System.Drawing.Point(63, 53);
            this.txbOverlap.MaxLength = 0;
            this.txbOverlap.Name = "txbOverlap";
            this.txbOverlap.RightToLeft = RightToLeft.No;
            this.txbOverlap.Size = new Size(122, 20);
            this.txbOverlap.TabIndex = 26;
            this.txbOverlap.Text = "0";
            this.txbOverlap.Leave += new EventHandler(this.txbOverlap_Leave);
            this.rdoAll.AutoSize = true;
            this.rdoAll.Checked = true;
            this.rdoAll.Location = new System.Drawing.Point(8, 5);
            this.rdoAll.Name = "rdoAll";
            this.rdoAll.Size = new Size(49, 18);
            this.rdoAll.TabIndex = 25;
            this.rdoAll.TabStop = true;
            this.rdoAll.Text = "所有";
            this.rdoAll.UseVisualStyleBackColor = true;
            this.rdoAll.CheckedChanged += new EventHandler(this.rdoAll_CheckedChanged);
            this.label5.AutoSize = true;
            this.label5.BackColor = SystemColors.Control;
            this.label5.Cursor = Cursors.Default;
            this.label5.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label5.ForeColor = SystemColors.ControlText;
            this.label5.Location = new System.Drawing.Point(11, 54);
            this.label5.Name = "label5";
            this.label5.RightToLeft = RightToLeft.No;
            this.label5.Size = new Size(46, 14);
            this.label5.TabIndex = 27;
            this.label5.Text = "重叠度:";
            this.txbStartPage.Enabled = false;
            this.txbStartPage.Location = new System.Drawing.Point(97, 27);
            int[] bits3 = new int[4];
            bits3[0] = 1;
            this.txbStartPage.Minimum = new decimal(bits3);
            this.txbStartPage.Name = "txbStartPage";
            this.txbStartPage.Size = new Size(44, 20);
            this.txbStartPage.TabIndex = 29;
            int[] bits4 = new int[4];
            bits4[0] = 1;
            this.txbStartPage.Value = new decimal(bits4);
            this.lblPageCount.BackColor = SystemColors.Control;
            this.lblPageCount.Cursor = Cursors.Default;
            this.lblPageCount.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.lblPageCount.ForeColor = SystemColors.ControlText;
            this.lblPageCount.Location = new System.Drawing.Point(75, 7);
            this.lblPageCount.Name = "lblPageCount";
            this.lblPageCount.RightToLeft = RightToLeft.No;
            this.lblPageCount.Size = new Size(129, 14);
            this.lblPageCount.TabIndex = 24;
            this.lblPageCount.Text = "页数: ";
            this.radioButton1.AutoSize = true;
            this.radioButton1.Location = new System.Drawing.Point(12, 116);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new Size(97, 18);
            this.radioButton1.TabIndex = 29;
            this.radioButton1.TabStop = true;
            this.radioButton1.Text = "缩放地图输出";
            this.radioButton1.UseVisualStyleBackColor = true;
            this.rdoTitle.AutoSize = true;
            this.rdoTitle.Checked = true;
            this.rdoTitle.Location = new System.Drawing.Point(12, 16);
            this.rdoTitle.Name = "rdoTitle";
            this.rdoTitle.Size = new Size(97, 18);
            this.rdoTitle.TabIndex = 28;
            this.rdoTitle.TabStop = true;
            this.rdoTitle.Text = "分割地图输出";
            this.rdoTitle.UseVisualStyleBackColor = true;
            this.rdoTitle.CheckedChanged += new EventHandler(this.rdoTitle_CheckedChanged);
            this.textBox_copied.Location = new System.Drawing.Point(103, 291);
            this.textBox_copied.Name = "textBox_copied";
            this.textBox_copied.Size = new Size(122, 21);
            this.textBox_copied.TabIndex = 25;
            this.textBox_copied.Text = "1";
            this.textBox_copied.Leave += new EventHandler(this.textBox_copied_Leave);
            this.label_copied.AutoSize = true;
            this.label_copied.Location = new System.Drawing.Point(28, 295);
            this.label_copied.Name = "label_copied";
            this.label_copied.Size = new Size(77, 12);
            this.label_copied.TabIndex = 13;
            this.label_copied.Text = "打 印 份 数:";
            this.cmdCancel.Location = new System.Drawing.Point(427, 306);
            this.cmdCancel.Name = "cmdCancel";
            this.cmdCancel.Size = new Size(75, 23);
            this.cmdCancel.TabIndex = 30;
            this.cmdCancel.Text = "取消";
            this.cmdPrint.BackColor = SystemColors.Control;
            this.cmdPrint.Cursor = Cursors.Default;
            this.cmdPrint.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cmdPrint.ForeColor = SystemColors.ControlText;
            this.cmdPrint.Location = new System.Drawing.Point(334, 306);
            this.cmdPrint.Name = "cmdPrint";
            this.cmdPrint.RightToLeft = RightToLeft.No;
            this.cmdPrint.Size = new Size(75, 23);
            this.cmdPrint.TabIndex = 29;
            this.cmdPrint.Text = "打  印";
            this.cmdPrint.UseVisualStyleBackColor = false;
            this.cmdPrint.Click += new EventHandler(this.cmdPrint_Click);
            this.AutoScaleBaseSize = new Size(6, 14);
            base.ClientSize = new Size(514, 341);
            base.Controls.Add(this.cmdCancel);
            base.Controls.Add(this.cmdPrint);
            base.Controls.Add(this.fraPrint);
            base.Controls.Add(this.frmPaper);
            base.Controls.Add(this.textBox_copied);
            base.Controls.Add(this.comboBox_printer);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.label_copied);
            base.Controls.Add(this.fraPrinter);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmPrint";
            this.Text = "打印";
            base.Load += new EventHandler(this.frmPrint_Load);
            this.fraPrinter.ResumeLayout(false);
            this.fraPrinter.PerformLayout();
            this.frmPaper.ResumeLayout(false);
            this.frmPaper.PerformLayout();
            this.trackBar1.EndInit();
            this.fraPrint.ResumeLayout(false);
            this.fraPrint.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.txbEndPage.EndInit();
            this.txbStartPage.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private Button btnprinterAttribute;
        private Button cmdCancel;
        private Button cmdPrint;
        private ComboBox comboBox_printer;
        private GroupBox fraPrint;
        private GroupBox fraPrinter;
        private GroupBox frmPaper;
        private Label label_copied;
        private Label label1;
        private Label label13;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label8;
        private Label lblPageCount;
        private Label lblPrinterName;
        private Label lblPrinterName2;
        private Label lblPrinterOrientation;
        private Label lblPrinterSize;
        private Panel panel1;
        private PrintDialog printDialog_0;
        private RadioButton radioButton1;
        private RadioButton rdoAll;
        private RadioButton rdoSpecify;
        private RadioButton rdoTitle;
        private TextBox textBox_copied;
        private TrackBar trackBar1;
        private NumericUpDown txbEndPage;
        private TextBox txbOverlap;
        private NumericUpDown txbStartPage;
        private TextBox txtQulity;
    }
}