using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geodatabase;
using Yutai.ArcGIS.Common.Query.UI;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class LineLabelSetCtrl
    {
        protected override void Dispose(bool bool_3)
        {
            if (bool_3 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_3);
        }

       
 private void InitializeComponent()
        {
            this.btnSQL = new SimpleButton();
            this.btnScaleSet = new SimpleButton();
            this.groupBox2 = new GroupBox();
            this.groupBox3 = new GroupBox();
            this.label4 = new Label();
            this.txtOffset = new TextEdit();
            this.label2 = new Label();
            this.chkBelow_Right = new CheckEdit();
            this.chkOnTop = new CheckEdit();
            this.chkTop_Left = new CheckEdit();
            this.groupBox4 = new GroupBox();
            this.rdoLineLabelPosition = new RadioGroup();
            this.btnLabelExpression = new GroupBox();
            this.btnEditSymbol = new SimpleButton();
            this.symbolItem = new SymbolItem();
            this.groupBox1 = new GroupBox();
            this.cboFields = new ComboBoxEdit();
            this.btnExpress = new SimpleButton();
            this.label1 = new Label();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.txtOffset.Properties.BeginInit();
            this.chkBelow_Right.Properties.BeginInit();
            this.chkOnTop.Properties.BeginInit();
            this.chkTop_Left.Properties.BeginInit();
            this.groupBox4.SuspendLayout();
            this.rdoLineLabelPosition.Properties.BeginInit();
            this.btnLabelExpression.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.cboFields.Properties.BeginInit();
            base.SuspendLayout();
            this.btnSQL.Location = new Point(112, 296);
            this.btnSQL.Name = "btnSQL";
            this.btnSQL.Size = new Size(56, 24);
            this.btnSQL.TabIndex = 18;
            this.btnSQL.Text = "SQL查询";
            this.btnSQL.Click += new EventHandler(this.btnSQL_Click);
            this.btnScaleSet.Location = new Point(32, 296);
            this.btnScaleSet.Name = "btnScaleSet";
            this.btnScaleSet.Size = new Size(64, 24);
            this.btnScaleSet.TabIndex = 17;
            this.btnScaleSet.Text = "比例范围";
            this.btnScaleSet.Click += new EventHandler(this.btnScaleSet_Click);
            this.groupBox2.Controls.Add(this.groupBox3);
            this.groupBox2.Controls.Add(this.groupBox4);
            this.groupBox2.Location = new Point(16, 152);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(360, 136);
            this.groupBox2.TabIndex = 16;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "放值属性";
            this.groupBox3.Controls.Add(this.label4);
            this.groupBox3.Controls.Add(this.txtOffset);
            this.groupBox3.Controls.Add(this.label2);
            this.groupBox3.Controls.Add(this.chkBelow_Right);
            this.groupBox3.Controls.Add(this.chkOnTop);
            this.groupBox3.Controls.Add(this.chkTop_Left);
            this.groupBox3.Location = new Point(144, 16);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(192, 112);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "位置";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(128, 82);
            this.label4.Name = "label4";
            this.label4.Size = new Size(54, 17);
            this.label4.TabIndex = 8;
            this.label4.Text = "地图单位";
            this.txtOffset.EditValue = "0";
            this.txtOffset.Location = new Point(63, 79);
            this.txtOffset.Name = "txtOffset";
            this.txtOffset.Size = new Size(56, 23);
            this.txtOffset.TabIndex = 7;
            this.txtOffset.EditValueChanged += new EventHandler(this.txtOffset_EditValueChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 82);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 17);
            this.label2.TabIndex = 6;
            this.label2.Text = "偏移";
            this.chkBelow_Right.Location = new Point(16, 55);
            this.chkBelow_Right.Name = "chkBelow_Right";
            this.chkBelow_Right.Properties.Caption = "下";
            this.chkBelow_Right.Size = new Size(56, 19);
            this.chkBelow_Right.TabIndex = 4;
            this.chkBelow_Right.CheckedChanged += new EventHandler(this.chkBelow_Right_CheckedChanged);
            this.chkOnTop.Location = new Point(16, 35);
            this.chkOnTop.Name = "chkOnTop";
            this.chkOnTop.Properties.Caption = "在线上";
            this.chkOnTop.Size = new Size(56, 19);
            this.chkOnTop.TabIndex = 3;
            this.chkOnTop.CheckedChanged += new EventHandler(this.chkOnTop_CheckedChanged);
            this.chkTop_Left.Location = new Point(16, 16);
            this.chkTop_Left.Name = "chkTop_Left";
            this.chkTop_Left.Properties.Caption = "上";
            this.chkTop_Left.Size = new Size(56, 19);
            this.chkTop_Left.TabIndex = 2;
            this.chkTop_Left.CheckedChanged += new EventHandler(this.chkTop_Left_CheckedChanged);
            this.groupBox4.Controls.Add(this.rdoLineLabelPosition);
            this.groupBox4.Location = new Point(24, 16);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(104, 112);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "方向";
            this.rdoLineLabelPosition.Location = new Point(8, 16);
            this.rdoLineLabelPosition.Name = "rdoLineLabelPosition";
            this.rdoLineLabelPosition.Properties.Appearance.BackColor = SystemColors.Control;
            this.rdoLineLabelPosition.Properties.Appearance.Options.UseBackColor = true;
            this.rdoLineLabelPosition.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoLineLabelPosition.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "水平放置"), new RadioGroupItem(null, "平行放置"), new RadioGroupItem(null, "弯曲放置"), new RadioGroupItem(null, "垂直放置") });
            this.rdoLineLabelPosition.Size = new Size(88, 80);
            this.rdoLineLabelPosition.TabIndex = 0;
            this.rdoLineLabelPosition.SelectedIndexChanged += new EventHandler(this.rdoLineLabelPosition_SelectedIndexChanged);
            this.btnLabelExpression.Controls.Add(this.btnEditSymbol);
            this.btnLabelExpression.Controls.Add(this.symbolItem);
            this.btnLabelExpression.Location = new Point(16, 73);
            this.btnLabelExpression.Name = "btnLabelExpression";
            this.btnLabelExpression.Size = new Size(360, 72);
            this.btnLabelExpression.TabIndex = 15;
            this.btnLabelExpression.TabStop = false;
            this.btnLabelExpression.Text = "文本符号";
            this.btnEditSymbol.Location = new Point(232, 24);
            this.btnEditSymbol.Name = "btnEditSymbol";
            this.btnEditSymbol.Size = new Size(64, 24);
            this.btnEditSymbol.TabIndex = 1;
            this.btnEditSymbol.Text = "符号...";
            this.btnEditSymbol.Click += new EventHandler(this.btnEditSymbol_Click);
            this.symbolItem.BackColor = SystemColors.ControlLight;
            this.symbolItem.Location = new Point(16, 24);
            this.symbolItem.Name = "symbolItem";
            this.symbolItem.Size = new Size(168, 40);
            this.symbolItem.Symbol = null;
            this.symbolItem.TabIndex = 0;
            this.groupBox1.Controls.Add(this.cboFields);
            this.groupBox1.Controls.Add(this.btnExpress);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new Point(16, 4);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(360, 64);
            this.groupBox1.TabIndex = 14;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "标注表达式";
            this.cboFields.EditValue = "";
            this.cboFields.Location = new Point(80, 24);
            this.cboFields.Name = "cboFields";
            this.cboFields.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboFields.Size = new Size(136, 23);
            this.cboFields.TabIndex = 5;
            this.cboFields.SelectedIndexChanged += new EventHandler(this.cboFields_SelectedIndexChanged);
            this.btnExpress.Location = new Point(240, 24);
            this.btnExpress.Name = "btnExpress";
            this.btnExpress.Size = new Size(64, 24);
            this.btnExpress.TabIndex = 4;
            this.btnExpress.Text = "表达式...";
            this.btnExpress.Click += new EventHandler(this.btnExpress_Click);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 26);
            this.label1.Name = "label1";
            this.label1.Size = new Size(54, 17);
            this.label1.TabIndex = 3;
            this.label1.Text = "标注字段";
            base.Controls.Add(this.btnSQL);
            base.Controls.Add(this.btnScaleSet);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.btnLabelExpression);
            base.Controls.Add(this.groupBox1);
            base.Name = "LineLabelSetCtrl";
            base.Size = new Size(384, 328);
            base.Load += new EventHandler(this.LineLabelSetCtrl_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.txtOffset.Properties.EndInit();
            this.chkBelow_Right.Properties.EndInit();
            this.chkOnTop.Properties.EndInit();
            this.chkTop_Left.Properties.EndInit();
            this.groupBox4.ResumeLayout(false);
            this.rdoLineLabelPosition.Properties.EndInit();
            this.btnLabelExpression.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.cboFields.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnEditSymbol;
        private SimpleButton btnExpress;
        private GroupBox btnLabelExpression;
        private SimpleButton btnScaleSet;
        private SimpleButton btnSQL;
        private ComboBoxEdit cboFields;
        private CheckEdit chkBelow_Right;
        private CheckEdit chkOnTop;
        private CheckEdit chkTop_Left;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private Label label1;
        private Label label2;
        private Label label4;
        private RadioGroup rdoLineLabelPosition;
        private SymbolItem symbolItem;
        private TextEdit txtOffset;
    }
}