using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.Symbol;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class MapDataFramePage
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MapDataFramePage));
            this.groupBox1 = new GroupBox();
            this.panelExtend = new Panel();
            this.btnSetExtend = new Button();
            this.txtRight = new TextBox();
            this.label5 = new Label();
            this.txtLeft = new TextBox();
            this.label4 = new Label();
            this.txtBottom = new TextBox();
            this.label3 = new Label();
            this.txtTop = new TextBox();
            this.label2 = new Label();
            this.panelmapscale = new Panel();
            this.cboMapScale = new System.Windows.Forms.ComboBox();
            this.label1 = new Label();
            this.cboExtendType = new System.Windows.Forms.ComboBox();
            this.groupBox2 = new GroupBox();
            this.checkBox1 = new CheckBox();
            this.btnSetClipEnt = new Button();
            this.btnExclude = new Button();
            this.cboClipType = new System.Windows.Forms.ComboBox();
            this.groupBox3 = new GroupBox();
            this.rdoOther = new RadioButton();
            this.rdoAllLayerExtend = new RadioButton();
            this.btnFullExtend = new Button();
            this.groupBox4 = new GroupBox();
            this.btnBorderInfo = new SimpleButton();
            this.btnBorderSelector = new SimpleButton();
            this.cboBorder = new StyleComboBox(this.icontainer_0);
            this.imageList_0 = new ImageList(this.icontainer_0);
            this.groupBox1.SuspendLayout();
            this.panelExtend.SuspendLayout();
            this.panelmapscale.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.panelExtend);
            this.groupBox1.Controls.Add(this.panelmapscale);
            this.groupBox1.Controls.Add(this.cboExtendType);
            this.groupBox1.Location = new System.Drawing.Point(5, 12);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(361, 168);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "范围";
            this.panelExtend.Controls.Add(this.btnSetExtend);
            this.panelExtend.Controls.Add(this.txtRight);
            this.panelExtend.Controls.Add(this.label5);
            this.panelExtend.Controls.Add(this.txtLeft);
            this.panelExtend.Controls.Add(this.label4);
            this.panelExtend.Controls.Add(this.txtBottom);
            this.panelExtend.Controls.Add(this.label3);
            this.panelExtend.Controls.Add(this.txtTop);
            this.panelExtend.Controls.Add(this.label2);
            this.panelExtend.Location = new System.Drawing.Point(9, 49);
            this.panelExtend.Name = "panelExtend";
            this.panelExtend.Size = new Size(346, 105);
            this.panelExtend.TabIndex = 2;
            this.panelExtend.Paint += new PaintEventHandler(this.panelExtend_Paint);
            this.btnSetExtend.Location = new System.Drawing.Point(255, 79);
            this.btnSetExtend.Name = "btnSetExtend";
            this.btnSetExtend.Size = new Size(75, 23);
            this.btnSetExtend.TabIndex = 9;
            this.btnSetExtend.Text = "指定范围";
            this.btnSetExtend.UseVisualStyleBackColor = true;
            this.btnSetExtend.Click += new EventHandler(this.btnSetExtend_Click);
            this.txtRight.Location = new System.Drawing.Point(205, 32);
            this.txtRight.Name = "txtRight";
            this.txtRight.Size = new Size(117, 21);
            this.txtRight.TabIndex = 8;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(182, 35);
            this.label5.Name = "label5";
            this.label5.Size = new Size(17, 12);
            this.label5.TabIndex = 7;
            this.label5.Text = "右";
            this.txtLeft.Location = new System.Drawing.Point(44, 32);
            this.txtLeft.Name = "txtLeft";
            this.txtLeft.Size = new Size(129, 21);
            this.txtLeft.TabIndex = 6;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(21, 35);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 12);
            this.label4.TabIndex = 5;
            this.label4.Text = "左";
            this.txtBottom.Location = new System.Drawing.Point(126, 59);
            this.txtBottom.Name = "txtBottom";
            this.txtBottom.Size = new Size(100, 21);
            this.txtBottom.TabIndex = 4;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(103, 62);
            this.label3.Name = "label3";
            this.label3.Size = new Size(17, 12);
            this.label3.TabIndex = 3;
            this.label3.Text = "下";
            this.txtTop.Location = new System.Drawing.Point(126, 3);
            this.txtTop.Name = "txtTop";
            this.txtTop.Size = new Size(100, 21);
            this.txtTop.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(103, 6);
            this.label2.Name = "label2";
            this.label2.Size = new Size(17, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "上";
            this.panelmapscale.Controls.Add(this.cboMapScale);
            this.panelmapscale.Controls.Add(this.label1);
            this.panelmapscale.Location = new System.Drawing.Point(19, 57);
            this.panelmapscale.Name = "panelmapscale";
            this.panelmapscale.Size = new Size(270, 49);
            this.panelmapscale.TabIndex = 1;
            this.cboMapScale.FormattingEnabled = true;
            this.cboMapScale.Items.AddRange(new object[] { "<使用当前比例尺>", "1:1000", "1:10000", "1:25000", "1:100000", "1:250000", "1:500000" });
            this.cboMapScale.Location = new System.Drawing.Point(64, 12);
            this.cboMapScale.Name = "cboMapScale";
            this.cboMapScale.Size = new Size(162, 20);
            this.cboMapScale.TabIndex = 1;
            this.cboMapScale.SelectedIndexChanged += new EventHandler(this.cboMapScale_SelectedIndexChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(17, 15);
            this.label1.Name = "label1";
            this.label1.Size = new Size(41, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "比例尺";
            this.cboExtendType.FormattingEnabled = true;
            this.cboExtendType.Items.AddRange(new object[] { "自动", "固体比例尺", "固定范围" });
            this.cboExtendType.Location = new System.Drawing.Point(3, 20);
            this.cboExtendType.Name = "cboExtendType";
            this.cboExtendType.Size = new Size(162, 20);
            this.cboExtendType.TabIndex = 0;
            this.cboExtendType.SelectedIndexChanged += new EventHandler(this.cboExtendType_SelectedIndexChanged);
            this.groupBox2.Controls.Add(this.groupBox4);
            this.groupBox2.Controls.Add(this.checkBox1);
            this.groupBox2.Controls.Add(this.btnSetClipEnt);
            this.groupBox2.Controls.Add(this.btnExclude);
            this.groupBox2.Controls.Add(this.cboClipType);
            this.groupBox2.Location = new System.Drawing.Point(8, 197);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(356, 146);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "数据裁剪";
            this.groupBox2.Enter += new EventHandler(this.groupBox2_Enter);
            this.checkBox1.AutoSize = true;
            this.checkBox1.Location = new System.Drawing.Point(19, 90);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new Size(120, 16);
            this.checkBox1.TabIndex = 3;
            this.checkBox1.Text = "裁剪格网和经纬网";
            this.checkBox1.UseVisualStyleBackColor = true;
            this.btnSetClipEnt.Location = new System.Drawing.Point(224, 20);
            this.btnSetClipEnt.Name = "btnSetClipEnt";
            this.btnSetClipEnt.Size = new Size(75, 23);
            this.btnSetClipEnt.TabIndex = 2;
            this.btnSetClipEnt.Text = "指定形状";
            this.btnSetClipEnt.UseVisualStyleBackColor = true;
            this.btnSetClipEnt.Click += new EventHandler(this.btnSetClipEnt_Click);
            this.btnExclude.Location = new System.Drawing.Point(19, 47);
            this.btnExclude.Name = "btnExclude";
            this.btnExclude.Size = new Size(75, 23);
            this.btnExclude.TabIndex = 1;
            this.btnExclude.Text = "排除图层";
            this.btnExclude.UseVisualStyleBackColor = true;
            this.btnExclude.Click += new EventHandler(this.btnExclude_Click);
            this.cboClipType.FormattingEnabled = true;
            this.cboClipType.Items.AddRange(new object[] { "无裁剪", "裁剪到范围" });
            this.cboClipType.Location = new System.Drawing.Point(19, 20);
            this.cboClipType.Name = "cboClipType";
            this.cboClipType.Size = new Size(162, 20);
            this.cboClipType.TabIndex = 0;
            this.cboClipType.SelectedIndexChanged += new EventHandler(this.cboClipType_SelectedIndexChanged);
            this.groupBox3.Controls.Add(this.rdoOther);
            this.groupBox3.Controls.Add(this.rdoAllLayerExtend);
            this.groupBox3.Controls.Add(this.btnFullExtend);
            this.groupBox3.Location = new System.Drawing.Point(20, 349);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(358, 85);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "全图命令使用的范围";
            this.groupBox3.Visible = false;
            this.rdoOther.AutoSize = true;
            this.rdoOther.Location = new System.Drawing.Point(10, 54);
            this.rdoOther.Name = "rdoOther";
            this.rdoOther.Size = new Size(47, 16);
            this.rdoOther.TabIndex = 4;
            this.rdoOther.Text = "其他";
            this.rdoOther.UseVisualStyleBackColor = true;
            this.rdoAllLayerExtend.AutoSize = true;
            this.rdoAllLayerExtend.Checked = true;
            this.rdoAllLayerExtend.Location = new System.Drawing.Point(8, 20);
            this.rdoAllLayerExtend.Name = "rdoAllLayerExtend";
            this.rdoAllLayerExtend.Size = new Size(131, 16);
            this.rdoAllLayerExtend.TabIndex = 3;
            this.rdoAllLayerExtend.TabStop = true;
            this.rdoAllLayerExtend.Text = "所有图层的数据范围";
            this.rdoAllLayerExtend.UseVisualStyleBackColor = true;
            this.btnFullExtend.Location = new System.Drawing.Point(96, 51);
            this.btnFullExtend.Name = "btnFullExtend";
            this.btnFullExtend.Size = new Size(75, 23);
            this.btnFullExtend.TabIndex = 2;
            this.btnFullExtend.Text = "指定范围";
            this.btnFullExtend.UseVisualStyleBackColor = true;
            this.btnFullExtend.Click += new EventHandler(this.btnFullExtend_Click);
            this.groupBox4.Controls.Add(this.btnBorderInfo);
            this.groupBox4.Controls.Add(this.btnBorderSelector);
            this.groupBox4.Controls.Add(this.cboBorder);
            this.groupBox4.Location = new System.Drawing.Point(149, 49);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(181, 60);
            this.groupBox4.TabIndex = 41;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "边框";
            this.btnBorderInfo.Appearance.BackColor = SystemColors.Window;
            this.btnBorderInfo.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBorderInfo.Appearance.Options.UseBackColor = true;
            this.btnBorderInfo.Appearance.Options.UseForeColor = true;
            this.btnBorderInfo.ButtonStyle = BorderStyles.Simple;
            this.btnBorderInfo.ImageIndex = 1;
            this.btnBorderInfo.ImageList = this.imageList_0;
            this.btnBorderInfo.Location = new System.Drawing.Point(160, 36);
            this.btnBorderInfo.Name = "btnBorderInfo";
            this.btnBorderInfo.Size = new Size(16, 16);
            this.btnBorderInfo.TabIndex = 33;
            this.btnBorderInfo.Click += new EventHandler(this.btnBorderInfo_Click);
            this.btnBorderSelector.Appearance.BackColor = SystemColors.Window;
            this.btnBorderSelector.Appearance.ForeColor = SystemColors.ControlLightLight;
            this.btnBorderSelector.Appearance.Options.UseBackColor = true;
            this.btnBorderSelector.Appearance.Options.UseForeColor = true;
            this.btnBorderSelector.ButtonStyle = BorderStyles.Simple;
            this.btnBorderSelector.ImageIndex = 0;
            this.btnBorderSelector.ImageList = this.imageList_0;
            this.btnBorderSelector.Location = new System.Drawing.Point(160, 20);
            this.btnBorderSelector.Name = "btnBorderSelector";
            this.btnBorderSelector.Size = new Size(16, 16);
            this.btnBorderSelector.TabIndex = 32;
            this.btnBorderSelector.Click += new EventHandler(this.btnBorderSelector_Click);
            this.cboBorder.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboBorder.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboBorder.DropDownWidth = 160;
            this.cboBorder.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboBorder.Location = new System.Drawing.Point(11, 20);
            this.cboBorder.Name = "cboBorder";
            this.cboBorder.Size = new Size(148, 31);
            this.cboBorder.TabIndex = 31;
            this.imageList_0.ImageStream = (ImageListStreamer)resources.GetObject("imageList1.ImageStream");
            this.imageList_0.TransparentColor = Color.Transparent;
            this.imageList_0.Images.SetKeyName(0, "");
            this.imageList_0.Images.SetKeyName(1, "");
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "MapDataFramePage";
            base.Size = new Size(381, 402);
            base.Load += new EventHandler(this.MapDataFramePage_Load);
            this.groupBox1.ResumeLayout(false);
            this.panelExtend.ResumeLayout(false);
            this.panelExtend.PerformLayout();
            this.panelmapscale.ResumeLayout(false);
            this.panelmapscale.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private SimpleButton btnBorderInfo;
        private SimpleButton btnBorderSelector;
        private Button btnExclude;
        private Button btnFullExtend;
        private Button btnSetClipEnt;
        private Button btnSetExtend;
        private StyleComboBox cboBorder;
        private System.Windows.Forms.ComboBox cboClipType;
        private System.Windows.Forms.ComboBox cboExtendType;
        private System.Windows.Forms.ComboBox cboMapScale;
        private CheckBox checkBox1;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private ImageList imageList_0;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Panel panelExtend;
        private Panel panelmapscale;
        private RadioButton rdoAllLayerExtend;
        private RadioButton rdoOther;
        private TextBox txtBottom;
        private TextBox txtLeft;
        private TextBox txtRight;
        private TextBox txtTop;
    }
}