using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Catalog.Geodatabase.UI;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class MapGridStylePropertyPage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
        private void InitializeComponent()
        {
            this.groupBoxMeasuredGridSpace = new GroupBox();
            this.lblYUnit = new Label();
            this.lblXUnit = new Label();
            this.txtMeasuredGridYSpace = new TextEdit();
            this.txtMeasuredGridXSpace = new TextEdit();
            this.label2 = new Label();
            this.label1 = new Label();
            this.groupBoxGraticuleStyle = new GroupBox();
            this.label14 = new Label();
            this.btnGraticulestyle = new StyleButton();
            this.rdoGraticuleStyle = new RadioGroup();
            this.groupBoxMeasuredGridStyle = new GroupBox();
            this.label15 = new Label();
            this.btnMeasuredGridStyle = new StyleButton();
            this.rdoMeasuredGridStyle = new RadioGroup();
            this.groupBoxCoordinate = new GroupBox();
            this.btnSpatialReference = new SimpleButton();
            this.txtSpatialReference = new MemoEdit();
            this.groupBoxGraticuleSpace = new GroupBox();
            this.label9 = new Label();
            this.label8 = new Label();
            this.label7 = new Label();
            this.txtHatchIntervalYSecond = new TextEdit();
            this.txtHatchIntervalYMinute = new TextEdit();
            this.txtHatchIntervalXSecond = new TextEdit();
            this.txtHatchIntervalXMinute = new TextEdit();
            this.label3 = new Label();
            this.label4 = new Label();
            this.txtHatchIntervalYDegree = new TextEdit();
            this.txtHatchIntervalXDegree = new TextEdit();
            this.label5 = new Label();
            this.label6 = new Label();
            this.groupBoxIndexGridSpace = new GroupBox();
            this.label10 = new Label();
            this.label11 = new Label();
            this.txtRowCount = new TextEdit();
            this.txtColumnCount = new TextEdit();
            this.label12 = new Label();
            this.label13 = new Label();
            this.groupBoxIndexGridStyle = new GroupBox();
            this.label16 = new Label();
            this.btnIndexGridStyle = new StyleButton();
            this.rdoIndexGridStyle = new RadioGroup();
            this.groupBoxMeasuredGridSpace.SuspendLayout();
            this.txtMeasuredGridYSpace.Properties.BeginInit();
            this.txtMeasuredGridXSpace.Properties.BeginInit();
            this.groupBoxGraticuleStyle.SuspendLayout();
            this.rdoGraticuleStyle.Properties.BeginInit();
            this.groupBoxMeasuredGridStyle.SuspendLayout();
            this.rdoMeasuredGridStyle.Properties.BeginInit();
            this.groupBoxCoordinate.SuspendLayout();
            this.txtSpatialReference.Properties.BeginInit();
            this.groupBoxGraticuleSpace.SuspendLayout();
            this.txtHatchIntervalYSecond.Properties.BeginInit();
            this.txtHatchIntervalYMinute.Properties.BeginInit();
            this.txtHatchIntervalXSecond.Properties.BeginInit();
            this.txtHatchIntervalXMinute.Properties.BeginInit();
            this.txtHatchIntervalYDegree.Properties.BeginInit();
            this.txtHatchIntervalXDegree.Properties.BeginInit();
            this.groupBoxIndexGridSpace.SuspendLayout();
            this.txtRowCount.Properties.BeginInit();
            this.txtColumnCount.Properties.BeginInit();
            this.groupBoxIndexGridStyle.SuspendLayout();
            this.rdoIndexGridStyle.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBoxMeasuredGridSpace.Controls.Add(this.lblYUnit);
            this.groupBoxMeasuredGridSpace.Controls.Add(this.lblXUnit);
            this.groupBoxMeasuredGridSpace.Controls.Add(this.txtMeasuredGridYSpace);
            this.groupBoxMeasuredGridSpace.Controls.Add(this.txtMeasuredGridXSpace);
            this.groupBoxMeasuredGridSpace.Controls.Add(this.label2);
            this.groupBoxMeasuredGridSpace.Controls.Add(this.label1);
            this.groupBoxMeasuredGridSpace.Location = new System.Drawing.Point(8, 176);
            this.groupBoxMeasuredGridSpace.Name = "groupBoxMeasuredGridSpace";
            this.groupBoxMeasuredGridSpace.Size = new Size(240, 80);
            this.groupBoxMeasuredGridSpace.TabIndex = 3;
            this.groupBoxMeasuredGridSpace.TabStop = false;
            this.groupBoxMeasuredGridSpace.Text = "间隔";
            this.lblYUnit.AutoSize = true;
            this.lblYUnit.Location = new System.Drawing.Point(152, 48);
            this.lblYUnit.Name = "lblYUnit";
            this.lblYUnit.Size = new Size(0, 17);
            this.lblYUnit.TabIndex = 5;
            this.lblXUnit.AutoSize = true;
            this.lblXUnit.Location = new System.Drawing.Point(152, 24);
            this.lblXUnit.Name = "lblXUnit";
            this.lblXUnit.Size = new Size(0, 17);
            this.lblXUnit.TabIndex = 4;
            this.txtMeasuredGridYSpace.EditValue = "";
            this.txtMeasuredGridYSpace.Location = new System.Drawing.Point(40, 48);
            this.txtMeasuredGridYSpace.Name = "txtMeasuredGridYSpace";
            this.txtMeasuredGridYSpace.Size = new Size(104, 23);
            this.txtMeasuredGridYSpace.TabIndex = 3;
            this.txtMeasuredGridXSpace.EditValue = "";
            this.txtMeasuredGridXSpace.Location = new System.Drawing.Point(40, 24);
            this.txtMeasuredGridXSpace.Name = "txtMeasuredGridXSpace";
            this.txtMeasuredGridXSpace.Size = new Size(104, 23);
            this.txtMeasuredGridXSpace.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(8, 52);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 17);
            this.label2.TabIndex = 1;
            this.label2.Text = "Y轴:";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(8, 29);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 0;
            this.label1.Text = "X轴:";
            this.groupBoxGraticuleStyle.Controls.Add(this.label14);
            this.groupBoxGraticuleStyle.Controls.Add(this.btnGraticulestyle);
            this.groupBoxGraticuleStyle.Controls.Add(this.rdoGraticuleStyle);
            this.groupBoxGraticuleStyle.Location = new System.Drawing.Point(8, 16);
            this.groupBoxGraticuleStyle.Name = "groupBoxGraticuleStyle";
            this.groupBoxGraticuleStyle.Size = new Size(240, 136);
            this.groupBoxGraticuleStyle.TabIndex = 2;
            this.groupBoxGraticuleStyle.TabStop = false;
            this.groupBoxGraticuleStyle.Text = "外观";
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(144, 24);
            this.label14.Name = "label14";
            this.label14.Size = new Size(29, 17);
            this.label14.TabIndex = 4;
            this.label14.Text = "样式";
            this.btnGraticulestyle.Location = new System.Drawing.Point(144, 48);
            this.btnGraticulestyle.Name = "btnGraticulestyle";
            this.btnGraticulestyle.Size = new Size(72, 25);
            this.btnGraticulestyle.Style = null;
            this.btnGraticulestyle.TabIndex = 3;
            this.btnGraticulestyle.Click += new EventHandler(this.btnGraticulestyle_Click);
            this.rdoGraticuleStyle.Location = new System.Drawing.Point(16, 24);
            this.rdoGraticuleStyle.Name = "rdoGraticuleStyle";
            this.rdoGraticuleStyle.Properties.Appearance.BackColor = SystemColors.InactiveBorder;
            this.rdoGraticuleStyle.Properties.Appearance.Options.UseBackColor = true;
            this.rdoGraticuleStyle.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoGraticuleStyle.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "只显示标注"), new RadioGroupItem(null, "刻度标志和标记"), new RadioGroupItem(null, "经纬网格和标注") });
            this.rdoGraticuleStyle.Size = new Size(160, 104);
            this.rdoGraticuleStyle.TabIndex = 0;
            this.rdoGraticuleStyle.SelectedIndexChanged += new EventHandler(this.rdoGraticuleStyle_SelectedIndexChanged);
            this.groupBoxMeasuredGridStyle.Controls.Add(this.label15);
            this.groupBoxMeasuredGridStyle.Controls.Add(this.btnMeasuredGridStyle);
            this.groupBoxMeasuredGridStyle.Controls.Add(this.rdoMeasuredGridStyle);
            this.groupBoxMeasuredGridStyle.Location = new System.Drawing.Point(8, 16);
            this.groupBoxMeasuredGridStyle.Name = "groupBoxMeasuredGridStyle";
            this.groupBoxMeasuredGridStyle.Size = new Size(240, 88);
            this.groupBoxMeasuredGridStyle.TabIndex = 4;
            this.groupBoxMeasuredGridStyle.TabStop = false;
            this.groupBoxMeasuredGridStyle.Text = "外观";
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(144, 16);
            this.label15.Name = "label15";
            this.label15.Size = new Size(29, 17);
            this.label15.TabIndex = 5;
            this.label15.Text = "样式";
            this.btnMeasuredGridStyle.Location = new System.Drawing.Point(144, 40);
            this.btnMeasuredGridStyle.Name = "btnMeasuredGridStyle";
            this.btnMeasuredGridStyle.Size = new Size(72, 25);
            this.btnMeasuredGridStyle.Style = null;
            this.btnMeasuredGridStyle.TabIndex = 3;
            this.btnMeasuredGridStyle.Click += new EventHandler(this.btnMeasuredGridStyle_Click);
            this.rdoMeasuredGridStyle.Location = new System.Drawing.Point(8, 16);
            this.rdoMeasuredGridStyle.Name = "rdoMeasuredGridStyle";
            this.rdoMeasuredGridStyle.Properties.Appearance.BackColor = SystemColors.InactiveBorder;
            this.rdoMeasuredGridStyle.Properties.Appearance.Options.UseBackColor = true;
            this.rdoMeasuredGridStyle.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoMeasuredGridStyle.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "只显示标注"), new RadioGroupItem(null, "刻度标志和标记"), new RadioGroupItem(null, "格网和标注") });
            this.rdoMeasuredGridStyle.Size = new Size(160, 64);
            this.rdoMeasuredGridStyle.TabIndex = 0;
            this.rdoMeasuredGridStyle.SelectedIndexChanged += new EventHandler(this.rdoMeasuredGridStyle_SelectedIndexChanged);
            this.groupBoxCoordinate.Controls.Add(this.btnSpatialReference);
            this.groupBoxCoordinate.Controls.Add(this.txtSpatialReference);
            this.groupBoxCoordinate.Location = new System.Drawing.Point(8, 107);
            this.groupBoxCoordinate.Name = "groupBoxCoordinate";
            this.groupBoxCoordinate.Size = new Size(240, 64);
            this.groupBoxCoordinate.TabIndex = 5;
            this.groupBoxCoordinate.TabStop = false;
            this.groupBoxCoordinate.Text = "坐标系";
            this.btnSpatialReference.Location = new System.Drawing.Point(160, 24);
            this.btnSpatialReference.Name = "btnSpatialReference";
            this.btnSpatialReference.Size = new Size(48, 24);
            this.btnSpatialReference.TabIndex = 1;
            this.btnSpatialReference.Text = "属性...";
            this.btnSpatialReference.Click += new EventHandler(this.btnSpatialReference_Click);
            this.txtSpatialReference.EditValue = "";
            this.txtSpatialReference.Location = new System.Drawing.Point(16, 16);
            this.txtSpatialReference.Name = "txtSpatialReference";
            this.txtSpatialReference.Size = new Size(128, 40);
            this.txtSpatialReference.TabIndex = 0;
            this.groupBoxGraticuleSpace.Controls.Add(this.label9);
            this.groupBoxGraticuleSpace.Controls.Add(this.label8);
            this.groupBoxGraticuleSpace.Controls.Add(this.label7);
            this.groupBoxGraticuleSpace.Controls.Add(this.txtHatchIntervalYSecond);
            this.groupBoxGraticuleSpace.Controls.Add(this.txtHatchIntervalYMinute);
            this.groupBoxGraticuleSpace.Controls.Add(this.txtHatchIntervalXSecond);
            this.groupBoxGraticuleSpace.Controls.Add(this.txtHatchIntervalXMinute);
            this.groupBoxGraticuleSpace.Controls.Add(this.label3);
            this.groupBoxGraticuleSpace.Controls.Add(this.label4);
            this.groupBoxGraticuleSpace.Controls.Add(this.txtHatchIntervalYDegree);
            this.groupBoxGraticuleSpace.Controls.Add(this.txtHatchIntervalXDegree);
            this.groupBoxGraticuleSpace.Controls.Add(this.label5);
            this.groupBoxGraticuleSpace.Controls.Add(this.label6);
            this.groupBoxGraticuleSpace.Location = new System.Drawing.Point(8, 152);
            this.groupBoxGraticuleSpace.Name = "groupBoxGraticuleSpace";
            this.groupBoxGraticuleSpace.Size = new Size(240, 104);
            this.groupBoxGraticuleSpace.TabIndex = 6;
            this.groupBoxGraticuleSpace.TabStop = false;
            this.groupBoxGraticuleSpace.Text = "间隔";
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(184, 20);
            this.label9.Name = "label9";
            this.label9.Size = new Size(17, 17);
            this.label9.TabIndex = 12;
            this.label9.Text = "秒";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(144, 20);
            this.label8.Name = "label8";
            this.label8.Size = new Size(17, 17);
            this.label8.TabIndex = 11;
            this.label8.Text = "分";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(99, 20);
            this.label7.Name = "label7";
            this.label7.Size = new Size(17, 17);
            this.label7.TabIndex = 10;
            this.label7.Text = "度";
            this.txtHatchIntervalYSecond.EditValue = "";
            this.txtHatchIntervalYSecond.Location = new System.Drawing.Point(168, 72);
            this.txtHatchIntervalYSecond.Name = "txtHatchIntervalYSecond";
            this.txtHatchIntervalYSecond.Size = new Size(32, 23);
            this.txtHatchIntervalYSecond.TabIndex = 9;
            this.txtHatchIntervalYMinute.EditValue = "";
            this.txtHatchIntervalYMinute.Location = new System.Drawing.Point(128, 72);
            this.txtHatchIntervalYMinute.Name = "txtHatchIntervalYMinute";
            this.txtHatchIntervalYMinute.Size = new Size(32, 23);
            this.txtHatchIntervalYMinute.TabIndex = 8;
            this.txtHatchIntervalXSecond.EditValue = "";
            this.txtHatchIntervalXSecond.Location = new System.Drawing.Point(168, 40);
            this.txtHatchIntervalXSecond.Name = "txtHatchIntervalXSecond";
            this.txtHatchIntervalXSecond.Size = new Size(32, 23);
            this.txtHatchIntervalXSecond.TabIndex = 7;
            this.txtHatchIntervalXMinute.EditValue = "";
            this.txtHatchIntervalXMinute.Location = new System.Drawing.Point(128, 40);
            this.txtHatchIntervalXMinute.Name = "txtHatchIntervalXMinute";
            this.txtHatchIntervalXMinute.Size = new Size(32, 23);
            this.txtHatchIntervalXMinute.TabIndex = 6;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(168, 64);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0, 17);
            this.label3.TabIndex = 5;
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(168, 40);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0, 17);
            this.label4.TabIndex = 4;
            this.txtHatchIntervalYDegree.EditValue = "";
            this.txtHatchIntervalYDegree.Location = new System.Drawing.Point(72, 72);
            this.txtHatchIntervalYDegree.Name = "txtHatchIntervalYDegree";
            this.txtHatchIntervalYDegree.Size = new Size(48, 23);
            this.txtHatchIntervalYDegree.TabIndex = 3;
            this.txtHatchIntervalXDegree.EditValue = "";
            this.txtHatchIntervalXDegree.Location = new System.Drawing.Point(72, 40);
            this.txtHatchIntervalXDegree.Name = "txtHatchIntervalXDegree";
            this.txtHatchIntervalXDegree.Size = new Size(48, 23);
            this.txtHatchIntervalXDegree.TabIndex = 2;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(24, 72);
            this.label5.Name = "label5";
            this.label5.Size = new Size(29, 17);
            this.label5.TabIndex = 1;
            this.label5.Text = "经度";
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(24, 42);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 17);
            this.label6.TabIndex = 0;
            this.label6.Text = "纬度";
            this.groupBoxIndexGridSpace.Controls.Add(this.label10);
            this.groupBoxIndexGridSpace.Controls.Add(this.label11);
            this.groupBoxIndexGridSpace.Controls.Add(this.txtRowCount);
            this.groupBoxIndexGridSpace.Controls.Add(this.txtColumnCount);
            this.groupBoxIndexGridSpace.Controls.Add(this.label12);
            this.groupBoxIndexGridSpace.Controls.Add(this.label13);
            this.groupBoxIndexGridSpace.Location = new System.Drawing.Point(8, 160);
            this.groupBoxIndexGridSpace.Name = "groupBoxIndexGridSpace";
            this.groupBoxIndexGridSpace.Size = new Size(240, 80);
            this.groupBoxIndexGridSpace.TabIndex = 7;
            this.groupBoxIndexGridSpace.TabStop = false;
            this.groupBoxIndexGridSpace.Text = "间隔";
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(152, 48);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0, 17);
            this.label10.TabIndex = 5;
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(152, 24);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0, 17);
            this.label11.TabIndex = 4;
            this.txtRowCount.EditValue = "";
            this.txtRowCount.Location = new System.Drawing.Point(40, 48);
            this.txtRowCount.Name = "txtRowCount";
            this.txtRowCount.Size = new Size(104, 23);
            this.txtRowCount.TabIndex = 3;
            this.txtColumnCount.EditValue = "";
            this.txtColumnCount.Location = new System.Drawing.Point(40, 24);
            this.txtColumnCount.Name = "txtColumnCount";
            this.txtColumnCount.Size = new Size(104, 23);
            this.txtColumnCount.TabIndex = 2;
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(8, 52);
            this.label12.Name = "label12";
            this.label12.Size = new Size(17, 17);
            this.label12.TabIndex = 1;
            this.label12.Text = "行";
            this.label13.AutoSize = true;
            this.label13.Location = new System.Drawing.Point(8, 29);
            this.label13.Name = "label13";
            this.label13.Size = new Size(17, 17);
            this.label13.TabIndex = 0;
            this.label13.Text = "列";
            this.groupBoxIndexGridStyle.Controls.Add(this.label16);
            this.groupBoxIndexGridStyle.Controls.Add(this.btnIndexGridStyle);
            this.groupBoxIndexGridStyle.Controls.Add(this.rdoIndexGridStyle);
            this.groupBoxIndexGridStyle.Location = new System.Drawing.Point(8, 16);
            this.groupBoxIndexGridStyle.Name = "groupBoxIndexGridStyle";
            this.groupBoxIndexGridStyle.Size = new Size(240, 128);
            this.groupBoxIndexGridStyle.TabIndex = 8;
            this.groupBoxIndexGridStyle.TabStop = false;
            this.groupBoxIndexGridStyle.Text = "外观";
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(144, 32);
            this.label16.Name = "label16";
            this.label16.Size = new Size(29, 17);
            this.label16.TabIndex = 5;
            this.label16.Text = "样式";
            this.btnIndexGridStyle.Location = new System.Drawing.Point(136, 64);
            this.btnIndexGridStyle.Name = "btnIndexGridStyle";
            this.btnIndexGridStyle.Size = new Size(72, 25);
            this.btnIndexGridStyle.Style = null;
            this.btnIndexGridStyle.TabIndex = 3;
            this.btnIndexGridStyle.Click += new EventHandler(this.btnIndexGridStyle_Click);
            this.rdoIndexGridStyle.Location = new System.Drawing.Point(8, 16);
            this.rdoIndexGridStyle.Name = "rdoIndexGridStyle";
            this.rdoIndexGridStyle.Properties.Appearance.BackColor = SystemColors.InactiveBorder;
            this.rdoIndexGridStyle.Properties.Appearance.Options.UseBackColor = true;
            this.rdoIndexGridStyle.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoIndexGridStyle.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "只显示索引标签"), new RadioGroupItem(null, "格网和索引标签") });
            this.rdoIndexGridStyle.Size = new Size(160, 88);
            this.rdoIndexGridStyle.TabIndex = 0;
            this.rdoIndexGridStyle.SelectedIndexChanged += new EventHandler(this.rdoIndexGridStyle_SelectedIndexChanged);
            base.Controls.Add(this.groupBoxIndexGridStyle);
            base.Controls.Add(this.groupBoxIndexGridSpace);
            base.Controls.Add(this.groupBoxGraticuleSpace);
            base.Controls.Add(this.groupBoxCoordinate);
            base.Controls.Add(this.groupBoxMeasuredGridStyle);
            base.Controls.Add(this.groupBoxMeasuredGridSpace);
            base.Controls.Add(this.groupBoxGraticuleStyle);
            base.Name = "MapGridStylePropertyPage";
            base.Size = new Size(272, 272);
            base.Load += new EventHandler(this.MapGridStylePropertyPage_Load);
            this.groupBoxMeasuredGridSpace.ResumeLayout(false);
            this.txtMeasuredGridYSpace.Properties.EndInit();
            this.txtMeasuredGridXSpace.Properties.EndInit();
            this.groupBoxGraticuleStyle.ResumeLayout(false);
            this.rdoGraticuleStyle.Properties.EndInit();
            this.groupBoxMeasuredGridStyle.ResumeLayout(false);
            this.rdoMeasuredGridStyle.Properties.EndInit();
            this.groupBoxCoordinate.ResumeLayout(false);
            this.txtSpatialReference.Properties.EndInit();
            this.groupBoxGraticuleSpace.ResumeLayout(false);
            this.txtHatchIntervalYSecond.Properties.EndInit();
            this.txtHatchIntervalYMinute.Properties.EndInit();
            this.txtHatchIntervalXSecond.Properties.EndInit();
            this.txtHatchIntervalXMinute.Properties.EndInit();
            this.txtHatchIntervalYDegree.Properties.EndInit();
            this.txtHatchIntervalXDegree.Properties.EndInit();
            this.groupBoxIndexGridSpace.ResumeLayout(false);
            this.txtRowCount.Properties.EndInit();
            this.txtColumnCount.Properties.EndInit();
            this.groupBoxIndexGridStyle.ResumeLayout(false);
            this.rdoIndexGridStyle.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private StyleButton btnGraticulestyle;
        private StyleButton btnIndexGridStyle;
        private StyleButton btnMeasuredGridStyle;
        private SimpleButton btnSpatialReference;
        private GroupBox groupBoxCoordinate;
        private GroupBox groupBoxGraticuleSpace;
        private GroupBox groupBoxGraticuleStyle;
        private GroupBox groupBoxIndexGridSpace;
        private GroupBox groupBoxIndexGridStyle;
        private GroupBox groupBoxMeasuredGridSpace;
        private GroupBox groupBoxMeasuredGridStyle;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label lblXUnit;
        private Label lblYUnit;
        private RadioGroup rdoGraticuleStyle;
        private RadioGroup rdoIndexGridStyle;
        private RadioGroup rdoMeasuredGridStyle;
        private TextEdit txtColumnCount;
        private TextEdit txtHatchIntervalXDegree;
        private TextEdit txtHatchIntervalXMinute;
        private TextEdit txtHatchIntervalXSecond;
        private TextEdit txtHatchIntervalYDegree;
        private TextEdit txtHatchIntervalYMinute;
        private TextEdit txtHatchIntervalYSecond;
        private TextEdit txtMeasuredGridXSpace;
        private TextEdit txtMeasuredGridYSpace;
        private TextEdit txtRowCount;
        private MemoEdit txtSpatialReference;
    }
}