using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class NumberAndLabelPropertyPage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
 private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.label8 = new Label();
            this.btnLabelSymbolSelector = new SimpleButton();
            this.txtLabelGap = new SpinEdit();
            this.label6 = new Label();
            this.cboMarkPosition = new ComboBoxEdit();
            this.label4 = new Label();
            this.cboMarkFrequency = new ComboBoxEdit();
            this.label1 = new Label();
            this.groupBox2 = new GroupBox();
            this.btnSubdivisionMarkSymbol = new SimpleButton();
            this.txtSubdivisionMarkHeight = new SpinEdit();
            this.lblsubMarkHeight = new Label();
            this.btnDivisionMarkSymbol = new SimpleButton();
            this.txtDivisionMarkHeight = new SpinEdit();
            this.lblMarkHeight = new Label();
            this.cboLabelPosition = new ComboBoxEdit();
            this.lblPosition = new Label();
            this.cboLabelFrequency = new ComboBoxEdit();
            this.label5 = new Label();
            this.groupBox1.SuspendLayout();
            this.txtLabelGap.Properties.BeginInit();
            this.cboMarkPosition.Properties.BeginInit();
            this.cboMarkFrequency.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.txtSubdivisionMarkHeight.Properties.BeginInit();
            this.txtDivisionMarkHeight.Properties.BeginInit();
            this.cboLabelPosition.Properties.BeginInit();
            this.cboLabelFrequency.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.btnLabelSymbolSelector);
            this.groupBox1.Controls.Add(this.txtLabelGap);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.cboMarkPosition);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.cboMarkFrequency);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(232, 136);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "数字";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(112, 72);
            this.label8.Name = "label8";
            this.label8.Size = new Size(17, 17);
            this.label8.TabIndex = 19;
            this.label8.Text = "点";
            this.btnLabelSymbolSelector.Location = new Point(176, 8);
            this.btnLabelSymbolSelector.Name = "btnLabelSymbolSelector";
            this.btnLabelSymbolSelector.Size = new Size(48, 24);
            this.btnLabelSymbolSelector.TabIndex = 18;
            this.btnLabelSymbolSelector.Text = "符号";
            this.btnLabelSymbolSelector.Visible = false;
            this.btnLabelSymbolSelector.Click += new EventHandler(this.btnLabelSymbolSelector_Click);
            this.txtLabelGap.EditValue = 0;
            this.txtLabelGap.Location = new Point(48, 72);
            this.txtLabelGap.Name = "txtLabelGap";
            this.txtLabelGap.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtLabelGap.Properties.UseCtrlIncrement = false;
            this.txtLabelGap.Size = new Size(56, 21);
            this.txtLabelGap.TabIndex = 17;
            this.txtLabelGap.EditValueChanged += new EventHandler(this.txtLabelGap_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(8, 72);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 17);
            this.label6.TabIndex = 16;
            this.label6.Text = "间隔";
            this.cboMarkPosition.EditValue = "";
            this.cboMarkPosition.Location = new Point(48, 45);
            this.cboMarkPosition.Name = "cboMarkPosition";
            this.cboMarkPosition.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboMarkPosition.Properties.Items.AddRange(new object[] { "在比例尺上面", "在标记前面", "在标记后面", "在比例尺前面", "在比例尺后面", "在比例尺下面" });
            this.cboMarkPosition.Size = new Size(168, 21);
            this.cboMarkPosition.TabIndex = 12;
            this.cboMarkPosition.SelectedIndexChanged += new EventHandler(this.cboMarkPosition_SelectedIndexChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(8, 48);
            this.label4.Name = "label4";
            this.label4.Size = new Size(29, 17);
            this.label4.TabIndex = 11;
            this.label4.Text = "位置";
            this.cboMarkFrequency.EditValue = "";
            this.cboMarkFrequency.Location = new Point(48, 17);
            this.cboMarkFrequency.Name = "cboMarkFrequency";
            this.cboMarkFrequency.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboMarkFrequency.Properties.Items.AddRange(new object[] { "无标注", "单个标注", "标注在尾段", "中分标注", "中分标注且第一段中间点标注", "中分标注且第一段标注下一级", "中分标注且标注下一级", "" });
            this.cboMarkFrequency.Size = new Size(168, 21);
            this.cboMarkFrequency.TabIndex = 1;
            this.cboMarkFrequency.SelectedIndexChanged += new EventHandler(this.cboMarkFrequency_SelectedIndexChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 22);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 0;
            this.label1.Text = "频率";
            this.groupBox2.Controls.Add(this.btnSubdivisionMarkSymbol);
            this.groupBox2.Controls.Add(this.txtSubdivisionMarkHeight);
            this.groupBox2.Controls.Add(this.lblsubMarkHeight);
            this.groupBox2.Controls.Add(this.btnDivisionMarkSymbol);
            this.groupBox2.Controls.Add(this.txtDivisionMarkHeight);
            this.groupBox2.Controls.Add(this.lblMarkHeight);
            this.groupBox2.Controls.Add(this.cboLabelPosition);
            this.groupBox2.Controls.Add(this.lblPosition);
            this.groupBox2.Controls.Add(this.cboLabelFrequency);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Location = new Point(8, 152);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(232, 184);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "标记";
            this.btnSubdivisionMarkSymbol.Location = new Point(152, 144);
            this.btnSubdivisionMarkSymbol.Name = "btnSubdivisionMarkSymbol";
            this.btnSubdivisionMarkSymbol.Size = new Size(48, 24);
            this.btnSubdivisionMarkSymbol.TabIndex = 21;
            this.btnSubdivisionMarkSymbol.Text = "符号";
            this.btnSubdivisionMarkSymbol.Click += new EventHandler(this.btnSubdivisionMarkSymbol_Click);
            this.txtSubdivisionMarkHeight.EditValue = 0;
            this.txtSubdivisionMarkHeight.Location = new Point(80, 144);
            this.txtSubdivisionMarkHeight.Name = "txtSubdivisionMarkHeight";
            this.txtSubdivisionMarkHeight.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtSubdivisionMarkHeight.Properties.UseCtrlIncrement = false;
            this.txtSubdivisionMarkHeight.Size = new Size(64, 21);
            this.txtSubdivisionMarkHeight.TabIndex = 20;
            this.txtSubdivisionMarkHeight.EditValueChanged += new EventHandler(this.txtSubdivisionMarkHeight_EditValueChanged);
            this.lblsubMarkHeight.AutoSize = true;
            this.lblsubMarkHeight.Location = new Point(8, 146);
            this.lblsubMarkHeight.Name = "lblsubMarkHeight";
            this.lblsubMarkHeight.Size = new Size(66, 17);
            this.lblsubMarkHeight.TabIndex = 19;
            this.lblsubMarkHeight.Text = "子刻度高度";
            this.btnDivisionMarkSymbol.Location = new Point(152, 113);
            this.btnDivisionMarkSymbol.Name = "btnDivisionMarkSymbol";
            this.btnDivisionMarkSymbol.Size = new Size(48, 24);
            this.btnDivisionMarkSymbol.TabIndex = 18;
            this.btnDivisionMarkSymbol.Text = "符号";
            this.btnDivisionMarkSymbol.Click += new EventHandler(this.btnDivisionMarkSymbol_Click);
            this.txtDivisionMarkHeight.EditValue = 0;
            this.txtDivisionMarkHeight.Location = new Point(80, 114);
            this.txtDivisionMarkHeight.Name = "txtDivisionMarkHeight";
            this.txtDivisionMarkHeight.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtDivisionMarkHeight.Properties.UseCtrlIncrement = false;
            this.txtDivisionMarkHeight.Size = new Size(64, 21);
            this.txtDivisionMarkHeight.TabIndex = 17;
            this.txtDivisionMarkHeight.EditValueChanged += new EventHandler(this.txtDivisionMarkHeight_EditValueChanged);
            this.lblMarkHeight.AutoSize = true;
            this.lblMarkHeight.Location = new Point(8, 120);
            this.lblMarkHeight.Name = "lblMarkHeight";
            this.lblMarkHeight.Size = new Size(54, 17);
            this.lblMarkHeight.TabIndex = 16;
            this.lblMarkHeight.Text = "刻度高度";
            this.cboLabelPosition.EditValue = "";
            this.cboLabelPosition.Location = new Point(8, 87);
            this.cboLabelPosition.Name = "cboLabelPosition";
            this.cboLabelPosition.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboLabelPosition.Properties.Items.AddRange(new object[] { "在比例尺上面", "在标记前面", "在标记后面", "在比例尺前面", "在比例尺后面", "在比例尺下面" });
            this.cboLabelPosition.Size = new Size(208, 21);
            this.cboLabelPosition.TabIndex = 12;
            this.cboLabelPosition.SelectedIndexChanged += new EventHandler(this.cboLabelPosition_SelectedIndexChanged);
            this.lblPosition.AutoSize = true;
            this.lblPosition.Location = new Point(8, 67);
            this.lblPosition.Name = "lblPosition";
            this.lblPosition.Size = new Size(29, 17);
            this.lblPosition.TabIndex = 11;
            this.lblPosition.Text = "位置";
            this.cboLabelFrequency.EditValue = "";
            this.cboLabelFrequency.Location = new Point(8, 39);
            this.cboLabelFrequency.Name = "cboLabelFrequency";
            this.cboLabelFrequency.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboLabelFrequency.Properties.Items.AddRange(new object[] { "无标注", "单个标注", "标注在尾段", "中分标注", "中分标注且第一段中间点标注", "中分标注且第一段标注下一级", "中分标注且标注下一级", "" });
            this.cboLabelFrequency.Size = new Size(208, 21);
            this.cboLabelFrequency.TabIndex = 1;
            this.cboLabelFrequency.SelectedIndexChanged += new EventHandler(this.cboLabelFrequency_SelectedIndexChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(8, 21);
            this.label5.Name = "label5";
            this.label5.Size = new Size(29, 17);
            this.label5.TabIndex = 0;
            this.label5.Text = "频率";
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "NumberAndLabelPropertyPage";
            base.Size = new Size(248, 352);
            base.Load += new EventHandler(this.NumberAndLabelPropertyPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.txtLabelGap.Properties.EndInit();
            this.cboMarkPosition.Properties.EndInit();
            this.cboMarkFrequency.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.txtSubdivisionMarkHeight.Properties.EndInit();
            this.txtDivisionMarkHeight.Properties.EndInit();
            this.cboLabelPosition.Properties.EndInit();
            this.cboLabelFrequency.Properties.EndInit();
            base.ResumeLayout(false);
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private SimpleButton btnDivisionMarkSymbol;
        private SimpleButton btnLabelSymbolSelector;
        private SimpleButton btnSubdivisionMarkSymbol;
        private ComboBoxEdit cboLabelFrequency;
        private ComboBoxEdit cboLabelPosition;
        private ComboBoxEdit cboMarkFrequency;
        private ComboBoxEdit cboMarkPosition;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private Label label1;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label8;
        private Label lblMarkHeight;
        private Label lblPosition;
        private Label lblsubMarkHeight;
        private SpinEdit txtDivisionMarkHeight;
        private SpinEdit txtLabelGap;
        private SpinEdit txtSubdivisionMarkHeight;
    }
}