using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using Yutai.Shared;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class ProportionalSymbolRendererCtrl
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.cboNormFields = new ComboBoxEdit();
            this.cboValueFields = new ComboBoxEdit();
            this.label2 = new Label();
            this.label1 = new Label();
            this.label5 = new Label();
            this.SymbolgroupBox1 = new GroupBox();
            this.chkFlannery = new CheckEdit();
            this.groupBox5 = new GroupBox();
            this.symbolItem1 = new SymbolItem();
            this.groupBox4 = new GroupBox();
            this.btnMinSymbol = new StyleButton();
            this.groupBoxBackgroundSymbol = new GroupBox();
            this.btnBackground = new StyleButton();
            this.SymbolgroupBox2 = new GroupBox();
            this.groupBox6 = new GroupBox();
            this.symbolItem2 = new SymbolItem();
            this.groupBox7 = new GroupBox();
            this.btnLineMinSymbol = new StyleButton();
            this.label3 = new Label();
            this.groupBox2 = new GroupBox();
            this.btnDataExclusion = new SimpleButton();
            this.cboLegendCount = new ComboBoxEdit();
            this.cboValueUnit = new ComboBoxEdit();
            this.groupBox1.SuspendLayout();
            this.cboNormFields.Properties.BeginInit();
            this.cboValueFields.Properties.BeginInit();
            this.SymbolgroupBox1.SuspendLayout();
            this.chkFlannery.Properties.BeginInit();
            this.groupBox5.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBoxBackgroundSymbol.SuspendLayout();
            this.SymbolgroupBox2.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.cboLegendCount.Properties.BeginInit();
            this.cboValueUnit.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.cboNormFields);
            this.groupBox1.Controls.Add(this.cboValueFields);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new System.Drawing.Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(248, 80);
            this.groupBox1.TabIndex = 40;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "字段";
            this.cboNormFields.EditValue = "";
            this.cboNormFields.Location = new System.Drawing.Point(88, 45);
            this.cboNormFields.Name = "cboNormFields";
            this.cboNormFields.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboNormFields.Size = new Size(152, 23);
            this.cboNormFields.TabIndex = 48;
            this.cboNormFields.SelectedIndexChanged += new EventHandler(this.cboNormFields_SelectedIndexChanged);
            this.cboValueFields.EditValue = "";
            this.cboValueFields.Location = new System.Drawing.Point(88, 13);
            this.cboValueFields.Name = "cboValueFields";
            this.cboValueFields.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboValueFields.Size = new Size(152, 23);
            this.cboValueFields.TabIndex = 47;
            this.cboValueFields.SelectedIndexChanged += new EventHandler(this.cboValueFields_SelectedIndexChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(8, 48);
            this.label2.Name = "label2";
            this.label2.Size = new Size(66, 17);
            this.label2.TabIndex = 39;
            this.label2.Text = "正则化字段";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(8, 18);
            this.label1.Name = "label1";
            this.label1.Size = new Size(42, 17);
            this.label1.TabIndex = 38;
            this.label1.Text = "值字段";
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(8, 96);
            this.label5.Name = "label5";
            this.label5.Size = new Size(42, 17);
            this.label5.TabIndex = 43;
            this.label5.Text = "值单位";
            this.SymbolgroupBox1.Controls.Add(this.chkFlannery);
            this.SymbolgroupBox1.Controls.Add(this.groupBox5);
            this.SymbolgroupBox1.Controls.Add(this.groupBox4);
            this.SymbolgroupBox1.Controls.Add(this.groupBoxBackgroundSymbol);
            this.SymbolgroupBox1.Location = new System.Drawing.Point(8, 120);
            this.SymbolgroupBox1.Name = "SymbolgroupBox1";
            this.SymbolgroupBox1.Size = new Size(288, 112);
            this.SymbolgroupBox1.TabIndex = 44;
            this.SymbolgroupBox1.TabStop = false;
            this.SymbolgroupBox1.Text = "符号";
            this.SymbolgroupBox1.Visible = false;
            this.chkFlannery.Location = new System.Drawing.Point(8, 80);
            this.chkFlannery.Name = "chkFlannery";
            this.chkFlannery.Properties.Caption = "外观补偿";
            this.chkFlannery.Size = new Size(80, 19);
            this.chkFlannery.TabIndex = 40;
            this.chkFlannery.CheckedChanged += new EventHandler(this.chkFlannery_CheckedChanged);
            this.groupBox5.Controls.Add(this.symbolItem1);
            this.groupBox5.Location = new System.Drawing.Point(184, 19);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(96, 85);
            this.groupBox5.TabIndex = 2;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "最大值";
            this.symbolItem1.BackColor = SystemColors.ControlLight;
            this.symbolItem1.Location = new System.Drawing.Point(9, 18);
            this.symbolItem1.Name = "symbolItem1";
            this.symbolItem1.Size = new Size(80, 56);
            this.symbolItem1.Symbol = null;
            this.symbolItem1.TabIndex = 0;
            this.groupBox4.Controls.Add(this.btnMinSymbol);
            this.groupBox4.Location = new System.Drawing.Point(96, 19);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(80, 53);
            this.groupBox4.TabIndex = 1;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "最小值";
            this.btnMinSymbol.Location = new System.Drawing.Point(8, 20);
            this.btnMinSymbol.Name = "btnMinSymbol";
            this.btnMinSymbol.Size = new Size(64, 24);
            this.btnMinSymbol.Style = null;
            this.btnMinSymbol.TabIndex = 42;
            this.btnMinSymbol.Click += new EventHandler(this.btnMinSymbol_Click);
            this.groupBoxBackgroundSymbol.Controls.Add(this.btnBackground);
            this.groupBoxBackgroundSymbol.Location = new System.Drawing.Point(8, 19);
            this.groupBoxBackgroundSymbol.Name = "groupBoxBackgroundSymbol";
            this.groupBoxBackgroundSymbol.Size = new Size(80, 53);
            this.groupBoxBackgroundSymbol.TabIndex = 0;
            this.groupBoxBackgroundSymbol.TabStop = false;
            this.groupBoxBackgroundSymbol.Text = "背景";
            this.btnBackground.Location = new System.Drawing.Point(8, 20);
            this.btnBackground.Name = "btnBackground";
            this.btnBackground.Size = new Size(64, 24);
            this.btnBackground.Style = null;
            this.btnBackground.TabIndex = 42;
            this.btnBackground.Click += new EventHandler(this.btnBackground_Click);
            this.SymbolgroupBox2.Controls.Add(this.groupBox6);
            this.SymbolgroupBox2.Controls.Add(this.groupBox7);
            this.SymbolgroupBox2.Location = new System.Drawing.Point(8, 120);
            this.SymbolgroupBox2.Name = "SymbolgroupBox2";
            this.SymbolgroupBox2.Size = new Size(208, 112);
            this.SymbolgroupBox2.TabIndex = 45;
            this.SymbolgroupBox2.TabStop = false;
            this.SymbolgroupBox2.Text = "符号";
            this.SymbolgroupBox2.Visible = false;
            this.groupBox6.Controls.Add(this.symbolItem2);
            this.groupBox6.Location = new System.Drawing.Point(96, 16);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new Size(96, 85);
            this.groupBox6.TabIndex = 2;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "最大值";
            this.symbolItem2.BackColor = SystemColors.ControlLight;
            this.symbolItem2.Location = new System.Drawing.Point(8, 19);
            this.symbolItem2.Name = "symbolItem2";
            this.symbolItem2.Size = new Size(80, 56);
            this.symbolItem2.Symbol = null;
            this.symbolItem2.TabIndex = 1;
            this.groupBox7.Controls.Add(this.btnLineMinSymbol);
            this.groupBox7.Location = new System.Drawing.Point(8, 16);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new Size(80, 53);
            this.groupBox7.TabIndex = 1;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "最小值";
            this.btnLineMinSymbol.Location = new System.Drawing.Point(8, 20);
            this.btnLineMinSymbol.Name = "btnLineMinSymbol";
            this.btnLineMinSymbol.Size = new Size(64, 24);
            this.btnLineMinSymbol.Style = null;
            this.btnLineMinSymbol.TabIndex = 42;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(8, 240);
            this.label3.Name = "label3";
            this.label3.Size = new Size(116, 17);
            this.label3.TabIndex = 47;
            this.label3.Text = "图例中显示的符号数";
            this.groupBox2.Controls.Add(this.btnDataExclusion);
            this.groupBox2.Location = new System.Drawing.Point(272, 8);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(128, 80);
            this.groupBox2.TabIndex = 48;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "数据";
            this.btnDataExclusion.Location = new System.Drawing.Point(32, 32);
            this.btnDataExclusion.Name = "btnDataExclusion";
            this.btnDataExclusion.Size = new Size(64, 32);
            this.btnDataExclusion.TabIndex = 0;
            this.btnDataExclusion.Text = "排除...";
            this.btnDataExclusion.Click += new EventHandler(this.btnDataExclusion_Click);
            this.cboLegendCount.EditValue = "";
            this.cboLegendCount.Location = new System.Drawing.Point(128, 237);
            this.cboLegendCount.Name = "cboLegendCount";
            this.cboLegendCount.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboLegendCount.Properties.Items.AddRange(new object[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" });
            this.cboLegendCount.Size = new Size(152, 23);
            this.cboLegendCount.TabIndex = 50;
            this.cboLegendCount.SelectedIndexChanged += new EventHandler(this.cboLegendCount_SelectedIndexChanged);
            this.cboValueUnit.EditValue = "";
            this.cboValueUnit.Location = new System.Drawing.Point(70, 92);
            this.cboValueUnit.Name = "cboValueUnit";
            this.cboValueUnit.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboValueUnit.Properties.Items.AddRange(new object[] { "未知单位", "英寸", "点", "英尺", "码", "英里", "海里", "毫米", "厘米", "米", "公里", "十进制度", "分米" });
            this.cboValueUnit.Size = new Size(152, 23);
            this.cboValueUnit.TabIndex = 49;
            this.cboValueUnit.SelectedIndexChanged += new EventHandler(this.cboValueUnit_SelectedIndexChanged);
            base.Controls.Add(this.cboLegendCount);
            base.Controls.Add(this.cboValueUnit);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.SymbolgroupBox1);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.SymbolgroupBox2);
            base.Name = "ProportionalSymbolRendererCtrl";
            base.Size = new Size(416, 264);
            base.Load += new EventHandler(this.ProportionalSymbolRendererCtrl_Load);
            this.groupBox1.ResumeLayout(false);
            this.cboNormFields.Properties.EndInit();
            this.cboValueFields.Properties.EndInit();
            this.SymbolgroupBox1.ResumeLayout(false);
            this.chkFlannery.Properties.EndInit();
            this.groupBox5.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBoxBackgroundSymbol.ResumeLayout(false);
            this.SymbolgroupBox2.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox7.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.cboLegendCount.Properties.EndInit();
            this.cboValueUnit.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private StyleButton btnBackground;
        private SimpleButton btnDataExclusion;
        private StyleButton btnLineMinSymbol;
        private StyleButton btnMinSymbol;
        private ComboBoxEdit cboLegendCount;
        private ComboBoxEdit cboNormFields;
        private ComboBoxEdit cboValueFields;
        private ComboBoxEdit cboValueUnit;
        private CheckEdit chkFlannery;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox4;
        private GroupBox groupBox5;
        private GroupBox groupBox6;
        private GroupBox groupBox7;
        private GroupBox groupBoxBackgroundSymbol;
        private IProportionalSymbolRenderer iproportionalSymbolRenderer_0;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label5;
        private GroupBox SymbolgroupBox1;
        private GroupBox SymbolgroupBox2;
        private SymbolItem symbolItem1;
        private SymbolItem symbolItem2;
    }
}