using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geodatabase;
using Yutai.ArcGIS.Common.Carto;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.Shared;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class RasterClassifiedRenderPage
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
 private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            this.cboColorRamp = new StyleComboBox(this.icontainer_0);
            this.label2 = new Label();
            this.colorEdit1 = new ColorEdit();
            this.label1 = new Label();
            this.Classifygroup = new GroupBox();
            this.cboClassifyNum = new ComboBoxEdit();
            this.cboClassifyMethod = new ComboBoxEdit();
            this.label4 = new Label();
            this.label5 = new Label();
            this.listView1 = new RenderInfoListView();
            this.columnHeader_0 = new ColumnHeader();
            this.columnHeader_1 = new ColumnHeader();
            this.columnHeader_2 = new ColumnHeader();
            this.groupBox1 = new GroupBox();
            this.cboNormFields = new ComboBoxEdit();
            this.cboValueFields = new ComboBoxEdit();
            this.label3 = new Label();
            this.label6 = new Label();
            this.checkBox1 = new CheckBox();
            this.txtZFactor = new TextBox();
            this.lblZFactor = new Label();
            this.colorEdit1.Properties.BeginInit();
            this.Classifygroup.SuspendLayout();
            this.cboClassifyNum.Properties.BeginInit();
            this.cboClassifyMethod.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.cboNormFields.Properties.BeginInit();
            this.cboValueFields.Properties.BeginInit();
            base.SuspendLayout();
            this.cboColorRamp.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboColorRamp.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboColorRamp.DropDownWidth = 160;
            this.cboColorRamp.Location = new Point(98, 101);
            this.cboColorRamp.Name = "cboColorRamp";
            this.cboColorRamp.Size = new Size(144, 22);
            this.cboColorRamp.TabIndex = 7;
            this.cboColorRamp.SelectedIndexChanged += new EventHandler(this.cboColorRamp_SelectedIndexChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(14, 105);
            this.label2.Name = "label2";
            this.label2.Size = new Size(53, 12);
            this.label2.TabIndex = 6;
            this.label2.Text = "颜色方案";
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new Point(329, 249);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 21);
            this.colorEdit1.TabIndex = 46;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(246, 254);
            this.label1.Name = "label1";
            this.label1.Size = new Size(77, 12);
            this.label1.TabIndex = 45;
            this.label1.Text = "空值显示颜色";
            this.Classifygroup.Controls.Add(this.cboClassifyNum);
            this.Classifygroup.Controls.Add(this.cboClassifyMethod);
            this.Classifygroup.Controls.Add(this.label4);
            this.Classifygroup.Controls.Add(this.label5);
            this.Classifygroup.Location = new Point(210, 5);
            this.Classifygroup.Name = "Classifygroup";
            this.Classifygroup.Size = new Size(167, 88);
            this.Classifygroup.TabIndex = 49;
            this.Classifygroup.TabStop = false;
            this.Classifygroup.Text = "分类";
            this.cboClassifyNum.EditValue = "";
            this.cboClassifyNum.Location = new Point(67, 56);
            this.cboClassifyNum.Name = "cboClassifyNum";
            this.cboClassifyNum.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboClassifyNum.Properties.Items.AddRange(new object[] { 
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", 
                "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32"
             });
            this.cboClassifyNum.Size = new Size(92, 21);
            this.cboClassifyNum.TabIndex = 49;
            this.cboClassifyNum.SelectedIndexChanged += new EventHandler(this.cboClassifyNum_SelectedIndexChanged);
            this.cboClassifyMethod.EditValue = "";
            this.cboClassifyMethod.Location = new Point(67, 24);
            this.cboClassifyMethod.Name = "cboClassifyMethod";
            this.cboClassifyMethod.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboClassifyMethod.Properties.Items.AddRange(new object[] { "等间隔", "分位数", "自然间隔" });
            this.cboClassifyMethod.Size = new Size(92, 21);
            this.cboClassifyMethod.TabIndex = 48;
            this.cboClassifyMethod.SelectedIndexChanged += new EventHandler(this.cboClassifyMethod_SelectedIndexChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(8, 56);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 12);
            this.label4.TabIndex = 39;
            this.label4.Text = "类";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(8, 24);
            this.label5.Name = "label5";
            this.label5.Size = new Size(53, 12);
            this.label5.TabIndex = 38;
            this.label5.Text = "分类方法";
            this.listView1.Columns.AddRange(new ColumnHeader[] { this.columnHeader_0, this.columnHeader_1, this.columnHeader_2 });
            this.listView1.FullRowSelect = true;
            this.listView1.Location = new Point(16, 130);
            this.listView1.Name = "listView1";
            this.listView1.Size = new Size(361, 109);
            this.listView1.TabIndex = 48;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = View.Details;
            this.columnHeader_0.Text = "符号";
            this.columnHeader_1.Text = "范围";
            this.columnHeader_1.Width = 97;
            this.columnHeader_2.Text = "标注";
            this.columnHeader_2.Width = 150;
            this.groupBox1.Controls.Add(this.cboNormFields);
            this.groupBox1.Controls.Add(this.cboValueFields);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Location = new Point(10, 2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(194, 88);
            this.groupBox1.TabIndex = 47;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "字段";
            this.cboNormFields.EditValue = "";
            this.cboNormFields.Location = new Point(78, 56);
            this.cboNormFields.Name = "cboNormFields";
            this.cboNormFields.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboNormFields.Size = new Size(104, 21);
            this.cboNormFields.TabIndex = 46;
            this.cboNormFields.SelectedIndexChanged += new EventHandler(this.cboNormFields_SelectedIndexChanged);
            this.cboValueFields.EditValue = "";
            this.cboValueFields.Location = new Point(78, 24);
            this.cboValueFields.Name = "cboValueFields";
            this.cboValueFields.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboValueFields.Size = new Size(104, 21);
            this.cboValueFields.TabIndex = 45;
            this.cboValueFields.SelectedIndexChanged += new EventHandler(this.cboValueFields_SelectedIndexChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 56);
            this.label3.Name = "label3";
            this.label3.Size = new Size(65, 12);
            this.label3.TabIndex = 39;
            this.label3.Text = "正则化字段";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(8, 24);
            this.label6.Name = "label6";
            this.label6.Size = new Size(41, 12);
            this.label6.TabIndex = 38;
            this.label6.Text = "值字段";
            this.checkBox1.AutoSize = true;
            this.checkBox1.Location = new Point(20, 250);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new Size(72, 16);
            this.checkBox1.TabIndex = 50;
            this.checkBox1.Text = "使用山影";
            this.checkBox1.UseVisualStyleBackColor = true;
            this.checkBox1.CheckedChanged += new EventHandler(this.checkBox1_CheckedChanged);
            this.txtZFactor.Location = new Point(157, 248);
            this.txtZFactor.Name = "txtZFactor";
            this.txtZFactor.Size = new Size(78, 21);
            this.txtZFactor.TabIndex = 51;
            this.txtZFactor.Text = "1";
            this.txtZFactor.TextChanged += new EventHandler(this.txtZFactor_TextChanged);
            this.lblZFactor.AutoSize = true;
            this.lblZFactor.Location = new Point(116, 252);
            this.lblZFactor.Name = "lblZFactor";
            this.lblZFactor.Size = new Size(35, 12);
            this.lblZFactor.TabIndex = 52;
            this.lblZFactor.Text = "Z因子";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.lblZFactor);
            base.Controls.Add(this.txtZFactor);
            base.Controls.Add(this.checkBox1);
            base.Controls.Add(this.Classifygroup);
            base.Controls.Add(this.listView1);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.colorEdit1);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.cboColorRamp);
            base.Controls.Add(this.label2);
            base.Name = "RasterClassifiedRenderPage";
            base.Size = new Size(413, 305);
            base.Load += new EventHandler(this.RasterClassifiedRenderPage_Load);
            this.colorEdit1.Properties.EndInit();
            this.Classifygroup.ResumeLayout(false);
            this.Classifygroup.PerformLayout();
            this.cboClassifyNum.Properties.EndInit();
            this.cboClassifyMethod.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.cboNormFields.Properties.EndInit();
            this.cboValueFields.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private ComboBoxEdit cboClassifyMethod;
        private ComboBoxEdit cboClassifyNum;
        private StyleComboBox cboColorRamp;
        private ComboBoxEdit cboNormFields;
        private ComboBoxEdit cboValueFields;
        private CheckBox checkBox1;
        private GroupBox Classifygroup;
        private ColorEdit colorEdit1;
        private ColumnHeader columnHeader_0;
        private ColumnHeader columnHeader_1;
        private ColumnHeader columnHeader_2;
        private GroupBox groupBox1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label lblZFactor;
        private RenderInfoListView listView1;
        private TextBox txtZFactor;
    }
}