using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.DataSourcesRaster;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using Yutai.ArcGIS.Common.Carto;
using Yutai.ArcGIS.Common.SymbolLib;

namespace Yutai.ArcGIS.Carto.UI
{
    partial class RasterStretchedRenderPage
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
 private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            this.label1 = new Label();
            this.label2 = new Label();
            this.lblLow = new Label();
            this.label4 = new Label();
            this.txtHeight = new TextBox();
            this.txtMedium = new TextBox();
            this.txtLow = new TextBox();
            this.cboColorRamp = new StyleComboBox(this.icontainer_0);
            this.label5 = new Label();
            this.colorEdit1 = new ColorEdit();
            this.colorEdit2 = new ColorEdit();
            this.lblBand = new Label();
            this.cboBand = new System.Windows.Forms.ComboBox();
            this.lblHight = new Label();
            this.chkShowBackground = new CheckBox();
            this.chkHillshade = new CheckBox();
            this.lblZFactor = new Label();
            this.txtZFactor = new TextBox();
            this.label3 = new Label();
            this.btnStretch = new Button();
            this.txtBackground = new TextBox();
            this.colorEdit1.Properties.BeginInit();
            this.colorEdit2.Properties.BeginInit();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(46, 32);
            this.label1.Name = "label1";
            this.label1.Size = new Size(17, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "值";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(119, 32);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "标记";
            this.lblLow.AutoSize = true;
            this.lblLow.Location = new Point(48, 104);
            this.lblLow.Name = "lblLow";
            this.lblLow.Size = new Size(41, 12);
            this.lblLow.TabIndex = 2;
            this.lblLow.Text = "label3";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(249, 174);
            this.label4.Name = "label4";
            this.label4.Size = new Size(65, 12);
            this.label4.TabIndex = 3;
            this.label4.Text = "背景值颜色";
            this.txtHeight.Location = new Point(121, 47);
            this.txtHeight.Name = "txtHeight";
            this.txtHeight.Size = new Size(100, 21);
            this.txtHeight.TabIndex = 4;
            this.txtHeight.TextChanged += new EventHandler(this.txtHeight_TextChanged);
            this.txtMedium.Location = new Point(121, 74);
            this.txtMedium.Name = "txtMedium";
            this.txtMedium.Size = new Size(100, 21);
            this.txtMedium.TabIndex = 5;
            this.txtMedium.TextChanged += new EventHandler(this.txtMedium_TextChanged);
            this.txtLow.Location = new Point(121, 101);
            this.txtLow.Name = "txtLow";
            this.txtLow.Size = new Size(100, 21);
            this.txtLow.TabIndex = 6;
            this.txtLow.TextChanged += new EventHandler(this.txtLow_TextChanged);
            this.cboColorRamp.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboColorRamp.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboColorRamp.DropDownWidth = 160;
            this.cboColorRamp.Location = new Point(90, 135);
            this.cboColorRamp.Name = "cboColorRamp";
            this.cboColorRamp.Size = new Size(144, 22);
            this.cboColorRamp.TabIndex = 8;
            this.cboColorRamp.SelectedIndexChanged += new EventHandler(this.cboColorRamp_SelectedIndexChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(34, 138);
            this.label5.Name = "label5";
            this.label5.Size = new Size(53, 12);
            this.label5.TabIndex = 7;
            this.label5.Text = "颜色方案";
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new Point(332, 168);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 21);
            this.colorEdit1.TabIndex = 46;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.colorEdit2.EditValue = Color.Empty;
            this.colorEdit2.Location = new Point(332, 195);
            this.colorEdit2.Name = "colorEdit2";
            this.colorEdit2.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit2.Size = new Size(48, 21);
            this.colorEdit2.TabIndex = 48;
            this.colorEdit2.EditValueChanged += new EventHandler(this.colorEdit2_EditValueChanged);
            this.lblBand.AutoSize = true;
            this.lblBand.Location = new Point(18, 8);
            this.lblBand.Name = "lblBand";
            this.lblBand.Size = new Size(29, 12);
            this.lblBand.TabIndex = 49;
            this.lblBand.Text = "波段";
            this.cboBand.FormattingEnabled = true;
            this.cboBand.Location = new Point(81, 8);
            this.cboBand.Name = "cboBand";
            this.cboBand.Size = new Size(264, 20);
            this.cboBand.TabIndex = 50;
            this.cboBand.SelectedIndexChanged += new EventHandler(this.cboBand_SelectedIndexChanged);
            this.lblHight.AutoSize = true;
            this.lblHight.Location = new Point(46, 47);
            this.lblHight.Name = "lblHight";
            this.lblHight.Size = new Size(41, 12);
            this.lblHight.TabIndex = 51;
            this.lblHight.Text = "label9";
            this.chkShowBackground.AutoSize = true;
            this.chkShowBackground.Location = new Point(36, 173);
            this.chkShowBackground.Name = "chkShowBackground";
            this.chkShowBackground.Size = new Size(84, 16);
            this.chkShowBackground.TabIndex = 52;
            this.chkShowBackground.Text = "显示背景值";
            this.chkShowBackground.UseVisualStyleBackColor = true;
            this.chkShowBackground.CheckedChanged += new EventHandler(this.chkShowBackground_CheckedChanged);
            this.chkHillshade.AutoSize = true;
            this.chkHillshade.Location = new Point(36, 196);
            this.chkHillshade.Name = "chkHillshade";
            this.chkHillshade.Size = new Size(72, 16);
            this.chkHillshade.TabIndex = 53;
            this.chkHillshade.Text = "显示山影";
            this.chkHillshade.UseVisualStyleBackColor = true;
            this.chkHillshade.CheckedChanged += new EventHandler(this.chkHillshade_CheckedChanged);
            this.lblZFactor.AutoSize = true;
            this.lblZFactor.Location = new Point(119, 196);
            this.lblZFactor.Name = "lblZFactor";
            this.lblZFactor.Size = new Size(35, 12);
            this.lblZFactor.TabIndex = 56;
            this.lblZFactor.Text = "Z因子";
            this.txtZFactor.Location = new Point(160, 192);
            this.txtZFactor.Name = "txtZFactor";
            this.txtZFactor.Size = new Size(61, 21);
            this.txtZFactor.TabIndex = 55;
            this.txtZFactor.Text = "1";
            this.txtZFactor.TextChanged += new EventHandler(this.txtZFactor_TextChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(249, 199);
            this.label3.Name = "label3";
            this.label3.Size = new Size(77, 12);
            this.label3.TabIndex = 54;
            this.label3.Text = "空值显示颜色";
            this.btnStretch.Location = new Point(251, 223);
            this.btnStretch.Name = "btnStretch";
            this.btnStretch.Size = new Size(94, 23);
            this.btnStretch.TabIndex = 57;
            this.btnStretch.Text = "拉伸设置...";
            this.btnStretch.UseVisualStyleBackColor = true;
            this.btnStretch.Click += new EventHandler(this.btnStretch_Click);
            this.txtBackground.Location = new Point(160, 163);
            this.txtBackground.Name = "txtBackground";
            this.txtBackground.Size = new Size(61, 21);
            this.txtBackground.TabIndex = 58;
            this.txtBackground.Text = "0";
            this.txtBackground.TextChanged += new EventHandler(this.txtBackground_TextChanged);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.txtBackground);
            base.Controls.Add(this.btnStretch);
            base.Controls.Add(this.lblZFactor);
            base.Controls.Add(this.txtZFactor);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.chkHillshade);
            base.Controls.Add(this.chkShowBackground);
            base.Controls.Add(this.lblHight);
            base.Controls.Add(this.cboBand);
            base.Controls.Add(this.lblBand);
            base.Controls.Add(this.colorEdit2);
            base.Controls.Add(this.colorEdit1);
            base.Controls.Add(this.cboColorRamp);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.txtLow);
            base.Controls.Add(this.txtMedium);
            base.Controls.Add(this.txtHeight);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.lblLow);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label1);
            base.Name = "RasterStretchedRenderPage";
            base.Size = new Size(439, 249);
            base.Load += new EventHandler(this.RasterStretchedRenderPage_Load);
            this.colorEdit1.Properties.EndInit();
            this.colorEdit2.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private Button btnStretch;
        private System.Windows.Forms.ComboBox cboBand;
        private StyleComboBox cboColorRamp;
        private CheckBox chkHillshade;
        private CheckBox chkShowBackground;
        private ColorEdit colorEdit1;
        private ColorEdit colorEdit2;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label lblBand;
        private Label lblHight;
        private Label lblLow;
        private Label lblZFactor;
        private TextBox txtBackground;
        private TextBox txtHeight;
        private TextBox txtLow;
        private TextBox txtMedium;
        private TextBox txtZFactor;
    }
}