using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Text;
using System.Windows.Forms;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Common.SymbolUI;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class CharacterMarkerControl
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.label1 = new Label();
            this.label3 = new Label();
            this.label7 = new Label();
            this.label5 = new Label();
            this.label4 = new Label();
            this.label6 = new Label();
            this.label8 = new Label();
            this.colorEdit1 = new ColorEdit();
            this.fontlistView = new FontListView();
            this.numUpDownXOffset = new SpinEdit();
            this.numUpDownYOffset = new SpinEdit();
            this.numUpDownNuicode = new SpinEdit();
            this.numUpDownSize = new SpinEdit();
            this.numUpDownAngle = new SpinEdit();
            this.cboFontName = new ComboBoxEdit();
            this.colorEdit1.Properties.BeginInit();
            this.numUpDownXOffset.Properties.BeginInit();
            this.numUpDownYOffset.Properties.BeginInit();
            this.numUpDownNuicode.Properties.BeginInit();
            this.numUpDownSize.Properties.BeginInit();
            this.numUpDownAngle.Properties.BeginInit();
            this.cboFontName.Properties.BeginInit();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(9, 13);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 0;
            this.label1.Text = "字体";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 236);
            this.label3.Name = "label3";
            this.label3.Size = new Size(29, 17);
            this.label3.TabIndex = 4;
            this.label3.Text = "编码";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(280, 35);
            this.label7.Name = "label7";
            this.label7.Size = new Size(29, 17);
            this.label7.TabIndex = 38;
            this.label7.Text = "角度";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(280, 214);
            this.label5.Name = "label5";
            this.label5.Size = new Size(35, 17);
            this.label5.TabIndex = 47;
            this.label5.Text = "Y偏移";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(280, 182);
            this.label4.Name = "label4";
            this.label4.Size = new Size(35, 17);
            this.label4.TabIndex = 44;
            this.label4.Text = "X偏移";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(280, 10);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 17);
            this.label6.TabIndex = 41;
            this.label6.Text = "大小";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(280, 98);
            this.label8.Name = "label8";
            this.label8.Size = new Size(29, 17);
            this.label8.TabIndex = 50;
            this.label8.Text = "颜色";
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new Point(320, 96);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 23);
            this.colorEdit1.TabIndex = 57;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.fontlistView.AutoScroll = true;
            this.fontlistView.AutoScrollMinSize = new Size(267, 150);
            this.fontlistView.BackColor = SystemColors.ControlLightLight;
            this.fontlistView.ItemSize = new Size(25, 25);
            this.fontlistView.Location = new Point(8, 48);
            this.fontlistView.Name = "fontlistView";
            this.fontlistView.SelectedIndex = -1;
            this.fontlistView.Size = new Size(267, 150);
            this.fontlistView.TabIndex = 58;
            this.fontlistView.TabStop = false;
            this.fontlistView.KeyPress += new KeyPressEventHandler(this.fontlistView_KeyPress);
            this.fontlistView.KeyDown += new KeyEventHandler(this.fontlistView_KeyDown);
            this.fontlistView.MouseDown += new MouseEventHandler(this.fontlistView_MouseDown);
            this.fontlistView.SelectedIndexChanged += new SelectedIndexChangedHandler(this.fontlistView_SelectedIndexChanged);
            int[] bits = new int[4];
            this.numUpDownXOffset.EditValue = new decimal(bits);
            this.numUpDownXOffset.Location = new Point(320, 176);
            this.numUpDownXOffset.Name = "numUpDownXOffset";
            this.numUpDownXOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numUpDownXOffset.Properties.DisplayFormat.FormatString = "0.####";
            this.numUpDownXOffset.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numUpDownXOffset.Properties.EditFormat.FormatString = "0.####";
            this.numUpDownXOffset.Properties.EditFormat.FormatType = FormatType.Numeric;
            int[] bits2 = new int[4];
            bits2[0] = 100;
            this.numUpDownXOffset.Properties.MaxValue = new decimal(bits2);
            int[] bits3 = new int[4];
            bits3[0] = 100;
            bits3[3] = -2147483648;
            this.numUpDownXOffset.Properties.MinValue = new decimal(bits3);
            this.numUpDownXOffset.Properties.UseCtrlIncrement = false;
            this.numUpDownXOffset.Size = new Size(72, 23);
            this.numUpDownXOffset.TabIndex = 59;
            this.numUpDownXOffset.TextChanged += new EventHandler(this.numUpDownXOffset_ValueChanged);
            int[] bits4 = new int[4];
            this.numUpDownYOffset.EditValue = new decimal(bits4);
            this.numUpDownYOffset.Location = new Point(320, 208);
            this.numUpDownYOffset.Name = "numUpDownYOffset";
            this.numUpDownYOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numUpDownYOffset.Properties.DisplayFormat.FormatString = "0.####";
            this.numUpDownYOffset.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numUpDownYOffset.Properties.EditFormat.FormatString = "0.####";
            this.numUpDownYOffset.Properties.EditFormat.FormatType = FormatType.Numeric;
            int[] bits5 = new int[4];
            bits5[0] = 100;
            this.numUpDownYOffset.Properties.MaxValue = new decimal(bits5);
            int[] bits6 = new int[4];
            bits6[0] = 100;
            bits6[3] = -2147483648;
            this.numUpDownYOffset.Properties.MinValue = new decimal(bits6);
            this.numUpDownYOffset.Properties.UseCtrlIncrement = false;
            this.numUpDownYOffset.Size = new Size(72, 23);
            this.numUpDownYOffset.TabIndex = 60;
            this.numUpDownYOffset.TextChanged += new EventHandler(this.numUpDownYOffset_ValueChanged);
            int[] bits7 = new int[4];
            bits7[0] = 33;
            this.numUpDownNuicode.EditValue = new decimal(bits7);
            this.numUpDownNuicode.Location = new Point(48, 232);
            this.numUpDownNuicode.Name = "numUpDownNuicode";
            this.numUpDownNuicode.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            int[] bits8 = new int[4];
            bits8[0] = 255;
            this.numUpDownNuicode.Properties.MaxValue = new decimal(bits8);
            int[] bits9 = new int[4];
            bits9[0] = 33;
            this.numUpDownNuicode.Properties.MinValue = new decimal(bits9);
            this.numUpDownNuicode.Properties.UseCtrlIncrement = false;
            this.numUpDownNuicode.Size = new Size(72, 23);
            this.numUpDownNuicode.TabIndex = 61;
            this.numUpDownNuicode.EditValueChanged += new EventHandler(this.numUpDownNuicode_EditValueChanged);
            this.numUpDownNuicode.TextChanged += new EventHandler(this.numUpDownNuicode_ValueChanged);
            int[] bits10 = new int[4];
            this.numUpDownSize.EditValue = new decimal(bits10);
            this.numUpDownSize.Location = new Point(320, 8);
            this.numUpDownSize.Name = "numUpDownSize";
            this.numUpDownSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numUpDownSize.Properties.DisplayFormat.FormatString = "0.####";
            this.numUpDownSize.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numUpDownSize.Properties.EditFormat.FormatString = "0.####";
            this.numUpDownSize.Properties.EditFormat.FormatType = FormatType.Numeric;
            int[] bits11 = new int[4];
            bits11[0] = 100;
            this.numUpDownSize.Properties.MaxValue = new decimal(bits11);
            this.numUpDownSize.Properties.UseCtrlIncrement = false;
            this.numUpDownSize.Size = new Size(64, 23);
            this.numUpDownSize.TabIndex = 62;
            this.numUpDownSize.EditValueChanged += new EventHandler(this.numUpDownSize_EditValueChanged);
            this.numUpDownSize.TextChanged += new EventHandler(this.numUpDownSize_ValueChanged);
            int[] bits12 = new int[4];
            this.numUpDownAngle.EditValue = new decimal(bits12);
            this.numUpDownAngle.Location = new Point(320, 32);
            this.numUpDownAngle.Name = "numUpDownAngle";
            this.numUpDownAngle.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numUpDownAngle.Properties.DisplayFormat.FormatString = "0.####";
            this.numUpDownAngle.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numUpDownAngle.Properties.EditFormat.FormatString = "0.####";
            this.numUpDownAngle.Properties.EditFormat.FormatType = FormatType.Numeric;
            int[] bits13 = new int[4];
            bits13[0] = 360;
            this.numUpDownAngle.Properties.MaxValue = new decimal(bits13);
            int[] bits14 = new int[4];
            bits14[0] = 360;
            bits14[3] = -2147483648;
            this.numUpDownAngle.Properties.MinValue = new decimal(bits14);
            this.numUpDownAngle.Properties.UseCtrlIncrement = false;
            this.numUpDownAngle.Size = new Size(64, 23);
            this.numUpDownAngle.TabIndex = 63;
            this.numUpDownAngle.EditValueChanged += new EventHandler(this.numUpDownAngle_EditValueChanged);
            this.numUpDownAngle.TextChanged += new EventHandler(this.numUpDownAngle_ValueChanged);
            this.cboFontName.EditValue = "";
            this.cboFontName.Location = new Point(48, 8);
            this.cboFontName.Name = "cboFontName";
            this.cboFontName.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboFontName.Size = new Size(216, 23);
            this.cboFontName.TabIndex = 64;
            this.cboFontName.SelectedIndexChanged += new EventHandler(this.cboFontName_SelectedIndexChanged);
            base.Controls.Add(this.cboFontName);
            base.Controls.Add(this.numUpDownAngle);
            base.Controls.Add(this.numUpDownSize);
            base.Controls.Add(this.numUpDownNuicode);
            base.Controls.Add(this.numUpDownYOffset);
            base.Controls.Add(this.numUpDownXOffset);
            base.Controls.Add(this.fontlistView);
            base.Controls.Add(this.colorEdit1);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.label1);
            base.Name = "CharacterMarkerControl";
            base.Size = new Size(408, 280);
            base.Load += new EventHandler(this.CharacterMarkerControl_Load);
            this.colorEdit1.Properties.EndInit();
            this.numUpDownXOffset.Properties.EndInit();
            this.numUpDownYOffset.Properties.EndInit();
            this.numUpDownNuicode.Properties.EndInit();
            this.numUpDownSize.Properties.EndInit();
            this.numUpDownAngle.Properties.EndInit();
            this.cboFontName.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private Container components;
        private ComboBoxEdit cboFontName;
        private ColorEdit colorEdit1;
        private FontListView fontlistView;
        private Label label1;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private bool m_CanDo;
        private SpinEdit numUpDownAngle;
        private SpinEdit numUpDownNuicode;
        private SpinEdit numUpDownSize;
        private SpinEdit numUpDownXOffset;
        private SpinEdit numUpDownYOffset;
    }
}