using System;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraTab;
using ESRI.ArcGIS.Analyst3D;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.esriSystem;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Common.SymbolUI;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
  
    partial class frmPointSymbolEdit
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.components = new Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPointSymbolEdit));
            this.groupBox1 = new GroupBox();
            this.tabControl1 = new XtraTabControl();
            this.cboUnit = new ComboBoxEdit();
            this.cboMarkerType = new ComboBoxEdit();
            this.tabControl11 = new TabControl();
            this.label2 = new Label();
            this.label1 = new Label();
            this.groupBox2 = new GroupBox();
            this.symbolItem1 = new SymbolItem();
            this.cboScale = new ComboBoxEdit();
            this.btnOnt2One = new SimpleButton();
            this.btnFixZoomOut = new SimpleButton();
            this.btnFixZoomIn = new SimpleButton();
            this.chkLine = new CheckBox();
            this.groupBox3 = new GroupBox();
            this.btnPaste = new SimpleButton();
            this.btnCopy = new SimpleButton();
            this.tnMoveDown = new SimpleButton();
            this.btnMoveUp = new SimpleButton();
            this.btnDeleteLayer = new SimpleButton();
            this.btnAddLayer = new SimpleButton();
            this.symbolListBox1 = new SymbolListBox();
            this.btnOK = new SimpleButton();
            this.btnCancel = new SimpleButton();
            this.barAndDockingController1 = new BarAndDockingController(this.components);
            this.groupBox1.SuspendLayout();
            this.tabControl1.BeginInit();
            this.cboUnit.Properties.BeginInit();
            this.cboMarkerType.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.cboScale.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.barAndDockingController1.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.tabControl1);
            this.groupBox1.Controls.Add(this.cboUnit);
            this.groupBox1.Controls.Add(this.cboMarkerType);
            this.groupBox1.Controls.Add(this.tabControl11);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Location = new Point(200, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(432, 392);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "属性";
            this.tabControl1.Location = new Point(16, 64);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.Size = new Size(408, 312);
            this.tabControl1.TabIndex = 15;
            this.tabControl1.Text = "xtraTabControl1";
            this.cboUnit.EditValue = "";
            this.cboUnit.Location = new Point(248, 30);
            this.cboUnit.Name = "cboUnit";
            this.cboUnit.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboUnit.Properties.Items.AddRange(new object[] { "点", "英寸", "厘米", "毫米" });
            this.cboUnit.Size = new Size(152, 21);
            this.cboUnit.TabIndex = 14;
            this.cboUnit.SelectedIndexChanged += new EventHandler(this.cboUnit_SelectedIndexChanged);
            this.cboMarkerType.EditValue = "";
            this.cboMarkerType.Location = new Point(48, 30);
            this.cboMarkerType.Name = "cboMarkerType";
            this.cboMarkerType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboMarkerType.Properties.Items.AddRange(new object[] { "简单点符号", "箭头点符号", "图片点符号", "字符点符号", "3D字符点符号", "3D简单点符号", "3D点符号" });
            this.cboMarkerType.Size = new Size(144, 21);
            this.cboMarkerType.TabIndex = 13;
            this.cboMarkerType.SelectedIndexChanged += new EventHandler(this.cboMarkerType_SelectedIndexChanged);
            this.tabControl11.Location = new Point(384, 64);
            this.tabControl11.Name = "tabControl11";
            this.tabControl11.SelectedIndex = 0;
            this.tabControl11.Size = new Size(40, 312);
            this.tabControl11.TabIndex = 6;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(208, 32);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 12);
            this.label2.TabIndex = 4;
            this.label2.Text = "单位";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 32);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 12);
            this.label1.TabIndex = 2;
            this.label1.Text = "类型";
            this.groupBox2.Controls.Add(this.symbolItem1);
            this.groupBox2.Controls.Add(this.cboScale);
            this.groupBox2.Controls.Add(this.btnOnt2One);
            this.groupBox2.Controls.Add(this.btnFixZoomOut);
            this.groupBox2.Controls.Add(this.btnFixZoomIn);
            this.groupBox2.Controls.Add(this.chkLine);
            this.groupBox2.Location = new Point(8, 8);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(168, 184);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "预览";
            this.symbolItem1.BackColor = SystemColors.ControlLight;
            this.symbolItem1.Location = new Point(8, 24);
            this.symbolItem1.Name = "symbolItem1";
            this.symbolItem1.Size = new Size(152, 96);
            this.symbolItem1.Symbol = null;
            this.symbolItem1.TabIndex = 29;
            this.cboScale.EditValue = "";
            this.cboScale.Location = new Point(92, 152);
            this.cboScale.Name = "cboScale";
            this.cboScale.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboScale.Properties.Items.AddRange(new object[] { "400%", "200%", "100%", "75%", "50%" });
            this.cboScale.Size = new Size(72, 21);
            this.cboScale.TabIndex = 28;
            this.cboScale.SelectedIndexChanged += new EventHandler(this.cboScale_SelectedIndexChanged);
            this.btnOnt2One.Image = (Image) resources.GetObject("btnOnt2One.Image");
            this.btnOnt2One.Location = new Point(60, 152);
            this.btnOnt2One.Name = "btnOnt2One";
            this.btnOnt2One.Size = new Size(22, 22);
            this.btnOnt2One.TabIndex = 27;
            this.btnOnt2One.Click += new EventHandler(this.btnOnt2One_Click);
            this.btnFixZoomOut.Image = (Image) resources.GetObject("btnFixZoomOut.Image");
            this.btnFixZoomOut.Location = new Point(34, 152);
            this.btnFixZoomOut.Name = "btnFixZoomOut";
            this.btnFixZoomOut.Size = new Size(22, 22);
            this.btnFixZoomOut.TabIndex = 26;
            this.btnFixZoomOut.Click += new EventHandler(this.btnFixZoomOut_Click);
            this.btnFixZoomIn.Image = (Image) resources.GetObject("btnFixZoomIn.Image");
            this.btnFixZoomIn.Location = new Point(4, 152);
            this.btnFixZoomIn.Name = "btnFixZoomIn";
            this.btnFixZoomIn.Size = new Size(22, 22);
            this.btnFixZoomIn.TabIndex = 25;
            this.btnFixZoomIn.Click += new EventHandler(this.btnFixZoomIn_Click);
            this.chkLine.Checked = true;
            this.chkLine.CheckState = CheckState.Checked;
            this.chkLine.Image = (Image) resources.GetObject("chkLine.Image");
            this.chkLine.ImageAlign = ContentAlignment.MiddleLeft;
            this.chkLine.Location = new Point(10, 128);
            this.chkLine.Name = "chkLine";
            this.chkLine.Size = new Size(56, 16);
            this.chkLine.TabIndex = 2;
            this.chkLine.CheckedChanged += new EventHandler(this.chkLine_CheckedChanged);
            this.groupBox3.Controls.Add(this.btnPaste);
            this.groupBox3.Controls.Add(this.btnCopy);
            this.groupBox3.Controls.Add(this.tnMoveDown);
            this.groupBox3.Controls.Add(this.btnMoveUp);
            this.groupBox3.Controls.Add(this.btnDeleteLayer);
            this.groupBox3.Controls.Add(this.btnAddLayer);
            this.groupBox3.Controls.Add(this.symbolListBox1);
            this.groupBox3.Location = new Point(16, 200);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(160, 232);
            this.groupBox3.TabIndex = 7;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "图层";
            this.btnPaste.Image = (Image) resources.GetObject("btnPaste.Image");
            this.btnPaste.Location = new Point(52, 200);
            this.btnPaste.Name = "btnPaste";
            this.btnPaste.Size = new Size(24, 24);
            this.btnPaste.TabIndex = 23;
            this.btnPaste.Click += new EventHandler(this.btnPaste_Click);
            this.btnCopy.Image = (Image) resources.GetObject("btnCopy.Image");
            this.btnCopy.Location = new Point(20, 200);
            this.btnCopy.Name = "btnCopy";
            this.btnCopy.Size = new Size(24, 24);
            this.btnCopy.TabIndex = 22;
            this.btnCopy.Click += new EventHandler(this.btnCopy_Click);
            this.tnMoveDown.Image = (Image) resources.GetObject("tnMoveDown.Image");
            this.tnMoveDown.Location = new Point(116, 168);
            this.tnMoveDown.Name = "tnMoveDown";
            this.tnMoveDown.Size = new Size(24, 24);
            this.tnMoveDown.TabIndex = 21;
            this.tnMoveDown.Click += new EventHandler(this.tnMoveDown_Click);
            this.btnMoveUp.Image = (Image) resources.GetObject("btnMoveUp.Image");
            this.btnMoveUp.Location = new Point(84, 168);
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.Size = new Size(24, 24);
            this.btnMoveUp.TabIndex = 20;
            this.btnMoveUp.Click += new EventHandler(this.btnMoveUp_Click);
            this.btnDeleteLayer.Image = (Image) resources.GetObject("btnDeleteLayer.Image");
            this.btnDeleteLayer.Location = new Point(52, 168);
            this.btnDeleteLayer.Name = "btnDeleteLayer";
            this.btnDeleteLayer.Size = new Size(24, 24);
            this.btnDeleteLayer.TabIndex = 19;
            this.btnDeleteLayer.Click += new EventHandler(this.btnDeleteLayer_Click);
            this.btnAddLayer.Image = (Image) resources.GetObject("btnAddLayer.Image");
            this.btnAddLayer.Location = new Point(20, 168);
            this.btnAddLayer.Name = "btnAddLayer";
            this.btnAddLayer.Size = new Size(24, 24);
            this.btnAddLayer.TabIndex = 18;
            this.btnAddLayer.Click += new EventHandler(this.btnAddLayer_Click);
            this.symbolListBox1.DrawMode = DrawMode.OwnerDrawVariable;
            this.symbolListBox1.Location = new Point(8, 16);
            this.symbolListBox1.Name = "symbolListBox1";
            this.symbolListBox1.Size = new Size(144, 144);
            this.symbolListBox1.TabIndex = 12;
            this.symbolListBox1.LayerVisibleChanged += new LayerVisibleChangedHandler(this.symbolListBox1_LayerVisibleChanged);
            this.symbolListBox1.LayerColorLockedChanged += new LayerColorLockedChangedHandler(this.symbolListBox1_LayerColorLockedChanged);
            this.symbolListBox1.SelectedIndexChanged += new EventHandler(this.symbolListBox1_SelectedIndexChanged);
            this.btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnOK.Location = new Point(488, 408);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(56, 24);
            this.btnOK.TabIndex = 10;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(568, 408);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(56, 24);
            this.btnCancel.TabIndex = 11;
            this.btnCancel.Text = "取消";
            this.btnCancel.Click += new EventHandler(this.btnCancel_Click);
            this.barAndDockingController1.PaintStyleName = "Office2003";
            this.barAndDockingController1.PropertiesBar.AllowLinkLighting = false;
            this.AutoScaleBaseSize = new Size(6, 14);
            base.ClientSize = new Size(642, 439);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmPointSymbolEdit";
            base.ShowInTaskbar = false;
            base.StartPosition = FormStartPosition.CenterParent;
            this.Text = "点符号编辑器";
            base.Load += new EventHandler(this.frmPointSymbolEdit_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tabControl1.EndInit();
            this.cboUnit.Properties.EndInit();
            this.cboMarkerType.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.cboScale.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.barAndDockingController1.EndInit();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private BarAndDockingController barAndDockingController1;
        private SimpleButton btnAddLayer;
        private SimpleButton btnCancel;
        private SimpleButton btnCopy;
        private SimpleButton btnDeleteLayer;
        private SimpleButton btnFixZoomIn;
        private SimpleButton btnFixZoomOut;
        private SimpleButton btnMoveUp;
        private SimpleButton btnOK;
        private SimpleButton btnOnt2One;
        private SimpleButton btnPaste;
        private ComboBoxEdit cboMarkerType;
        private ComboBoxEdit cboScale;
        private ComboBoxEdit cboUnit;
        private CheckBox chkLine;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private Label label1;
        private Label label2;
        private IMultiLayerMarkerSymbol m_pMultiMarkerSymbol;
        private ISymbol m_pOldSymbol;
        private SymbolItem symbolItem1;
        private SymbolListBox symbolListBox1;
        private XtraTabControl tabControl1;
        private TabControl tabControl11;
        private SimpleButton tnMoveDown;
    }
}