using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common.SymbolLib;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class GridHatchPropertyPage
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.label9 = new Label();
            this.label8 = new Label();
            this.label7 = new Label();
            this.txtHatchIntervalYSecond = new TextEdit();
            this.txtHatchIntervalYMinute = new TextEdit();
            this.txtHatchIntervalXSecond = new TextEdit();
            this.txtHatchIntervalXMinute = new TextEdit();
            this.label3 = new Label();
            this.label4 = new Label();
            this.txtHatchIntervalYDegree = new TextEdit();
            this.txtHatchIntervalXDegree = new TextEdit();
            this.label5 = new Label();
            this.label6 = new Label();
            this.groupBox2 = new GroupBox();
            this.label13 = new Label();
            this.label14 = new Label();
            this.txtHatchLength = new SpinEdit();
            this.comboBoxEdit1 = new ComboBoxEdit();
            this.btnStyle = new StyleButton();
            this.chkHatchDirectional = new CheckEdit();
            this.groupBox3 = new GroupBox();
            this.comboBoxEdit2 = new ComboBoxEdit();
            this.txtAxisTickOffset = new SpinEdit();
            this.label1 = new Label();
            this.groupBox1.SuspendLayout();
            this.txtHatchIntervalYSecond.Properties.BeginInit();
            this.txtHatchIntervalYMinute.Properties.BeginInit();
            this.txtHatchIntervalXSecond.Properties.BeginInit();
            this.txtHatchIntervalXMinute.Properties.BeginInit();
            this.txtHatchIntervalYDegree.Properties.BeginInit();
            this.txtHatchIntervalXDegree.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.txtHatchLength.Properties.BeginInit();
            this.comboBoxEdit1.Properties.BeginInit();
            this.chkHatchDirectional.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.comboBoxEdit2.Properties.BeginInit();
            this.txtAxisTickOffset.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.label9);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.txtHatchIntervalYSecond);
            this.groupBox1.Controls.Add(this.txtHatchIntervalYMinute);
            this.groupBox1.Controls.Add(this.txtHatchIntervalXSecond);
            this.groupBox1.Controls.Add(this.txtHatchIntervalXMinute);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.txtHatchIntervalYDegree);
            this.groupBox1.Controls.Add(this.txtHatchIntervalXDegree);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Location = new Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(272, 112);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "细切线间隔";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(176, 24);
            this.label9.Name = "label9";
            this.label9.Size = new Size(17, 17);
            this.label9.TabIndex = 25;
            this.label9.Text = "秒";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(136, 24);
            this.label8.Name = "label8";
            this.label8.Size = new Size(17, 17);
            this.label8.TabIndex = 24;
            this.label8.Text = "分";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(96, 24);
            this.label7.Name = "label7";
            this.label7.Size = new Size(17, 17);
            this.label7.TabIndex = 23;
            this.label7.Text = "度";
            this.txtHatchIntervalYSecond.EditValue = "";
            this.txtHatchIntervalYSecond.Location = new Point(160, 80);
            this.txtHatchIntervalYSecond.Name = "txtHatchIntervalYSecond";
            this.txtHatchIntervalYSecond.Size = new Size(32, 23);
            this.txtHatchIntervalYSecond.TabIndex = 22;
            this.txtHatchIntervalYSecond.EditValueChanged += new EventHandler(this.txtHatchIntervalXDegree_EditValueChanged);
            this.txtHatchIntervalYMinute.EditValue = "";
            this.txtHatchIntervalYMinute.Location = new Point(120, 80);
            this.txtHatchIntervalYMinute.Name = "txtHatchIntervalYMinute";
            this.txtHatchIntervalYMinute.Size = new Size(32, 23);
            this.txtHatchIntervalYMinute.TabIndex = 21;
            this.txtHatchIntervalYMinute.EditValueChanged += new EventHandler(this.txtHatchIntervalXDegree_EditValueChanged);
            this.txtHatchIntervalXSecond.EditValue = "";
            this.txtHatchIntervalXSecond.Location = new Point(160, 48);
            this.txtHatchIntervalXSecond.Name = "txtHatchIntervalXSecond";
            this.txtHatchIntervalXSecond.Size = new Size(32, 23);
            this.txtHatchIntervalXSecond.TabIndex = 20;
            this.txtHatchIntervalXSecond.EditValueChanged += new EventHandler(this.txtHatchIntervalXDegree_EditValueChanged);
            this.txtHatchIntervalXMinute.EditValue = "";
            this.txtHatchIntervalXMinute.Location = new Point(120, 48);
            this.txtHatchIntervalXMinute.Name = "txtHatchIntervalXMinute";
            this.txtHatchIntervalXMinute.Size = new Size(32, 23);
            this.txtHatchIntervalXMinute.TabIndex = 19;
            this.txtHatchIntervalXMinute.EditValueChanged += new EventHandler(this.txtHatchIntervalXDegree_EditValueChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(160, 72);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0, 17);
            this.label3.TabIndex = 18;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(160, 48);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0, 17);
            this.label4.TabIndex = 17;
            this.txtHatchIntervalYDegree.EditValue = "";
            this.txtHatchIntervalYDegree.Location = new Point(64, 80);
            this.txtHatchIntervalYDegree.Name = "txtHatchIntervalYDegree";
            this.txtHatchIntervalYDegree.Size = new Size(48, 23);
            this.txtHatchIntervalYDegree.TabIndex = 16;
            this.txtHatchIntervalYDegree.EditValueChanged += new EventHandler(this.txtHatchIntervalXDegree_EditValueChanged);
            this.txtHatchIntervalXDegree.EditValue = "";
            this.txtHatchIntervalXDegree.Location = new Point(64, 48);
            this.txtHatchIntervalXDegree.Name = "txtHatchIntervalXDegree";
            this.txtHatchIntervalXDegree.Size = new Size(48, 23);
            this.txtHatchIntervalXDegree.TabIndex = 15;
            this.txtHatchIntervalXDegree.EditValueChanged += new EventHandler(this.txtHatchIntervalXDegree_EditValueChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(16, 80);
            this.label5.Name = "label5";
            this.label5.Size = new Size(29, 17);
            this.label5.TabIndex = 14;
            this.label5.Text = "经度";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(16, 48);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 17);
            this.label6.TabIndex = 13;
            this.label6.Text = "纬度";
            this.groupBox2.Controls.Add(this.chkHatchDirectional);
            this.groupBox2.Controls.Add(this.btnStyle);
            this.groupBox2.Controls.Add(this.comboBoxEdit1);
            this.groupBox2.Controls.Add(this.txtHatchLength);
            this.groupBox2.Controls.Add(this.label13);
            this.groupBox2.Controls.Add(this.label14);
            this.groupBox2.Location = new Point(8, 128);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(272, 120);
            this.groupBox2.TabIndex = 3;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "细切线标记";
            this.label13.AutoSize = true;
            this.label13.Location = new Point(16, 56);
            this.label13.Name = "label13";
            this.label13.Size = new Size(29, 17);
            this.label13.TabIndex = 14;
            this.label13.Text = "长度";
            this.label14.AutoSize = true;
            this.label14.Location = new Point(16, 24);
            this.label14.Name = "label14";
            this.label14.Size = new Size(29, 17);
            this.label14.TabIndex = 13;
            this.label14.Text = "符号";
            int[] bits = new int[4];
            this.txtHatchLength.EditValue = new decimal(bits);
            this.txtHatchLength.Location = new Point(56, 56);
            this.txtHatchLength.Name = "txtHatchLength";
            this.txtHatchLength.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtHatchLength.Properties.UseCtrlIncrement = false;
            this.txtHatchLength.Size = new Size(80, 23);
            this.txtHatchLength.TabIndex = 15;
            this.txtHatchLength.EditValueChanged += new EventHandler(this.txtHatchLength_EditValueChanged);
            this.comboBoxEdit1.EditValue = "点";
            this.comboBoxEdit1.Location = new Point(152, 56);
            this.comboBoxEdit1.Name = "comboBoxEdit1";
            this.comboBoxEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.comboBoxEdit1.Properties.Enabled = false;
            this.comboBoxEdit1.Properties.Items.AddRange(new object[] { "点", "厘米", "毫米", "英寸" });
            this.comboBoxEdit1.Size = new Size(56, 23);
            this.comboBoxEdit1.TabIndex = 16;
            this.btnStyle.Location = new Point(56, 24);
            this.btnStyle.Name = "btnStyle";
            this.btnStyle.Size = new Size(80, 24);
            this.btnStyle.TabIndex = 17;
            this.chkHatchDirectional.Location = new Point(16, 88);
            this.chkHatchDirectional.Name = "chkHatchDirectional";
            this.chkHatchDirectional.Properties.Caption = "细切标记显示相对于中央子午线和赤道方向";
            this.chkHatchDirectional.Size = new Size(256, 19);
            this.chkHatchDirectional.TabIndex = 18;
            this.chkHatchDirectional.CheckedChanged += new EventHandler(this.chkHatchDirectional_CheckedChanged);
            this.groupBox3.Controls.Add(this.comboBoxEdit2);
            this.groupBox3.Controls.Add(this.txtAxisTickOffset);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Location = new Point(8, 256);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(272, 72);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "轴刻度";
            this.comboBoxEdit2.EditValue = "点";
            this.comboBoxEdit2.Location = new Point(184, 24);
            this.comboBoxEdit2.Name = "comboBoxEdit2";
            this.comboBoxEdit2.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.comboBoxEdit2.Properties.Enabled = false;
            this.comboBoxEdit2.Properties.Items.AddRange(new object[] { "点", "厘米", "毫米", "英寸" });
            this.comboBoxEdit2.Size = new Size(56, 23);
            this.comboBoxEdit2.TabIndex = 16;
            bits = new int[4];
            this.txtAxisTickOffset.EditValue = new decimal(bits);
            this.txtAxisTickOffset.Location = new Point(80, 24);
            this.txtAxisTickOffset.Name = "txtAxisTickOffset";
            this.txtAxisTickOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtAxisTickOffset.Properties.UseCtrlIncrement = false;
            this.txtAxisTickOffset.Size = new Size(80, 23);
            this.txtAxisTickOffset.TabIndex = 15;
            this.txtAxisTickOffset.EditValueChanged += new EventHandler(this.txtAxisTickOffset_EditValueChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 24);
            this.label1.Name = "label1";
            this.label1.Size = new Size(66, 17);
            this.label1.TabIndex = 14;
            this.label1.Text = "轴刻度偏移";
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "GridHatchPropertyPage";
            base.Size = new Size(312, 344);
            base.Load += new EventHandler(this.GridHatchPropertyPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.txtHatchIntervalYSecond.Properties.EndInit();
            this.txtHatchIntervalYMinute.Properties.EndInit();
            this.txtHatchIntervalXSecond.Properties.EndInit();
            this.txtHatchIntervalXMinute.Properties.EndInit();
            this.txtHatchIntervalYDegree.Properties.EndInit();
            this.txtHatchIntervalXDegree.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.txtHatchLength.Properties.EndInit();
            this.comboBoxEdit1.Properties.EndInit();
            this.chkHatchDirectional.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.comboBoxEdit2.Properties.EndInit();
            this.txtAxisTickOffset.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private Container components = null;
        private StyleButton btnStyle;
        private CheckEdit chkHatchDirectional;
        private ComboBoxEdit comboBoxEdit1;
        private ComboBoxEdit comboBoxEdit2;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private Label label1;
        private Label label13;
        private Label label14;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private SpinEdit txtAxisTickOffset;
        private TextEdit txtHatchIntervalXDegree;
        private TextEdit txtHatchIntervalXMinute;
        private TextEdit txtHatchIntervalXSecond;
        private TextEdit txtHatchIntervalYDegree;
        private TextEdit txtHatchIntervalYMinute;
        private TextEdit txtHatchIntervalYSecond;
        private SpinEdit txtHatchLength;
    }
}