using System;
using System.ComponentModel;
using System.Drawing;
using System.Resources;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class LineFeaturePlaceSetCtrl
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(LineFeaturePlaceSetCtrl));
            this.groupBox1 = new GroupBox();
            this.rdoLineLabelPosition = new RadioGroup();
            this.groupBox2 = new GroupBox();
            this.pictureEdit2 = new PictureEdit();
            this.pictureEdit1 = new PictureEdit();
            this.label4 = new Label();
            this.txtOffset = new TextEdit();
            this.label1 = new Label();
            this.cboCoorType = new ComboBoxEdit();
            this.chkBelow_Right = new CheckEdit();
            this.chkOnTop = new CheckEdit();
            this.chkTop_Left = new CheckEdit();
            this.label2 = new Label();
            this.groupBox3 = new GroupBox();
            this.cboPlaceLinePos = new ComboBoxEdit();
            this.label3 = new Label();
            this.groupBox1.SuspendLayout();
            this.rdoLineLabelPosition.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.pictureEdit2.Properties.BeginInit();
            this.pictureEdit1.Properties.BeginInit();
            this.txtOffset.Properties.BeginInit();
            this.cboCoorType.Properties.BeginInit();
            this.chkBelow_Right.Properties.BeginInit();
            this.chkOnTop.Properties.BeginInit();
            this.chkTop_Left.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.cboPlaceLinePos.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.rdoLineLabelPosition);
            this.groupBox1.Location = new Point(8, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(104, 160);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "方向";
            this.rdoLineLabelPosition.Location = new Point(8, 24);
            this.rdoLineLabelPosition.Name = "rdoLineLabelPosition";
            this.rdoLineLabelPosition.Properties.Appearance.BackColor = SystemColors.Control;
            this.rdoLineLabelPosition.Properties.Appearance.Options.UseBackColor = true;
            this.rdoLineLabelPosition.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoLineLabelPosition.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "水平放置"), new RadioGroupItem(null, "平行放置"), new RadioGroupItem(null, "弯曲放置"), new RadioGroupItem(null, "垂直放置") });
            this.rdoLineLabelPosition.Size = new Size(88, 80);
            this.rdoLineLabelPosition.TabIndex = 0;
            this.rdoLineLabelPosition.SelectedIndexChanged += new EventHandler(this.rdoLineLabelPosition_SelectedIndexChanged);
            this.groupBox2.Controls.Add(this.pictureEdit2);
            this.groupBox2.Controls.Add(this.pictureEdit1);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.txtOffset);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.cboCoorType);
            this.groupBox2.Controls.Add(this.chkBelow_Right);
            this.groupBox2.Controls.Add(this.chkOnTop);
            this.groupBox2.Controls.Add(this.chkTop_Left);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Location = new Point(120, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(192, 160);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "位置";
            this.pictureEdit2.EditValue = (object)resources.GetObject("pictureEdit2.EditValue");
            this.pictureEdit2.Location = new Point(72, 9);
            this.pictureEdit2.Name = "pictureEdit2";
            this.pictureEdit2.Properties.BorderStyle = BorderStyles.NoBorder;
            this.pictureEdit2.Properties.SizeMode = PictureSizeMode.Clip;
            this.pictureEdit2.Size = new Size(66, 81);
            this.pictureEdit2.TabIndex = 10;
            this.pictureEdit1.EditValue = (object)resources.GetObject("pictureEdit1.EditValue");
            this.pictureEdit1.Location = new Point(72, 9);
            this.pictureEdit1.Name = "pictureEdit1";
            this.pictureEdit1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.pictureEdit1.Properties.SizeMode = PictureSizeMode.Clip;
            this.pictureEdit1.Size = new Size(66, 81);
            this.pictureEdit1.TabIndex = 9;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(136, 128);
            this.label4.Name = "label4";
            this.label4.Size = new Size(54, 17);
            this.label4.TabIndex = 8;
            this.label4.Text = "地图单位";
            this.txtOffset.EditValue = "0";
            this.txtOffset.Location = new Point(72, 126);
            this.txtOffset.Name = "txtOffset";
            this.txtOffset.Size = new Size(56, 23);
            this.txtOffset.TabIndex = 7;
            this.txtOffset.EditValueChanged += new EventHandler(this.txtOffset_EditValueChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 128);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 6;
            this.label1.Text = "偏移";
            this.cboCoorType.EditValue = "页面";
            this.cboCoorType.Location = new Point(72, 96);
            this.cboCoorType.Name = "cboCoorType";
            this.cboCoorType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboCoorType.Properties.Items.AddRange(new object[] { "线", "页面" });
            this.cboCoorType.Size = new Size(64, 23);
            this.cboCoorType.TabIndex = 5;
            this.cboCoorType.SelectedIndexChanged += new EventHandler(this.cboCoorType_SelectedIndexChanged);
            this.chkBelow_Right.Location = new Point(16, 64);
            this.chkBelow_Right.Name = "chkBelow_Right";
            this.chkBelow_Right.Properties.Caption = "下";
            this.chkBelow_Right.Size = new Size(56, 19);
            this.chkBelow_Right.TabIndex = 4;
            this.chkBelow_Right.CheckedChanged += new EventHandler(this.chkBelow_Right_CheckedChanged);
            this.chkOnTop.Location = new Point(16, 40);
            this.chkOnTop.Name = "chkOnTop";
            this.chkOnTop.Properties.Caption = "在线上";
            this.chkOnTop.Size = new Size(56, 19);
            this.chkOnTop.TabIndex = 3;
            this.chkOnTop.CheckedChanged += new EventHandler(this.chkOnTop_CheckedChanged);
            this.chkTop_Left.Location = new Point(16, 16);
            this.chkTop_Left.Name = "chkTop_Left";
            this.chkTop_Left.Properties.Caption = "上";
            this.chkTop_Left.Size = new Size(56, 19);
            this.chkTop_Left.TabIndex = 2;
            this.chkTop_Left.CheckedChanged += new EventHandler(this.chkTop_Left_CheckedChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 102);
            this.label2.Name = "label2";
            this.label2.Size = new Size(54, 17);
            this.label2.TabIndex = 1;
            this.label2.Text = "方向系统";
            this.groupBox3.Controls.Add(this.cboPlaceLinePos);
            this.groupBox3.Controls.Add(this.label3);
            this.groupBox3.Location = new Point(8, 163);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(304, 56);
            this.groupBox3.TabIndex = 3;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "标注位置";
            this.cboPlaceLinePos.EditValue = "最佳位置";
            this.cboPlaceLinePos.Location = new Point(112, 16);
            this.cboPlaceLinePos.Name = "cboPlaceLinePos";
            this.cboPlaceLinePos.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboPlaceLinePos.Properties.Items.AddRange(new object[] { "最佳位置", "开始位置", "结束位置" });
            this.cboPlaceLinePos.Size = new Size(88, 23);
            this.cboPlaceLinePos.TabIndex = 6;
            this.cboPlaceLinePos.SelectedIndexChanged += new EventHandler(this.cboPlaceLinePos_SelectedIndexChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 24);
            this.label3.Name = "label3";
            this.label3.Size = new Size(91, 17);
            this.label3.TabIndex = 1;
            this.label3.Text = "沿线型方向标注";
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "LineFeaturePlaceSetCtrl";
            base.Size = new Size(320, 232);
            base.Load += new EventHandler(this.LineFeaturePlaceSetCtrl_Load);
            this.groupBox1.ResumeLayout(false);
            this.rdoLineLabelPosition.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.pictureEdit2.Properties.EndInit();
            this.pictureEdit1.Properties.EndInit();
            this.txtOffset.Properties.EndInit();
            this.cboCoorType.Properties.EndInit();
            this.chkBelow_Right.Properties.EndInit();
            this.chkOnTop.Properties.EndInit();
            this.chkTop_Left.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.cboPlaceLinePos.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private Container components = null;
        private ComboBoxEdit cboCoorType;
        private ComboBoxEdit cboPlaceLinePos;
        private CheckEdit chkBelow_Right;
        private CheckEdit chkOnTop;
        private CheckEdit chkTop_Left;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private PictureEdit pictureEdit1;
        private PictureEdit pictureEdit2;
        private RadioGroup rdoLineLabelPosition;
        private TextEdit txtOffset;
    }
}