using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Analyst3D;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Controls;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common.SymbolUI;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class Marker3DSymbolCtrl
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Marker3DSymbolCtrl));
            this.groupBox2 = new GroupBox();
            this.axSceneControl1 = new AxSceneControl();
            this.groupBox1 = new GroupBox();
            this.chkMaintainAspectRatio = new CheckEdit();
            this.txtDepth1 = new SpinEdit();
            this.label4 = new Label();
            this.txtWidth = new SpinEdit();
            this.txtSize = new SpinEdit();
            this.label6 = new Label();
            this.label7 = new Label();
            this.colorEdit1 = new ColorEdit();
            this.label8 = new Label();
            this.btnSelectPicture = new SimpleButton();
            this.lblPathName = new Label();
            this.checkEdit1 = new CheckEdit();
            this.groupBox2.SuspendLayout();
            this.axSceneControl1.BeginInit();
            this.groupBox1.SuspendLayout();
            this.chkMaintainAspectRatio.Properties.BeginInit();
            this.txtDepth1.Properties.BeginInit();
            this.txtWidth.Properties.BeginInit();
            this.txtSize.Properties.BeginInit();
            this.colorEdit1.Properties.BeginInit();
            this.checkEdit1.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox2.Controls.Add(this.axSceneControl1);
            this.groupBox2.Location = new System.Drawing.Point(194, 80);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(176, 160);
            this.groupBox2.TabIndex = 88;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "3D预览";
            this.axSceneControl1.Location = new System.Drawing.Point(6, 20);
            this.axSceneControl1.Name = "axSceneControl1";
            this.axSceneControl1.OcxState = (AxHost.State) resources.GetObject("axSceneControl1.OcxState");
            this.axSceneControl1.Size = new Size(164, 134);
            this.axSceneControl1.TabIndex = 1;
            this.groupBox1.Controls.Add(this.chkMaintainAspectRatio);
            this.groupBox1.Controls.Add(this.txtDepth1);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.txtWidth);
            this.groupBox1.Controls.Add(this.txtSize);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Location = new System.Drawing.Point(8, 72);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(152, 152);
            this.groupBox1.TabIndex = 87;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "尺寸";
            this.chkMaintainAspectRatio.Location = new System.Drawing.Point(16, 80);
            this.chkMaintainAspectRatio.Name = "chkMaintainAspectRatio";
            this.chkMaintainAspectRatio.Properties.Caption = "保持长宽比";
            this.chkMaintainAspectRatio.Size = new Size(104, 19);
            this.chkMaintainAspectRatio.TabIndex = 85;
            this.chkMaintainAspectRatio.CheckedChanged += new EventHandler(this.chkMaintainAspectRatio_CheckedChanged);
            int[] bits = new int[4];
            this.txtDepth1.EditValue = new decimal(bits);
            this.txtDepth1.Location = new System.Drawing.Point(56, 112);
            this.txtDepth1.Name = "txtDepth1";
            this.txtDepth1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtDepth1.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtDepth1.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.txtDepth1.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 100;
            bits[3] = -2147483648;
            this.txtDepth1.Properties.MinValue = new decimal(bits);
            this.txtDepth1.Size = new Size(72, 21);
            this.txtDepth1.TabIndex = 84;
            this.txtDepth1.EditValueChanged += new EventHandler(this.txtDepth1_EditValueChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(16, 120);
            this.label4.Name = "label4";
            this.label4.Size = new Size(29, 12);
            this.label4.TabIndex = 83;
            this.label4.Text = "深度";
            bits = new int[4];
            this.txtWidth.EditValue = new decimal(bits);
            this.txtWidth.Location = new System.Drawing.Point(56, 48);
            this.txtWidth.Name = "txtWidth";
            this.txtWidth.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtWidth.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtWidth.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 360;
            this.txtWidth.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 360;
            bits[3] = -2147483648;
            this.txtWidth.Properties.MinValue = new decimal(bits);
            this.txtWidth.Size = new Size(64, 21);
            this.txtWidth.TabIndex = 82;
            this.txtWidth.EditValueChanged += new EventHandler(this.txtWidth_EditValueChanged);
            bits = new int[4];
            this.txtSize.EditValue = new decimal(bits);
            this.txtSize.Location = new System.Drawing.Point(56, 24);
            this.txtSize.Name = "txtSize";
            this.txtSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtSize.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtSize.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.txtSize.Properties.MaxValue = new decimal(bits);
            this.txtSize.Size = new Size(64, 21);
            this.txtSize.TabIndex = 81;
            this.txtSize.EditValueChanged += new EventHandler(this.txtSize_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(16, 24);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 12);
            this.label6.TabIndex = 80;
            this.label6.Text = "大小";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(16, 56);
            this.label7.Name = "label7";
            this.label7.Size = new Size(35, 12);
            this.label7.TabIndex = 79;
            this.label7.Text = "宽度:";
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new System.Drawing.Point(64, 48);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 21);
            this.colorEdit1.TabIndex = 86;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(24, 48);
            this.label8.Name = "label8";
            this.label8.Size = new Size(29, 12);
            this.label8.TabIndex = 85;
            this.label8.Text = "颜色";
            this.btnSelectPicture.Location = new System.Drawing.Point(16, 8);
            this.btnSelectPicture.Name = "btnSelectPicture";
            this.btnSelectPicture.Size = new Size(64, 24);
            this.btnSelectPicture.TabIndex = 90;
            this.btnSelectPicture.Text = " 导入...";
            this.btnSelectPicture.Click += new EventHandler(this.btnSelectPicture_Click);
            this.lblPathName.Location = new System.Drawing.Point(96, 8);
            this.lblPathName.Name = "lblPathName";
            this.lblPathName.Size = new Size(280, 24);
            this.lblPathName.TabIndex = 89;
            this.checkEdit1.Location = new System.Drawing.Point(136, 48);
            this.checkEdit1.Name = "checkEdit1";
            this.checkEdit1.Properties.Caption = "使用材质覆盖";
            this.checkEdit1.Size = new Size(112, 19);
            this.checkEdit1.TabIndex = 100;
            this.checkEdit1.CheckedChanged += new EventHandler(this.checkEdit1_CheckedChanged);
            base.Controls.Add(this.checkEdit1);
            base.Controls.Add(this.btnSelectPicture);
            base.Controls.Add(this.lblPathName);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.colorEdit1);
            base.Controls.Add(this.label8);
            base.Name = "Marker3DSymbolCtrl";
            base.Size = new Size(384, 280);
            base.Load += new EventHandler(this.Marker3DSymbolCtrl_Load);
            this.groupBox2.ResumeLayout(false);
            this.axSceneControl1.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.chkMaintainAspectRatio.Properties.EndInit();
            this.txtDepth1.Properties.EndInit();
            this.txtWidth.Properties.EndInit();
            this.txtSize.Properties.EndInit();
            this.colorEdit1.Properties.EndInit();
            this.checkEdit1.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private Container components = null;
        private AxSceneControl axSceneControl1;
        private SimpleButton btnSelectPicture;
        private CheckEdit checkEdit1;
        private CheckEdit chkMaintainAspectRatio;
        private ColorEdit colorEdit1;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private Label label4;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label lblPathName;
        private SpinEdit txtDepth1;
        private SpinEdit txtSize;
        private SpinEdit txtWidth;
    }
}