using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common.SymbolUI;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class PictureMarkerControl
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.lblPathName = new Label();
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.colorEditForeColor = new ColorEdit();
            this.colorEditBackgroundColor = new ColorEdit();
            this.colorEditTransColor = new ColorEdit();
            this.label7 = new Label();
            this.numericUpDownAngle = new SpinEdit();
            this.numericUpDownSize = new SpinEdit();
            this.numericUpDownYOffset = new SpinEdit();
            this.numericUpDownXOffset = new SpinEdit();
            this.chkSwapFGBG = new CheckEdit();
            this.btnSelectPicture = new SimpleButton();
            this.colorEditForeColor.Properties.BeginInit();
            this.colorEditBackgroundColor.Properties.BeginInit();
            this.colorEditTransColor.Properties.BeginInit();
            this.numericUpDownAngle.Properties.BeginInit();
            this.numericUpDownSize.Properties.BeginInit();
            this.numericUpDownYOffset.Properties.BeginInit();
            this.numericUpDownXOffset.Properties.BeginInit();
            this.chkSwapFGBG.Properties.BeginInit();
            base.SuspendLayout();
            this.lblPathName.Location = new Point(96, 16);
            this.lblPathName.Name = "lblPathName";
            this.lblPathName.Size = new Size(280, 24);
            this.lblPathName.TabIndex = 1;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 86);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 2;
            this.label1.Text = "角度";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 118);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 17);
            this.label2.TabIndex = 3;
            this.label2.Text = "X偏移";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(16, 148);
            this.label3.Name = "label3";
            this.label3.Size = new Size(35, 17);
            this.label3.TabIndex = 4;
            this.label3.Text = "Y偏移";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(160, 86);
            this.label4.Name = "label4";
            this.label4.Size = new Size(42, 17);
            this.label4.TabIndex = 8;
            this.label4.Text = "前景色";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(160, 118);
            this.label5.Name = "label5";
            this.label5.Size = new Size(42, 17);
            this.label5.TabIndex = 9;
            this.label5.Text = "背景色";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(160, 148);
            this.label6.Name = "label6";
            this.label6.Size = new Size(42, 17);
            this.label6.TabIndex = 10;
            this.label6.Text = "透明色";
            this.colorEditForeColor.EditValue = Color.Empty;
            this.colorEditForeColor.Location = new Point(216, 80);
            this.colorEditForeColor.Name = "colorEditForeColor";
            this.colorEditForeColor.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEditForeColor.Size = new Size(48, 23);
            this.colorEditForeColor.TabIndex = 11;
            this.colorEditForeColor.EditValueChanged += new EventHandler(this.colorEditForeColor_EditValueChanged);
            this.colorEditBackgroundColor.EditValue = Color.Empty;
            this.colorEditBackgroundColor.Location = new Point(216, 112);
            this.colorEditBackgroundColor.Name = "colorEditBackgroundColor";
            this.colorEditBackgroundColor.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEditBackgroundColor.Size = new Size(48, 23);
            this.colorEditBackgroundColor.TabIndex = 12;
            this.colorEditBackgroundColor.EditValueChanged += new EventHandler(this.colorEditBackgroundColor_EditValueChanged);
            this.colorEditTransColor.EditValue = Color.Empty;
            this.colorEditTransColor.Location = new Point(216, 144);
            this.colorEditTransColor.Name = "colorEditTransColor";
            this.colorEditTransColor.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEditTransColor.Size = new Size(48, 23);
            this.colorEditTransColor.TabIndex = 13;
            this.colorEditTransColor.EditValueChanged += new EventHandler(this.colorEditTransColor_EditValueChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(16, 53);
            this.label7.Name = "label7";
            this.label7.Size = new Size(29, 17);
            this.label7.TabIndex = 15;
            this.label7.Text = "大小";
            int[] bits = new int[4];
            this.numericUpDownAngle.EditValue = new decimal(bits);
            this.numericUpDownAngle.Location = new Point(64, 80);
            this.numericUpDownAngle.Name = "numericUpDownAngle";
            this.numericUpDownAngle.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownAngle.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownAngle.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownAngle.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownAngle.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 360;
            this.numericUpDownAngle.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 360;
            bits[3] = -2147483648;
            this.numericUpDownAngle.Properties.MinValue = new decimal(bits);
            this.numericUpDownAngle.Properties.UseCtrlIncrement = false;
            this.numericUpDownAngle.Size = new Size(64, 23);
            this.numericUpDownAngle.TabIndex = 67;
            this.numericUpDownAngle.TextChanged += new EventHandler(this.numericUpDownAngle_ValueChanged);
            bits = new int[4];
            this.numericUpDownSize.EditValue = new decimal(bits);
            this.numericUpDownSize.Location = new Point(64, 48);
            this.numericUpDownSize.Name = "numericUpDownSize";
            this.numericUpDownSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownSize.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownSize.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownSize.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownSize.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownSize.Properties.MaxValue = new decimal(bits);
            this.numericUpDownSize.Properties.UseCtrlIncrement = false;
            this.numericUpDownSize.Size = new Size(64, 23);
            this.numericUpDownSize.TabIndex = 66;
            this.numericUpDownSize.TextChanged += new EventHandler(this.numericUpDownSize_ValueChanged);
            bits = new int[4];
            this.numericUpDownYOffset.EditValue = new decimal(bits);
            this.numericUpDownYOffset.Location = new Point(64, 144);
            this.numericUpDownYOffset.Name = "numericUpDownYOffset";
            this.numericUpDownYOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownYOffset.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownYOffset.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownYOffset.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownYOffset.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownYOffset.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 100;
            bits[3] = -2147483648;
            this.numericUpDownYOffset.Properties.MinValue = new decimal(bits);
            this.numericUpDownYOffset.Properties.UseCtrlIncrement = false;
            this.numericUpDownYOffset.Size = new Size(64, 23);
            this.numericUpDownYOffset.TabIndex = 65;
            this.numericUpDownYOffset.TextChanged += new EventHandler(this.numericUpDownYOffset_ValueChanged);
            bits = new int[4];
            this.numericUpDownXOffset.EditValue = new decimal(bits);
            this.numericUpDownXOffset.Location = new Point(64, 112);
            this.numericUpDownXOffset.Name = "numericUpDownXOffset";
            this.numericUpDownXOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownXOffset.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownXOffset.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownXOffset.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownXOffset.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownXOffset.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 100;
            bits[3] = -2147483648;
            this.numericUpDownXOffset.Properties.MinValue = new decimal(bits);
            this.numericUpDownXOffset.Properties.UseCtrlIncrement = false;
            this.numericUpDownXOffset.Size = new Size(64, 23);
            this.numericUpDownXOffset.TabIndex = 64;
            this.numericUpDownXOffset.TextChanged += new EventHandler(this.numericUpDownXOffset_ValueChanged);
            this.chkSwapFGBG.Location = new Point(16, 176);
            this.chkSwapFGBG.Name = "chkSwapFGBG";
            this.chkSwapFGBG.Properties.Caption = "交换前后景色";
            this.chkSwapFGBG.Size = new Size(128, 19);
            this.chkSwapFGBG.TabIndex = 83;
            this.chkSwapFGBG.CheckedChanged += new EventHandler(this.chkSwapFGBG_CheckedChanged);
            this.btnSelectPicture.Location = new Point(16, 16);
            this.btnSelectPicture.Name = "btnSelectPicture";
            this.btnSelectPicture.Size = new Size(64, 24);
            this.btnSelectPicture.TabIndex = 84;
            this.btnSelectPicture.Text = "图片...";
            this.btnSelectPicture.Click += new EventHandler(this.btnSelectPicture_Click);
            base.Controls.Add(this.btnSelectPicture);
            base.Controls.Add(this.chkSwapFGBG);
            base.Controls.Add(this.numericUpDownAngle);
            base.Controls.Add(this.numericUpDownSize);
            base.Controls.Add(this.numericUpDownYOffset);
            base.Controls.Add(this.numericUpDownXOffset);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.colorEditTransColor);
            base.Controls.Add(this.colorEditBackgroundColor);
            base.Controls.Add(this.colorEditForeColor);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.lblPathName);
            base.Name = "PictureMarkerControl";
            base.Size = new Size(376, 240);
            base.Load += new EventHandler(this.PictureMarkerControl_Load);
            this.colorEditForeColor.Properties.EndInit();
            this.colorEditBackgroundColor.Properties.EndInit();
            this.colorEditTransColor.Properties.EndInit();
            this.numericUpDownAngle.Properties.EndInit();
            this.numericUpDownSize.Properties.EndInit();
            this.numericUpDownYOffset.Properties.EndInit();
            this.numericUpDownXOffset.Properties.EndInit();
            this.chkSwapFGBG.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private Container components = null;
        private SimpleButton btnSelectPicture;
        private CheckEdit chkSwapFGBG;
        private ColorEdit colorEditBackgroundColor;
        private ColorEdit colorEditForeColor;
        private ColorEdit colorEditTransColor;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label lblPathName;
        private SpinEdit numericUpDownAngle;
        private SpinEdit numericUpDownSize;
        private SpinEdit numericUpDownXOffset;
        private SpinEdit numericUpDownYOffset;
    }
}