using System;
using System.ComponentModel;
using System.Drawing;
using System.Resources;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class PointFeatureLabelCtrl
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.components = new Container();
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(PointFeatureLabelCtrl));
            this.rdoPointPlacementMethod = new RadioGroup();
            this.panel1 = new Panel();
            this.label3 = new Label();
            this.imageComboBoxEdit1 = new ImageComboBoxEdit();
            this.imageList1 = new ImageList(this.components);
            this.panel2 = new Panel();
            this.label1 = new Label();
            this.txtAngle = new TextEdit();
            this.groupBox1 = new GroupBox();
            this.btnMoveDown = new SimpleButton();
            this.btnMoveUp = new SimpleButton();
            this.btnDeleteLayer = new SimpleButton();
            this.listPointPlacementAngles = new ListBox();
            this.btnAddAngle = new SimpleButton();
            this.panel3 = new Panel();
            this.pictureEdit2 = new PictureEdit();
            this.pictureEdit1 = new PictureEdit();
            this.chkPerpendicularToAngle = new CheckEdit();
            this.cboFields = new ComboBoxEdit();
            this.rdoRotationType = new RadioGroup();
            this.label2 = new Label();
            this.rdoPointPlacementMethod.Properties.BeginInit();
            this.panel1.SuspendLayout();
            this.imageComboBoxEdit1.Properties.BeginInit();
            this.panel2.SuspendLayout();
            this.txtAngle.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.pictureEdit2.Properties.BeginInit();
            this.pictureEdit1.Properties.BeginInit();
            this.chkPerpendicularToAngle.Properties.BeginInit();
            this.cboFields.Properties.BeginInit();
            this.rdoRotationType.Properties.BeginInit();
            base.SuspendLayout();
            this.rdoPointPlacementMethod.Location = new Point(8, 1);
            this.rdoPointPlacementMethod.Name = "rdoPointPlacementMethod";
            this.rdoPointPlacementMethod.Properties.Appearance.BackColor = SystemColors.Control;
            this.rdoPointPlacementMethod.Properties.Appearance.Options.UseBackColor = true;
            this.rdoPointPlacementMethod.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoPointPlacementMethod.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "在点周围水平偏移标注"), new RadioGroupItem(null, "在点上部放置标注"), new RadioGroupItem(null, "以指定角度放置标注"), new RadioGroupItem(null, "根据字段值设置标注角度") });
            this.rdoPointPlacementMethod.Size = new Size(224, 72);
            this.rdoPointPlacementMethod.TabIndex = 0;
            this.rdoPointPlacementMethod.SelectedIndexChanged += new EventHandler(this.rdoPointPlacementMethod_SelectedIndexChanged);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.imageComboBoxEdit1);
            this.panel1.Location = new Point(16, 74);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(224, 120);
            this.panel1.TabIndex = 1;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(16, 96);
            this.label3.Name = "label3";
            this.label3.Size = new Size(196, 17);
            this.label3.TabIndex = 2;
            this.label3.Text = "优先级：0=禁止，1=最高，3=最低 ";
            this.imageComboBoxEdit1.EditValue = "001000000";
            this.imageComboBoxEdit1.Location = new Point(16, 16);
            this.imageComboBoxEdit1.Name = "imageComboBoxEdit1";
            this.imageComboBoxEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.imageComboBoxEdit1.Properties.Items.AddRange(new object[] { 
                new ImageComboBoxItem("仅在右上", "001000000", 0), new ImageComboBoxItem("", "010000000", 1), new ImageComboBoxItem("", "100000000", 2), new ImageComboBoxItem("", "000001000", 3), new ImageComboBoxItem("", "000000001", 4), new ImageComboBoxItem("", "000000010", 5), new ImageComboBoxItem("", "000000100", 6), new ImageComboBoxItem("", "000100000", 7), new ImageComboBoxItem("", "221000000", 8), new ImageComboBoxItem("", "001002002", 9), new ImageComboBoxItem("", "212000000", 10), new ImageComboBoxItem("", "002001002", 11), new ImageComboBoxItem("", "002002001", 12), new ImageComboBoxItem("", "000000221", 13), new ImageComboBoxItem("", "000000212", 14), new ImageComboBoxItem("", "000000122", 15), 
                new ImageComboBoxItem("", "200200100", 16), new ImageComboBoxItem("", "200100200", 17), new ImageComboBoxItem("", "100200200", 18), new ImageComboBoxItem("", "122000000", 19), new ImageComboBoxItem("", "221003003", 20), new ImageComboBoxItem("", "331002002", 21), new ImageComboBoxItem("", "002002331", 22), new ImageComboBoxItem("", "003003221", 23), new ImageComboBoxItem("", "200200133", 24), new ImageComboBoxItem("", "300300122", 25), new ImageComboBoxItem("", "122300300", 26), new ImageComboBoxItem("", "133200200", 27), new ImageComboBoxItem("", "221302332", 28), new ImageComboBoxItem("", "212202232", 29), new ImageComboBoxItem("", "122203233", 30), new ImageComboBoxItem("", "222103222", 31), 
                new ImageComboBoxItem("", "233203122", 32), new ImageComboBoxItem("", "232202212", 33), new ImageComboBoxItem("", "332302221", 34), new ImageComboBoxItem("", "222301222", 35)
             });
            this.imageComboBoxEdit1.Properties.LargeImages = this.imageList1;
            this.imageComboBoxEdit1.Properties.SmallImages = this.imageList1;
            this.imageComboBoxEdit1.Size = new Size(104, 67);
            this.imageComboBoxEdit1.TabIndex = 1;
            this.imageComboBoxEdit1.SelectedIndexChanged += new EventHandler(this.imageComboBoxEdit1_SelectedIndexChanged);
            this.imageList1.ColorDepth = ColorDepth.Depth32Bit;
            this.imageList1.ImageSize = new Size(78, 63);
            this.imageList1.ImageStream = (ImageListStreamer) resources.GetObject("imageList1.ImageStream");
            this.imageList1.TransparentColor = Color.Transparent;
            this.panel2.Controls.Add(this.label1);
            this.panel2.Controls.Add(this.txtAngle);
            this.panel2.Controls.Add(this.groupBox1);
            this.panel2.Controls.Add(this.btnAddAngle);
            this.panel2.Location = new Point(16, 74);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(240, 168);
            this.panel2.TabIndex = 2;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 8);
            this.label1.Name = "label1";
            this.label1.Size = new Size(54, 17);
            this.label1.TabIndex = 3;
            this.label1.Text = "新建角度";
            this.txtAngle.EditValue = "";
            this.txtAngle.Location = new Point(72, 4);
            this.txtAngle.Name = "txtAngle";
            this.txtAngle.Size = new Size(64, 23);
            this.txtAngle.TabIndex = 2;
            this.groupBox1.Controls.Add(this.btnMoveDown);
            this.groupBox1.Controls.Add(this.btnMoveUp);
            this.groupBox1.Controls.Add(this.btnDeleteLayer);
            this.groupBox1.Controls.Add(this.listPointPlacementAngles);
            this.groupBox1.Location = new Point(16, 32);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(200, 136);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "角度";
            this.btnMoveDown.Image = (Image) resources.GetObject("btnMoveDown.Image");
            this.btnMoveDown.Location = new Point(136, 48);
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.Size = new Size(24, 24);
            this.btnMoveDown.TabIndex = 24;
            this.btnMoveDown.Click += new EventHandler(this.btnMoveDown_Click);
            this.btnMoveUp.Image = (Image) resources.GetObject("btnMoveUp.Image");
            this.btnMoveUp.Location = new Point(136, 16);
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.Size = new Size(24, 24);
            this.btnMoveUp.TabIndex = 23;
            this.btnMoveUp.Click += new EventHandler(this.btnMoveUp_Click);
            this.btnDeleteLayer.Image = (Image) resources.GetObject("btnDeleteLayer.Image");
            this.btnDeleteLayer.Location = new Point(136, 80);
            this.btnDeleteLayer.Name = "btnDeleteLayer";
            this.btnDeleteLayer.Size = new Size(24, 24);
            this.btnDeleteLayer.TabIndex = 22;
            this.btnDeleteLayer.Click += new EventHandler(this.btnDeleteLayer_Click);
            this.listPointPlacementAngles.ItemHeight = 12;
            this.listPointPlacementAngles.Location = new Point(8, 16);
            this.listPointPlacementAngles.Name = "listPointPlacementAngles";
            this.listPointPlacementAngles.Size = new Size(120, 88);
            this.listPointPlacementAngles.TabIndex = 0;
            this.listPointPlacementAngles.SelectedIndexChanged += new EventHandler(this.listPointPlacementAngles_SelectedIndexChanged);
            this.btnAddAngle.Location = new Point(144, 8);
            this.btnAddAngle.Name = "btnAddAngle";
            this.btnAddAngle.Size = new Size(72, 24);
            this.btnAddAngle.TabIndex = 0;
            this.btnAddAngle.Text = "添加角度";
            this.btnAddAngle.Click += new EventHandler(this.btnAddAngle_Click);
            this.panel3.Controls.Add(this.pictureEdit2);
            this.panel3.Controls.Add(this.pictureEdit1);
            this.panel3.Controls.Add(this.chkPerpendicularToAngle);
            this.panel3.Controls.Add(this.cboFields);
            this.panel3.Controls.Add(this.rdoRotationType);
            this.panel3.Controls.Add(this.label2);
            this.panel3.Location = new Point(16, 74);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(192, 168);
            this.panel3.TabIndex = 3;
            this.pictureEdit2.EditValue = resources.GetObject("pictureEdit2.EditValue");
            this.pictureEdit2.Location = new Point(88, 48);
            this.pictureEdit2.Name = "pictureEdit2";
            this.pictureEdit2.Properties.BorderStyle = BorderStyles.NoBorder;
            this.pictureEdit2.Properties.SizeMode = PictureSizeMode.Clip;
            this.pictureEdit2.Size = new Size(59, 59);
            this.pictureEdit2.TabIndex = 9;
            this.pictureEdit1.EditValue = (object)resources.GetObject("pictureEdit1.EditValue");
            this.pictureEdit1.Location = new Point(16, 48);
            this.pictureEdit1.Name = "pictureEdit1";
            this.pictureEdit1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.pictureEdit1.Properties.SizeMode = PictureSizeMode.Clip;
            this.pictureEdit1.Size = new Size(59, 59);
            this.pictureEdit1.TabIndex = 8;
            this.chkPerpendicularToAngle.Location = new Point(16, 136);
            this.chkPerpendicularToAngle.Name = "chkPerpendicularToAngle";
            this.chkPerpendicularToAngle.Properties.Caption = "标注方向垂直于该角度";
            this.chkPerpendicularToAngle.Size = new Size(152, 19);
            this.chkPerpendicularToAngle.TabIndex = 7;
            this.chkPerpendicularToAngle.CheckedChanged += new EventHandler(this.chkPerpendicularToAngle_CheckedChanged);
            this.cboFields.EditValue = "";
            this.cboFields.Location = new Point(48, 16);
            this.cboFields.Name = "cboFields";
            this.cboFields.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboFields.Size = new Size(112, 23);
            this.cboFields.TabIndex = 6;
            this.cboFields.SelectedIndexChanged += new EventHandler(this.comboBoxEdit1_SelectedIndexChanged);
            this.rdoRotationType.Location = new Point(16, 104);
            this.rdoRotationType.Name = "rdoRotationType";
            this.rdoRotationType.Properties.Appearance.BackColor = SystemColors.Control;
            this.rdoRotationType.Properties.Appearance.Options.UseBackColor = true;
            this.rdoRotationType.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoRotationType.Properties.Columns = 2;
            this.rdoRotationType.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "地理的"), new RadioGroupItem(null, "数学的") });
            this.rdoRotationType.Size = new Size(152, 32);
            this.rdoRotationType.TabIndex = 5;
            this.rdoRotationType.SelectedIndexChanged += new EventHandler(this.rdoRotationType_SelectedIndexChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 16);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 17);
            this.label2.TabIndex = 4;
            this.label2.Text = "字段";
            base.Controls.Add(this.panel3);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.rdoPointPlacementMethod);
            base.Name = "PointFeatureLabelCtrl";
            base.Size = new Size(272, 256);
            base.Load += new EventHandler(this.PointFeatureLabelCtrl_Load);
            this.rdoPointPlacementMethod.Properties.EndInit();
            this.panel1.ResumeLayout(false);
            this.imageComboBoxEdit1.Properties.EndInit();
            this.panel2.ResumeLayout(false);
            this.txtAngle.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.pictureEdit2.Properties.EndInit();
            this.pictureEdit1.Properties.EndInit();
            this.chkPerpendicularToAngle.Properties.EndInit();
            this.cboFields.Properties.EndInit();
            this.rdoRotationType.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private SimpleButton btnAddAngle;
        private SimpleButton btnDeleteLayer;
        private SimpleButton btnMoveDown;
        private SimpleButton btnMoveUp;
        private ComboBoxEdit cboFields;
        private CheckEdit chkPerpendicularToAngle;
        private GroupBox groupBox1;
        private ImageComboBoxEdit imageComboBoxEdit1;
        private ImageList imageList1;
        private Label label1;
        private Label label2;
        private Label label3;
        private ListBox listPointPlacementAngles;
        private Panel panel1;
        private Panel panel2;
        private Panel panel3;
        private PictureEdit pictureEdit1;
        private PictureEdit pictureEdit2;
        private RadioGroup rdoPointPlacementMethod;
        private RadioGroup rdoRotationType;
        private TextEdit txtAngle;
    }
}