using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Text;
using System.Resources;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class PrincipalDigitsLabelPropertyPage
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.components = new Container();
            System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(PrincipalDigitsLabelPropertyPage));
            this.groupBox1 = new GroupBox();
            this.groupBox2 = new GroupBox();
            this.groupBox3 = new GroupBox();
            this.label4 = new Label();
            this.label2 = new Label();
            this.label1 = new Label();
            this.cboFontSize = new ComboBoxEdit();
            this.colorEdit1 = new ColorEdit();
            this.chkUnderLine = new CheckBox();
            this.imageList1 = new ImageList(this.components);
            this.chkIta = new CheckBox();
            this.chkBold = new CheckBox();
            this.cboFontName = new System.Windows.Forms.ComboBox();
            this.label3 = new Label();
            this.label5 = new Label();
            this.txtPrincipalDigitCount = new SpinEdit();
            this.txtBaseDigitCount = new SpinEdit();
            this.label6 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.txtUnitSuffix = new TextEdit();
            this.txtEastingSuffix = new TextEdit();
            this.txtNorthingSuffix = new TextEdit();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.cboFontSize.Properties.BeginInit();
            this.colorEdit1.Properties.BeginInit();
            this.txtPrincipalDigitCount.Properties.BeginInit();
            this.txtBaseDigitCount.Properties.BeginInit();
            this.txtUnitSuffix.Properties.BeginInit();
            this.txtEastingSuffix.Properties.BeginInit();
            this.txtNorthingSuffix.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.cboFontSize);
            this.groupBox1.Controls.Add(this.colorEdit1);
            this.groupBox1.Controls.Add(this.chkUnderLine);
            this.groupBox1.Controls.Add(this.chkIta);
            this.groupBox1.Controls.Add(this.chkBold);
            this.groupBox1.Controls.Add(this.cboFontName);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Location = new Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(256, 120);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "次要字体";
            this.groupBox2.Controls.Add(this.txtBaseDigitCount);
            this.groupBox2.Controls.Add(this.txtPrincipalDigitCount);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Location = new Point(8, 136);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(248, 96);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "数字";
            this.groupBox3.Controls.Add(this.txtNorthingSuffix);
            this.groupBox3.Controls.Add(this.txtEastingSuffix);
            this.groupBox3.Controls.Add(this.txtUnitSuffix);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Controls.Add(this.label6);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Location = new Point(16, 240);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(248, 104);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "字符串";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(16, 53);
            this.label4.Name = "label4";
            this.label4.Size = new Size(35, 17);
            this.label4.TabIndex = 48;
            this.label4.Text = "大小:";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 85);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 17);
            this.label2.TabIndex = 47;
            this.label2.Text = "颜色:";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 29);
            this.label1.Name = "label1";
            this.label1.Size = new Size(35, 17);
            this.label1.TabIndex = 46;
            this.label1.Text = "字体:";
            this.cboFontSize.EditValue = "5";
            this.cboFontSize.Location = new Point(56, 53);
            this.cboFontSize.Name = "cboFontSize";
            this.cboFontSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboFontSize.Properties.Items.AddRange(new object[] { 
                "5", "6", "7", "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", 
                "34", "36", "48", "72"
             });
            this.cboFontSize.Size = new Size(64, 23);
            this.cboFontSize.TabIndex = 45;
            this.cboFontSize.SelectedIndexChanged += new EventHandler(this.cboFontSize_SelectedIndexChanged);
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new Point(56, 85);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 23);
            this.colorEdit1.TabIndex = 44;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.chkUnderLine.Appearance = Appearance.Button;
            this.chkUnderLine.ImageIndex = 2;
            this.chkUnderLine.ImageList = this.imageList1;
            this.chkUnderLine.Location = new Point(200, 53);
            this.chkUnderLine.Name = "chkUnderLine";
            this.chkUnderLine.Size = new Size(28, 24);
            this.chkUnderLine.TabIndex = 43;
            this.chkUnderLine.CheckedChanged += new EventHandler(this.chkUnderLine_CheckedChanged);
            this.imageList1.ImageSize = new Size(16, 16);
            this.imageList1.ImageStream = (ImageListStreamer) resources.GetObject("imageList1.ImageStream");
            this.imageList1.TransparentColor = Color.Magenta;
            this.chkIta.Appearance = Appearance.Button;
            this.chkIta.ImageIndex = 1;
            this.chkIta.ImageList = this.imageList1;
            this.chkIta.Location = new Point(168, 53);
            this.chkIta.Name = "chkIta";
            this.chkIta.Size = new Size(28, 24);
            this.chkIta.TabIndex = 42;
            this.chkIta.CheckedChanged += new EventHandler(this.chkIta_CheckedChanged);
            this.chkBold.Appearance = Appearance.Button;
            this.chkBold.ImageIndex = 0;
            this.chkBold.ImageList = this.imageList1;
            this.chkBold.Location = new Point(136, 53);
            this.chkBold.Name = "chkBold";
            this.chkBold.Size = new Size(28, 24);
            this.chkBold.TabIndex = 41;
            this.chkBold.CheckedChanged += new EventHandler(this.chkBold_CheckedChanged);
            this.cboFontName.Location = new Point(56, 29);
            this.cboFontName.Name = "cboFontName";
            this.cboFontName.Size = new Size(184, 20);
            this.cboFontName.TabIndex = 40;
            this.cboFontName.SelectedIndexChanged += new EventHandler(this.cboFontName_SelectedIndexChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(24, 24);
            this.label3.Name = "label3";
            this.label3.Size = new Size(79, 17);
            this.label3.TabIndex = 0;
            this.label3.Text = "主要数字位数";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(24, 56);
            this.label5.Name = "label5";
            this.label5.Size = new Size(79, 17);
            this.label5.TabIndex = 1;
            this.label5.Text = "基础数字位数";
            int[] bits = new int[4];
            bits[0] = 2;
            this.txtPrincipalDigitCount.EditValue = new decimal(bits);
            this.txtPrincipalDigitCount.Location = new Point(120, 24);
            this.txtPrincipalDigitCount.Name = "txtPrincipalDigitCount";
            this.txtPrincipalDigitCount.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtPrincipalDigitCount.Properties.UseCtrlIncrement = false;
            this.txtPrincipalDigitCount.Size = new Size(80, 23);
            this.txtPrincipalDigitCount.TabIndex = 2;
            this.txtPrincipalDigitCount.EditValueChanged += new EventHandler(this.txtPrincipalDigitCount_EditValueChanged);
            bits = new int[4];
            bits[0] = 4;
            this.txtBaseDigitCount.EditValue = new decimal(bits);
            this.txtBaseDigitCount.Location = new Point(120, 56);
            this.txtBaseDigitCount.Name = "txtBaseDigitCount";
            this.txtBaseDigitCount.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.txtBaseDigitCount.Properties.UseCtrlIncrement = false;
            this.txtBaseDigitCount.Size = new Size(80, 23);
            this.txtBaseDigitCount.TabIndex = 3;
            this.txtBaseDigitCount.EditValueChanged += new EventHandler(this.txtBaseDigitCount_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(8, 40);
            this.label6.Name = "label6";
            this.label6.Size = new Size(54, 17);
            this.label6.TabIndex = 3;
            this.label6.Text = "东向后缀";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(8, 16);
            this.label7.Name = "label7";
            this.label7.Size = new Size(54, 17);
            this.label7.TabIndex = 2;
            this.label7.Text = "单位后缀";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(8, 72);
            this.label8.Name = "label8";
            this.label8.Size = new Size(54, 17);
            this.label8.TabIndex = 4;
            this.label8.Text = "北向后缀";
            this.txtUnitSuffix.EditValue = "m.";
            this.txtUnitSuffix.Location = new Point(72, 16);
            this.txtUnitSuffix.Name = "txtUnitSuffix";
            this.txtUnitSuffix.Size = new Size(88, 23);
            this.txtUnitSuffix.TabIndex = 5;
            this.txtUnitSuffix.EditValueChanged += new EventHandler(this.txtUnitSuffix_EditValueChanged);
            this.txtEastingSuffix.EditValue = "E";
            this.txtEastingSuffix.Location = new Point(72, 44);
            this.txtEastingSuffix.Name = "txtEastingSuffix";
            this.txtEastingSuffix.Size = new Size(88, 23);
            this.txtEastingSuffix.TabIndex = 6;
            this.txtEastingSuffix.EditValueChanged += new EventHandler(this.txtEastingSuffix_EditValueChanged);
            this.txtNorthingSuffix.EditValue = "N";
            this.txtNorthingSuffix.Location = new Point(72, 72);
            this.txtNorthingSuffix.Name = "txtNorthingSuffix";
            this.txtNorthingSuffix.Size = new Size(88, 23);
            this.txtNorthingSuffix.TabIndex = 7;
            this.txtNorthingSuffix.EditValueChanged += new EventHandler(this.txtNorthingSuffix_EditValueChanged);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "PrincipalDigitsLabelPropertyPage";
            base.Size = new Size(288, 352);
            base.Load += new EventHandler(this.PrincipalDigitsLabelPropertyPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.cboFontSize.Properties.EndInit();
            this.colorEdit1.Properties.EndInit();
            this.txtPrincipalDigitCount.Properties.EndInit();
            this.txtBaseDigitCount.Properties.EndInit();
            this.txtUnitSuffix.Properties.EndInit();
            this.txtEastingSuffix.Properties.EndInit();
            this.txtNorthingSuffix.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private System.Windows.Forms.ComboBox cboFontName;
        private ComboBoxEdit cboFontSize;
        private CheckBox chkBold;
        private CheckBox chkIta;
        private CheckBox chkUnderLine;
        private ColorEdit colorEdit1;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private ImageList imageList1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private SpinEdit txtBaseDigitCount;
        private TextEdit txtEastingSuffix;
        private TextEdit txtNorthingSuffix;
        private SpinEdit txtPrincipalDigitCount;
        private TextEdit txtUnitSuffix;
    }
}