using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common.SymbolUI;

namespace Yutai.ArcGIS.Controls.SymbolUI
{
    partial class SimpleMarkerControl
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.label7 = new Label();
            this.colorEdit1 = new ColorEdit();
            this.colorEditOutline = new ColorEdit();
            this.numericUpDownSize = new SpinEdit();
            this.numericUpDownYOffset = new SpinEdit();
            this.numericUpDownXOffset = new SpinEdit();
            this.numericUpDownOutlineWidth = new SpinEdit();
            this.cboStyle = new ComboBoxEdit();
            this.chkUseOutline = new CheckEdit();
            this.colorEdit1.Properties.BeginInit();
            this.colorEditOutline.Properties.BeginInit();
            this.numericUpDownSize.Properties.BeginInit();
            this.numericUpDownYOffset.Properties.BeginInit();
            this.numericUpDownXOffset.Properties.BeginInit();
            this.numericUpDownOutlineWidth.Properties.BeginInit();
            this.cboStyle.Properties.BeginInit();
            this.chkUseOutline.Properties.BeginInit();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 21);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 0;
            this.label1.Text = "颜色";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 53);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 17);
            this.label2.TabIndex = 2;
            this.label2.Text = "样式";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(16, 85);
            this.label3.Name = "label3";
            this.label3.Size = new Size(29, 17);
            this.label3.TabIndex = 4;
            this.label3.Text = "大小";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(16, 117);
            this.label4.Name = "label4";
            this.label4.Size = new Size(35, 17);
            this.label4.TabIndex = 7;
            this.label4.Text = "X偏移";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(16, 149);
            this.label5.Name = "label5";
            this.label5.Size = new Size(35, 17);
            this.label5.TabIndex = 10;
            this.label5.Text = "Y偏移";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(184, 114);
            this.label6.Name = "label6";
            this.label6.Size = new Size(66, 17);
            this.label6.TabIndex = 14;
            this.label6.Text = "轮廓线颜色";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(184, 145);
            this.label7.Name = "label7";
            this.label7.Size = new Size(54, 17);
            this.label7.TabIndex = 16;
            this.label7.Text = "轮廓线宽";
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new Point(56, 16);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 23);
            this.colorEdit1.TabIndex = 45;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.colorEditOutline.EditValue = Color.Empty;
            this.colorEditOutline.Location = new Point(256, 112);
            this.colorEditOutline.Name = "colorEditOutline";
            this.colorEditOutline.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEditOutline.Size = new Size(48, 23);
            this.colorEditOutline.TabIndex = 46;
            this.colorEditOutline.EditValueChanged += new EventHandler(this.colorEditOutline_EditValueChanged);
            int[] bits = new int[4];
            this.numericUpDownSize.EditValue = new decimal(bits);
            this.numericUpDownSize.Location = new Point(56, 80);
            this.numericUpDownSize.Name = "numericUpDownSize";
            this.numericUpDownSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownSize.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownSize.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownSize.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownSize.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownSize.Properties.MaxValue = new decimal(bits);
            this.numericUpDownSize.Properties.UseCtrlIncrement = false;
            this.numericUpDownSize.Size = new Size(80, 23);
            this.numericUpDownSize.TabIndex = 69;
            this.numericUpDownSize.TextChanged += new EventHandler(this.numericUpDownSize_ValueChanged);
            bits = new int[4];
            this.numericUpDownYOffset.EditValue = new decimal(bits);
            this.numericUpDownYOffset.Location = new Point(56, 144);
            this.numericUpDownYOffset.Name = "numericUpDownYOffset";
            this.numericUpDownYOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownYOffset.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownYOffset.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownYOffset.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownYOffset.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownYOffset.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 100;
            bits[3] = -2147483648;
            this.numericUpDownYOffset.Properties.MinValue = new decimal(bits);
            this.numericUpDownYOffset.Properties.UseCtrlIncrement = false;
            this.numericUpDownYOffset.Size = new Size(80, 23);
            this.numericUpDownYOffset.TabIndex = 68;
            this.numericUpDownYOffset.TextChanged += new EventHandler(this.numericUpDownYOffset_ValueChanged);
            bits = new int[4];
            this.numericUpDownXOffset.EditValue = new decimal(bits);
            this.numericUpDownXOffset.Location = new Point(56, 112);
            this.numericUpDownXOffset.Name = "numericUpDownXOffset";
            this.numericUpDownXOffset.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownXOffset.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownXOffset.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownXOffset.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownXOffset.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownXOffset.Properties.MaxValue = new decimal(bits);
            bits = new int[4];
            bits[0] = 100;
            bits[3] = -2147483648;
            this.numericUpDownXOffset.Properties.MinValue = new decimal(bits);
            this.numericUpDownXOffset.Properties.UseCtrlIncrement = false;
            this.numericUpDownXOffset.Size = new Size(80, 23);
            this.numericUpDownXOffset.TabIndex = 67;
            this.numericUpDownXOffset.TextChanged += new EventHandler(this.numericUpDownXOffset_ValueChanged);
            bits = new int[4];
            this.numericUpDownOutlineWidth.EditValue = new decimal(bits);
            this.numericUpDownOutlineWidth.Location = new Point(256, 144);
            this.numericUpDownOutlineWidth.Name = "numericUpDownOutlineWidth";
            this.numericUpDownOutlineWidth.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.numericUpDownOutlineWidth.Properties.DisplayFormat.FormatString = "0.####";
            this.numericUpDownOutlineWidth.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.numericUpDownOutlineWidth.Properties.EditFormat.FormatString = "0.####";
            this.numericUpDownOutlineWidth.Properties.EditFormat.FormatType = FormatType.Numeric;
            bits = new int[4];
            bits[0] = 100;
            this.numericUpDownOutlineWidth.Properties.MaxValue = new decimal(bits);
            this.numericUpDownOutlineWidth.Properties.UseCtrlIncrement = false;
            this.numericUpDownOutlineWidth.Size = new Size(80, 23);
            this.numericUpDownOutlineWidth.TabIndex = 70;
            this.numericUpDownOutlineWidth.TextChanged += new EventHandler(this.numericUpDownOutlineWidth_ValueChanged);
            this.cboStyle.EditValue = "";
            this.cboStyle.Location = new Point(56, 48);
            this.cboStyle.Name = "cboStyle";
            this.cboStyle.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboStyle.Properties.Items.AddRange(new object[] { "圆形", "方形", "十字形", "X形", "棱形" });
            this.cboStyle.Size = new Size(80, 23);
            this.cboStyle.TabIndex = 71;
            this.cboStyle.SelectedIndexChanged += new EventHandler(this.cboStyle_SelectedIndexChanged);
            this.chkUseOutline.Location = new Point(184, 80);
            this.chkUseOutline.Name = "chkUseOutline";
            this.chkUseOutline.Properties.Caption = "使用轮廓线";
            this.chkUseOutline.Size = new Size(88, 19);
            this.chkUseOutline.TabIndex = 72;
            this.chkUseOutline.CheckedChanged += new EventHandler(this.chkUseOutline_CheckedChanged);
            base.Controls.Add(this.chkUseOutline);
            base.Controls.Add(this.cboStyle);
            base.Controls.Add(this.numericUpDownOutlineWidth);
            base.Controls.Add(this.numericUpDownSize);
            base.Controls.Add(this.numericUpDownYOffset);
            base.Controls.Add(this.numericUpDownXOffset);
            base.Controls.Add(this.colorEditOutline);
            base.Controls.Add(this.colorEdit1);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label5);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label1);
            base.Name = "SimpleMarkerControl";
            base.Size = new Size(376, 272);
            base.Load += new EventHandler(this.SimpleMarkerControl_Load);
            this.colorEdit1.Properties.EndInit();
            this.colorEditOutline.Properties.EndInit();
            this.numericUpDownSize.Properties.EndInit();
            this.numericUpDownYOffset.Properties.EndInit();
            this.numericUpDownXOffset.Properties.EndInit();
            this.numericUpDownOutlineWidth.Properties.EndInit();
            this.cboStyle.Properties.EndInit();
            this.chkUseOutline.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private Container components = null;
        private ComboBoxEdit cboStyle;
        private CheckEdit chkUseOutline;
        private ColorEdit colorEdit1;
        private ColorEdit colorEditOutline;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private SpinEdit numericUpDownOutlineWidth;
        private SpinEdit numericUpDownSize;
        private SpinEdit numericUpDownXOffset;
        private SpinEdit numericUpDownYOffset;
    }
}