using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.ADF;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.Geometry;

namespace Yutai.ArcGIS.Common.Query.UI
{
    partial class SpatialAndAttributeQueryCtrl
    {
        protected override void Dispose(bool bool_0)
        {
            if (bool_0 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_0);
        }

       
 private void InitializeComponent()
        {
            this.btnApply = new SimpleButton();
            this.chkUsetSelectedLayer = new CheckEdit();
            this.label2 = new Label();
            this.cboOperationType = new ComboBoxEdit();
            this.label1 = new Label();
            this.memEditWhereCaluse = new MemoEdit();
            this.comboBoxLayer = new ComboBoxEdit();
            this.label4 = new Label();
            this.groupBox1 = new GroupBox();
            this.cboUnit = new ComboBoxEdit();
            this.txtRadius = new TextEdit();
            this.chkUseBuffer = new CheckEdit();
            this.chkUseSelectFeature = new CheckEdit();
            this.cboSourceLayer = new ComboBoxEdit();
            this.label3 = new Label();
            this.cboSpatialRelation = new ComboBoxEdit();
            this.panel1 = new Panel();
            this.lblStatu = new Label();
            this.btnCreateQuery = new SimpleButton();
            this.chkUsetSelectedLayer.Properties.BeginInit();
            this.cboOperationType.Properties.BeginInit();
            this.memEditWhereCaluse.Properties.BeginInit();
            this.comboBoxLayer.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.cboUnit.Properties.BeginInit();
            this.txtRadius.Properties.BeginInit();
            this.chkUseBuffer.Properties.BeginInit();
            this.chkUseSelectFeature.Properties.BeginInit();
            this.cboSourceLayer.Properties.BeginInit();
            this.cboSpatialRelation.Properties.BeginInit();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            this.btnApply.Location = new System.Drawing.Point(267, 331);
            this.btnApply.Name = "btnApply";
            this.btnApply.Size = new Size(64, 24);
            this.btnApply.TabIndex = 27;
            this.btnApply.Text = "应用";
            this.btnApply.Click += new EventHandler(this.btnApply_Click);
            this.chkUsetSelectedLayer.Location = new System.Drawing.Point(52, 45);
            this.chkUsetSelectedLayer.Name = "chkUsetSelectedLayer";
            this.chkUsetSelectedLayer.Properties.Caption = "只显示可选图层";
            this.chkUsetSelectedLayer.Size = new Size(112, 19);
            this.chkUsetSelectedLayer.TabIndex = 19;
            this.chkUsetSelectedLayer.Visible = false;
            this.chkUsetSelectedLayer.CheckedChanged += new EventHandler(this.chkUsetSelectedLayer_CheckedChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(17, 27);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 12);
            this.label2.TabIndex = 18;
            this.label2.Text = "图层";
            this.cboOperationType.EditValue = "选择要素";
            this.cboOperationType.Location = new System.Drawing.Point(17, 70);
            this.cboOperationType.Name = "cboOperationType";
            this.cboOperationType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboOperationType.Properties.Items.AddRange(new object[] { "选择要素", "选择要素,并添加到选择集中", "的选择集中删除", "的选择集中选择" });
            this.cboOperationType.Size = new Size(248, 21);
            this.cboOperationType.TabIndex = 16;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(17, 3);
            this.label1.Name = "label1";
            this.label1.Size = new Size(209, 12);
            this.label1.TabIndex = 15;
            this.label1.Text = "根据要素的空间关系从图层中选择要素";
            this.memEditWhereCaluse.EditValue = "";
            this.memEditWhereCaluse.Location = new System.Drawing.Point(7, 263);
            this.memEditWhereCaluse.Name = "memEditWhereCaluse";
            this.memEditWhereCaluse.Size = new Size(343, 62);
            this.memEditWhereCaluse.TabIndex = 29;
            this.comboBoxLayer.EditValue = "";
            this.comboBoxLayer.Location = new System.Drawing.Point(52, 18);
            this.comboBoxLayer.Name = "comboBoxLayer";
            this.comboBoxLayer.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.comboBoxLayer.Size = new Size(288, 21);
            this.comboBoxLayer.TabIndex = 49;
            this.comboBoxLayer.SelectedIndexChanged += new EventHandler(this.comboBoxLayer_SelectedIndexChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(13, 241);
            this.label4.Name = "label4";
            this.label4.Size = new Size(125, 12);
            this.label4.TabIndex = 50;
            this.label4.Text = "并满足如下条件的要素";
            this.groupBox1.Controls.Add(this.cboUnit);
            this.groupBox1.Controls.Add(this.txtRadius);
            this.groupBox1.Controls.Add(this.chkUseBuffer);
            this.groupBox1.Controls.Add(this.chkUseSelectFeature);
            this.groupBox1.Controls.Add(this.cboSourceLayer);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.cboSpatialRelation);
            this.groupBox1.Location = new System.Drawing.Point(7, 93);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(343, 145);
            this.groupBox1.TabIndex = 51;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "空间过滤";
            this.cboUnit.EditValue = "";
            this.cboUnit.Location = new System.Drawing.Point(106, 118);
            this.cboUnit.Name = "cboUnit";
            this.cboUnit.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboUnit.Size = new Size(96, 21);
            this.cboUnit.TabIndex = 33;
            this.cboUnit.Visible = false;
            this.txtRadius.EditValue = "0";
            this.txtRadius.Location = new System.Drawing.Point(10, 118);
            this.txtRadius.Name = "txtRadius";
            this.txtRadius.Size = new Size(88, 21);
            this.txtRadius.TabIndex = 32;
            this.chkUseBuffer.Location = new System.Drawing.Point(10, 94);
            this.chkUseBuffer.Name = "chkUseBuffer";
            this.chkUseBuffer.Properties.Caption = "对要素进行缓冲区操作";
            this.chkUseBuffer.Size = new Size(168, 19);
            this.chkUseBuffer.TabIndex = 31;
            this.chkUseBuffer.CheckedChanged += new EventHandler(this.chkUseBuffer_CheckedChanged);
            this.chkUseSelectFeature.Location = new System.Drawing.Point(162, 36);
            this.chkUseSelectFeature.Name = "chkUseSelectFeature";
            this.chkUseSelectFeature.Properties.Caption = "使用选中的要素";
            this.chkUseSelectFeature.Size = new Size(104, 19);
            this.chkUseSelectFeature.TabIndex = 30;
            this.cboSourceLayer.EditValue = "";
            this.cboSourceLayer.Location = new System.Drawing.Point(10, 36);
            this.cboSourceLayer.Name = "cboSourceLayer";
            this.cboSourceLayer.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboSourceLayer.Size = new Size(144, 21);
            this.cboSourceLayer.TabIndex = 29;
            this.cboSourceLayer.SelectedIndexChanged += new EventHandler(this.cboSourceLayer_SelectedIndexChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(10, 20);
            this.label3.Name = "label3";
            this.label3.Size = new Size(89, 12);
            this.label3.TabIndex = 28;
            this.label3.Text = "与图层中的要素";
            this.cboSpatialRelation.EditValue = "相交";
            this.cboSpatialRelation.Location = new System.Drawing.Point(10, 65);
            this.cboSpatialRelation.Name = "cboSpatialRelation";
            this.cboSpatialRelation.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboSpatialRelation.Properties.Items.AddRange(new object[] { "相交", "包围矩形相交", "相接", "重叠", "被包含", "包含" });
            this.cboSpatialRelation.Size = new Size(248, 21);
            this.cboSpatialRelation.TabIndex = 27;
            this.panel1.Controls.Add(this.lblStatu);
            this.panel1.Location = new System.Drawing.Point(162, 191);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(152, 64);
            this.panel1.TabIndex = 52;
            this.panel1.Visible = false;
            this.lblStatu.AutoSize = true;
            this.lblStatu.Location = new System.Drawing.Point(8, 8);
            this.lblStatu.Name = "lblStatu";
            this.lblStatu.Size = new Size(107, 12);
            this.lblStatu.TabIndex = 14;
            this.lblStatu.Text = "正在查找请稍候...";
            this.btnCreateQuery.Location = new System.Drawing.Point(7, 331);
            this.btnCreateQuery.Name = "btnCreateQuery";
            this.btnCreateQuery.Size = new Size(93, 24);
            this.btnCreateQuery.TabIndex = 53;
            this.btnCreateQuery.Text = "构建查询条件";
            this.btnCreateQuery.Click += new EventHandler(this.btnCreateQuery_Click);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.btnCreateQuery);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.comboBoxLayer);
            base.Controls.Add(this.memEditWhereCaluse);
            base.Controls.Add(this.btnApply);
            base.Controls.Add(this.chkUsetSelectedLayer);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.cboOperationType);
            base.Controls.Add(this.label1);
            base.Name = "SpatialAndAttributeQueryCtrl";
            base.Size = new Size(366, 384);
            base.Load += new EventHandler(this.SpatialAndAttributeQueryCtrl_Load);
            this.chkUsetSelectedLayer.Properties.EndInit();
            this.cboOperationType.Properties.EndInit();
            this.memEditWhereCaluse.Properties.EndInit();
            this.comboBoxLayer.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.cboUnit.Properties.EndInit();
            this.txtRadius.Properties.EndInit();
            this.chkUseBuffer.Properties.EndInit();
            this.chkUseSelectFeature.Properties.EndInit();
            this.cboSourceLayer.Properties.EndInit();
            this.cboSpatialRelation.Properties.EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private SimpleButton btnApply;
        private SimpleButton btnCreateQuery;
        private ComboBoxEdit cboOperationType;
        private ComboBoxEdit cboSourceLayer;
        private ComboBoxEdit cboSpatialRelation;
        private ComboBoxEdit cboUnit;
        private CheckEdit chkUseBuffer;
        private CheckEdit chkUseSelectFeature;
        private CheckEdit chkUsetSelectedLayer;
        private ComboBoxEdit comboBoxLayer;
        private GroupBox groupBox1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label lblStatu;
        private MemoEdit memEditWhereCaluse;
        private Panel panel1;
        private TextEdit txtRadius;
    }
}