using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common.BaseClasses;

namespace Yutai.ArcGIS.Carto.MapCartoTemplateLib
{
    partial class ElementPosition
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
        private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.label2 = new Label();
            this.rdoLowRight = new RadioButton();
            this.rdoLowLeft = new RadioButton();
            this.rdoUpperRight = new RadioButton();
            this.rdoUpperLeft = new RadioButton();
            this.rdoLowCenter = new RadioButton();
            this.rdoLeftCenter = new RadioButton();
            this.rdoLeftLow = new RadioButton();
            this.rdoRightLow = new RadioButton();
            this.rdoRightCenter = new RadioButton();
            this.rdoRightUpper = new RadioButton();
            this.rdoUpperCenter = new RadioButton();
            this.rdoLeftUpper = new RadioButton();
            this.lblOffsetX = new Label();
            this.label1 = new Label();
            this.txtOffsetX = new TextBox();
            this.txtOffsetY = new TextBox();
            this.txtW = new TextBox();
            this.txtH = new TextBox();
            this.label3 = new Label();
            this.label4 = new Label();
            this.groupBox2 = new GroupBox();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.rdoLowRight);
            this.groupBox1.Controls.Add(this.rdoLowLeft);
            this.groupBox1.Controls.Add(this.rdoUpperRight);
            this.groupBox1.Controls.Add(this.rdoUpperLeft);
            this.groupBox1.Controls.Add(this.rdoLowCenter);
            this.groupBox1.Controls.Add(this.rdoLeftCenter);
            this.groupBox1.Controls.Add(this.rdoLeftLow);
            this.groupBox1.Controls.Add(this.rdoRightLow);
            this.groupBox1.Controls.Add(this.rdoRightCenter);
            this.groupBox1.Controls.Add(this.rdoRightUpper);
            this.groupBox1.Controls.Add(this.rdoUpperCenter);
            this.groupBox1.Controls.Add(this.rdoLeftUpper);
            this.groupBox1.Location = new System.Drawing.Point(12, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(289, 132);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "放置位置";
            this.label2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.label2.Location = new System.Drawing.Point(60, 45);
            this.label2.Name = "label2";
            this.label2.Size = new Size(130, 58);
            this.label2.TabIndex = 12;
            this.label2.Text = "图框";
            this.label2.TextAlign = ContentAlignment.MiddleCenter;
            this.rdoLowRight.AutoSize = true;
            this.rdoLowRight.Location = new System.Drawing.Point(168, 109);
            this.rdoLowRight.Name = "rdoLowRight";
            this.rdoLowRight.Size = new Size(47, 16);
            this.rdoLowRight.TabIndex = 11;
            this.rdoLowRight.Text = "下右";
            this.rdoLowRight.UseVisualStyleBackColor = true;
            this.rdoLowRight.CheckedChanged += new EventHandler(this.rdoLowRight_CheckedChanged);
            this.rdoLowLeft.AutoSize = true;
            this.rdoLowLeft.Location = new System.Drawing.Point(53, 109);
            this.rdoLowLeft.Name = "rdoLowLeft";
            this.rdoLowLeft.Size = new Size(47, 16);
            this.rdoLowLeft.TabIndex = 10;
            this.rdoLowLeft.Text = "下左";
            this.rdoLowLeft.UseVisualStyleBackColor = true;
            this.rdoUpperRight.AutoSize = true;
            this.rdoUpperRight.Location = new System.Drawing.Point(159, 20);
            this.rdoUpperRight.Name = "rdoUpperRight";
            this.rdoUpperRight.Size = new Size(47, 16);
            this.rdoUpperRight.TabIndex = 9;
            this.rdoUpperRight.Text = "上右";
            this.rdoUpperRight.UseVisualStyleBackColor = true;
            this.rdoUpperLeft.AutoSize = true;
            this.rdoUpperLeft.Location = new System.Drawing.Point(53, 20);
            this.rdoUpperLeft.Name = "rdoUpperLeft";
            this.rdoUpperLeft.Size = new Size(47, 16);
            this.rdoUpperLeft.TabIndex = 8;
            this.rdoUpperLeft.Text = "上左";
            this.rdoUpperLeft.UseVisualStyleBackColor = true;
            this.rdoLowCenter.AutoSize = true;
            this.rdoLowCenter.Location = new System.Drawing.Point(106, 109);
            this.rdoLowCenter.Name = "rdoLowCenter";
            this.rdoLowCenter.Size = new Size(47, 16);
            this.rdoLowCenter.TabIndex = 7;
            this.rdoLowCenter.Text = "下中";
            this.rdoLowCenter.UseVisualStyleBackColor = true;
            this.rdoLowCenter.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoLeftCenter.AutoSize = true;
            this.rdoLeftCenter.Location = new System.Drawing.Point(6, 65);
            this.rdoLeftCenter.Name = "rdoLeftCenter";
            this.rdoLeftCenter.Size = new Size(47, 16);
            this.rdoLeftCenter.TabIndex = 6;
            this.rdoLeftCenter.Text = "左中";
            this.rdoLeftCenter.UseVisualStyleBackColor = true;
            this.rdoLeftCenter.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoLeftLow.AutoSize = true;
            this.rdoLeftLow.Location = new System.Drawing.Point(6, 87);
            this.rdoLeftLow.Name = "rdoLeftLow";
            this.rdoLeftLow.Size = new Size(47, 16);
            this.rdoLeftLow.TabIndex = 5;
            this.rdoLeftLow.Text = "左下";
            this.rdoLeftLow.UseVisualStyleBackColor = true;
            this.rdoLeftLow.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoRightLow.AutoSize = true;
            this.rdoRightLow.Location = new System.Drawing.Point(212, 87);
            this.rdoRightLow.Name = "rdoRightLow";
            this.rdoRightLow.Size = new Size(47, 16);
            this.rdoRightLow.TabIndex = 4;
            this.rdoRightLow.Text = "右下";
            this.rdoRightLow.UseVisualStyleBackColor = true;
            this.rdoRightLow.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoRightCenter.AutoSize = true;
            this.rdoRightCenter.Location = new System.Drawing.Point(212, 65);
            this.rdoRightCenter.Name = "rdoRightCenter";
            this.rdoRightCenter.Size = new Size(47, 16);
            this.rdoRightCenter.TabIndex = 3;
            this.rdoRightCenter.Text = "右中";
            this.rdoRightCenter.UseVisualStyleBackColor = true;
            this.rdoRightCenter.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoRightUpper.AutoSize = true;
            this.rdoRightUpper.Location = new System.Drawing.Point(212, 42);
            this.rdoRightUpper.Name = "rdoRightUpper";
            this.rdoRightUpper.Size = new Size(47, 16);
            this.rdoRightUpper.TabIndex = 2;
            this.rdoRightUpper.Text = "右上";
            this.rdoRightUpper.UseVisualStyleBackColor = true;
            this.rdoRightUpper.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoUpperCenter.AutoSize = true;
            this.rdoUpperCenter.Location = new System.Drawing.Point(106, 20);
            this.rdoUpperCenter.Name = "rdoUpperCenter";
            this.rdoUpperCenter.Size = new Size(47, 16);
            this.rdoUpperCenter.TabIndex = 1;
            this.rdoUpperCenter.Text = "上中";
            this.rdoUpperCenter.UseVisualStyleBackColor = true;
            this.rdoUpperCenter.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.rdoLeftUpper.AutoSize = true;
            this.rdoLeftUpper.Checked = true;
            this.rdoLeftUpper.Location = new System.Drawing.Point(6, 42);
            this.rdoLeftUpper.Name = "rdoLeftUpper";
            this.rdoLeftUpper.Size = new Size(47, 16);
            this.rdoLeftUpper.TabIndex = 0;
            this.rdoLeftUpper.TabStop = true;
            this.rdoLeftUpper.Text = "左上";
            this.rdoLeftUpper.UseVisualStyleBackColor = true;
            this.rdoLeftUpper.CheckedChanged += new EventHandler(this.rdoLeftUpper_CheckedChanged);
            this.lblOffsetX.AutoSize = true;
            this.lblOffsetX.Location = new System.Drawing.Point(16, 149);
            this.lblOffsetX.Name = "lblOffsetX";
            this.lblOffsetX.Size = new Size(53, 12);
            this.lblOffsetX.TabIndex = 1;
            this.lblOffsetX.Text = "水平偏移";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(16, 182);
            this.label1.Name = "label1";
            this.label1.Size = new Size(53, 12);
            this.label1.TabIndex = 2;
            this.label1.Text = "竖直偏移";
            this.txtOffsetX.Location = new System.Drawing.Point(75, 146);
            this.txtOffsetX.Name = "txtOffsetX";
            this.txtOffsetX.Size = new Size(73, 21);
            this.txtOffsetX.TabIndex = 3;
            this.txtOffsetX.Text = "0";
            this.txtOffsetX.TextChanged += new EventHandler(this.txtOffsetY_TextChanged);
            this.txtOffsetY.Location = new System.Drawing.Point(75, 179);
            this.txtOffsetY.Name = "txtOffsetY";
            this.txtOffsetY.Size = new Size(73, 21);
            this.txtOffsetY.TabIndex = 4;
            this.txtOffsetY.Text = "0";
            this.txtOffsetY.TextChanged += new EventHandler(this.txtOffsetY_TextChanged);
            this.txtW.Location = new System.Drawing.Point(39, 49);
            this.txtW.Name = "txtW";
            this.txtW.Size = new Size(90, 21);
            this.txtW.TabIndex = 8;
            this.txtW.Text = "0";
            this.txtW.TextChanged += new EventHandler(this.txtW_TextChanged);
            this.txtH.Location = new System.Drawing.Point(39, 16);
            this.txtH.Name = "txtH";
            this.txtH.Size = new Size(90, 21);
            this.txtH.TabIndex = 7;
            this.txtH.Text = "0";
            this.txtH.TextChanged += new EventHandler(this.txtH_TextChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(16, 54);
            this.label3.Name = "label3";
            this.label3.Size = new Size(17, 12);
            this.label3.TabIndex = 6;
            this.label3.Text = "宽";
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(16, 21);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 12);
            this.label4.TabIndex = 5;
            this.label4.Text = "高";
            this.groupBox2.Controls.Add(this.txtW);
            this.groupBox2.Controls.Add(this.txtH);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Location = new System.Drawing.Point(157, 141);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(144, 79);
            this.groupBox2.TabIndex = 6;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "大小";
            this.groupBox2.Visible = false;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.txtOffsetY);
            base.Controls.Add(this.txtOffsetX);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.lblOffsetX);
            base.Controls.Add(this.groupBox1);
            base.Name = "ElementPosition";
            base.Size = new Size(314, 223);
            base.Load += new EventHandler(this.ElementPosition_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label lblOffsetX;
        private MapCartoTemplateLib.MapTemplateElement mapTemplateElement_0;
        private RadioButton rdoLeftCenter;
        private RadioButton rdoLeftLow;
        private RadioButton rdoLeftUpper;
        private RadioButton rdoLowCenter;
        private RadioButton rdoLowLeft;
        private RadioButton rdoLowRight;
        private RadioButton rdoRightCenter;
        private RadioButton rdoRightLow;
        private RadioButton rdoRightUpper;
        private RadioButton rdoUpperCenter;
        private RadioButton rdoUpperLeft;
        private RadioButton rdoUpperRight;
        private TextBox txtH;
        private TextBox txtOffsetX;
        private TextBox txtOffsetY;
        private TextBox txtW;
    }
}