using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Windows.Forms;

namespace Yutai.ArcGIS.Carto.MapCartoTemplateLib
{
    partial class frmExpressBulider
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.label2 = new Label();
            this.btnMatchString = new Button();
            this.btnAdd = new Button();
            this.btnOr = new Button();
            this.btnBracket = new Button();
            this.btnMatchOneChar = new Button();
            this.btnAnd = new Button();
            this.btnLittleEqual = new Button();
            this.btnLittle = new Button();
            this.btnSelectOne = new Button();
            this.btnIsTrue = new Button();
            this.btnGreat = new Button();
            this.btnNotEqual = new Button();
            this.btnGreatEqual = new Button();
            this.btnEqual = new Button();
            this.memEditWhereCaluse = new TextBox();
            this.Fieldlist = new ListBox();
            this.label4 = new Label();
            this.UniqueValuelist = new ListBox();
            this.btnOK = new Button();
            this.label1 = new Label();
            this.btnCancel = new Button();
            this.btnSubstruct = new Button();
            this.btnDivide = new Button();
            this.btnNum5 = new Button();
            this.btnNum2 = new Button();
            this.btnNum6 = new Button();
            this.btnNum1 = new Button();
            this.btnNum3 = new Button();
            this.btnNum4 = new Button();
            this.btnNum8 = new Button();
            this.btnNum7 = new Button();
            this.btnNum9 = new Button();
            this.btnNumDot = new Button();
            this.btnNum0 = new Button();
            this.label3 = new Label();
            base.SuspendLayout();
            this.label2.Location = new Point(16, 8);
            this.label2.Name = "label2";
            this.label2.Size = new Size(48, 16);
            this.label2.TabIndex = 43;
            this.label2.Text = "参数";
            this.btnMatchString.Location = new Point(330, 54);
            this.btnMatchString.Name = "btnMatchString";
            this.btnMatchString.Size = new Size(32, 24);
            this.btnMatchString.TabIndex = 42;
            this.btnMatchString.Text = "%";
            this.btnMatchString.Click += new EventHandler(this.btnMatchString_Click);
            this.btnAdd.Location = new Point(254, 24);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new Size(32, 24);
            this.btnAdd.TabIndex = 41;
            this.btnAdd.Text = "+";
            this.btnAdd.Click += new EventHandler(this.btnAdd_Click);
            this.btnOr.Location = new Point(254, 144);
            this.btnOr.Name = "btnOr";
            this.btnOr.Size = new Size(32, 24);
            this.btnOr.TabIndex = 40;
            this.btnOr.Text = "||";
            this.btnOr.Click += new EventHandler(this.btnOr_Click);
            this.btnBracket.Location = new Point(330, 24);
            this.btnBracket.Name = "btnBracket";
            this.btnBracket.Size = new Size(32, 24);
            this.btnBracket.TabIndex = 39;
            this.btnBracket.Text = "()";
            this.btnBracket.Click += new EventHandler(this.btnBracket_Click);
            this.btnMatchOneChar.Location = new Point(254, 54);
            this.btnMatchOneChar.Name = "btnMatchOneChar";
            this.btnMatchOneChar.Size = new Size(32, 24);
            this.btnMatchOneChar.TabIndex = 38;
            this.btnMatchOneChar.Text = "*";
            this.btnMatchOneChar.Click += new EventHandler(this.btnMatchOneChar_Click);
            this.btnAnd.Location = new Point(330, 144);
            this.btnAnd.Name = "btnAnd";
            this.btnAnd.Size = new Size(32, 24);
            this.btnAnd.TabIndex = 37;
            this.btnAnd.Tag = "&&";
            this.btnAnd.Text = "&&";
            this.btnAnd.Click += new EventHandler(this.btnAnd_Click);
            this.btnLittleEqual.Location = new Point(292, 114);
            this.btnLittleEqual.Name = "btnLittleEqual";
            this.btnLittleEqual.Size = new Size(32, 24);
            this.btnLittleEqual.TabIndex = 36;
            this.btnLittleEqual.Text = "<=";
            this.btnLittleEqual.Click += new EventHandler(this.btnLittleEqual_Click);
            this.btnLittle.Location = new Point(292, 84);
            this.btnLittle.Name = "btnLittle";
            this.btnLittle.Size = new Size(32, 24);
            this.btnLittle.TabIndex = 35;
            this.btnLittle.Text = "<";
            this.btnLittle.Click += new EventHandler(this.btnLittle_Click);
            this.btnSelectOne.Location = new Point(202, 144);
            this.btnSelectOne.Name = "btnSelectOne";
            this.btnSelectOne.Size = new Size(32, 24);
            this.btnSelectOne.TabIndex = 34;
            this.btnSelectOne.Text = ":";
            this.btnSelectOne.Click += new EventHandler(this.btnDivide_Click);
            this.btnIsTrue.Location = new Point(126, 144);
            this.btnIsTrue.Name = "btnIsTrue";
            this.btnIsTrue.Size = new Size(32, 24);
            this.btnIsTrue.TabIndex = 33;
            this.btnIsTrue.Text = "?";
            this.btnIsTrue.Click += new EventHandler(this.btnDivide_Click);
            this.btnGreat.Location = new Point(254, 84);
            this.btnGreat.Name = "btnGreat";
            this.btnGreat.Size = new Size(32, 24);
            this.btnGreat.TabIndex = 32;
            this.btnGreat.Text = ">";
            this.btnGreat.Click += new EventHandler(this.btnGreat_Click);
            this.btnNotEqual.Location = new Point(330, 114);
            this.btnNotEqual.Name = "btnNotEqual";
            this.btnNotEqual.Size = new Size(32, 24);
            this.btnNotEqual.TabIndex = 31;
            this.btnNotEqual.Text = "!=";
            this.btnNotEqual.Click += new EventHandler(this.btnNotEqual_Click);
            this.btnGreatEqual.Location = new Point(254, 114);
            this.btnGreatEqual.Name = "btnGreatEqual";
            this.btnGreatEqual.Size = new Size(32, 24);
            this.btnGreatEqual.TabIndex = 30;
            this.btnGreatEqual.Text = ">=";
            this.btnGreatEqual.Click += new EventHandler(this.btnGreatEqual_Click);
            this.btnEqual.Location = new Point(330, 84);
            this.btnEqual.Name = "btnEqual";
            this.btnEqual.Size = new Size(32, 24);
            this.btnEqual.TabIndex = 29;
            this.btnEqual.Text = "==";
            this.btnEqual.Click += new EventHandler(this.btnEqual_Click);
            this.memEditWhereCaluse.Location = new Point(45, 230);
            this.memEditWhereCaluse.Name = "memEditWhereCaluse";
            this.memEditWhereCaluse.Size = new Size(452, 21);
            this.memEditWhereCaluse.TabIndex = 26;
            this.Fieldlist.ItemHeight = 12;
            this.Fieldlist.Location = new Point(16, 24);
            this.Fieldlist.Name = "Fieldlist";
            this.Fieldlist.Size = new Size(104, 160);
            this.Fieldlist.TabIndex = 24;
            this.Fieldlist.DoubleClick += new EventHandler(this.Fieldlist_DoubleClick);
            this.label4.Location = new Point(379, 5);
            this.label4.Name = "label4";
            this.label4.Size = new Size(52, 16);
            this.label4.TabIndex = 48;
            this.label4.Text = "函数";
            this.UniqueValuelist.ItemHeight = 12;
            this.UniqueValuelist.Items.AddRange(new object[] { 
                "sin()", "cos()", "log10()", "tan()", "sqrt()", "exp()", "floor()", "pow(,)", "log(,)", "abs()", "acos()", "asin()", "atan()", "atn2(,)", "ceiling()", "cosh()", 
                "ieeeremainder(,)", "max(,)", "min(,)", "sinh()", "truncate()"
             });
            this.UniqueValuelist.Location = new Point(377, 24);
            this.UniqueValuelist.Name = "UniqueValuelist";
            this.UniqueValuelist.Size = new Size(120, 160);
            this.UniqueValuelist.TabIndex = 47;
            this.btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnOK.Location = new Point(345, 272);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(69, 23);
            this.btnOK.TabIndex = 50;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 204);
            this.label1.Name = "label1";
            this.label1.Size = new Size(41, 12);
            this.label1.TabIndex = 51;
            this.label1.Text = "表达式";
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(430, 272);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(69, 23);
            this.btnCancel.TabIndex = 52;
            this.btnCancel.Text = "取消";
            this.btnSubstruct.Location = new Point(292, 24);
            this.btnSubstruct.Name = "btnSubstruct";
            this.btnSubstruct.Size = new Size(32, 24);
            this.btnSubstruct.TabIndex = 53;
            this.btnSubstruct.Text = "-";
            this.btnSubstruct.Click += new EventHandler(this.btnDivide_Click);
            this.btnDivide.Location = new Point(292, 54);
            this.btnDivide.Name = "btnDivide";
            this.btnDivide.Size = new Size(32, 24);
            this.btnDivide.TabIndex = 54;
            this.btnDivide.Text = "/";
            this.btnDivide.Click += new EventHandler(this.btnDivide_Click);
            this.btnNum5.Location = new Point(164, 54);
            this.btnNum5.Name = "btnNum5";
            this.btnNum5.Size = new Size(32, 24);
            this.btnNum5.TabIndex = 63;
            this.btnNum5.Text = "5";
            this.btnNum5.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum2.Location = new Point(164, 24);
            this.btnNum2.Name = "btnNum2";
            this.btnNum2.Size = new Size(32, 24);
            this.btnNum2.TabIndex = 62;
            this.btnNum2.Text = "2";
            this.btnNum2.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum6.Location = new Point(202, 54);
            this.btnNum6.Name = "btnNum6";
            this.btnNum6.Size = new Size(32, 24);
            this.btnNum6.TabIndex = 61;
            this.btnNum6.Text = "6";
            this.btnNum6.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum1.Location = new Point(126, 24);
            this.btnNum1.Name = "btnNum1";
            this.btnNum1.Size = new Size(32, 24);
            this.btnNum1.TabIndex = 60;
            this.btnNum1.Text = "1";
            this.btnNum1.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum3.Location = new Point(202, 24);
            this.btnNum3.Name = "btnNum3";
            this.btnNum3.Size = new Size(32, 24);
            this.btnNum3.TabIndex = 59;
            this.btnNum3.Text = "3";
            this.btnNum3.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum4.Location = new Point(126, 54);
            this.btnNum4.Name = "btnNum4";
            this.btnNum4.Size = new Size(32, 24);
            this.btnNum4.TabIndex = 58;
            this.btnNum4.Text = "4";
            this.btnNum4.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum8.Location = new Point(164, 84);
            this.btnNum8.Name = "btnNum8";
            this.btnNum8.Size = new Size(32, 24);
            this.btnNum8.TabIndex = 57;
            this.btnNum8.Text = "8";
            this.btnNum8.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum7.Location = new Point(126, 84);
            this.btnNum7.Name = "btnNum7";
            this.btnNum7.Size = new Size(32, 24);
            this.btnNum7.TabIndex = 56;
            this.btnNum7.Text = "7";
            this.btnNum7.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum9.Location = new Point(202, 84);
            this.btnNum9.Name = "btnNum9";
            this.btnNum9.Size = new Size(32, 24);
            this.btnNum9.TabIndex = 55;
            this.btnNum9.Text = "9";
            this.btnNum9.Click += new EventHandler(this.btnNum0_Click);
            this.btnNumDot.Location = new Point(202, 114);
            this.btnNumDot.Name = "btnNumDot";
            this.btnNumDot.Size = new Size(32, 24);
            this.btnNumDot.TabIndex = 65;
            this.btnNumDot.Text = ".";
            this.btnNumDot.Click += new EventHandler(this.btnNum0_Click);
            this.btnNum0.Location = new Point(126, 114);
            this.btnNum0.Name = "btnNum0";
            this.btnNum0.Size = new Size(32, 24);
            this.btnNum0.TabIndex = 64;
            this.btnNum0.Text = "0";
            this.btnNum0.Click += new EventHandler(this.btnNum0_Click);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(28, 233);
            this.label3.Name = "label3";
            this.label3.Size = new Size(11, 12);
            this.label3.TabIndex = 66;
            this.label3.Text = "=";
            base.ClientSize = new Size(521, 304);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.btnNumDot);
            base.Controls.Add(this.btnNum0);
            base.Controls.Add(this.btnNum5);
            base.Controls.Add(this.btnNum2);
            base.Controls.Add(this.btnNum6);
            base.Controls.Add(this.btnNum1);
            base.Controls.Add(this.btnNum3);
            base.Controls.Add(this.btnNum4);
            base.Controls.Add(this.btnNum8);
            base.Controls.Add(this.btnNum7);
            base.Controls.Add(this.btnNum9);
            base.Controls.Add(this.btnDivide);
            base.Controls.Add(this.btnSubstruct);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.UniqueValuelist);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.btnMatchString);
            base.Controls.Add(this.btnAdd);
            base.Controls.Add(this.btnOr);
            base.Controls.Add(this.btnBracket);
            base.Controls.Add(this.btnMatchOneChar);
            base.Controls.Add(this.btnAnd);
            base.Controls.Add(this.btnLittleEqual);
            base.Controls.Add(this.btnLittle);
            base.Controls.Add(this.btnSelectOne);
            base.Controls.Add(this.btnIsTrue);
            base.Controls.Add(this.btnGreat);
            base.Controls.Add(this.btnNotEqual);
            base.Controls.Add(this.btnGreatEqual);
            base.Controls.Add(this.btnEqual);
            base.Controls.Add(this.memEditWhereCaluse);
            base.Controls.Add(this.Fieldlist);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmExpressBulider";
            this.Text = "表达式构造器";
            base.Load += new EventHandler(this.frmExpressBulider_Load);
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private Button btnAdd;
        private Button btnAnd;
        private Button btnBracket;
        private Button btnCancel;
        private Button btnDivide;
        private Button btnEqual;
        private Button btnGreat;
        private Button btnGreatEqual;
        private Button btnIsTrue;
        private Button btnLittle;
        private Button btnLittleEqual;
        private Button btnMatchOneChar;
        private Button btnMatchString;
        private Button btnNotEqual;
        private Button btnNum0;
        private Button btnNum1;
        private Button btnNum2;
        private Button btnNum3;
        private Button btnNum4;
        private Button btnNum5;
        private Button btnNum6;
        private Button btnNum7;
        private Button btnNum8;
        private Button btnNum9;
        private Button btnNumDot;
        private Button btnOK;
        private Button btnOr;
        private Button btnSelectOne;
        private Button btnSubstruct;
        private ListBox Fieldlist;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private MapCartoTemplateLib.MapTemplate mapTemplate_0;
        private TextBox memEditWhereCaluse;
        private ListBox UniqueValuelist;
    }
}