using System;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Windows.Forms;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.MapCartoTemplateLib
{
    partial class GridAxisPropertyPage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_2);
        }

        ~GridAxisPropertyPage()
        {
            this.imapGrid_0 = null;
            m_pOldMapGrid = null;
        }

       
        private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.label4 = new Label();
            this.label3 = new Label();
            this.btnStyle = new StyleButton();
            this.label2 = new Label();
            this.label1 = new Label();
            this.chkMainRight = new CheckBox();
            this.chkMainBottom = new CheckBox();
            this.chkMainLeft = new CheckBox();
            this.chkMainTop = new CheckBox();
            this.groupBox2 = new GroupBox();
            this.label9 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.btnSubStyle = new StyleButton();
            this.label7 = new Label();
            this.label8 = new Label();
            this.chkSubRight = new CheckBox();
            this.chkSubBottom = new CheckBox();
            this.chkSubLeft = new CheckBox();
            this.chkSubTop = new CheckBox();
            this.groupBox3 = new GroupBox();
            this.label10 = new Label();
            this.cboBorderType = new ComboBox();
            this.rdoInOutside = new RadioButton();
            this.rdoInInner = new RadioButton();
            this.txtTikLength = new DomainUpDown();
            this.txtSubCount = new DomainUpDown();
            this.rdoSubTickInner = new RadioButton();
            this.rdoSubTickOutside = new RadioButton();
            this.txtSubTickLength = new DomainUpDown();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.txtTikLength);
            this.groupBox1.Controls.Add(this.rdoInInner);
            this.groupBox1.Controls.Add(this.rdoInOutside);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.btnStyle);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.chkMainRight);
            this.groupBox1.Controls.Add(this.chkMainBottom);
            this.groupBox1.Controls.Add(this.chkMainLeft);
            this.groupBox1.Controls.Add(this.chkMainTop);
            this.groupBox1.Location = new Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(264, 130);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "主分划刻度";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(240, 88);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 12);
            this.label4.TabIndex = 10;
            this.label4.Text = "点";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(128, 88);
            this.label3.Name = "label3";
            this.label3.Size = new Size(53, 12);
            this.label3.TabIndex = 8;
            this.label3.Text = "刻度大于";
            this.btnStyle.Location = new Point(56, 48);
            this.btnStyle.Name = "btnStyle";
            this.btnStyle.Size = new Size(64, 24);
            this.btnStyle.Style = null;
            this.btnStyle.TabIndex = 6;
            this.btnStyle.Click += new EventHandler(this.btnStyle_Click);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 88);
            this.label2.Name = "label2";
            this.label2.Size = new Size(53, 12);
            this.label2.TabIndex = 5;
            this.label2.Text = "显示刻度";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 56);
            this.label1.Name = "label1";
            this.label1.Size = new Size(35, 12);
            this.label1.TabIndex = 4;
            this.label1.Text = "符号:";
            this.chkMainRight.Location = new Point(176, 24);
            this.chkMainRight.Name = "chkMainRight";
            this.chkMainRight.Size = new Size(48, 19);
            this.chkMainRight.TabIndex = 3;
            this.chkMainRight.Text = "右";
            this.chkMainRight.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.chkMainBottom.Location = new Point(120, 24);
            this.chkMainBottom.Name = "chkMainBottom";
            this.chkMainBottom.Size = new Size(48, 19);
            this.chkMainBottom.TabIndex = 2;
            this.chkMainBottom.Text = "下";
            this.chkMainBottom.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.chkMainLeft.Location = new Point(64, 24);
            this.chkMainLeft.Name = "chkMainLeft";
            this.chkMainLeft.Size = new Size(48, 19);
            this.chkMainLeft.TabIndex = 1;
            this.chkMainLeft.Text = "左";
            this.chkMainLeft.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.chkMainTop.Location = new Point(8, 24);
            this.chkMainTop.Name = "chkMainTop";
            this.chkMainTop.Size = new Size(48, 19);
            this.chkMainTop.TabIndex = 0;
            this.chkMainTop.Text = "上";
            this.chkMainTop.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.groupBox2.Controls.Add(this.txtSubTickLength);
            this.groupBox2.Controls.Add(this.rdoSubTickInner);
            this.groupBox2.Controls.Add(this.rdoSubTickOutside);
            this.groupBox2.Controls.Add(this.txtSubCount);
            this.groupBox2.Controls.Add(this.label9);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.btnSubStyle);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.label8);
            this.groupBox2.Controls.Add(this.chkSubRight);
            this.groupBox2.Controls.Add(this.chkSubBottom);
            this.groupBox2.Controls.Add(this.chkSubLeft);
            this.groupBox2.Controls.Add(this.chkSubTop);
            this.groupBox2.Location = new Point(8, 144);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(264, 160);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "子分划刻度";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(8, 56);
            this.label9.Name = "label9";
            this.label9.Size = new Size(59, 12);
            this.label9.TabIndex = 18;
            this.label9.Text = "子刻度数:";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(240, 120);
            this.label5.Name = "label5";
            this.label5.Size = new Size(17, 12);
            this.label5.TabIndex = 17;
            this.label5.Text = "点";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(128, 120);
            this.label6.Name = "label6";
            this.label6.Size = new Size(53, 12);
            this.label6.TabIndex = 15;
            this.label6.Text = "刻度大于";
            this.btnSubStyle.Location = new Point(56, 80);
            this.btnSubStyle.Name = "btnSubStyle";
            this.btnSubStyle.Size = new Size(64, 24);
            this.btnSubStyle.Style = null;
            this.btnSubStyle.TabIndex = 13;
            this.btnSubStyle.Click += new EventHandler(this.btnSubStyle_Click);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(8, 120);
            this.label7.Name = "label7";
            this.label7.Size = new Size(53, 12);
            this.label7.TabIndex = 12;
            this.label7.Text = "显示刻度";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(8, 88);
            this.label8.Name = "label8";
            this.label8.Size = new Size(35, 12);
            this.label8.TabIndex = 11;
            this.label8.Text = "符号:";
            this.chkSubRight.Location = new Point(176, 24);
            this.chkSubRight.Name = "chkSubRight";
            this.chkSubRight.Size = new Size(48, 19);
            this.chkSubRight.TabIndex = 7;
            this.chkSubRight.Text = "右";
            this.chkSubRight.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.chkSubBottom.Location = new Point(120, 24);
            this.chkSubBottom.Name = "chkSubBottom";
            this.chkSubBottom.Size = new Size(48, 19);
            this.chkSubBottom.TabIndex = 6;
            this.chkSubBottom.Text = "下";
            this.chkSubBottom.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.chkSubLeft.Location = new Point(64, 24);
            this.chkSubLeft.Name = "chkSubLeft";
            this.chkSubLeft.Size = new Size(48, 19);
            this.chkSubLeft.TabIndex = 5;
            this.chkSubLeft.Text = "左";
            this.chkSubLeft.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.chkSubTop.Location = new Point(8, 24);
            this.chkSubTop.Name = "chkSubTop";
            this.chkSubTop.Size = new Size(48, 19);
            this.chkSubTop.TabIndex = 4;
            this.chkSubTop.Text = "上";
            this.chkSubTop.CheckedChanged += new EventHandler(this.chkSubTop_CheckedChanged);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.cboBorderType);
            this.groupBox3.Location = new Point(8, 312);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(264, 80);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "边框属性";
            this.groupBox3.Visible = false;
            this.label10.AutoSize = true;
            this.label10.Location = new Point(8, 32);
            this.label10.Name = "label10";
            this.label10.Size = new Size(35, 12);
            this.label10.TabIndex = 12;
            this.label10.Text = "边框:";
            this.cboBorderType.Text = "";
            this.cboBorderType.Location = new Point(49, 28);
            this.cboBorderType.Name = "cboBorderType";
            this.cboBorderType.Items.AddRange(new object[] { "简单的边框", "校准的边框" });
            this.cboBorderType.Size = new Size(112, 21);
            this.cboBorderType.TabIndex = 0;
            this.cboBorderType.SelectedIndexChanged += new EventHandler(this.cboBorderType_SelectedIndexChanged);
            this.rdoInOutside.AutoSize = true;
            this.rdoInOutside.Location = new Point(67, 108);
            this.rdoInOutside.Name = "rdoInOutside";
            this.rdoInOutside.Size = new Size(59, 16);
            this.rdoInOutside.TabIndex = 11;
            this.rdoInOutside.Text = "在外部";
            this.rdoInOutside.UseVisualStyleBackColor = true;
            this.rdoInInner.AutoSize = true;
            this.rdoInInner.Checked = true;
            this.rdoInInner.Location = new Point(67, 86);
            this.rdoInInner.Name = "rdoInInner";
            this.rdoInInner.Size = new Size(59, 16);
            this.rdoInInner.TabIndex = 12;
            this.rdoInInner.TabStop = true;
            this.rdoInInner.Text = "在内部";
            this.rdoInInner.UseVisualStyleBackColor = true;
            this.txtTikLength.Location = new Point(187, 86);
            this.txtTikLength.Name = "txtTikLength";
            this.txtTikLength.Size = new Size(47, 21);
            this.txtTikLength.TabIndex = 13;
            this.txtTikLength.Text = "0";
            this.txtSubCount.Location = new Point(67, 54);
            this.txtSubCount.Name = "txtSubCount";
            this.txtSubCount.Size = new Size(75, 21);
            this.txtSubCount.TabIndex = 20;
            this.txtSubCount.Text = "0";
            this.rdoSubTickInner.AutoSize = true;
            this.rdoSubTickInner.Checked = true;
            this.rdoSubTickInner.Location = new Point(67, 118);
            this.rdoSubTickInner.Name = "rdoSubTickInner";
            this.rdoSubTickInner.Size = new Size(59, 16);
            this.rdoSubTickInner.TabIndex = 22;
            this.rdoSubTickInner.TabStop = true;
            this.rdoSubTickInner.Text = "在内部";
            this.rdoSubTickInner.UseVisualStyleBackColor = true;
            this.rdoSubTickOutside.AutoSize = true;
            this.rdoSubTickOutside.Location = new Point(67, 140);
            this.rdoSubTickOutside.Name = "rdoSubTickOutside";
            this.rdoSubTickOutside.Size = new Size(59, 16);
            this.rdoSubTickOutside.TabIndex = 21;
            this.rdoSubTickOutside.Text = "在外部";
            this.rdoSubTickOutside.UseVisualStyleBackColor = true;
            this.txtSubTickLength.Location = new Point(186, 117);
            this.txtSubTickLength.Name = "txtSubTickLength";
            this.txtSubTickLength.Size = new Size(47, 21);
            this.txtSubTickLength.TabIndex = 23;
            this.txtSubTickLength.Text = "0";
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "GridAxisPropertyPage";
            base.Size = new Size(288, 311);
            base.Load += new EventHandler(this.GridAxisPropertyPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            base.ResumeLayout(false);
        }

       
        private StyleButton btnStyle;
        private StyleButton btnSubStyle;
        private ComboBox cboBorderType;
        private CheckBox chkMainBottom;
        private CheckBox chkMainLeft;
        private CheckBox chkMainRight;
        private CheckBox chkMainTop;
        private CheckBox chkSubBottom;
        private CheckBox chkSubLeft;
        private CheckBox chkSubRight;
        private CheckBox chkSubTop;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private Label label1;
        private Label label10;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private MapCartoTemplateLib.MapTemplate mapTemplate_0;
        private RadioButton rdoInInner;
        private RadioButton rdoInOutside;
        private RadioButton rdoSubTickInner;
        private RadioButton rdoSubTickOutside;
        private DomainUpDown txtSubCount;
        private DomainUpDown txtSubTickLength;
        private DomainUpDown txtTikLength;
    }
}