using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.ControlExtend;
using Yutai.ArcGIS.Common.Symbol;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.MapCartoTemplateLib
{
    partial class LegendPropertyPage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
 private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            ListViewItem item = new ListViewItem(new string[] { "标题和项", "8" }, -1);
            ListViewItem item2 = new ListViewItem(new string[] { "项", "5" }, -1);
            ListViewItem item3 = new ListViewItem(new string[] { "列", "5" }, -1);
            ListViewItem item4 = new ListViewItem(new string[] { "图层名称和组", "5" }, -1);
            ListViewItem item5 = new ListViewItem(new string[] { "组", "5" }, -1);
            ListViewItem item6 = new ListViewItem(new string[] { "标题和类", "5" }, -1);
            ListViewItem item7 = new ListViewItem(new string[] { "标注和描述", "5" }, -1);
            ListViewItem item8 = new ListViewItem(new string[] { "区块(垂直)", "5" }, -1);
            ListViewItem item9 = new ListViewItem(new string[] { "区块和标注", "5" }, -1);
            this.groupBox1 = new GroupBox();
            this.cboTitlePosition = new ComboBoxEdit();
            this.btnTitleSymbol = new SimpleButton();
            this.label1 = new Label();
            this.chkShow = new CheckEdit();
            this.txtTitle = new MemoEdit();
            this.groupBox2 = new GroupBox();
            this.cboAreaPatches = new StyleComboBox(this.icontainer_0);
            this.cboLinePatches = new StyleComboBox(this.icontainer_0);
            this.label6 = new Label();
            this.label7 = new Label();
            this.label5 = new Label();
            this.label4 = new Label();
            this.txtHeight = new TextEdit();
            this.txtWidth = new TextEdit();
            this.label3 = new Label();
            this.label2 = new Label();
            this.groupBox3 = new GroupBox();
            this.listView1 = new EditListView();
            this.lvcolumnHeader_0 = new LVColumnHeader();
            this.lvcolumnHeader_1 = new LVColumnHeader();
            this.chkRightToLeft = new CheckEdit();
            this.groupBox1.SuspendLayout();
            this.cboTitlePosition.Properties.BeginInit();
            this.chkShow.Properties.BeginInit();
            this.txtTitle.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.txtHeight.Properties.BeginInit();
            this.txtWidth.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.chkRightToLeft.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox1.Controls.Add(this.cboTitlePosition);
            this.groupBox1.Controls.Add(this.btnTitleSymbol);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.chkShow);
            this.groupBox1.Controls.Add(this.txtTitle);
            this.groupBox1.Location = new Point(8, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(368, 136);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "标题";
            this.cboTitlePosition.EditValue = "上";
            this.cboTitlePosition.Location = new Point(161, 103);
            this.cboTitlePosition.Name = "cboTitlePosition";
            this.cboTitlePosition.Properties.Items.AddRange(new object[] { "上", "下", "左", "右" });
            this.cboTitlePosition.Size = new Size(64, 23);
            this.cboTitlePosition.TabIndex = 5;
            this.cboTitlePosition.SelectedIndexChanged += new EventHandler(this.cboTitlePosition_SelectedIndexChanged);
            this.btnTitleSymbol.Location = new Point(304, 104);
            this.btnTitleSymbol.Name = "btnTitleSymbol";
            this.btnTitleSymbol.Size = new Size(48, 24);
            this.btnTitleSymbol.TabIndex = 4;
            this.btnTitleSymbol.Text = "符号";
            this.btnTitleSymbol.Click += new EventHandler(this.btnTitleSymbol_Click);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(128, 108);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 2;
            this.label1.Text = "位置";
            this.chkShow.Location = new Point(8, 104);
            this.chkShow.Name = "chkShow";
            this.chkShow.Properties.Caption = "显示";
            this.chkShow.Size = new Size(48, 19);
            this.chkShow.TabIndex = 1;
            this.chkShow.Click += new EventHandler(this.chkShow_Click);
            this.chkShow.CheckedChanged += new EventHandler(this.chkShow_CheckedChanged);
            this.txtTitle.EditValue = "memoEdit1";
            this.txtTitle.Location = new Point(8, 16);
            this.txtTitle.Name = "txtTitle";
            this.txtTitle.Size = new Size(344, 80);
            this.txtTitle.TabIndex = 0;
            this.txtTitle.EditValueChanged += new EventHandler(this.txtTitle_EditValueChanged);
            this.groupBox2.Controls.Add(this.cboAreaPatches);
            this.groupBox2.Controls.Add(this.cboLinePatches);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.txtHeight);
            this.groupBox2.Controls.Add(this.txtWidth);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Location = new Point(8, 152);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(120, 144);
            this.groupBox2.TabIndex = 10;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "区块";
            this.cboAreaPatches.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboAreaPatches.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboAreaPatches.DropDownWidth = 64;
            this.cboAreaPatches.Font = new Font("宋体", 15f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboAreaPatches.ItemHeight = 20;
            this.cboAreaPatches.Location = new Point(40, 104);
            this.cboAreaPatches.Name = "cboAreaPatches";
            this.cboAreaPatches.Size = new Size(64, 26);
            this.cboAreaPatches.TabIndex = 9;
            this.cboAreaPatches.SelectedIndexChanged += new EventHandler(this.cboAreaPatches_SelectedIndexChanged);
            this.cboLinePatches.DrawMode = DrawMode.OwnerDrawVariable;
            this.cboLinePatches.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboLinePatches.DropDownWidth = 64;
            this.cboLinePatches.Font = new Font("宋体", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.cboLinePatches.ItemHeight = 20;
            this.cboLinePatches.Location = new Point(40, 72);
            this.cboLinePatches.Name = "cboLinePatches";
            this.cboLinePatches.Size = new Size(64, 26);
            this.cboLinePatches.TabIndex = 8;
            this.cboLinePatches.SelectedIndexChanged += new EventHandler(this.cboLinePatches_SelectedIndexChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(8, 112);
            this.label6.Name = "label6";
            this.label6.Size = new Size(23, 17);
            this.label6.TabIndex = 7;
            this.label6.Text = "面:";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(8, 80);
            this.label7.Name = "label7";
            this.label7.Size = new Size(23, 17);
            this.label7.TabIndex = 6;
            this.label7.Text = "线:";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(91, 45);
            this.label5.Name = "label5";
            this.label5.Size = new Size(17, 17);
            this.label5.TabIndex = 5;
            this.label5.Text = "点";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(91, 19);
            this.label4.Name = "label4";
            this.label4.Size = new Size(17, 17);
            this.label4.TabIndex = 4;
            this.label4.Text = "点";
            this.txtHeight.EditValue = "";
            this.txtHeight.Location = new Point(40, 42);
            this.txtHeight.Name = "txtHeight";
            this.txtHeight.Size = new Size(48, 23);
            this.txtHeight.TabIndex = 3;
            this.txtHeight.EditValueChanged += new EventHandler(this.txtHeight_EditValueChanged);
            this.txtWidth.EditValue = "";
            this.txtWidth.Location = new Point(40, 16);
            this.txtWidth.Name = "txtWidth";
            this.txtWidth.Size = new Size(48, 23);
            this.txtWidth.TabIndex = 2;
            this.txtWidth.EditValueChanged += new EventHandler(this.txtWidth_EditValueChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 47);
            this.label3.Name = "label3";
            this.label3.Size = new Size(35, 17);
            this.label3.TabIndex = 1;
            this.label3.Text = "高度:";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 20);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 17);
            this.label2.TabIndex = 0;
            this.label2.Text = "宽度:";
            this.groupBox3.Controls.Add(this.listView1);
            this.groupBox3.Location = new Point(136, 152);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(240, 144);
            this.groupBox3.TabIndex = 11;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "间隔";
            this.listView1.Columns.AddRange(new ColumnHeader[] { this.lvcolumnHeader_0, this.lvcolumnHeader_1 });
            this.listView1.ComboBoxBgColor = Color.LightBlue;
            this.listView1.ComboBoxFont = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.listView1.EditBgColor = Color.LightBlue;
            this.listView1.EditFont = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.listView1.FullRowSelect = true;
            this.listView1.GridLines = true;
            this.listView1.HeaderStyle = ColumnHeaderStyle.None;
            this.listView1.Items.AddRange(new ListViewItem[] { item, item2, item3, item4, item5, item6, item7, item8, item9 });
            this.listView1.Location = new Point(16, 24);
            this.listView1.LockRowCount = 0;
            this.listView1.Name = "listView1";
            this.listView1.Size = new Size(208, 104);
            this.listView1.TabIndex = 0;
            this.listView1.View = View.Details;
            this.listView1.ValueChanged += new ValueChangedHandler(this.method_2);
            this.lvcolumnHeader_0.ColumnStyle = ListViewColumnStyle.ReadOnly;
            this.lvcolumnHeader_0.Width = 88;
            this.lvcolumnHeader_1.ColumnStyle = ListViewColumnStyle.ReadOnly;
            this.lvcolumnHeader_1.Width = 93;
            this.chkRightToLeft.Location = new Point(16, 304);
            this.chkRightToLeft.Name = "chkRightToLeft";
            this.chkRightToLeft.Properties.Caption = "从右到左读取";
            this.chkRightToLeft.Size = new Size(112, 19);
            this.chkRightToLeft.TabIndex = 12;
            this.chkRightToLeft.Click += new EventHandler(this.chkRightToLeft_Click);
            this.chkRightToLeft.CheckedChanged += new EventHandler(this.chkRightToLeft_CheckedChanged);
            base.Controls.Add(this.chkRightToLeft);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.groupBox1);
            base.Name = "LegendPropertyPage";
            base.Size = new Size(392, 344);
            base.Load += new EventHandler(this.LegendPropertyPage_Load);
            this.groupBox1.ResumeLayout(false);
            this.cboTitlePosition.Properties.EndInit();
            this.chkShow.Properties.EndInit();
            this.txtTitle.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.txtHeight.Properties.EndInit();
            this.txtWidth.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.chkRightToLeft.Properties.EndInit();
            base.ResumeLayout(false);
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private SimpleButton btnTitleSymbol;
        private StyleComboBox cboAreaPatches;
        private StyleComboBox cboLinePatches;
        private ComboBoxEdit cboTitlePosition;
        private CheckEdit chkRightToLeft;
        private CheckEdit chkShow;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private IContainer icontainer_0;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private EditListView listView1;
        private LVColumnHeader lvcolumnHeader_0;
        private LVColumnHeader lvcolumnHeader_1;
        private TextEdit txtHeight;
        private MemoEdit txtTitle;
        private TextEdit txtWidth;
    }
}