using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using System.Xml;
using ESRI.ArcGIS.Display;
using Yutai.ArcGIS.Common;
using Yutai.ArcGIS.Common.SymbolLib;
using Yutai.ArcGIS.Controls.SymbolUI;
using IPropertyPage = Yutai.ArcGIS.Common.BaseClasses.IPropertyPage;
using IPropertyPageEvents = Yutai.ArcGIS.Common.BaseClasses.IPropertyPageEvents;
using OnValueChangeEventHandler = Yutai.ArcGIS.Common.BaseClasses.OnValueChangeEventHandler;

namespace Yutai.ArcGIS.Carto.MapCartoTemplateLib
{
    partial class StarndFenFuMapTemplatePage
    {
        protected override void Dispose(bool bool_2)
        {
            if (bool_2 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_2);
        }

       
 private void InitializeComponent()
        {
            this.groupBox4 = new GroupBox();
            this.groupBox5 = new GroupBox();
            this.txtRightSpace = new TextBox();
            this.label25 = new Label();
            this.txtLeftSpace = new TextBox();
            this.label26 = new Label();
            this.txtBottomSpace = new TextBox();
            this.label23 = new Label();
            this.txtTopSpace = new TextBox();
            this.label24 = new Label();
            this.rdoFill = new RadioButton();
            this.rdoLine = new RadioButton();
            this.label18 = new Label();
            this.txtOutBorderWidth = new TextBox();
            this.label20 = new Label();
            this.label16 = new Label();
            this.styleButton1 = new StyleButton();
            this.groupBox3 = new GroupBox();
            this.label11 = new Label();
            this.label10 = new Label();
            this.txtXInterval = new TextBox();
            this.txtYInterval = new TextBox();
            this.label1 = new Label();
            this.label2 = new Label();
            this.btnClear = new Button();
            this.button1 = new Button();
            this.txtLegendInfo = new TextBox();
            this.label15 = new Label();
            this.txtName = new TextBox();
            this.label14 = new Label();
            this.groupBox2 = new GroupBox();
            this.label13 = new Label();
            this.label5 = new Label();
            this.txtStartY = new TextBox();
            this.txtStartX = new TextBox();
            this.label6 = new Label();
            this.label7 = new Label();
            this.groupBox4.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            base.SuspendLayout();
            this.groupBox4.Controls.Add(this.rdoFill);
            this.groupBox4.Controls.Add(this.rdoLine);
            this.groupBox4.Controls.Add(this.label18);
            this.groupBox4.Controls.Add(this.txtOutBorderWidth);
            this.groupBox4.Controls.Add(this.label20);
            this.groupBox4.Controls.Add(this.label16);
            this.groupBox4.Controls.Add(this.styleButton1);
            this.groupBox4.Location = new Point(10, 138);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(466, 96);
            this.groupBox4.TabIndex = 89;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "边框设置";
            this.groupBox5.Controls.Add(this.txtRightSpace);
            this.groupBox5.Controls.Add(this.label25);
            this.groupBox5.Controls.Add(this.txtLeftSpace);
            this.groupBox5.Controls.Add(this.label26);
            this.groupBox5.Controls.Add(this.txtBottomSpace);
            this.groupBox5.Controls.Add(this.label23);
            this.groupBox5.Controls.Add(this.txtTopSpace);
            this.groupBox5.Controls.Add(this.label24);
            this.groupBox5.Location = new Point(190, 40);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(286, 92);
            this.groupBox5.TabIndex = 100;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "内外框间距(厘米)";
            this.txtRightSpace.Location = new Point(173, 50);
            this.txtRightSpace.Name = "txtRightSpace";
            this.txtRightSpace.Size = new Size(43, 21);
            this.txtRightSpace.TabIndex = 16;
            this.txtRightSpace.Text = "1";
            this.label25.AutoSize = true;
            this.label25.Location = new Point(114, 53);
            this.label25.Name = "label25";
            this.label25.Size = new Size(53, 12);
            this.label25.TabIndex = 15;
            this.label25.Text = "右部间距";
            this.txtLeftSpace.Location = new Point(65, 50);
            this.txtLeftSpace.Name = "txtLeftSpace";
            this.txtLeftSpace.Size = new Size(43, 21);
            this.txtLeftSpace.TabIndex = 14;
            this.txtLeftSpace.Text = "1";
            this.label26.AutoSize = true;
            this.label26.Location = new Point(6, 53);
            this.label26.Name = "label26";
            this.label26.Size = new Size(53, 12);
            this.label26.TabIndex = 13;
            this.label26.Text = "左部间距";
            this.txtBottomSpace.Location = new Point(173, 24);
            this.txtBottomSpace.Name = "txtBottomSpace";
            this.txtBottomSpace.Size = new Size(43, 21);
            this.txtBottomSpace.TabIndex = 12;
            this.txtBottomSpace.Text = "1";
            this.label23.AutoSize = true;
            this.label23.Location = new Point(114, 27);
            this.label23.Name = "label23";
            this.label23.Size = new Size(53, 12);
            this.label23.TabIndex = 11;
            this.label23.Text = "底部间距";
            this.txtTopSpace.Location = new Point(65, 24);
            this.txtTopSpace.Name = "txtTopSpace";
            this.txtTopSpace.Size = new Size(43, 21);
            this.txtTopSpace.TabIndex = 10;
            this.txtTopSpace.Text = "1";
            this.label24.AutoSize = true;
            this.label24.Location = new Point(6, 27);
            this.label24.Name = "label24";
            this.label24.Size = new Size(53, 12);
            this.label24.TabIndex = 9;
            this.label24.Text = "顶部间距";
            this.rdoFill.AutoSize = true;
            this.rdoFill.Location = new Point(284, 17);
            this.rdoFill.Name = "rdoFill";
            this.rdoFill.Size = new Size(35, 16);
            this.rdoFill.TabIndex = 22;
            this.rdoFill.Text = "面";
            this.rdoFill.UseVisualStyleBackColor = true;
            this.rdoFill.CheckedChanged += new EventHandler(this.rdoFill_CheckedChanged);
            this.rdoLine.AutoSize = true;
            this.rdoLine.Checked = true;
            this.rdoLine.Location = new Point(226, 17);
            this.rdoLine.Name = "rdoLine";
            this.rdoLine.Size = new Size(35, 16);
            this.rdoLine.TabIndex = 21;
            this.rdoLine.TabStop = true;
            this.rdoLine.Text = "线";
            this.rdoLine.UseVisualStyleBackColor = true;
            this.rdoLine.CheckedChanged += new EventHandler(this.rdoLine_CheckedChanged);
            this.label18.AutoSize = true;
            this.label18.Location = new Point(133, 17);
            this.label18.Name = "label18";
            this.label18.Size = new Size(29, 12);
            this.label18.TabIndex = 20;
            this.label18.Text = "厘米";
            this.txtOutBorderWidth.Location = new Point(87, 14);
            this.txtOutBorderWidth.Name = "txtOutBorderWidth";
            this.txtOutBorderWidth.Size = new Size(43, 21);
            this.txtOutBorderWidth.TabIndex = 19;
            this.txtOutBorderWidth.Text = "1";
            this.txtOutBorderWidth.TextChanged += new EventHandler(this.txtOutBorderWidth_TextChanged);
            this.label20.AutoSize = true;
            this.label20.Location = new Point(16, 17);
            this.label20.Name = "label20";
            this.label20.Size = new Size(41, 12);
            this.label20.TabIndex = 18;
            this.label20.Text = "外框宽";
            this.label16.AutoSize = true;
            this.label16.Location = new Point(224, 52);
            this.label16.Name = "label16";
            this.label16.Size = new Size(29, 12);
            this.label16.TabIndex = 10;
            this.label16.Text = "符号";
            this.styleButton1.Location = new Point(271, 42);
            this.styleButton1.Name = "styleButton1";
            this.styleButton1.Size = new Size(96, 31);
            this.styleButton1.Style = null;
            this.styleButton1.TabIndex = 9;
            this.styleButton1.Click += new EventHandler(this.styleButton1_Click);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.txtXInterval);
            this.groupBox3.Controls.Add(this.txtYInterval);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Controls.Add(this.label2);
            this.groupBox3.Location = new Point(9, 40);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(175, 92);
            this.groupBox3.TabIndex = 90;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "坐标轴间隔";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(120, 55);
            this.label11.Name = "label11";
            this.label11.Size = new Size(29, 12);
            this.label11.TabIndex = 6;
            this.label11.Text = "厘米";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(120, 27);
            this.label10.Name = "label10";
            this.label10.Size = new Size(29, 12);
            this.label10.TabIndex = 5;
            this.label10.Text = "厘米";
            this.txtXInterval.Location = new Point(62, 52);
            this.txtXInterval.Name = "txtXInterval";
            this.txtXInterval.Size = new Size(52, 21);
            this.txtXInterval.TabIndex = 3;
            this.txtXInterval.Text = "10";
            this.txtXInterval.TextChanged += new EventHandler(this.txtXInterval_TextChanged);
            this.txtYInterval.Location = new Point(62, 24);
            this.txtYInterval.Name = "txtYInterval";
            this.txtYInterval.Size = new Size(52, 21);
            this.txtYInterval.TabIndex = 2;
            this.txtYInterval.Text = "10";
            this.txtYInterval.TextChanged += new EventHandler(this.txtYInterval_TextChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new Point(15, 55);
            this.label1.Name = "label1";
            this.label1.Size = new Size(41, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "横坐标";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(15, 27);
            this.label2.Name = "label2";
            this.label2.Size = new Size(41, 12);
            this.label2.TabIndex = 0;
            this.label2.Text = "纵坐标";
            this.btnClear.Location = new Point(437, 256);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new Size(45, 19);
            this.btnClear.TabIndex = 96;
            this.btnClear.Text = "清除";
            this.btnClear.UseVisualStyleBackColor = true;
            this.btnClear.Visible = false;
            this.button1.Location = new Point(397, 256);
            this.button1.Name = "button1";
            this.button1.Size = new Size(34, 19);
            this.button1.TabIndex = 95;
            this.button1.Text = "...";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Visible = false;
            this.txtLegendInfo.Location = new Point(107, 256);
            this.txtLegendInfo.Name = "txtLegendInfo";
            this.txtLegendInfo.ReadOnly = true;
            this.txtLegendInfo.Size = new Size(270, 21);
            this.txtLegendInfo.TabIndex = 94;
            this.txtLegendInfo.Visible = false;
            this.label15.AutoSize = true;
            this.label15.Location = new Point(24, 259);
            this.label15.Name = "label15";
            this.label15.Size = new Size(77, 12);
            this.label15.TabIndex = 93;
            this.label15.Text = "图例配置文件";
            this.label15.Visible = false;
            this.txtName.Location = new Point(49, 9);
            this.txtName.Name = "txtName";
            this.txtName.Size = new Size(427, 21);
            this.txtName.TabIndex = 98;
            this.txtName.Text = "模板";
            this.txtName.TextChanged += new EventHandler(this.txtName_TextChanged);
            this.label14.AutoSize = true;
            this.label14.Location = new Point(8, 12);
            this.label14.Name = "label14";
            this.label14.Size = new Size(29, 12);
            this.label14.TabIndex = 97;
            this.label14.Text = "名称";
            this.groupBox2.Controls.Add(this.label13);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.txtStartY);
            this.groupBox2.Controls.Add(this.txtStartX);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Location = new Point(380, 302);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(173, 92);
            this.groupBox2.TabIndex = 99;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "左下角坐标基数";
            this.groupBox2.Visible = false;
            this.label13.AutoSize = true;
            this.label13.Location = new Point(132, 55);
            this.label13.Name = "label13";
            this.label13.Size = new Size(17, 12);
            this.label13.TabIndex = 7;
            this.label13.Text = "米";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(131, 27);
            this.label5.Name = "label5";
            this.label5.Size = new Size(17, 12);
            this.label5.TabIndex = 6;
            this.label5.Text = "米";
            this.txtStartY.Location = new Point(62, 52);
            this.txtStartY.Name = "txtStartY";
            this.txtStartY.Size = new Size(64, 21);
            this.txtStartY.TabIndex = 3;
            this.txtStartY.Text = "0";
            this.txtStartY.TextChanged += new EventHandler(this.txtStartY_TextChanged);
            this.txtStartX.Location = new Point(62, 24);
            this.txtStartX.Name = "txtStartX";
            this.txtStartX.Size = new Size(64, 21);
            this.txtStartX.TabIndex = 2;
            this.txtStartX.Text = "0";
            this.txtStartX.TextChanged += new EventHandler(this.txtStartX_TextChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(15, 55);
            this.label6.Name = "label6";
            this.label6.Size = new Size(41, 12);
            this.label6.TabIndex = 1;
            this.label6.Text = "横坐标";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(15, 27);
            this.label7.Name = "label7";
            this.label7.Size = new Size(41, 12);
            this.label7.TabIndex = 0;
            this.label7.Text = "纵坐标";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.groupBox5);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.txtName);
            base.Controls.Add(this.label14);
            base.Controls.Add(this.btnClear);
            base.Controls.Add(this.button1);
            base.Controls.Add(this.txtLegendInfo);
            base.Controls.Add(this.label15);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox4);
            base.Name = "StarndFenFuMapTemplatePage";
            base.Size = new Size(490, 296);
            base.Load += new EventHandler(this.StarndFenFuMapTemplatePage_Load);
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        void IPropertyPage.Hide()
        {
            base.Hide();
        }

       
        private Button btnClear;
        private Button button1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private GroupBox groupBox5;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label18;
        private Label label2;
        private Label label20;
        private Label label23;
        private Label label24;
        private Label label25;
        private Label label26;
        private Label label5;
        private Label label6;
        private Label label7;
        private RadioButton rdoFill;
        private RadioButton rdoLine;
        private StyleButton styleButton1;
        private TextBox txtBottomSpace;
        private TextBox txtLeftSpace;
        private TextBox txtLegendInfo;
        private TextBox txtName;
        private TextBox txtOutBorderWidth;
        private TextBox txtRightSpace;
        private TextBox txtStartX;
        private TextBox txtStartY;
        private TextBox txtTopSpace;
        private TextBox txtXInterval;
        private TextBox txtYInterval;
    }
}