using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common.Helpers;

namespace Yutai.ArcGIS.Controls.Controls
{
    partial class GeoCoordSys
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.textEditName = new TextEdit();
            this.label1 = new Label();
            this.groupBox1 = new GroupBox();
            this.cboDatumName = new ComboBoxEdit();
            this.groupBox2 = new GroupBox();
            this.cboSpheres = new ComboBoxEdit();
            this.txtFlattening = new TextEdit();
            this.txtMiniorAxis = new TextEdit();
            this.txtMajorAxis = new TextEdit();
            this.rdoFlattening = new RadioButton();
            this.rdoMiniorAxis = new RadioButton();
            this.label4 = new Label();
            this.label3 = new Label();
            this.label2 = new Label();
            this.groupBox4 = new GroupBox();
            this.cboAngleName = new ComboBoxEdit();
            this.txtValue = new TextEdit();
            this.label6 = new Label();
            this.label5 = new Label();
            this.groupBox3 = new GroupBox();
            this.cboPrimeMeridians = new ComboBoxEdit();
            this.label11 = new Label();
            this.label10 = new Label();
            this.label9 = new Label();
            this.txtSecond = new TextEdit();
            this.txtMinute = new TextEdit();
            this.txtDegree = new TextEdit();
            this.label7 = new Label();
            this.label8 = new Label();
            this.textEditName.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.cboDatumName.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.cboSpheres.Properties.BeginInit();
            this.txtFlattening.Properties.BeginInit();
            this.txtMiniorAxis.Properties.BeginInit();
            this.txtMajorAxis.Properties.BeginInit();
            this.groupBox4.SuspendLayout();
            this.cboAngleName.Properties.BeginInit();
            this.txtValue.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.cboPrimeMeridians.Properties.BeginInit();
            this.txtSecond.Properties.BeginInit();
            this.txtMinute.Properties.BeginInit();
            this.txtDegree.Properties.BeginInit();
            base.SuspendLayout();
            this.textEditName.EditValue = "";
            this.textEditName.Location = new System.Drawing.Point(48, 8);
            this.textEditName.Name = "textEditName";
            this.textEditName.Size = new Size(248, 21);
            this.textEditName.TabIndex = 0;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(8, 8);
            this.label1.Name = "label1";
            this.label1.Size = new Size(29, 17);
            this.label1.TabIndex = 1;
            this.label1.Text = "名称";
            this.groupBox1.Controls.Add(this.cboDatumName);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Location = new System.Drawing.Point(8, 32);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(296, 216);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "数据";
            this.cboDatumName.EditValue = "";
            this.cboDatumName.Location = new System.Drawing.Point(64, 24);
            this.cboDatumName.Name = "cboDatumName";
            this.cboDatumName.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboDatumName.Size = new Size(216, 21);
            this.cboDatumName.TabIndex = 6;
            this.cboDatumName.SelectedIndexChanged += new EventHandler(this.cboDatumName_SelectedIndexChanged);
            this.groupBox2.Controls.Add(this.cboSpheres);
            this.groupBox2.Controls.Add(this.txtFlattening);
            this.groupBox2.Controls.Add(this.txtMiniorAxis);
            this.groupBox2.Controls.Add(this.txtMajorAxis);
            this.groupBox2.Controls.Add(this.rdoFlattening);
            this.groupBox2.Controls.Add(this.rdoMiniorAxis);
            this.groupBox2.Controls.Add(this.label4);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Location = new System.Drawing.Point(16, 56);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(264, 152);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "椭球参数";
            this.cboSpheres.EditValue = "";
            this.cboSpheres.Location = new System.Drawing.Point(80, 24);
            this.cboSpheres.Name = "cboSpheres";
            this.cboSpheres.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboSpheres.Size = new Size(160, 21);
            this.cboSpheres.TabIndex = 9;
            this.cboSpheres.SelectedIndexChanged += new EventHandler(this.cboSpheres_SelectedIndexChanged);
            this.txtFlattening.EditValue = "1";
            this.txtFlattening.Location = new System.Drawing.Point(80, 120);
            this.txtFlattening.Name = "txtFlattening";
            this.txtFlattening.Size = new Size(160, 21);
            this.txtFlattening.TabIndex = 8;
            this.txtFlattening.EditValueChanged += new EventHandler(this.txtFlattening_EditValueChanged);
            this.txtMiniorAxis.EditValue = "1";
            this.txtMiniorAxis.Location = new System.Drawing.Point(80, 88);
            this.txtMiniorAxis.Name = "txtMiniorAxis";
            this.txtMiniorAxis.Size = new Size(160, 21);
            this.txtMiniorAxis.TabIndex = 7;
            this.txtMiniorAxis.EditValueChanged += new EventHandler(this.txtMiniorAxis_EditValueChanged);
            this.txtMajorAxis.EditValue = "1";
            this.txtMajorAxis.Location = new System.Drawing.Point(80, 56);
            this.txtMajorAxis.Name = "txtMajorAxis";
            this.txtMajorAxis.Size = new Size(160, 21);
            this.txtMajorAxis.TabIndex = 6;
            this.txtMajorAxis.EditValueChanged += new EventHandler(this.txtMajorAxis_EditValueChanged);
            this.rdoFlattening.Location = new System.Drawing.Point(8, 118);
            this.rdoFlattening.Name = "rdoFlattening";
            this.rdoFlattening.Size = new Size(72, 24);
            this.rdoFlattening.TabIndex = 4;
            this.rdoFlattening.Text = "扁率倒数";
            this.rdoFlattening.Click += new EventHandler(this.rdoFlattening_Click);
            this.rdoMiniorAxis.Location = new System.Drawing.Point(8, 83);
            this.rdoMiniorAxis.Name = "rdoMiniorAxis";
            this.rdoMiniorAxis.Size = new Size(64, 24);
            this.rdoMiniorAxis.TabIndex = 3;
            this.rdoMiniorAxis.Text = "短半轴";
            this.rdoMiniorAxis.Click += new EventHandler(this.rdoMiniorAxis_Click);
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(8, 57);
            this.label4.Name = "label4";
            this.label4.Size = new Size(48, 17);
            this.label4.TabIndex = 2;
            this.label4.Text = "长半轴:";
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(8, 24);
            this.label3.Name = "label3";
            this.label3.Size = new Size(35, 17);
            this.label3.TabIndex = 1;
            this.label3.Text = "名称:";
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(16, 24);
            this.label2.Name = "label2";
            this.label2.Size = new Size(29, 17);
            this.label2.TabIndex = 0;
            this.label2.Text = "名称";
            this.groupBox4.Controls.Add(this.cboAngleName);
            this.groupBox4.Controls.Add(this.txtValue);
            this.groupBox4.Controls.Add(this.label6);
            this.groupBox4.Controls.Add(this.label5);
            this.groupBox4.Location = new System.Drawing.Point(8, 256);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(296, 88);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "角度单位";
            this.cboAngleName.EditValue = "";
            this.cboAngleName.Location = new System.Drawing.Point(88, 24);
            this.cboAngleName.Name = "cboAngleName";
            this.cboAngleName.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboAngleName.Size = new Size(184, 21);
            this.cboAngleName.TabIndex = 10;
            this.cboAngleName.SelectedIndexChanged += new EventHandler(this.cboAngleName_SelectedIndexChanged);
            this.txtValue.EditValue = "1";
            this.txtValue.Location = new System.Drawing.Point(88, 56);
            this.txtValue.Name = "txtValue";
            this.txtValue.Size = new Size(184, 21);
            this.txtValue.TabIndex = 9;
            this.txtValue.EditValueChanged += new EventHandler(this.txtValue_EditValueChanged);
            this.label6.Location = new System.Drawing.Point(16, 60);
            this.label6.Name = "label6";
            this.label6.Size = new Size(72, 16);
            this.label6.TabIndex = 4;
            this.label6.Text = "单位(弧度):";
            this.label5.Location = new System.Drawing.Point(16, 24);
            this.label5.Name = "label5";
            this.label5.Size = new Size(56, 16);
            this.label5.TabIndex = 2;
            this.label5.Text = "名称:";
            this.groupBox3.Controls.Add(this.cboPrimeMeridians);
            this.groupBox3.Controls.Add(this.label11);
            this.groupBox3.Controls.Add(this.label10);
            this.groupBox3.Controls.Add(this.label9);
            this.groupBox3.Controls.Add(this.txtSecond);
            this.groupBox3.Controls.Add(this.txtMinute);
            this.groupBox3.Controls.Add(this.txtDegree);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Location = new System.Drawing.Point(8, 352);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(296, 88);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "本初子午线";
            this.cboPrimeMeridians.EditValue = "";
            this.cboPrimeMeridians.Location = new System.Drawing.Point(64, 24);
            this.cboPrimeMeridians.Name = "cboPrimeMeridians";
            this.cboPrimeMeridians.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboPrimeMeridians.Size = new Size(216, 21);
            this.cboPrimeMeridians.TabIndex = 15;
            this.cboPrimeMeridians.SelectedIndexChanged += new EventHandler(this.cboPrimeMeridians_SelectedIndexChanged);
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(272, 56);
            this.label11.Name = "label11";
            this.label11.Size = new Size(17, 17);
            this.label11.TabIndex = 11;
            this.label11.Text = "″";
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(184, 56);
            this.label10.Name = "label10";
            this.label10.Size = new Size(17, 17);
            this.label10.TabIndex = 10;
            this.label10.Text = "′";
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(112, 56);
            this.label9.Name = "label9";
            this.label9.Size = new Size(17, 17);
            this.label9.TabIndex = 9;
            this.label9.Text = "\x00b0";
            this.txtSecond.EditValue = "0";
            this.txtSecond.Location = new System.Drawing.Point(208, 56);
            this.txtSecond.Name = "txtSecond";
            this.txtSecond.Size = new Size(48, 21);
            this.txtSecond.TabIndex = 14;
            this.txtSecond.EditValueChanged += new EventHandler(this.txtSecond_EditValueChanged);
            this.txtMinute.EditValue = "0";
            this.txtMinute.Location = new System.Drawing.Point(136, 56);
            this.txtMinute.Name = "txtMinute";
            this.txtMinute.Size = new Size(48, 21);
            this.txtMinute.TabIndex = 13;
            this.txtMinute.EditValueChanged += new EventHandler(this.txtMinute_EditValueChanged);
            this.txtDegree.EditValue = "0";
            this.txtDegree.Location = new System.Drawing.Point(64, 56);
            this.txtDegree.Name = "txtDegree";
            this.txtDegree.Size = new Size(40, 21);
            this.txtDegree.TabIndex = 12;
            this.txtDegree.EditValueChanged += new EventHandler(this.txtDegree_EditValueChanged);
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(16, 56);
            this.label7.Name = "label7";
            this.label7.Size = new Size(35, 17);
            this.label7.TabIndex = 4;
            this.label7.Text = "经度:";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(16, 25);
            this.label8.Name = "label8";
            this.label8.Size = new Size(35, 17);
            this.label8.TabIndex = 2;
            this.label8.Text = "名称:";
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.textEditName);
            base.Name = "GeoCoordSys";
            base.Size = new Size(320, 456);
            base.Load += new EventHandler(this.GeoCoordSys_Load);
            this.textEditName.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.cboDatumName.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.cboSpheres.Properties.EndInit();
            this.txtFlattening.Properties.EndInit();
            this.txtMiniorAxis.Properties.EndInit();
            this.txtMajorAxis.Properties.EndInit();
            this.groupBox4.ResumeLayout(false);
            this.cboAngleName.Properties.EndInit();
            this.txtValue.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.cboPrimeMeridians.Properties.EndInit();
            this.txtSecond.Properties.EndInit();
            this.txtMinute.Properties.EndInit();
            this.txtDegree.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private Container components = null;
        private ComboBoxEdit cboAngleName;
        private ComboBoxEdit cboDatumName;
        private ComboBoxEdit cboPrimeMeridians;
        private ComboBoxEdit cboSpheres;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private IDatum m_Datum;
        private IGeographicCoordinateSystem m_GeoCoordSys;
        private IPrimeMeridian m_PrimeMeridian;
        private ISpheroid m_pSphere;
        private IUnit m_Unit;
        private RadioButton rdoFlattening;
        private RadioButton rdoMiniorAxis;
        private TextEdit textEditName;
        private TextEdit txtDegree;
        private TextEdit txtFlattening;
        private TextEdit txtMajorAxis;
        private TextEdit txtMiniorAxis;
        private TextEdit txtMinute;
        private TextEdit txtSecond;
        private TextEdit txtValue;
    }
}