namespace Yutai.ArcGIS.Controls.Controls
{
    public enum LVS_EX
    {
        LVS_EX_BORDERSELECT = 32768,
        LVS_EX_CHECKBOXES = 4,
        LVS_EX_DOUBLEBUFFER = 65536,
        LVS_EX_FLATSB = 256,
        LVS_EX_FULLROWSELECT = 32,
        LVS_EX_GRIDLINES = 1,
        LVS_EX_HEADERDRAGDROP = 16,
        LVS_EX_HIDELABELS = 131072,
        LVS_EX_INFOTIP = 1024,
        LVS_EX_LABELTIP = 16384,
        LVS_EX_MULTIWORKAREAS = 8192,
        LVS_EX_ONECLICKACTIVATE = 64,
        LVS_EX_REGIONAL = 512,
        LVS_EX_SIMPLESELECT = 1048576,
        LVS_EX_SINGLEROW = 262144,
        LVS_EX_SNAPTOGRID = 524288,
        LVS_EX_SUBITEMIMAGES = 2,
        LVS_EX_TRACKSELECT = 8,
        LVS_EX_TWOCLICKACTIVATE = 128,
        LVS_EX_UNDERLINECOLD = 4096,
        LVS_EX_UNDERLINEHOT = 2048
    }
}

