
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Controls;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.Geometry;

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using Yutai.Plugins.Interfaces;

namespace Yutai.Pipeline.Analysis.QueryForms
{
	    partial class ComplexQueryUI
    {
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

	
	private void InitializeComponent()
		{
			this.groupBox1 = new GroupBox();
			this.LayerBox = new ComboBox();
			this.FieldBox = new ListBox();
			this.ValueBox = new ListBox();
			this.SqlBox = new RichTextBox();
			this.AndRaio = new RadioButton();
			this.OrRadio = new RadioButton();
			this.AddItem = new Button();
			this.ClearAll = new Button();
			this.QueryButton = new Button();
			this.CloseButton = new Button();
			this.BigRadio = new RadioButton();
			this.SmallRadio = new RadioButton();
			this.BigeRadio = new RadioButton();
			this.SmalleRadio = new RadioButton();
			this.Noequradio = new RadioButton();
			this.Likeradio = new RadioButton();
			this.Equradio = new RadioButton();
			this.ValueEdit = new TextBox();
			this.groupBox2 = new GroupBox();
			this.bGeo = new CheckBox();
			this.SelectText = new TextBox();
			this.groupBox3 = new GroupBox();
			this.groupBox4 = new GroupBox();
			this.groupBox5 = new GroupBox();
			this.label1 = new Label();
			this.GlacisUpDown = new NumericUpDown();
			this.chkBoxTwice = new CheckBox();
			this.groupBox1.SuspendLayout();
			this.groupBox2.SuspendLayout();
			this.groupBox3.SuspendLayout();
			this.groupBox4.SuspendLayout();
			this.groupBox5.SuspendLayout();
			((ISupportInitialize)this.GlacisUpDown).BeginInit();
			base.SuspendLayout();
			this.groupBox1.Controls.Add(this.LayerBox);
			this.groupBox1.Location = new System.Drawing.Point(0, 2);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new Size(175, 45);
			this.groupBox1.TabIndex = 1;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "图层列表";
			this.LayerBox.DropDownStyle = ComboBoxStyle.DropDownList;
			this.LayerBox.FormattingEnabled = true;
			this.LayerBox.Location = new System.Drawing.Point(5, 17);
			this.LayerBox.Name = "LayerBox";
			this.LayerBox.Size = new Size(166, 20);
			this.LayerBox.TabIndex = 0;
			this.LayerBox.SelectedIndexChanged += new EventHandler(this.LayerBox_SelectedIndexChanged);
			this.FieldBox.FormattingEnabled = true;
			this.FieldBox.ItemHeight = 12;
			this.FieldBox.Location = new System.Drawing.Point(8, 15);
			this.FieldBox.Name = "FieldBox";
			this.FieldBox.Size = new Size(157, 100);
			this.FieldBox.TabIndex = 2;
			this.FieldBox.SelectedIndexChanged += new EventHandler(this.FieldBox_SelectedIndexChanged);
			this.ValueBox.FormattingEnabled = true;
			this.ValueBox.ItemHeight = 12;
			this.ValueBox.Location = new System.Drawing.Point(340, 37);
			this.ValueBox.Name = "ValueBox";
			this.ValueBox.Size = new Size(113, 124);
			this.ValueBox.Sorted = true;
			this.ValueBox.TabIndex = 3;
			this.ValueBox.MouseDoubleClick += new MouseEventHandler(this.ValueBox_MouseDoubleClick);
			this.ValueBox.SelectedIndexChanged += new EventHandler(this.ValueBox_SelectedIndexChanged);
			this.SqlBox.Location = new System.Drawing.Point(3, 206);
			this.SqlBox.Name = "SqlBox";
			this.SqlBox.Size = new Size(450, 21);
			this.SqlBox.TabIndex = 4;
			this.SqlBox.Text = "";
			this.AndRaio.AutoSize = true;
			this.AndRaio.Location = new System.Drawing.Point(6, 16);
			this.AndRaio.Name = "AndRaio";
			this.AndRaio.Size = new Size(47, 16);
			this.AndRaio.TabIndex = 5;
			this.AndRaio.Text = "并且";
			this.AndRaio.UseVisualStyleBackColor = true;
			this.OrRadio.AutoSize = true;
			this.OrRadio.Checked = true;
			this.OrRadio.Location = new System.Drawing.Point(78, 16);
			this.OrRadio.Name = "OrRadio";
			this.OrRadio.Size = new Size(47, 16);
			this.OrRadio.TabIndex = 6;
			this.OrRadio.TabStop = true;
			this.OrRadio.Text = "或者";
			this.OrRadio.UseVisualStyleBackColor = true;
			this.AddItem.Location = new System.Drawing.Point(462, 6);
			this.AddItem.Name = "AddItem";
			this.AddItem.Size = new Size(72, 24);
			this.AddItem.TabIndex = 7;
			this.AddItem.Text = "添加(&A)";
			this.AddItem.UseVisualStyleBackColor = true;
			this.AddItem.Click += new EventHandler(this.AddItem_Click);
			this.ClearAll.Location = new System.Drawing.Point(462, 37);
			this.ClearAll.Name = "ClearAll";
			this.ClearAll.Size = new Size(72, 24);
			this.ClearAll.TabIndex = 8;
			this.ClearAll.Text = "清空(&C)";
			this.ClearAll.UseVisualStyleBackColor = true;
			this.ClearAll.Click += new EventHandler(this.ClearAll_Click);
			this.QueryButton.Location = new System.Drawing.Point(462, 178);
			this.QueryButton.Name = "QueryButton";
			this.QueryButton.Size = new Size(72, 24);
			this.QueryButton.TabIndex = 9;
			this.QueryButton.Text = "查询(&Q)";
			this.QueryButton.UseVisualStyleBackColor = true;
			this.QueryButton.Click += new EventHandler(this.QueryButton_Click);
			this.CloseButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.CloseButton.Location = new System.Drawing.Point(462, 232);
			this.CloseButton.Name = "CloseButton";
			this.CloseButton.Size = new Size(72, 24);
			this.CloseButton.TabIndex = 10;
			this.CloseButton.Text = "关闭(&C)\u3000";
			this.CloseButton.UseVisualStyleBackColor = true;
			this.CloseButton.Click += new EventHandler(this.CloseButton_Click);
			this.BigRadio.AutoSize = true;
			this.BigRadio.Location = new System.Drawing.Point(51, 15);
			this.BigRadio.Name = "BigRadio";
			this.BigRadio.Size = new Size(29, 16);
			this.BigRadio.TabIndex = 11;
			this.BigRadio.TabStop = true;
			this.BigRadio.Text = ">";
			this.BigRadio.UseVisualStyleBackColor = true;
			this.SmallRadio.AutoSize = true;
			this.SmallRadio.Location = new System.Drawing.Point(96, 15);
			this.SmallRadio.Name = "SmallRadio";
			this.SmallRadio.Size = new Size(29, 16);
			this.SmallRadio.TabIndex = 12;
			this.SmallRadio.TabStop = true;
			this.SmallRadio.Text = "<";
			this.SmallRadio.UseVisualStyleBackColor = true;
			this.BigeRadio.AutoSize = true;
			this.BigeRadio.Location = new System.Drawing.Point(6, 49);
			this.BigeRadio.Name = "BigeRadio";
			this.BigeRadio.Size = new Size(35, 16);
			this.BigeRadio.TabIndex = 13;
			this.BigeRadio.TabStop = true;
			this.BigeRadio.Text = ">=";
			this.BigeRadio.UseVisualStyleBackColor = true;
			this.SmalleRadio.AutoSize = true;
			this.SmalleRadio.Location = new System.Drawing.Point(51, 49);
			this.SmalleRadio.Name = "SmalleRadio";
			this.SmalleRadio.Size = new Size(35, 16);
			this.SmalleRadio.TabIndex = 14;
			this.SmalleRadio.TabStop = true;
			this.SmalleRadio.Text = "<=";
			this.SmalleRadio.UseVisualStyleBackColor = true;
			this.Noequradio.AutoSize = true;
			this.Noequradio.Location = new System.Drawing.Point(96, 50);
			this.Noequradio.Name = "Noequradio";
			this.Noequradio.Size = new Size(35, 16);
			this.Noequradio.TabIndex = 15;
			this.Noequradio.TabStop = true;
			this.Noequradio.Text = "!=";
			this.Noequradio.UseVisualStyleBackColor = true;
			this.Likeradio.AutoSize = true;
			this.Likeradio.Location = new System.Drawing.Point(6, 83);
			this.Likeradio.Name = "Likeradio";
			this.Likeradio.Size = new Size(47, 16);
			this.Likeradio.TabIndex = 16;
			this.Likeradio.TabStop = true;
			this.Likeradio.Text = "相似";
			this.Likeradio.UseVisualStyleBackColor = true;
			this.Equradio.AutoSize = true;
			this.Equradio.Checked = true;
			this.Equradio.Location = new System.Drawing.Point(6, 15);
			this.Equradio.Name = "Equradio";
			this.Equradio.Size = new Size(29, 16);
			this.Equradio.TabIndex = 17;
			this.Equradio.TabStop = true;
			this.Equradio.Text = "=";
			this.Equradio.UseVisualStyleBackColor = true;
			this.ValueEdit.Location = new System.Drawing.Point(340, 9);
			this.ValueEdit.Name = "ValueEdit";
			this.ValueEdit.Size = new Size(113, 21);
			this.ValueEdit.TabIndex = 18;
			this.ValueEdit.TextChanged += new EventHandler(this.ValueEdit_TextChanged);
			this.groupBox2.Controls.Add(this.OrRadio);
			this.groupBox2.Controls.Add(this.AndRaio);
			this.groupBox2.Location = new System.Drawing.Point(183, 124);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new Size(136, 40);
			this.groupBox2.TabIndex = 19;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "关系运算符";
			this.bGeo.AutoSize = true;
			this.bGeo.Location = new System.Drawing.Point(457, 297);
			this.bGeo.Name = "bGeo";
			this.bGeo.Size = new Size(72, 16);
			this.bGeo.TabIndex = 20;
			this.bGeo.Text = "空间范围";
			this.bGeo.UseVisualStyleBackColor = true;
			this.bGeo.CheckedChanged += new EventHandler(this.bGeo_CheckedChanged);
			this.SelectText.Location = new System.Drawing.Point(3, 181);
			this.SelectText.Name = "SelectText";
			this.SelectText.ReadOnly = true;
			this.SelectText.Size = new Size(450, 21);
			this.SelectText.TabIndex = 21;
			this.groupBox3.Controls.Add(this.FieldBox);
			this.groupBox3.Location = new System.Drawing.Point(3, 53);
			this.groupBox3.Name = "groupBox3";
			this.groupBox3.Size = new Size(172, 120);
			this.groupBox3.TabIndex = 22;
			this.groupBox3.TabStop = false;
			this.groupBox3.Text = "字段列表";
			this.groupBox4.Controls.Add(this.Equradio);
			this.groupBox4.Controls.Add(this.BigRadio);
			this.groupBox4.Controls.Add(this.SmallRadio);
			this.groupBox4.Controls.Add(this.BigeRadio);
			this.groupBox4.Controls.Add(this.SmalleRadio);
			this.groupBox4.Controls.Add(this.Noequradio);
			this.groupBox4.Controls.Add(this.Likeradio);
			this.groupBox4.Location = new System.Drawing.Point(183, 2);
			this.groupBox4.Name = "groupBox4";
			this.groupBox4.Size = new Size(134, 106);
			this.groupBox4.TabIndex = 23;
			this.groupBox4.TabStop = false;
			this.groupBox4.Text = "操作符";
			this.groupBox5.Controls.Add(this.label1);
			this.groupBox5.Controls.Add(this.GlacisUpDown);
			this.groupBox5.Location = new System.Drawing.Point(3, 280);
			this.groupBox5.Name = "groupBox5";
			this.groupBox5.Size = new Size(450, 43);
			this.groupBox5.TabIndex = 24;
			this.groupBox5.TabStop = false;
			this.groupBox5.Text = "缓冲区半径";
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(131, 22);
			this.label1.Name = "label1";
			this.label1.Size = new Size(17, 12);
			this.label1.TabIndex = 2;
			this.label1.Text = "米";
			this.GlacisUpDown.Location = new System.Drawing.Point(9, 17);
			int[] array = new int[4];
			array[0] = 1000;
			this.GlacisUpDown.Maximum = new decimal(array);
			this.GlacisUpDown.Name = "GlacisUpDown";
			this.GlacisUpDown.Size = new Size(120, 21);
			this.GlacisUpDown.TabIndex = 1;
			this.GlacisUpDown.ValueChanged += new EventHandler(this.GlacisUpDown_ValueChanged);
			this.chkBoxTwice.AutoSize = true;
			this.chkBoxTwice.Location = new System.Drawing.Point(4, 240);
			this.chkBoxTwice.Name = "chkBoxTwice";
			this.chkBoxTwice.Size = new Size(144, 16);
			this.chkBoxTwice.TabIndex = 25;
			this.chkBoxTwice.Text = "在查询结果中进行查询";
			this.chkBoxTwice.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new SizeF(6f, 12f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new Size(539, 323);
			base.Controls.Add(this.chkBoxTwice);
			base.Controls.Add(this.groupBox5);
			base.Controls.Add(this.groupBox4);
			base.Controls.Add(this.groupBox3);
			base.Controls.Add(this.SelectText);
			base.Controls.Add(this.bGeo);
			base.Controls.Add(this.groupBox2);
			base.Controls.Add(this.ValueEdit);
			base.Controls.Add(this.CloseButton);
			base.Controls.Add(this.QueryButton);
			base.Controls.Add(this.ClearAll);
			base.Controls.Add(this.AddItem);
			base.Controls.Add(this.SqlBox);
			base.Controls.Add(this.ValueBox);
			base.Controls.Add(this.groupBox1);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.MaximizeBox = false;
			base.Name = "ComplexQueryUI";
			base.ShowInTaskbar = false;
			this.Text = "复合查询";
			base.Load += new EventHandler(this.ComplexQueryUI_Load);
			base.VisibleChanged += new EventHandler(this.ComplexQueryUI_VisibleChanged);
			base.HelpRequested += new HelpEventHandler(this.ComplexQueryUI_HelpRequested);
			this.groupBox1.ResumeLayout(false);
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			this.groupBox3.ResumeLayout(false);
			this.groupBox4.ResumeLayout(false);
			this.groupBox4.PerformLayout();
			this.groupBox5.ResumeLayout(false);
			this.groupBox5.PerformLayout();
			((ISupportInitialize)this.GlacisUpDown).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

	
		private IContainer components = null;
		private GroupBox groupBox1;
		private ListBox FieldBox;
		private ListBox ValueBox;
		private RichTextBox SqlBox;
		private RadioButton AndRaio;
		private RadioButton OrRadio;
		private Button AddItem;
		private Button ClearAll;
		private Button QueryButton;
		private Button CloseButton;
		private RadioButton BigRadio;
		private RadioButton SmallRadio;
		private RadioButton BigeRadio;
		private RadioButton SmalleRadio;
		private RadioButton Noequradio;
		private RadioButton Likeradio;
		private RadioButton Equradio;
		private TextBox ValueEdit;
		private GroupBox groupBox2;
		private CheckBox bGeo;
		private TextBox SelectText;
		private ComboBox LayerBox;
		private GroupBox groupBox3;
		private GroupBox groupBox4;
		private GroupBox groupBox5;
		private NumericUpDown GlacisUpDown;
		private Label label1;
		private CheckBox chkBoxTwice;
		private IFeatureLayer SelectLayer;
		private IFields myfields;
		private IField myfield;
		private int SelectType;
		private QueryResult resultDlg;
		private ISelectionSet m_pSelectionSetForSearch;
    }
}