
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Controls;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.Geometry;

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

using Yutai.Plugins.Interfaces;

namespace Yutai.Pipeline.Analysis.QueryForms
{
	    partial class SimpleStatMyshUI
    {
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

	
	private void InitializeComponent()
		{
			this.groupBox4 = new GroupBox();
			this.label1 = new Label();
			this.dataGridView1 = new DataGridView();
			this.Column1 = new DataGridViewTextBoxColumn();
			this.Column4 = new DataGridViewTextBoxColumn();
			this.groupBox3 = new GroupBox();
			this.InsertBut = new Button();
			this.button5 = new Button();
			this.button4 = new Button();
			this.button3 = new Button();
			this.button2 = new Button();
			this.groupBox2 = new GroupBox();
			this.label2 = new Label();
			this.numericUpDown1 = new NumericUpDown();
			this.listBox1 = new ListBox();
			this.groupBox1 = new GroupBox();
			this.RevBut = new Button();
			this.NoneBut = new Button();
			this.AllBut = new Button();
			this.checkedListBox1 = new CheckedListBox();
			this.CalButton = new Button();
			this.button1 = new Button();
			this.GeometrySet = new CheckBox();
			this.groupBox4.SuspendLayout();
			((ISupportInitialize)this.dataGridView1).BeginInit();
			this.groupBox3.SuspendLayout();
			this.groupBox2.SuspendLayout();
			((ISupportInitialize)this.numericUpDown1).BeginInit();
			this.groupBox1.SuspendLayout();
			base.SuspendLayout();
			this.groupBox4.Controls.Add(this.label1);
			this.groupBox4.Controls.Add(this.dataGridView1);
			this.groupBox4.Location = new System.Drawing.Point(182, 117);
			this.groupBox4.Name = "groupBox4";
			this.groupBox4.Size = new Size(139, 180);
			this.groupBox4.TabIndex = 25;
			this.groupBox4.TabStop = false;
			this.groupBox4.Text = "统计范围设置";
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(15, 157);
			this.label1.Name = "label1";
			this.label1.Size = new Size(107, 12);
			this.label1.TabIndex = 5;
			this.label1.Text = "下限=<统计值<上限";
			this.dataGridView1.AllowUserToAddRows = false;
			this.dataGridView1.BackgroundColor = SystemColors.ActiveCaptionText;
			this.dataGridView1.Columns.AddRange(new DataGridViewColumn[]
			{
				this.Column1,
				this.Column4
			});
			this.dataGridView1.GridColor = SystemColors.ControlText;
			this.dataGridView1.Location = new System.Drawing.Point(8, 12);
			this.dataGridView1.Name = "dataGridView1";
			this.dataGridView1.RowHeadersVisible = false;
			this.dataGridView1.RowTemplate.Height = 23;
			this.dataGridView1.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			this.dataGridView1.Size = new Size(125, 142);
			this.dataGridView1.TabIndex = 4;
			this.Column1.Frozen = true;
			this.Column1.HeaderText = "下限";
			this.Column1.MaxInputLength = 6;
			this.Column1.MinimumWidth = 6;
			this.Column1.Name = "Column1";
			this.Column1.Width = 60;
			this.Column4.HeaderText = "上限";
			this.Column4.MaxInputLength = 6;
			this.Column4.Name = "Column4";
			this.Column4.Width = 60;
			this.groupBox3.Controls.Add(this.InsertBut);
			this.groupBox3.Controls.Add(this.button5);
			this.groupBox3.Controls.Add(this.button4);
			this.groupBox3.Controls.Add(this.button3);
			this.groupBox3.Controls.Add(this.button2);
			this.groupBox3.Location = new System.Drawing.Point(98, 117);
			this.groupBox3.Name = "groupBox3";
			this.groupBox3.Size = new Size(78, 180);
			this.groupBox3.TabIndex = 24;
			this.groupBox3.TabStop = false;
			this.groupBox3.Text = "操作";
			this.InsertBut.Location = new System.Drawing.Point(3, 148);
			this.InsertBut.Name = "InsertBut";
			this.InsertBut.Size = new Size(69, 23);
			this.InsertBut.TabIndex = 28;
			this.InsertBut.Text = "插入行";
			this.InsertBut.UseVisualStyleBackColor = true;
			this.InsertBut.Click += new EventHandler(this.InsertBut_Click);
			this.button5.Location = new System.Drawing.Point(3, 84);
			this.button5.Name = "button5";
			this.button5.Size = new Size(69, 23);
			this.button5.TabIndex = 27;
			this.button5.Text = "添加行";
			this.button5.UseVisualStyleBackColor = true;
			this.button5.Click += new EventHandler(this.button5_Click);
			this.button4.Location = new System.Drawing.Point(3, 116);
			this.button4.Name = "button4";
			this.button4.Size = new Size(69, 23);
			this.button4.TabIndex = 26;
			this.button4.Text = "删除行";
			this.button4.UseVisualStyleBackColor = true;
			this.button4.Click += new EventHandler(this.button4_Click);
			this.button3.Location = new System.Drawing.Point(3, 52);
			this.button3.Name = "button3";
			this.button3.Size = new Size(69, 23);
			this.button3.TabIndex = 25;
			this.button3.Text = "添加上限";
			this.button3.UseVisualStyleBackColor = true;
			this.button3.Click += new EventHandler(this.button3_Click);
			this.button2.Location = new System.Drawing.Point(3, 20);
			this.button2.Name = "button2";
			this.button2.Size = new Size(69, 23);
			this.button2.TabIndex = 21;
			this.button2.Text = "添加下限";
			this.button2.UseVisualStyleBackColor = true;
			this.button2.Click += new EventHandler(this.button2_Click);
			this.groupBox2.Controls.Add(this.label2);
			this.groupBox2.Controls.Add(this.numericUpDown1);
			this.groupBox2.Controls.Add(this.listBox1);
			this.groupBox2.Location = new System.Drawing.Point(9, 117);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new Size(83, 180);
			this.groupBox2.TabIndex = 23;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "埋深范围";
			this.label2.AutoSize = true;
			this.label2.Location = new System.Drawing.Point(8, 136);
			this.label2.Name = "label2";
			this.label2.Size = new Size(59, 12);
			this.label2.TabIndex = 29;
			this.label2.Text = "埋深分段:";
			this.numericUpDown1.Location = new System.Drawing.Point(8, 153);
			int[] array = new int[4];
			array[0] = 20;
			this.numericUpDown1.Maximum = new decimal(array);
			int[] array2 = new int[4];
			array2[0] = 1;
			this.numericUpDown1.Minimum = new decimal(array2);
			this.numericUpDown1.Name = "numericUpDown1";
			this.numericUpDown1.Size = new Size(71, 21);
			this.numericUpDown1.TabIndex = 28;
			this.numericUpDown1.TextAlign = HorizontalAlignment.Center;
			int[] array3 = new int[4];
			array3[0] = 5;
			this.numericUpDown1.Value = new decimal(array3);
			this.numericUpDown1.ValueChanged += new EventHandler(this.numericUpDown1_ValueChanged);
			this.listBox1.FormattingEnabled = true;
			this.listBox1.ItemHeight = 12;
			this.listBox1.Location = new System.Drawing.Point(6, 20);
			this.listBox1.Name = "listBox1";
			this.listBox1.Size = new Size(71, 112);
			this.listBox1.Sorted = true;
			this.listBox1.TabIndex = 17;
			this.listBox1.SelectedIndexChanged += new EventHandler(this.listBox1_SelectedIndexChanged);
			this.groupBox1.Controls.Add(this.RevBut);
			this.groupBox1.Controls.Add(this.NoneBut);
			this.groupBox1.Controls.Add(this.AllBut);
			this.groupBox1.Controls.Add(this.checkedListBox1);
			this.groupBox1.Location = new System.Drawing.Point(9, 3);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new Size(312, 108);
			this.groupBox1.TabIndex = 22;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "管线数据层列表";
			this.RevBut.Location = new System.Drawing.Point(228, 74);
			this.RevBut.Name = "RevBut";
			this.RevBut.Size = new Size(76, 23);
			this.RevBut.TabIndex = 6;
			this.RevBut.Text = "反选(&I)";
			this.RevBut.UseVisualStyleBackColor = true;
			this.RevBut.Click += new EventHandler(this.RevBut_Click);
			this.NoneBut.Location = new System.Drawing.Point(229, 45);
			this.NoneBut.Name = "NoneBut";
			this.NoneBut.Size = new Size(76, 23);
			this.NoneBut.TabIndex = 5;
			this.NoneBut.Text = "全不选(&N)";
			this.NoneBut.UseVisualStyleBackColor = true;
			this.NoneBut.Click += new EventHandler(this.NoneBut_Click);
			this.AllBut.Location = new System.Drawing.Point(229, 16);
			this.AllBut.Name = "AllBut";
			this.AllBut.Size = new Size(76, 23);
			this.AllBut.TabIndex = 4;
			this.AllBut.Text = "全选(&A)";
			this.AllBut.UseVisualStyleBackColor = true;
			this.AllBut.Click += new EventHandler(this.AllBut_Click);
			this.checkedListBox1.CheckOnClick = true;
			this.checkedListBox1.FormattingEnabled = true;
			this.checkedListBox1.Location = new System.Drawing.Point(6, 16);
			this.checkedListBox1.Name = "checkedListBox1";
			this.checkedListBox1.Size = new Size(208, 84);
			this.checkedListBox1.Sorted = true;
			this.checkedListBox1.TabIndex = 2;
			this.checkedListBox1.SelectedIndexChanged += new EventHandler(this.checkedListBox1_SelectedIndexChanged);
			this.CalButton.Location = new System.Drawing.Point(101, 303);
			this.CalButton.Name = "CalButton";
			this.CalButton.Size = new Size(71, 23);
			this.CalButton.TabIndex = 26;
			this.CalButton.Text = "确定(&Q)";
			this.CalButton.UseVisualStyleBackColor = true;
			this.CalButton.Click += new EventHandler(this.CalButton_Click);
			this.button1.Location = new System.Drawing.Point(188, 303);
			this.button1.Name = "button1";
			this.button1.Size = new Size(75, 23);
			this.button1.TabIndex = 27;
			this.button1.Text = "关闭(&G)";
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Click += new EventHandler(this.button1_Click);
			this.GeometrySet.AutoSize = true;
			this.GeometrySet.Location = new System.Drawing.Point(17, 307);
			this.GeometrySet.Name = "GeometrySet";
			this.GeometrySet.Size = new Size(72, 16);
			this.GeometrySet.TabIndex = 28;
			this.GeometrySet.Text = "空间范围";
			this.GeometrySet.UseVisualStyleBackColor = true;
			this.GeometrySet.Click += new EventHandler(this.GeometrySet_Click);
			base.AutoScaleDimensions = new SizeF(6f, 12f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new Size(329, 328);
			base.Controls.Add(this.GeometrySet);
			base.Controls.Add(this.button1);
			base.Controls.Add(this.CalButton);
			base.Controls.Add(this.groupBox4);
			base.Controls.Add(this.groupBox3);
			base.Controls.Add(this.groupBox2);
			base.Controls.Add(this.groupBox1);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			base.MaximizeBox = false;
			base.Name = "SimpleStatMyshUI";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			this.Text = "埋深分段统计";
			base.Load += new EventHandler(this.SimpleStatMyshUI_Load);
			base.VisibleChanged += new EventHandler(this.SimpleStatMyshUI_VisibleChanged);
			base.HelpRequested += new HelpEventHandler(this.SimpleStatMyshUI_HelpRequested);
			this.groupBox4.ResumeLayout(false);
			this.groupBox4.PerformLayout();
			((ISupportInitialize)this.dataGridView1).EndInit();
			this.groupBox3.ResumeLayout(false);
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			((ISupportInitialize)this.numericUpDown1).EndInit();
			this.groupBox1.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

	
		private IContainer components = null;
		private GroupBox groupBox4;
		private DataGridView dataGridView1;
		private GroupBox groupBox3;
		private Button button4;
		private Button button3;
		private Button button2;
		private GroupBox groupBox2;
		private ListBox listBox1;
		private GroupBox groupBox1;
		private Button RevBut;
		private Button NoneBut;
		private Button AllBut;
		private CheckedListBox checkedListBox1;
		private Button CalButton;
		private Button button1;
		private Button button5;
		private DataGridViewTextBoxColumn Column1;
		private DataGridViewTextBoxColumn Column4;
		private Label label1;
		private NumericUpDown numericUpDown1;
		private Label label2;
		private Button InsertBut;
		private CheckBox GeometrySet;
		private IField myfield;
		private IFeatureLayer SelectLayer;
		private IFields myfields;
		private double minNum;
		private double maxNum;
    }
}