using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.GISClient;

namespace Yutai.ArcGIS.Catalog.UI
{
    partial class frmArcGISServerManageProperty
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.btnOK = new SimpleButton();
            this.btnCancel = new SimpleButton();
            this.groupBox1 = new GroupBox();
            this.chkSaveManage = new CheckEdit();
            this.txtPaswordMan = new TextEdit();
            this.txtUserManage = new TextEdit();
            this.label8 = new Label();
            this.label9 = new Label();
            this.simpleButton1 = new SimpleButton();
            this.cboServerType = new System.Windows.Forms.ComboBox();
            this.label7 = new Label();
            this.label6 = new Label();
            this.label4 = new Label();
            this.txtMUrl = new TextEdit();
            this.txtTempFolder = new TextEdit();
            this.label1 = new Label();
            this.chkUseDefaultFolder = new CheckEdit();
            this.groupBox1.SuspendLayout();
            this.chkSaveManage.Properties.BeginInit();
            this.txtPaswordMan.Properties.BeginInit();
            this.txtUserManage.Properties.BeginInit();
            this.txtMUrl.Properties.BeginInit();
            this.txtTempFolder.Properties.BeginInit();
            this.chkUseDefaultFolder.Properties.BeginInit();
            base.SuspendLayout();
            this.btnOK.Location = new Point(224, 286);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(60, 28);
            this.btnOK.TabIndex = 24;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.Location = new Point(309, 286);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(60, 28);
            this.btnCancel.TabIndex = 23;
            this.btnCancel.Text = "取消";
            this.groupBox1.Controls.Add(this.chkSaveManage);
            this.groupBox1.Controls.Add(this.txtPaswordMan);
            this.groupBox1.Controls.Add(this.txtUserManage);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.label9);
            this.groupBox1.Enabled = false;
            this.groupBox1.Location = new Point(14, 153);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(388, 116);
            this.groupBox1.TabIndex = 28;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "帐户";
            this.chkSaveManage.EditValue = true;
            this.chkSaveManage.Enabled = false;
            this.chkSaveManage.Location = new Point(16, 88);
            this.chkSaveManage.Name = "chkSaveManage";
            this.chkSaveManage.Properties.Caption = "保存用户名/密码";
            this.chkSaveManage.Size = new Size(112, 19);
            this.chkSaveManage.TabIndex = 4;
            this.txtPaswordMan.EditValue = "";
            this.txtPaswordMan.Location = new Point(68, 52);
            this.txtPaswordMan.Name = "txtPaswordMan";
            this.txtPaswordMan.Properties.PasswordChar = '*';
            this.txtPaswordMan.Size = new Size(304, 21);
            this.txtPaswordMan.TabIndex = 3;
            this.txtUserManage.EditValue = "";
            this.txtUserManage.Location = new Point(68, 20);
            this.txtUserManage.Name = "txtUserManage";
            this.txtUserManage.Size = new Size(304, 21);
            this.txtUserManage.TabIndex = 2;
            this.label8.AutoSize = true;
            this.label8.Location = new Point(16, 56);
            this.label8.Name = "label8";
            this.label8.Size = new Size(47, 12);
            this.label8.TabIndex = 1;
            this.label8.Text = "密  码:";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(16, 24);
            this.label9.Name = "label9";
            this.label9.Size = new Size(47, 12);
            this.label9.TabIndex = 0;
            this.label9.Text = "用户名:";
            this.simpleButton1.Location = new Point(361, 93);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new Size(31, 28);
            this.simpleButton1.TabIndex = 27;
            this.simpleButton1.Text = "...";
            this.cboServerType.FormattingEnabled = true;
            this.cboServerType.Items.AddRange(new object[] { "ArcGIS Server" });
            this.cboServerType.Location = new Point(89, 65);
            this.cboServerType.Name = "cboServerType";
            this.cboServerType.Size = new Size(303, 20);
            this.cboServerType.TabIndex = 26;
            this.cboServerType.Text = "ArcGIS Server";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(12, 68);
            this.label7.Name = "label7";
            this.label7.Size = new Size(71, 12);
            this.label7.TabIndex = 25;
            this.label7.Text = "服务器类型:";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(87, 28);
            this.label6.Name = "label6";
            this.label6.Size = new Size(305, 12);
            this.label6.TabIndex = 24;
            this.label6.Text = "ArcGIS Server:http://myserver:6080/arcgis/services";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(12, 9);
            this.label4.Name = "label4";
            this.label4.Size = new Size(65, 12);
            this.label4.TabIndex = 20;
            this.label4.Text = "服务器URL:";
            this.txtMUrl.EditValue = "http://";
            this.txtMUrl.Location = new Point(89, 4);
            this.txtMUrl.Name = "txtMUrl";
            this.txtMUrl.Size = new Size(303, 21);
            this.txtMUrl.TabIndex = 19;
            this.txtTempFolder.EditValue = "";
            this.txtTempFolder.Location = new Point(89, 99);
            this.txtTempFolder.Name = "txtTempFolder";
            this.txtTempFolder.Size = new Size(266, 21);
            this.txtTempFolder.TabIndex = 18;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(12, 103);
            this.label1.Name = "label1";
            this.label1.Size = new Size(71, 12);
            this.label1.TabIndex = 13;
            this.label1.Text = "过渡文件夹:";
            this.chkUseDefaultFolder.EditValue = true;
            this.chkUseDefaultFolder.Location = new Point(12, 128);
            this.chkUseDefaultFolder.Name = "chkUseDefaultFolder";
            this.chkUseDefaultFolder.Properties.Caption = "使用默认过渡文件夹";
            this.chkUseDefaultFolder.Size = new Size(138, 19);
            this.chkUseDefaultFolder.TabIndex = 30;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(416, 335);
            base.Controls.Add(this.chkUseDefaultFolder);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.simpleButton1);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.cboServerType);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.label4);
            base.Controls.Add(this.label6);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.txtTempFolder);
            base.Controls.Add(this.txtMUrl);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmArcGISServerManageProperty";
            this.Text = "ArcGIS Server管理员连接属性";
            base.Load += new EventHandler(this.frmArcGISServerManageProperty_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.chkSaveManage.Properties.EndInit();
            this.txtPaswordMan.Properties.EndInit();
            this.txtUserManage.Properties.EndInit();
            this.txtMUrl.Properties.EndInit();
            this.txtTempFolder.Properties.EndInit();
            this.chkUseDefaultFolder.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private bool bool_0;
        private SimpleButton btnCancel;
        private SimpleButton btnOK;
        private System.Windows.Forms.ComboBox cboServerType;
        private CheckEdit chkSaveManage;
        private CheckEdit chkUseDefaultFolder;
        private GroupBox groupBox1;
        private IAGSServerConnection iagsserverConnection_0;
        private IAGSServerConnectionName iagsserverConnectionName_0;
        private IMapDescription imapDescription_0;
        private IMapServer imapServer_0;
        private IPropertySet ipropertySet_0;
        private Label label1;
        private Label label4;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private SimpleButton simpleButton1;
        private string string_0;
        private string string_1;
        private string string_2;
        private TextEdit txtMUrl;
        private TextEdit txtPaswordMan;
        private TextEdit txtTempFolder;
        private TextEdit txtUserManage;
    }
}