using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geodatabase;
using Yutai.ArcGIS.Common.Geodatabase;

namespace Yutai.ArcGIS.Catalog.UI
{
    partial class frmDatasetUnion
    {
        protected override void Dispose(bool bool_0)
        {
            if (bool_0 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_0);
        }

       
 private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmDatasetUnion));
            this.radioGroup1 = new RadioGroup();
            this.panel1 = new Panel();
            this.rdoDatasetType = new RadioGroup();
            this.btnSelectWorkspace = new SimpleButton();
            this.txtDatasetName = new TextEdit();
            this.txtWorkspaceName = new TextEdit();
            this.label2 = new Label();
            this.label1 = new Label();
            this.panel2 = new Panel();
            this.btnSelectOutDataset = new SimpleButton();
            this.txtOutDataset = new TextEdit();
            this.label4 = new Label();
            this.groupBox1 = new GroupBox();
            this.btnAdd = new SimpleButton();
            this.txtInputFeatureClass = new TextEdit();
            this.label3 = new Label();
            this.btnDelete = new SimpleButton();
            this.label5 = new Label();
            this.SourceDatalistBox = new ListBoxControl();
            this.btnSelectInputFeatures = new SimpleButton();
            this.btnCancel = new SimpleButton();
            this.btnOK = new SimpleButton();
            this.lblProcess = new Label();
            this.radioGroup1.Properties.BeginInit();
            this.panel1.SuspendLayout();
            this.rdoDatasetType.Properties.BeginInit();
            this.txtDatasetName.Properties.BeginInit();
            this.txtWorkspaceName.Properties.BeginInit();
            this.panel2.SuspendLayout();
            this.txtOutDataset.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.txtInputFeatureClass.Properties.BeginInit();
            ((ISupportInitialize) this.SourceDatalistBox).BeginInit();
            base.SuspendLayout();
            this.radioGroup1.Location = new Point(8, 8);
            this.radioGroup1.Name = "radioGroup1";
            this.radioGroup1.Properties.Appearance.BackColor = Color.Transparent;
            this.radioGroup1.Properties.Appearance.Options.UseBackColor = true;
            this.radioGroup1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.radioGroup1.Properties.Columns = 2;
            this.radioGroup1.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "创建新数据集"), new RadioGroupItem(null, "使用已有数据集") });
            this.radioGroup1.Size = new Size(224, 24);
            this.radioGroup1.TabIndex = 0;
            this.radioGroup1.SelectedIndexChanged += new EventHandler(this.radioGroup1_SelectedIndexChanged);
            this.panel1.Controls.Add(this.rdoDatasetType);
            this.panel1.Controls.Add(this.btnSelectWorkspace);
            this.panel1.Controls.Add(this.txtDatasetName);
            this.panel1.Controls.Add(this.txtWorkspaceName);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Location = new Point(0, 32);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(344, 72);
            this.panel1.TabIndex = 1;
            this.rdoDatasetType.Location = new Point(216, 40);
            this.rdoDatasetType.Name = "rdoDatasetType";
            this.rdoDatasetType.Properties.Appearance.BackColor = Color.Transparent;
            this.rdoDatasetType.Properties.Appearance.Options.UseBackColor = true;
            this.rdoDatasetType.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoDatasetType.Properties.Columns = 2;
            this.rdoDatasetType.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "要素类"), new RadioGroupItem(null, "表") });
            this.rdoDatasetType.Size = new Size(124, 24);
            this.rdoDatasetType.TabIndex = 20;
            this.btnSelectWorkspace.Location = new Point(288, 8);
            this.btnSelectWorkspace.Name = "btnSelectWorkspace";
            this.btnSelectWorkspace.Size = new Size(32, 24);
            this.btnSelectWorkspace.TabIndex = 4;
            this.btnSelectWorkspace.Text = "...";
            this.btnSelectWorkspace.Click += new EventHandler(this.btnSelectWorkspace_Click);
            this.txtDatasetName.EditValue = "";
            this.txtDatasetName.Location = new Point(88, 40);
            this.txtDatasetName.Name = "txtDatasetName";
            this.txtDatasetName.Size = new Size(120, 21);
            this.txtDatasetName.TabIndex = 3;
            this.txtWorkspaceName.EditValue = "";
            this.txtWorkspaceName.Location = new Point(88, 8);
            this.txtWorkspaceName.Name = "txtWorkspaceName";
            this.txtWorkspaceName.Size = new Size(184, 21);
            this.txtWorkspaceName.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 48);
            this.label2.Name = "label2";
            this.label2.Size = new Size(65, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "数据集名称";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 16);
            this.label1.Name = "label1";
            this.label1.Size = new Size(77, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "选择存储位置";
            this.panel2.Controls.Add(this.btnSelectOutDataset);
            this.panel2.Controls.Add(this.txtOutDataset);
            this.panel2.Controls.Add(this.label4);
            this.panel2.Location = new Point(0, 32);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(344, 74);
            this.panel2.TabIndex = 2;
            this.panel2.Visible = false;
            this.btnSelectOutDataset.Location = new Point(304, 8);
            this.btnSelectOutDataset.Name = "btnSelectOutDataset";
            this.btnSelectOutDataset.Size = new Size(32, 24);
            this.btnSelectOutDataset.TabIndex = 4;
            this.btnSelectOutDataset.Text = "...";
            this.btnSelectOutDataset.Click += new EventHandler(this.btnSelectOutDataset_Click);
            this.txtOutDataset.EditValue = "";
            this.txtOutDataset.Location = new Point(104, 8);
            this.txtOutDataset.Name = "txtOutDataset";
            this.txtOutDataset.Size = new Size(184, 21);
            this.txtOutDataset.TabIndex = 2;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(8, 16);
            this.label4.Name = "label4";
            this.label4.Size = new Size(89, 12);
            this.label4.TabIndex = 0;
            this.label4.Text = "选择已有数据集";
            this.groupBox1.Controls.Add(this.btnAdd);
            this.groupBox1.Controls.Add(this.txtInputFeatureClass);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.btnDelete);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.SourceDatalistBox);
            this.groupBox1.Controls.Add(this.btnSelectInputFeatures);
            this.groupBox1.Location = new Point(8, 112);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(344, 280);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "导入数据";
            this.btnAdd.Enabled = false;
            this.btnAdd.Image = (Image) resources.GetObject("btnAdd.Image");
            this.btnAdd.Location = new Point(304, 104);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new Size(24, 24);
            this.btnAdd.TabIndex = 18;
            this.btnAdd.Click += new EventHandler(this.btnAdd_Click);
            this.txtInputFeatureClass.EditValue = "";
            this.txtInputFeatureClass.Location = new Point(8, 48);
            this.txtInputFeatureClass.Name = "txtInputFeatureClass";
            this.txtInputFeatureClass.Properties.Appearance.BackColor = SystemColors.InactiveBorder;
            this.txtInputFeatureClass.Properties.Appearance.Options.UseBackColor = true;
            this.txtInputFeatureClass.Properties.ReadOnly = true;
            this.txtInputFeatureClass.Size = new Size(288, 21);
            this.txtInputFeatureClass.TabIndex = 17;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 24);
            this.label3.Name = "label3";
            this.label3.Size = new Size(53, 12);
            this.label3.TabIndex = 16;
            this.label3.Text = "输入数据";
            this.btnDelete.Enabled = false;
            this.btnDelete.Image = (Image) resources.GetObject("btnDelete.Image");
            this.btnDelete.Location = new Point(304, 136);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new Size(24, 24);
            this.btnDelete.TabIndex = 15;
            this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(8, 80);
            this.label5.Name = "label5";
            this.label5.Size = new Size(65, 12);
            this.label5.TabIndex = 14;
            this.label5.Text = "源数据列表";
            this.SourceDatalistBox.ItemHeight = 17;
            this.SourceDatalistBox.Location = new Point(8, 104);
            this.SourceDatalistBox.Name = "SourceDatalistBox";
            this.SourceDatalistBox.SelectionMode = SelectionMode.MultiExtended;
            this.SourceDatalistBox.Size = new Size(288, 160);
            this.SourceDatalistBox.TabIndex = 13;
            this.SourceDatalistBox.SelectedIndexChanged += new EventHandler(this.SourceDatalistBox_SelectedIndexChanged);
            this.btnSelectInputFeatures.Image = (Image) resources.GetObject("btnSelectInputFeatures.Image");
            this.btnSelectInputFeatures.Location = new Point(304, 48);
            this.btnSelectInputFeatures.Name = "btnSelectInputFeatures";
            this.btnSelectInputFeatures.Size = new Size(24, 24);
            this.btnSelectInputFeatures.TabIndex = 12;
            this.btnSelectInputFeatures.Click += new EventHandler(this.btnSelectInputFeatures_Click);
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(296, 408);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(48, 24);
            this.btnCancel.TabIndex = 5;
            this.btnCancel.Text = "取消";
            this.btnOK.Location = new Point(216, 408);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(48, 24);
            this.btnOK.TabIndex = 4;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.lblProcess.Location = new Point(8, 400);
            this.lblProcess.Name = "lblProcess";
            this.lblProcess.Size = new Size(200, 24);
            this.lblProcess.TabIndex = 6;
            this.AutoScaleBaseSize = new Size(6, 14);
            base.ClientSize = new Size(360, 437);
            base.Controls.Add(this.lblProcess);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.radioGroup1);
            
            base.Name = "frmDatasetUnion";
            this.Text = "合并数据";
            this.radioGroup1.Properties.EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.rdoDatasetType.Properties.EndInit();
            this.txtDatasetName.Properties.EndInit();
            this.txtWorkspaceName.Properties.EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.txtOutDataset.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.txtInputFeatureClass.Properties.EndInit();
            ((ISupportInitialize) this.SourceDatalistBox).EndInit();
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnAdd;
        private SimpleButton btnCancel;
        private SimpleButton btnDelete;
        private SimpleButton btnOK;
        private SimpleButton btnSelectInputFeatures;
        private SimpleButton btnSelectOutDataset;
        private SimpleButton btnSelectWorkspace;
        private GroupBox groupBox1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label lblProcess;
        private Panel panel1;
        private Panel panel2;
        private RadioGroup radioGroup1;
        private RadioGroup rdoDatasetType;
        private ListBoxControl SourceDatalistBox;
        private TextEdit txtDatasetName;
        private TextEdit txtInputFeatureClass;
        private TextEdit txtOutDataset;
        private TextEdit txtWorkspaceName;
    }
}