using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.GISClient;

namespace Yutai.ArcGIS.Catalog.UI
{
    partial class frmNewArcGISServer
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.btnOK = new SimpleButton();
            this.btnCancel = new SimpleButton();
            this.groupBox2 = new GroupBox();
            this.chkSaveUserNameAndPsw = new CheckEdit();
            this.txtPassword = new TextEdit();
            this.txtUser = new TextEdit();
            this.label3 = new Label();
            this.label2 = new Label();
            this.txtServer = new TextEdit();
            this.lblServerInfo = new Label();
            this.panel1 = new Panel();
            this.label5 = new Label();
            this.panel2 = new Panel();
            this.chkUseDefaultFolder = new CheckEdit();
            this.groupBox1 = new GroupBox();
            this.chkSaveManage = new CheckEdit();
            this.txtPaswordMan = new TextEdit();
            this.txtUserManage = new TextEdit();
            this.label8 = new Label();
            this.label9 = new Label();
            this.btnSelect = new SimpleButton();
            this.cboServerType = new System.Windows.Forms.ComboBox();
            this.label7 = new Label();
            this.label6 = new Label();
            this.label4 = new Label();
            this.txtMUrl = new TextEdit();
            this.txtTempFolder = new TextEdit();
            this.label1 = new Label();
            this.radioGroup1 = new RadioGroup();
            this.groupBox2.SuspendLayout();
            this.chkSaveUserNameAndPsw.Properties.BeginInit();
            this.txtPassword.Properties.BeginInit();
            this.txtUser.Properties.BeginInit();
            this.txtServer.Properties.BeginInit();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.chkUseDefaultFolder.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.chkSaveManage.Properties.BeginInit();
            this.txtPaswordMan.Properties.BeginInit();
            this.txtUserManage.Properties.BeginInit();
            this.txtMUrl.Properties.BeginInit();
            this.txtTempFolder.Properties.BeginInit();
            this.radioGroup1.Properties.BeginInit();
            base.SuspendLayout();
            this.btnOK.Location = new Point(276, 345);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(60, 28);
            this.btnOK.TabIndex = 24;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(361, 345);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(60, 28);
            this.btnCancel.TabIndex = 23;
            this.btnCancel.Text = "取消";
            this.groupBox2.Controls.Add(this.chkSaveUserNameAndPsw);
            this.groupBox2.Controls.Add(this.txtPassword);
            this.groupBox2.Controls.Add(this.txtUser);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Location = new Point(7, 94);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(388, 116);
            this.groupBox2.TabIndex = 22;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "帐户";
            this.chkSaveUserNameAndPsw.EditValue = true;
            this.chkSaveUserNameAndPsw.Enabled = false;
            this.chkSaveUserNameAndPsw.Location = new Point(16, 88);
            this.chkSaveUserNameAndPsw.Name = "chkSaveUserNameAndPsw";
            this.chkSaveUserNameAndPsw.Properties.Caption = "保存用户名/密码";
            this.chkSaveUserNameAndPsw.Size = new Size(112, 19);
            this.chkSaveUserNameAndPsw.TabIndex = 4;
            this.txtPassword.EditValue = "";
            this.txtPassword.Location = new Point(68, 52);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new Size(304, 21);
            this.txtPassword.TabIndex = 3;
            this.txtUser.EditValue = "";
            this.txtUser.Location = new Point(68, 20);
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new Size(304, 21);
            this.txtUser.TabIndex = 2;
            this.txtUser.EditValueChanged += new EventHandler(this.txtUser_EditValueChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(16, 56);
            this.label3.Name = "label3";
            this.label3.Size = new Size(47, 12);
            this.label3.TabIndex = 1;
            this.label3.Text = "密  码:";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 24);
            this.label2.Name = "label2";
            this.label2.Size = new Size(47, 12);
            this.label2.TabIndex = 0;
            this.label2.Text = "用户名:";
            this.txtServer.EditValue = "http://";
            this.txtServer.Location = new Point(76, 17);
            this.txtServer.Name = "txtServer";
            this.txtServer.Size = new Size(319, 21);
            this.txtServer.TabIndex = 16;
            this.lblServerInfo.AutoSize = true;
            this.lblServerInfo.Location = new Point(5, 20);
            this.lblServerInfo.Name = "lblServerInfo";
            this.lblServerInfo.Size = new Size(65, 12);
            this.lblServerInfo.TabIndex = 12;
            this.lblServerInfo.Text = "服务器URL:";
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.txtServer);
            this.panel1.Controls.Add(this.groupBox2);
            this.panel1.Controls.Add(this.lblServerInfo);
            this.panel1.Location = new Point(12, 49);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(410, 230);
            this.panel1.TabIndex = 25;
            this.label5.AutoSize = true;
            this.label5.Location = new Point(74, 50);
            this.label5.Name = "label5";
            this.label5.Size = new Size(305, 12);
            this.label5.TabIndex = 23;
            this.label5.Text = "ArcGIS Server:http://myserver:6080/arcgis/services";
            this.panel2.Controls.Add(this.chkUseDefaultFolder);
            this.panel2.Controls.Add(this.groupBox1);
            this.panel2.Controls.Add(this.btnSelect);
            this.panel2.Controls.Add(this.cboServerType);
            this.panel2.Controls.Add(this.label7);
            this.panel2.Controls.Add(this.label6);
            this.panel2.Controls.Add(this.label4);
            this.panel2.Controls.Add(this.txtMUrl);
            this.panel2.Controls.Add(this.txtTempFolder);
            this.panel2.Controls.Add(this.label1);
            this.panel2.Location = new Point(12, 49);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(448, 290);
            this.panel2.TabIndex = 26;
            this.panel2.Visible = false;
            this.chkUseDefaultFolder.EditValue = true;
            this.chkUseDefaultFolder.Location = new Point(23, 140);
            this.chkUseDefaultFolder.Name = "chkUseDefaultFolder";
            this.chkUseDefaultFolder.Properties.Caption = "使用默认过渡文件夹";
            this.chkUseDefaultFolder.Size = new Size(138, 19);
            this.chkUseDefaultFolder.TabIndex = 29;
            this.chkUseDefaultFolder.CheckedChanged += new EventHandler(this.chkUseDefaultFolder_CheckedChanged);
            this.groupBox1.Controls.Add(this.chkSaveManage);
            this.groupBox1.Controls.Add(this.txtPaswordMan);
            this.groupBox1.Controls.Add(this.txtUserManage);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.label9);
            this.groupBox1.Location = new Point(25, 165);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(388, 116);
            this.groupBox1.TabIndex = 28;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "帐户";
            this.chkSaveManage.EditValue = true;
            this.chkSaveManage.Enabled = false;
            this.chkSaveManage.Location = new Point(16, 88);
            this.chkSaveManage.Name = "chkSaveManage";
            this.chkSaveManage.Properties.Caption = "保存用户名/密码";
            this.chkSaveManage.Size = new Size(112, 19);
            this.chkSaveManage.TabIndex = 4;
            this.txtPaswordMan.EditValue = "";
            this.txtPaswordMan.Location = new Point(68, 52);
            this.txtPaswordMan.Name = "txtPaswordMan";
            this.txtPaswordMan.Properties.PasswordChar = '*';
            this.txtPaswordMan.Size = new Size(304, 21);
            this.txtPaswordMan.TabIndex = 3;
            this.txtUserManage.EditValue = "";
            this.txtUserManage.Location = new Point(68, 20);
            this.txtUserManage.Name = "txtUserManage";
            this.txtUserManage.Size = new Size(304, 21);
            this.txtUserManage.TabIndex = 2;
            this.txtUserManage.EditValueChanged += new EventHandler(this.txtUserManage_EditValueChanged);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(16, 56);
            this.label8.Name = "label8";
            this.label8.Size = new Size(47, 12);
            this.label8.TabIndex = 1;
            this.label8.Text = "密  码:";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(16, 24);
            this.label9.Name = "label9";
            this.label9.Size = new Size(47, 12);
            this.label9.TabIndex = 0;
            this.label9.Text = "用户名:";
            this.btnSelect.Enabled = false;
            this.btnSelect.Location = new Point(368, 99);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new Size(31, 28);
            this.btnSelect.TabIndex = 27;
            this.btnSelect.Text = "...";
            this.cboServerType.FormattingEnabled = true;
            this.cboServerType.Items.AddRange(new object[] { "ArcGIS Server" });
            this.cboServerType.Location = new Point(96, 71);
            this.cboServerType.Name = "cboServerType";
            this.cboServerType.Size = new Size(303, 20);
            this.cboServerType.TabIndex = 26;
            this.cboServerType.Text = "ArcGIS Server";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(19, 74);
            this.label7.Name = "label7";
            this.label7.Size = new Size(71, 12);
            this.label7.TabIndex = 25;
            this.label7.Text = "服务器类型:";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(94, 34);
            this.label6.Name = "label6";
            this.label6.Size = new Size(251, 12);
            this.label6.TabIndex = 24;
            this.label6.Text = "ArcGIS Server:http://myserver:6080/arcgis";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(19, 15);
            this.label4.Name = "label4";
            this.label4.Size = new Size(65, 12);
            this.label4.TabIndex = 20;
            this.label4.Text = "服务器URL:";
            this.txtMUrl.EditValue = "http://";
            this.txtMUrl.Location = new Point(96, 10);
            this.txtMUrl.Name = "txtMUrl";
            this.txtMUrl.Size = new Size(303, 21);
            this.txtMUrl.TabIndex = 19;
            this.txtTempFolder.EditValue = "";
            this.txtTempFolder.Enabled = false;
            this.txtTempFolder.Location = new Point(96, 105);
            this.txtTempFolder.Name = "txtTempFolder";
            this.txtTempFolder.Size = new Size(266, 21);
            this.txtTempFolder.TabIndex = 18;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(19, 109);
            this.label1.Name = "label1";
            this.label1.Size = new Size(71, 12);
            this.label1.TabIndex = 13;
            this.label1.Text = "过渡文件夹:";
            this.radioGroup1.Location = new Point(12, 12);
            this.radioGroup1.Name = "radioGroup1";
            this.radioGroup1.Properties.Appearance.BackColor = SystemColors.Control;
            this.radioGroup1.Properties.Appearance.Options.UseBackColor = true;
            this.radioGroup1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.radioGroup1.Properties.Columns = 3;
            this.radioGroup1.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "使用GIS服务"), new RadioGroupItem(null, "管理GIS服务"), new RadioGroupItem(null, "发布GIS服务") });
            this.radioGroup1.Size = new Size(448, 31);
            this.radioGroup1.TabIndex = 27;
            this.radioGroup1.SelectedIndexChanged += new EventHandler(this.radioGroup1_SelectedIndexChanged);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(475, 385);
            base.Controls.Add(this.radioGroup1);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.btnCancel);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmNewArcGISServer";
            this.Text = "添加ArcGIS Server";
            base.Load += new EventHandler(this.frmNewArcGISServer_Load);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.chkSaveUserNameAndPsw.Properties.EndInit();
            this.txtPassword.Properties.EndInit();
            this.txtUser.Properties.EndInit();
            this.txtServer.Properties.EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.chkUseDefaultFolder.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.chkSaveManage.Properties.EndInit();
            this.txtPaswordMan.Properties.EndInit();
            this.txtUserManage.Properties.EndInit();
            this.txtMUrl.Properties.EndInit();
            this.txtTempFolder.Properties.EndInit();
            this.radioGroup1.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private bool bool_0;
        private SimpleButton btnCancel;
        private SimpleButton btnOK;
        private SimpleButton btnSelect;
        private System.Windows.Forms.ComboBox cboServerType;
        private CheckEdit chkSaveManage;
        private CheckEdit chkSaveUserNameAndPsw;
        private CheckEdit chkUseDefaultFolder;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private IAGSServerConnection iagsserverConnection_0;
        private IMapDescription imapDescription_0;
        private IMapServer imapServer_0;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label lblServerInfo;
        private Panel panel1;
        private Panel panel2;
        private RadioGroup radioGroup1;
        private string string_0;
        private string string_1;
        private TextEdit txtMUrl;
        private TextEdit txtPassword;
        private TextEdit txtPaswordMan;
        private TextEdit txtServer;
        private TextEdit txtTempFolder;
        private TextEdit txtUser;
        private TextEdit txtUserManage;
    }
}