using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Text;
using System.Resources;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Carto;
using ESRI.ArcGIS.Display;
using ESRI.ArcGIS.Geodatabase;

namespace Yutai.ArcGIS.Catalog.Geodatabase.UI
{
    partial class AnnoClassSetCtrl
    {
        protected override void Dispose(bool bool_0)
        {
            if (bool_0 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_0);
        }

       
        private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
           System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AnnoClassSetCtrl));
            this.label1 = new Label();
            this.listBoxControl1 = new ListBoxControl();
            this.btnNew = new SimpleButton();
            this.btnDelete = new SimpleButton();
            this.btnReName = new SimpleButton();
            this.imageList_0 = new ImageList(this.icontainer_0);
            this.imageList_1 = new ImageList(this.icontainer_0);
            this.panel1 = new Panel();
            this.groupBox1 = new GroupBox();
            this.simpleButton2 = new SimpleButton();
            this.simpleButton1 = new SimpleButton();
            this.cboFontSize = new ComboBoxEdit();
            this.colorEdit1 = new ColorEdit();
            this.chkUnderline = new CheckBox();
            this.chkItalic = new CheckBox();
            this.chkBold = new CheckBox();
            this.cboFontName = new System.Windows.Forms.ComboBox();
            this.gropScaleset = new GroupBox();
            this.panelScaleSet = new Panel();
            this.txtMaxScale = new TextEdit();
            this.txtMinScale = new TextEdit();
            this.label3 = new Label();
            this.label2 = new Label();
            this.rdoDisplayScale = new RadioGroup();
            this.panel2 = new Panel();
            this.btnLabelExpress = new SimpleButton();
            this.cboLabelField = new ComboBoxEdit();
            this.label5 = new Label();
            this.groupBox2 = new GroupBox();
            this.simpleButton3 = new SimpleButton();
            this.simpleButton4 = new SimpleButton();
            this.cboFontSize_rel = new ComboBoxEdit();
            this.colorEdit2 = new ColorEdit();
            this.chkUnderLine_rel = new CheckBox();
            this.chkIta_rel = new CheckBox();
            this.chkBold_rel = new CheckBox();
            this.cboFontName_rel = new System.Windows.Forms.ComboBox();
            this.groupPlaceSet = new GroupBox();
            this.chkCanPalceOuter = new CheckEdit();
            this.chkOverPlace = new CheckEdit();
            this.chkHorPlace = new CheckEdit();
            this.label6 = new Label();
            this.imageComboBoxEdit1 = new ImageComboBoxEdit();
            this.textEdit1 = new TextEdit();
            this.label4 = new Label();
            ((ISupportInitialize) this.listBoxControl1).BeginInit();
            this.panel1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.cboFontSize.Properties.BeginInit();
            this.colorEdit1.Properties.BeginInit();
            this.gropScaleset.SuspendLayout();
            this.panelScaleSet.SuspendLayout();
            this.txtMaxScale.Properties.BeginInit();
            this.txtMinScale.Properties.BeginInit();
            this.rdoDisplayScale.Properties.BeginInit();
            this.panel2.SuspendLayout();
            this.cboLabelField.Properties.BeginInit();
            this.groupBox2.SuspendLayout();
            this.cboFontSize_rel.Properties.BeginInit();
            this.colorEdit2.Properties.BeginInit();
            this.groupPlaceSet.SuspendLayout();
            this.chkCanPalceOuter.Properties.BeginInit();
            this.chkOverPlace.Properties.BeginInit();
            this.chkHorPlace.Properties.BeginInit();
            this.imageComboBoxEdit1.Properties.BeginInit();
            this.textEdit1.Properties.BeginInit();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(8, 8);
            this.label1.Name = "label1";
            this.label1.Size = new Size(42, 17);
            this.label1.TabIndex = 0;
            this.label1.Text = "注记类";
            this.listBoxControl1.ItemHeight = 17;
            this.listBoxControl1.Location = new Point(8, 32);
            this.listBoxControl1.Name = "listBoxControl1";
            this.listBoxControl1.Size = new Size(304, 112);
            this.listBoxControl1.TabIndex = 1;
            this.listBoxControl1.SelectedIndexChanged += new EventHandler(this.listBoxControl1_SelectedIndexChanged);
            this.btnNew.Location = new Point(336, 40);
            this.btnNew.Name = "btnNew";
            this.btnNew.Size = new Size(48, 24);
            this.btnNew.TabIndex = 2;
            this.btnNew.Text = "新建";
            this.btnNew.Click += new EventHandler(this.btnNew_Click);
            this.btnDelete.Location = new Point(336, 72);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new Size(48, 24);
            this.btnDelete.TabIndex = 3;
            this.btnDelete.Text = "删除";
            this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
            this.btnReName.Location = new Point(336, 104);
            this.btnReName.Name = "btnReName";
            this.btnReName.Size = new Size(48, 24);
            this.btnReName.TabIndex = 4;
            this.btnReName.Text = "重命名";
            this.btnReName.Click += new EventHandler(this.btnReName_Click);
            this.imageList_0.ImageSize = new Size(16, 16);
            this.imageList_0.ImageStream = (ImageListStreamer) resources.GetObject("imageList1.ImageStream");
            this.imageList_0.TransparentColor = Color.Magenta;
            this.imageList_1.ImageSize = new Size(81, 58);
            this.imageList_1.ImageStream = (ImageListStreamer) resources.GetObject("imageList2.ImageStream");
            this.imageList_1.TransparentColor = Color.Transparent;
            this.panel1.Controls.Add(this.groupBox1);
            this.panel1.Controls.Add(this.gropScaleset);
            this.panel1.Location = new Point(8, 152);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(384, 264);
            this.panel1.TabIndex = 8;
            this.groupBox1.Controls.Add(this.simpleButton2);
            this.groupBox1.Controls.Add(this.simpleButton1);
            this.groupBox1.Controls.Add(this.cboFontSize);
            this.groupBox1.Controls.Add(this.colorEdit1);
            this.groupBox1.Controls.Add(this.chkUnderline);
            this.groupBox1.Controls.Add(this.chkItalic);
            this.groupBox1.Controls.Add(this.chkBold);
            this.groupBox1.Controls.Add(this.cboFontName);
            this.groupBox1.Location = new Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(384, 88);
            this.groupBox1.TabIndex = 8;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "文本符号";
            this.simpleButton2.Location = new Point(328, 48);
            this.simpleButton2.Name = "simpleButton2";
            this.simpleButton2.Size = new Size(48, 24);
            this.simpleButton2.TabIndex = 16;
            this.simpleButton2.Text = "引导线";
            this.simpleButton1.Location = new Point(272, 48);
            this.simpleButton1.Name = "simpleButton1";
            this.simpleButton1.Size = new Size(48, 24);
            this.simpleButton1.TabIndex = 15;
            this.simpleButton1.Text = "符号";
            this.cboFontSize.EditValue = "5";
            this.cboFontSize.Location = new Point(312, 16);
            this.cboFontSize.Name = "cboFontSize";
            this.cboFontSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboFontSize.Properties.Items.AddRange(new object[] { 
                "5", "6", "7", "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", 
                "34", "36", "48", "72"
             });
            this.cboFontSize.Size = new Size(64, 23);
            this.cboFontSize.TabIndex = 14;
            this.cboFontSize.SelectedIndexChanged += new EventHandler(this.cboFontSize_SelectedIndexChanged);
            this.colorEdit1.EditValue = Color.Empty;
            this.colorEdit1.Location = new Point(120, 48);
            this.colorEdit1.Name = "colorEdit1";
            this.colorEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit1.Size = new Size(48, 23);
            this.colorEdit1.TabIndex = 13;
            this.colorEdit1.EditValueChanged += new EventHandler(this.colorEdit1_EditValueChanged);
            this.chkUnderline.Appearance = Appearance.Button;
            this.chkUnderline.ImageIndex = 2;
            this.chkUnderline.ImageList = this.imageList_0;
            this.chkUnderline.Location = new Point(240, 48);
            this.chkUnderline.Name = "chkUnderline";
            this.chkUnderline.Size = new Size(28, 24);
            this.chkUnderline.TabIndex = 7;
            this.chkUnderline.CheckedChanged += new EventHandler(this.chkUnderline_CheckedChanged);
            this.chkItalic.Appearance = Appearance.Button;
            this.chkItalic.ImageIndex = 1;
            this.chkItalic.ImageList = this.imageList_0;
            this.chkItalic.Location = new Point(208, 48);
            this.chkItalic.Name = "chkItalic";
            this.chkItalic.Size = new Size(28, 24);
            this.chkItalic.TabIndex = 6;
            this.chkItalic.CheckedChanged += new EventHandler(this.chkItalic_CheckedChanged);
            this.chkBold.Appearance = Appearance.Button;
            this.chkBold.ImageIndex = 0;
            this.chkBold.ImageList = this.imageList_0;
            this.chkBold.Location = new Point(176, 48);
            this.chkBold.Name = "chkBold";
            this.chkBold.Size = new Size(28, 24);
            this.chkBold.TabIndex = 5;
            this.chkBold.CheckedChanged += new EventHandler(this.chkBold_CheckedChanged);
            this.cboFontName.Location = new Point(120, 16);
            this.cboFontName.Name = "cboFontName";
            this.cboFontName.Size = new Size(184, 20);
            this.cboFontName.TabIndex = 2;
            this.cboFontName.SelectedIndexChanged += new EventHandler(this.cboFontName_SelectedIndexChanged);
            this.gropScaleset.Controls.Add(this.panelScaleSet);
            this.gropScaleset.Controls.Add(this.rdoDisplayScale);
            this.gropScaleset.Location = new Point(0, 96);
            this.gropScaleset.Name = "gropScaleset";
            this.gropScaleset.Size = new Size(384, 160);
            this.gropScaleset.TabIndex = 7;
            this.gropScaleset.TabStop = false;
            this.gropScaleset.Text = "比例范围";
            this.panelScaleSet.Controls.Add(this.txtMaxScale);
            this.panelScaleSet.Controls.Add(this.txtMinScale);
            this.panelScaleSet.Controls.Add(this.label3);
            this.panelScaleSet.Controls.Add(this.label2);
            this.panelScaleSet.Location = new Point(8, 80);
            this.panelScaleSet.Name = "panelScaleSet";
            this.panelScaleSet.Size = new Size(368, 72);
            this.panelScaleSet.TabIndex = 5;
            this.txtMaxScale.EditValue = "";
            this.txtMaxScale.Location = new Point(80, 41);
            this.txtMaxScale.Name = "txtMaxScale";
            this.txtMaxScale.Size = new Size(240, 23);
            this.txtMaxScale.TabIndex = 8;
            this.txtMaxScale.EditValueChanged += new EventHandler(this.txtMaxScale_EditValueChanged);
            this.txtMinScale.EditValue = "";
            this.txtMinScale.Location = new Point(80, 9);
            this.txtMinScale.Name = "txtMinScale";
            this.txtMinScale.Size = new Size(240, 23);
            this.txtMinScale.TabIndex = 7;
            this.txtMinScale.EditValueChanged += new EventHandler(this.txtMinScale_EditValueChanged);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(0, 41);
            this.label3.Name = "label3";
            this.label3.Size = new Size(66, 17);
            this.label3.TabIndex = 6;
            this.label3.Text = "放大超过1:";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(0, 9);
            this.label2.Name = "label2";
            this.label2.Size = new Size(66, 17);
            this.label2.TabIndex = 5;
            this.label2.Text = "缩小超过1:";
            this.rdoDisplayScale.Location = new Point(8, 24);
            this.rdoDisplayScale.Name = "rdoDisplayScale";
            this.rdoDisplayScale.Properties.Appearance.BackColor = SystemColors.InactiveBorder;
            this.rdoDisplayScale.Properties.Appearance.Options.UseBackColor = true;
            this.rdoDisplayScale.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoDisplayScale.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "在所有比例尺下都显示"), new RadioGroupItem(null, "不显示注记，当") });
            this.rdoDisplayScale.Size = new Size(168, 48);
            this.rdoDisplayScale.TabIndex = 0;
            this.rdoDisplayScale.SelectedIndexChanged += new EventHandler(this.rdoDisplayScale_SelectedIndexChanged);
            this.panel2.Controls.Add(this.btnLabelExpress);
            this.panel2.Controls.Add(this.cboLabelField);
            this.panel2.Controls.Add(this.label5);
            this.panel2.Controls.Add(this.groupBox2);
            this.panel2.Controls.Add(this.groupPlaceSet);
            this.panel2.Location = new Point(8, 144);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(408, 296);
            this.panel2.TabIndex = 9;
            this.btnLabelExpress.Location = new Point(304, 8);
            this.btnLabelExpress.Name = "btnLabelExpress";
            this.btnLabelExpress.Size = new Size(72, 24);
            this.btnLabelExpress.TabIndex = 16;
            this.btnLabelExpress.Text = "表达式";
            this.btnLabelExpress.Click += new EventHandler(this.btnLabelExpress_Click);
            this.cboLabelField.EditValue = "";
            this.cboLabelField.Location = new Point(80, 8);
            this.cboLabelField.Name = "cboLabelField";
            this.cboLabelField.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboLabelField.Size = new Size(200, 23);
            this.cboLabelField.TabIndex = 11;
            this.cboLabelField.SelectedIndexChanged += new EventHandler(this.cboLabelField_SelectedIndexChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(0, 16);
            this.label5.Name = "label5";
            this.label5.Size = new Size(54, 17);
            this.label5.TabIndex = 10;
            this.label5.Text = "标注字段";
            this.groupBox2.Controls.Add(this.simpleButton3);
            this.groupBox2.Controls.Add(this.simpleButton4);
            this.groupBox2.Controls.Add(this.cboFontSize_rel);
            this.groupBox2.Controls.Add(this.colorEdit2);
            this.groupBox2.Controls.Add(this.chkUnderLine_rel);
            this.groupBox2.Controls.Add(this.chkIta_rel);
            this.groupBox2.Controls.Add(this.chkBold_rel);
            this.groupBox2.Controls.Add(this.cboFontName_rel);
            this.groupBox2.Location = new Point(0, 36);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(384, 84);
            this.groupBox2.TabIndex = 9;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "文本符号";
            this.simpleButton3.Location = new Point(328, 48);
            this.simpleButton3.Name = "simpleButton3";
            this.simpleButton3.Size = new Size(48, 24);
            this.simpleButton3.TabIndex = 16;
            this.simpleButton3.Text = "引导线";
            this.simpleButton3.Visible = false;
            this.simpleButton4.Location = new Point(272, 48);
            this.simpleButton4.Name = "simpleButton4";
            this.simpleButton4.Size = new Size(48, 24);
            this.simpleButton4.TabIndex = 15;
            this.simpleButton4.Text = "符号";
            this.simpleButton4.Visible = false;
            this.cboFontSize_rel.EditValue = "5";
            this.cboFontSize_rel.Location = new Point(312, 16);
            this.cboFontSize_rel.Name = "cboFontSize_rel";
            this.cboFontSize_rel.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboFontSize_rel.Properties.Items.AddRange(new object[] { 
                "5", "6", "7", "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", 
                "34", "36", "48", "72"
             });
            this.cboFontSize_rel.Size = new Size(64, 23);
            this.cboFontSize_rel.TabIndex = 14;
            this.cboFontSize_rel.SelectedIndexChanged += new EventHandler(this.cboFontSize_rel_SelectedIndexChanged);
            this.colorEdit2.EditValue = Color.Empty;
            this.colorEdit2.Location = new Point(120, 48);
            this.colorEdit2.Name = "colorEdit2";
            this.colorEdit2.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.colorEdit2.Size = new Size(48, 23);
            this.colorEdit2.TabIndex = 13;
            this.colorEdit2.EditValueChanged += new EventHandler(this.colorEdit2_EditValueChanged);
            this.chkUnderLine_rel.Appearance = Appearance.Button;
            this.chkUnderLine_rel.ImageIndex = 2;
            this.chkUnderLine_rel.ImageList = this.imageList_0;
            this.chkUnderLine_rel.Location = new Point(240, 48);
            this.chkUnderLine_rel.Name = "chkUnderLine_rel";
            this.chkUnderLine_rel.Size = new Size(28, 24);
            this.chkUnderLine_rel.TabIndex = 7;
            this.chkUnderLine_rel.CheckedChanged += new EventHandler(this.chkUnderLine_rel_CheckedChanged);
            this.chkIta_rel.Appearance = Appearance.Button;
            this.chkIta_rel.ImageIndex = 1;
            this.chkIta_rel.ImageList = this.imageList_0;
            this.chkIta_rel.Location = new Point(208, 48);
            this.chkIta_rel.Name = "chkIta_rel";
            this.chkIta_rel.Size = new Size(28, 24);
            this.chkIta_rel.TabIndex = 6;
            this.chkIta_rel.CheckedChanged += new EventHandler(this.chkIta_rel_CheckedChanged);
            this.chkBold_rel.Appearance = Appearance.Button;
            this.chkBold_rel.ImageIndex = 0;
            this.chkBold_rel.ImageList = this.imageList_0;
            this.chkBold_rel.Location = new Point(176, 48);
            this.chkBold_rel.Name = "chkBold_rel";
            this.chkBold_rel.Size = new Size(28, 24);
            this.chkBold_rel.TabIndex = 5;
            this.chkBold_rel.CheckedChanged += new EventHandler(this.chkBold_rel_CheckedChanged);
            this.cboFontName_rel.Location = new Point(120, 16);
            this.cboFontName_rel.Name = "cboFontName_rel";
            this.cboFontName_rel.Size = new Size(184, 20);
            this.cboFontName_rel.TabIndex = 2;
            this.cboFontName_rel.SelectedIndexChanged += new EventHandler(this.cboFontName_rel_SelectedIndexChanged);
            this.groupPlaceSet.Controls.Add(this.chkCanPalceOuter);
            this.groupPlaceSet.Controls.Add(this.chkOverPlace);
            this.groupPlaceSet.Controls.Add(this.chkHorPlace);
            this.groupPlaceSet.Controls.Add(this.label6);
            this.groupPlaceSet.Controls.Add(this.imageComboBoxEdit1);
            this.groupPlaceSet.Controls.Add(this.textEdit1);
            this.groupPlaceSet.Controls.Add(this.label4);
            this.groupPlaceSet.Location = new Point(0, 128);
            this.groupPlaceSet.Name = "groupPlaceSet";
            this.groupPlaceSet.Size = new Size(384, 136);
            this.groupPlaceSet.TabIndex = 8;
            this.groupPlaceSet.TabStop = false;
            this.groupPlaceSet.Text = "放置属性";
            this.chkCanPalceOuter.Location = new Point(128, 48);
            this.chkCanPalceOuter.Name = "chkCanPalceOuter";
            this.chkCanPalceOuter.Properties.Caption = "可以在外部放置标注";
            this.chkCanPalceOuter.Size = new Size(136, 19);
            this.chkCanPalceOuter.TabIndex = 9;
            this.chkOverPlace.Location = new Point(132, 72);
            this.chkOverPlace.Name = "chkOverPlace";
            this.chkOverPlace.Properties.Caption = "堆叠标注";
            this.chkOverPlace.Size = new Size(120, 19);
            this.chkOverPlace.TabIndex = 8;
            this.chkHorPlace.Location = new Point(128, 24);
            this.chkHorPlace.Name = "chkHorPlace";
            this.chkHorPlace.Properties.Caption = "首先尽量水平";
            this.chkHorPlace.Size = new Size(120, 19);
            this.chkHorPlace.TabIndex = 7;
            this.label6.AutoSize = true;
            this.label6.Location = new Point(16, 16);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 17);
            this.label6.TabIndex = 6;
            this.label6.Text = "位置";
            this.imageComboBoxEdit1.EditValue = 0;
            this.imageComboBoxEdit1.Location = new Point(16, 40);
            this.imageComboBoxEdit1.Name = "imageComboBoxEdit1";
            this.imageComboBoxEdit1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.imageComboBoxEdit1.Properties.Items.AddRange(new object[] { new ImageComboBoxItem("水平", 0, 0), new ImageComboBoxItem("平直", 1, 1), new ImageComboBoxItem("弯曲", 2, 2), new ImageComboBoxItem("水平偏移", 3, 3), new ImageComboBoxItem("边界", 4, 4) });
            this.imageComboBoxEdit1.Properties.LargeImages = this.imageList_1;
            this.imageComboBoxEdit1.Size = new Size(104, 62);
            this.imageComboBoxEdit1.TabIndex = 5;
            this.textEdit1.EditValue = "";
            this.textEdit1.Location = new Point(136, 104);
            this.textEdit1.Name = "textEdit1";
            this.textEdit1.Size = new Size(136, 23);
            this.textEdit1.TabIndex = 4;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(88, 112);
            this.label4.Name = "label4";
            this.label4.Size = new Size(35, 17);
            this.label4.TabIndex = 2;
            this.label4.Text = "偏移:";
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.btnReName);
            base.Controls.Add(this.btnDelete);
            base.Controls.Add(this.btnNew);
            base.Controls.Add(this.listBoxControl1);
            base.Controls.Add(this.label1);
            base.Name = "AnnoClassSetCtrl";
            base.Size = new Size(456, 456);
            base.Load += new EventHandler(this.AnnoClassSetCtrl_Load);
            ((ISupportInitialize) this.listBoxControl1).EndInit();
            this.panel1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.cboFontSize.Properties.EndInit();
            this.colorEdit1.Properties.EndInit();
            this.gropScaleset.ResumeLayout(false);
            this.panelScaleSet.ResumeLayout(false);
            this.txtMaxScale.Properties.EndInit();
            this.txtMinScale.Properties.EndInit();
            this.rdoDisplayScale.Properties.EndInit();
            this.panel2.ResumeLayout(false);
            this.cboLabelField.Properties.EndInit();
            this.groupBox2.ResumeLayout(false);
            this.cboFontSize_rel.Properties.EndInit();
            this.colorEdit2.Properties.EndInit();
            this.groupPlaceSet.ResumeLayout(false);
            this.chkCanPalceOuter.Properties.EndInit();
            this.chkOverPlace.Properties.EndInit();
            this.chkHorPlace.Properties.EndInit();
            this.imageComboBoxEdit1.Properties.EndInit();
            this.textEdit1.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnDelete;
        private SimpleButton btnLabelExpress;
        private SimpleButton btnNew;
        private SimpleButton btnReName;
        private System.Windows.Forms.ComboBox cboFontName;
        private System.Windows.Forms.ComboBox cboFontName_rel;
        private ComboBoxEdit cboFontSize;
        private ComboBoxEdit cboFontSize_rel;
        private ComboBoxEdit cboLabelField;
        private CheckBox chkBold;
        private CheckBox chkBold_rel;
        private CheckEdit chkCanPalceOuter;
        private CheckEdit chkHorPlace;
        private CheckBox chkIta_rel;
        private CheckBox chkItalic;
        private CheckEdit chkOverPlace;
        private CheckBox chkUnderline;
        private CheckBox chkUnderLine_rel;
        private ColorEdit colorEdit1;
        private ColorEdit colorEdit2;
        private GroupBox gropScaleset;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupPlaceSet;
        private IContainer icontainer_0;
        private ImageComboBoxEdit imageComboBoxEdit1;
        private ImageList imageList_0;
        private ImageList imageList_1;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private ListBoxControl listBoxControl1;
        private Panel panel1;
        private Panel panel2;
        private Panel panelScaleSet;
        private RadioGroup rdoDisplayScale;
        private SimpleButton simpleButton1;
        private SimpleButton simpleButton2;
        private SimpleButton simpleButton3;
        private SimpleButton simpleButton4;
        private TextEdit textEdit1;
        private TextEdit txtMaxScale;
        private TextEdit txtMinScale;
    }
}