using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Resources;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geodatabase;
using ESRI.ArcGIS.GeoDatabaseDistributed;
using Yutai.ArcGIS.Catalog.UI;

namespace Yutai.ArcGIS.Catalog.Geodatabase.UI
{
    partial class CheckInSetupCtrl
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
           System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CheckInSetupCtrl));
            this.panel_by_MasterGDB = new Panel();
            this.groupBox1 = new GroupBox();
            this.panel2 = new Panel();
            this.btnSelectDelta = new SimpleButton();
            this.txtDelta = new TextEdit();
            this.panel1 = new Panel();
            this.btnSelectGDB = new SimpleButton();
            this.txtGDB = new TextEdit();
            this.radioGroup1 = new RadioGroup();
            this.chkReconcile = new CheckEdit();
            this.lblCheckInGDB = new Label();
            this.label4 = new Label();
            this.lblCheckOutName = new Label();
            this.label1 = new Label();
            this.panelbycheckoutdb = new Panel();
            this.lblCheckInGDB2 = new Label();
            this.label8 = new Label();
            this.chkReconcile2 = new CheckEdit();
            this.lblMasterGDB2 = new Label();
            this.label3 = new Label();
            this.lblCheckOutName1 = new Label();
            this.label6 = new Label();
            this.panel_by_MasterGDB.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.txtDelta.Properties.BeginInit();
            this.panel1.SuspendLayout();
            this.txtGDB.Properties.BeginInit();
            this.radioGroup1.Properties.BeginInit();
            this.chkReconcile.Properties.BeginInit();
            this.panelbycheckoutdb.SuspendLayout();
            this.chkReconcile2.Properties.BeginInit();
            base.SuspendLayout();
            this.panel_by_MasterGDB.Controls.Add(this.groupBox1);
            this.panel_by_MasterGDB.Controls.Add(this.chkReconcile);
            this.panel_by_MasterGDB.Controls.Add(this.lblCheckInGDB);
            this.panel_by_MasterGDB.Controls.Add(this.label4);
            this.panel_by_MasterGDB.Controls.Add(this.lblCheckOutName);
            this.panel_by_MasterGDB.Controls.Add(this.label1);
            this.panel_by_MasterGDB.Location = new Point(8, 8);
            this.panel_by_MasterGDB.Name = "panel_by_MasterGDB";
            this.panel_by_MasterGDB.Size = new Size(376, 264);
            this.panel_by_MasterGDB.TabIndex = 6;
            this.groupBox1.Controls.Add(this.panel2);
            this.groupBox1.Controls.Add(this.panel1);
            this.groupBox1.Controls.Add(this.radioGroup1);
            this.groupBox1.Location = new Point(0, 8);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(360, 136);
            this.groupBox1.TabIndex = 11;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "选择检入数据";
            this.panel2.Controls.Add(this.btnSelectDelta);
            this.panel2.Controls.Add(this.txtDelta);
            this.panel2.Enabled = false;
            this.panel2.Location = new Point(28, 88);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(304, 32);
            this.panel2.TabIndex = 3;
            this.btnSelectDelta.Image = (Image) resources.GetObject("btnSelectDelta.Image");
            this.btnSelectDelta.Location = new Point(272, 6);
            this.btnSelectDelta.Name = "btnSelectDelta";
            this.btnSelectDelta.Size = new Size(24, 24);
            this.btnSelectDelta.TabIndex = 10;
            this.btnSelectDelta.Click += new EventHandler(this.btnSelectDelta_Click);
            this.txtDelta.EditValue = "";
            this.txtDelta.Location = new Point(16, 6);
            this.txtDelta.Name = "txtDelta";
            this.txtDelta.Properties.ReadOnly = true;
            this.txtDelta.Size = new Size(224, 23);
            this.txtDelta.TabIndex = 0;
            this.panel1.Controls.Add(this.btnSelectGDB);
            this.panel1.Controls.Add(this.txtGDB);
            this.panel1.Enabled = false;
            this.panel1.Location = new Point(24, 32);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(304, 32);
            this.panel1.TabIndex = 2;
            this.btnSelectGDB.Image = (Image) resources.GetObject("btnSelectGDB.Image");
            this.btnSelectGDB.Location = new Point(272, 6);
            this.btnSelectGDB.Name = "btnSelectGDB";
            this.btnSelectGDB.Size = new Size(24, 24);
            this.btnSelectGDB.TabIndex = 10;
            this.btnSelectGDB.Click += new EventHandler(this.btnSelectGDB_Click);
            this.txtGDB.EditValue = "";
            this.txtGDB.Location = new Point(16, 6);
            this.txtGDB.Name = "txtGDB";
            this.txtGDB.Properties.ReadOnly = true;
            this.txtGDB.Size = new Size(224, 23);
            this.txtGDB.TabIndex = 0;
            this.radioGroup1.Location = new Point(8, -8);
            this.radioGroup1.Name = "radioGroup1";
            this.radioGroup1.Properties.Appearance.BackColor = Color.Transparent;
            this.radioGroup1.Properties.Appearance.Options.UseBackColor = true;
            this.radioGroup1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.radioGroup1.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "空间数据库"), new RadioGroupItem(null, "增量数据库或增量xml文件") });
            this.radioGroup1.Size = new Size(264, 112);
            this.radioGroup1.TabIndex = 0;
            this.radioGroup1.SelectedIndexChanged += new EventHandler(this.radioGroup1_SelectedIndexChanged);
            this.chkReconcile.Location = new Point(0, 224);
            this.chkReconcile.Name = "chkReconcile";
            this.chkReconcile.Properties.Caption = "与父版本协调和提交";
            this.chkReconcile.Size = new Size(144, 19);
            this.chkReconcile.TabIndex = 10;
            this.lblCheckInGDB.AutoSize = true;
            this.lblCheckInGDB.Location = new Point(72, 192);
            this.lblCheckInGDB.Name = "lblCheckInGDB";
            this.lblCheckInGDB.Size = new Size(0, 17);
            this.lblCheckInGDB.TabIndex = 9;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(0, 192);
            this.label4.Name = "label4";
            this.label4.Size = new Size(72, 17);
            this.label4.TabIndex = 8;
            this.label4.Text = "目的数据库:";
            this.lblCheckOutName.AutoSize = true;
            this.lblCheckOutName.Location = new Point(72, 160);
            this.lblCheckOutName.Name = "lblCheckOutName";
            this.lblCheckOutName.Size = new Size(0, 17);
            this.lblCheckOutName.TabIndex = 7;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(0, 160);
            this.label1.Name = "label1";
            this.label1.Size = new Size(60, 17);
            this.label1.TabIndex = 6;
            this.label1.Text = "检出名字:";
            this.panelbycheckoutdb.Controls.Add(this.lblCheckInGDB2);
            this.panelbycheckoutdb.Controls.Add(this.label8);
            this.panelbycheckoutdb.Controls.Add(this.chkReconcile2);
            this.panelbycheckoutdb.Controls.Add(this.lblMasterGDB2);
            this.panelbycheckoutdb.Controls.Add(this.label3);
            this.panelbycheckoutdb.Controls.Add(this.lblCheckOutName1);
            this.panelbycheckoutdb.Controls.Add(this.label6);
            this.panelbycheckoutdb.Location = new Point(8, 8);
            this.panelbycheckoutdb.Name = "panelbycheckoutdb";
            this.panelbycheckoutdb.Size = new Size(376, 176);
            this.panelbycheckoutdb.TabIndex = 7;
            this.panelbycheckoutdb.Visible = false;
            this.lblCheckInGDB2.AutoSize = true;
            this.lblCheckInGDB2.Location = new Point(120, 24);
            this.lblCheckInGDB2.Name = "lblCheckInGDB2";
            this.lblCheckInGDB2.Size = new Size(0, 17);
            this.lblCheckInGDB2.TabIndex = 17;
            this.lblCheckInGDB2.Tag = "";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(16, 24);
            this.label8.Name = "label8";
            this.label8.Size = new Size(97, 17);
            this.label8.TabIndex = 16;
            this.label8.Text = "要检入的数据库:";
            this.chkReconcile2.Location = new Point(16, 136);
            this.chkReconcile2.Name = "chkReconcile2";
            this.chkReconcile2.Properties.Caption = "与父版本协调和提交";
            this.chkReconcile2.Size = new Size(144, 19);
            this.chkReconcile2.TabIndex = 15;
            this.lblMasterGDB2.AutoSize = true;
            this.lblMasterGDB2.Location = new Point(120, 104);
            this.lblMasterGDB2.Name = "lblMasterGDB2";
            this.lblMasterGDB2.Size = new Size(0, 17);
            this.lblMasterGDB2.TabIndex = 14;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(16, 104);
            this.label3.Name = "label3";
            this.label3.Size = new Size(72, 17);
            this.label3.TabIndex = 13;
            this.label3.Text = "目的数据库:";
            this.lblCheckOutName1.AutoSize = true;
            this.lblCheckOutName1.Location = new Point(120, 64);
            this.lblCheckOutName1.Name = "lblCheckOutName1";
            this.lblCheckOutName1.Size = new Size(0, 17);
            this.lblCheckOutName1.TabIndex = 12;
            this.label6.AutoSize = true;
            this.label6.Location = new Point(16, 64);
            this.label6.Name = "label6";
            this.label6.Size = new Size(60, 17);
            this.label6.TabIndex = 11;
            this.label6.Text = "检出名字:";
            base.Controls.Add(this.panelbycheckoutdb);
            base.Controls.Add(this.panel_by_MasterGDB);
            base.Name = "CheckInSetupCtrl";
            base.Size = new Size(400, 288);
            base.Load += new EventHandler(this.CheckInSetupCtrl_Load);
            this.panel_by_MasterGDB.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.txtDelta.Properties.EndInit();
            this.panel1.ResumeLayout(false);
            this.txtGDB.Properties.EndInit();
            this.radioGroup1.Properties.EndInit();
            this.chkReconcile.Properties.EndInit();
            this.panelbycheckoutdb.ResumeLayout(false);
            this.chkReconcile2.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnSelectDelta;
        private SimpleButton btnSelectGDB;
        private CheckEdit chkReconcile;
        private CheckEdit chkReconcile2;
        private GroupBox groupBox1;
        private Label label1;
        private Label label3;
        private Label label4;
        private Label label6;
        private Label label8;
        private Label lblCheckInGDB;
        private Label lblCheckInGDB2;
        private Label lblCheckOutName;
        private Label lblCheckOutName1;
        private Label lblMasterGDB2;
        private Panel panel_by_MasterGDB;
        private Panel panel1;
        private Panel panel2;
        private Panel panelbycheckoutdb;
        private RadioGroup radioGroup1;
        private TextEdit txtDelta;
        private TextEdit txtGDB;
    }
}