using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.DataSourcesGDB;
using ESRI.ArcGIS.esriSystem;
using ESRI.ArcGIS.Geodatabase;
using Yutai.Shared;

namespace Yutai.ArcGIS.Catalog.Geodatabase.UI
{
    partial class frmAddGDBConnection
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAddGDBConnection));
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.groupBox2 = new GroupBox();
            this.btnChangeVersion = new SimpleButton();
            this.chkSaveVersion = new CheckEdit();
            this.lblVersion = new Label();
            this.txtServer = new TextEdit();
            this.txtInstance = new TextEdit();
            this.txtDatabase = new TextEdit();
            this.btnOK = new SimpleButton();
            this.btnCancel = new SimpleButton();
            this.rdoAuthentic = new RadioGroup();
            this.groupBox1 = new GroupBox();
            this.txtUser = new TextEdit();
            this.label4 = new Label();
            this.chkSaveUserandPsw = new CheckEdit();
            this.label5 = new Label();
            this.txtPassword = new TextEdit();
            this.btnTestConnection = new SimpleButton();
            this.groupBox2.SuspendLayout();
            this.chkSaveVersion.Properties.BeginInit();
            this.txtServer.Properties.BeginInit();
            this.txtInstance.Properties.BeginInit();
            this.txtDatabase.Properties.BeginInit();
            this.rdoAuthentic.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.txtUser.Properties.BeginInit();
            this.chkSaveUserandPsw.Properties.BeginInit();
            this.txtPassword.Properties.BeginInit();
            base.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(16, 12);
            this.label1.Name = "label1";
            this.label1.Size = new Size(47, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "服务器:";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(16, 41);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 12);
            this.label2.TabIndex = 2;
            this.label2.Text = "服务:";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(16, 75);
            this.label3.Name = "label3";
            this.label3.Size = new Size(47, 12);
            this.label3.TabIndex = 3;
            this.label3.Text = "数据库:";
            this.groupBox2.Controls.Add(this.btnChangeVersion);
            this.groupBox2.Controls.Add(this.chkSaveVersion);
            this.groupBox2.Controls.Add(this.lblVersion);
            this.groupBox2.Location = new Point(13, 273);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(272, 80);
            this.groupBox2.TabIndex = 5;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "版本";
            this.btnChangeVersion.Location = new Point(168, 48);
            this.btnChangeVersion.Name = "btnChangeVersion";
            this.btnChangeVersion.Size = new Size(56, 24);
            this.btnChangeVersion.TabIndex = 2;
            this.btnChangeVersion.Text = "更改...";
            this.btnChangeVersion.Click += new EventHandler(this.btnChangeVersion_Click);
            this.chkSaveVersion.Location = new Point(16, 16);
            this.chkSaveVersion.Name = "chkSaveVersion";
            this.chkSaveVersion.Properties.Caption = "保存版本";
            this.chkSaveVersion.Size = new Size(88, 19);
            this.chkSaveVersion.TabIndex = 1;
            this.lblVersion.Location = new Point(16, 48);
            this.lblVersion.Name = "lblVersion";
            this.lblVersion.Size = new Size(128, 16);
            this.lblVersion.TabIndex = 1;
            this.lblVersion.Text = "DEFAULT";
            this.txtServer.EditValue = "";
            this.txtServer.Location = new Point(64, 8);
            this.txtServer.Name = "txtServer";
            this.txtServer.Size = new Size(208, 21);
            this.txtServer.TabIndex = 1;
            this.txtServer.EditValueChanged += new EventHandler(this.txtServer_EditValueChanged);
            this.txtInstance.EditValue = "5151";
            this.txtInstance.Location = new Point(64, 38);
            this.txtInstance.Name = "txtInstance";
            this.txtInstance.Size = new Size(208, 21);
            this.txtInstance.TabIndex = 2;
            this.txtInstance.EditValueChanged += new EventHandler(this.txtInstance_EditValueChanged);
            this.txtDatabase.EditValue = "";
            this.txtDatabase.Location = new Point(64, 72);
            this.txtDatabase.Name = "txtDatabase";
            this.txtDatabase.Size = new Size(208, 21);
            this.txtDatabase.TabIndex = 3;
            this.btnOK.Location = new Point(144, 366);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(64, 24);
            this.btnOK.TabIndex = 6;
            this.btnOK.Text = "确定";
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(224, 366);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(64, 24);
            this.btnCancel.TabIndex = 7;
            this.btnCancel.Text = "取消";
            this.btnCancel.Click += new EventHandler(this.btnCancel_Click);
            this.rdoAuthentic.Location = new Point(3, -35);
            this.rdoAuthentic.Name = "rdoAuthentic";
            this.rdoAuthentic.Properties.Appearance.BackColor = Color.Transparent;
            this.rdoAuthentic.Properties.Appearance.Options.UseBackColor = true;
            this.rdoAuthentic.Properties.BorderStyle = BorderStyles.NoBorder;
            this.rdoAuthentic.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "数据库验证"), new RadioGroupItem(null, "操作系统验证") });
            this.rdoAuthentic.Size = new Size(100, 239);
            this.rdoAuthentic.TabIndex = 1;
            this.rdoAuthentic.SelectedIndexChanged += new EventHandler(this.rdoAuthentic_SelectedIndexChanged);
            this.groupBox1.Controls.Add(this.txtUser);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.chkSaveUserandPsw);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.txtPassword);
            this.groupBox1.Controls.Add(this.rdoAuthentic);
            this.groupBox1.Location = new Point(12, 108);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(272, 160);
            this.groupBox1.TabIndex = 11;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "帐号";
            this.groupBox1.Enter += new EventHandler(this.groupBox1_Enter);
            this.txtUser.EditValue = "";
            this.txtUser.Location = new Point(64, 45);
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new Size(192, 21);
            this.txtUser.TabIndex = 12;
            this.txtUser.EditValueChanged += new EventHandler(this.txtUser_EditValueChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new Point(16, 49);
            this.label4.Name = "label4";
            this.label4.Size = new Size(47, 12);
            this.label4.TabIndex = 11;
            this.label4.Text = "用户名:";
            this.chkSaveUserandPsw.Location = new Point(64, 109);
            this.chkSaveUserandPsw.Name = "chkSaveUserandPsw";
            this.chkSaveUserandPsw.Properties.Caption = "保存名称和密码";
            this.chkSaveUserandPsw.Size = new Size(120, 19);
            this.chkSaveUserandPsw.TabIndex = 15;
            this.chkSaveUserandPsw.CheckedChanged += new EventHandler(this.chkSaveUserandPsw_CheckedChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new Point(16, 79);
            this.label5.Name = "label5";
            this.label5.Size = new Size(35, 12);
            this.label5.TabIndex = 13;
            this.label5.Text = "密码:";
            this.txtPassword.EditValue = "";
            this.txtPassword.Location = new Point(64, 77);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Properties.PasswordChar = '*';
            this.txtPassword.Size = new Size(192, 21);
            this.txtPassword.TabIndex = 14;
            this.txtPassword.EditValueChanged += new EventHandler(this.txtPassword_EditValueChanged);
            this.btnTestConnection.Enabled = false;
            this.btnTestConnection.Location = new Point(13, 364);
            this.btnTestConnection.Name = "btnTestConnection";
            this.btnTestConnection.Size = new Size(64, 24);
            this.btnTestConnection.TabIndex = 16;
            this.btnTestConnection.Text = "测试连接";
            this.btnTestConnection.Click += new EventHandler(this.btnTestConnection_Click);
            this.AutoScaleBaseSize = new Size(6, 14);
            base.ClientSize = new Size(310, 416);
            base.Controls.Add(this.btnTestConnection);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.txtDatabase);
            base.Controls.Add(this.txtInstance);
            base.Controls.Add(this.txtServer);
            base.Controls.Add(this.groupBox2);
            base.Controls.Add(this.label3);
            base.Controls.Add(this.label2);
            base.Controls.Add(this.label1);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "frmAddGDBConnection";
            base.ShowInTaskbar = false;
            this.Text = "空间数据库连接";
            this.groupBox2.ResumeLayout(false);
            this.chkSaveVersion.Properties.EndInit();
            this.txtServer.Properties.EndInit();
            this.txtInstance.Properties.EndInit();
            this.txtDatabase.Properties.EndInit();
            this.rdoAuthentic.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.txtUser.Properties.EndInit();
            this.chkSaveUserandPsw.Properties.EndInit();
            this.txtPassword.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private SimpleButton btnCancel;
        private SimpleButton btnChangeVersion;
        private SimpleButton btnOK;
        private SimpleButton btnTestConnection;
        private CheckEdit chkSaveUserandPsw;
        private CheckEdit chkSaveVersion;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label lblVersion;
        private RadioGroup rdoAuthentic;
        private string string_0;
        private TextEdit txtDatabase;
        private TextEdit txtInstance;
        private TextEdit txtPassword;
        private TextEdit txtServer;
        private TextEdit txtUser;
    }
}