using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ESRI.ArcGIS.Geometry;

namespace Yutai.ArcGIS.Catalog.Geodatabase.UI
{
    partial class NewDatasetCoordinateDomainPage
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
 private void InitializeComponent()
        {
            this.groupXY = new GroupBox();
            this.lblXYResolution = new Label();
            this.textBoxMaxY = new TextEdit();
            this.textBoxMinY = new TextEdit();
            this.txtXYPrecision = new TextEdit();
            this.textBoxMaxX = new TextEdit();
            this.textBoxMinX = new TextEdit();
            this.label5 = new Label();
            this.label4 = new Label();
            this.label3 = new Label();
            this.label2 = new Label();
            this.label1 = new Label();
            this.groupZ = new GroupBox();
            this.lblZResolution = new Label();
            this.txtZPrecision = new TextEdit();
            this.txtZMaxValue = new TextEdit();
            this.txtZMinValue = new TextEdit();
            this.label6 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.groupM = new GroupBox();
            this.lblMResolution = new Label();
            this.txtMPrecision = new TextEdit();
            this.txtMMaxValue = new TextEdit();
            this.txtMMinValue = new TextEdit();
            this.label9 = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.groupXY.SuspendLayout();
            this.textBoxMaxY.Properties.BeginInit();
            this.textBoxMinY.Properties.BeginInit();
            this.txtXYPrecision.Properties.BeginInit();
            this.textBoxMaxX.Properties.BeginInit();
            this.textBoxMinX.Properties.BeginInit();
            this.groupZ.SuspendLayout();
            this.txtZPrecision.Properties.BeginInit();
            this.txtZMaxValue.Properties.BeginInit();
            this.txtZMinValue.Properties.BeginInit();
            this.groupM.SuspendLayout();
            this.txtMPrecision.Properties.BeginInit();
            this.txtMMaxValue.Properties.BeginInit();
            this.txtMMinValue.Properties.BeginInit();
            base.SuspendLayout();
            this.groupXY.Controls.Add(this.lblXYResolution);
            this.groupXY.Controls.Add(this.textBoxMaxY);
            this.groupXY.Controls.Add(this.textBoxMinY);
            this.groupXY.Controls.Add(this.txtXYPrecision);
            this.groupXY.Controls.Add(this.textBoxMaxX);
            this.groupXY.Controls.Add(this.textBoxMinX);
            this.groupXY.Controls.Add(this.label5);
            this.groupXY.Controls.Add(this.label4);
            this.groupXY.Controls.Add(this.label3);
            this.groupXY.Controls.Add(this.label2);
            this.groupXY.Controls.Add(this.label1);
            this.groupXY.Location = new System.Drawing.Point(13, 9);
            this.groupXY.Name = "groupXY";
            this.groupXY.Size = new Size(390, 140);
            this.groupXY.TabIndex = 0;
            this.groupXY.TabStop = false;
            this.groupXY.Text = "XY";
            this.lblXYResolution.AutoSize = true;
            this.lblXYResolution.Location = new System.Drawing.Point(164, 19);
            this.lblXYResolution.Name = "lblXYResolution";
            this.lblXYResolution.Size = new Size(0, 12);
            this.lblXYResolution.TabIndex = 39;
            this.textBoxMaxY.EditValue = "450359962737.0495";
            this.textBoxMaxY.Location = new System.Drawing.Point(133, 44);
            this.textBoxMaxY.Name = "textBoxMaxY";
            this.textBoxMaxY.Size = new Size(131, 21);
            this.textBoxMaxY.TabIndex = 38;
            this.textBoxMaxY.Leave += new EventHandler(this.textBoxMaxY_Leave);
            this.textBoxMaxY.EditValueChanged += new EventHandler(this.textBoxMaxY_EditValueChanged);
            this.textBoxMinY.EditValue = "-450359962737.0495";
            this.textBoxMinY.Location = new System.Drawing.Point(133, 110);
            this.textBoxMinY.Name = "textBoxMinY";
            this.textBoxMinY.Size = new Size(131, 21);
            this.textBoxMinY.TabIndex = 37;
            this.textBoxMinY.EditValueChanged += new EventHandler(this.textBoxMinY_EditValueChanged);
            this.txtXYPrecision.EditValue = "0.0001";
            this.txtXYPrecision.Location = new System.Drawing.Point(63, 14);
            this.txtXYPrecision.Name = "txtXYPrecision";
            this.txtXYPrecision.Size = new Size(93, 21);
            this.txtXYPrecision.TabIndex = 36;
            this.txtXYPrecision.EditValueChanged += new EventHandler(this.txtXYPrecision_EditValueChanged);
            this.textBoxMaxX.EditValue = "450359962737.0495";
            this.textBoxMaxX.Location = new System.Drawing.Point(249, 75);
            this.textBoxMaxX.Name = "textBoxMaxX";
            this.textBoxMaxX.Size = new Size(131, 21);
            this.textBoxMaxX.TabIndex = 35;
            this.textBoxMaxX.Leave += new EventHandler(this.textBoxMaxX_Leave);
            this.textBoxMaxX.EditValueChanged += new EventHandler(this.textBoxMaxX_EditValueChanged);
            this.textBoxMinX.EditValue = "-450359962737.0495";
            this.textBoxMinX.Location = new System.Drawing.Point(58, 71);
            this.textBoxMinX.Name = "textBoxMinX";
            this.textBoxMinX.Size = new Size(131, 21);
            this.textBoxMinX.TabIndex = 34;
            this.textBoxMinX.EditValueChanged += new EventHandler(this.textBoxMinX_EditValueChanged);
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(14, 19);
            this.label5.Name = "label5";
            this.label5.Size = new Size(29, 12);
            this.label5.TabIndex = 33;
            this.label5.Text = "精度";
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(79, 49);
            this.label4.Name = "label4";
            this.label4.Size = new Size(35, 12);
            this.label4.TabIndex = 32;
            this.label4.Text = "最大Y";
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(205, 80);
            this.label3.Name = "label3";
            this.label3.Size = new Size(35, 12);
            this.label3.TabIndex = 31;
            this.label3.Text = "最大X";
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(79, 115);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 12);
            this.label2.TabIndex = 30;
            this.label2.Text = "最小Y";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(14, 76);
            this.label1.Name = "label1";
            this.label1.Size = new Size(35, 12);
            this.label1.TabIndex = 29;
            this.label1.Text = "最小X";
            this.groupZ.Controls.Add(this.lblZResolution);
            this.groupZ.Controls.Add(this.txtZPrecision);
            this.groupZ.Controls.Add(this.txtZMaxValue);
            this.groupZ.Controls.Add(this.txtZMinValue);
            this.groupZ.Controls.Add(this.label6);
            this.groupZ.Controls.Add(this.label7);
            this.groupZ.Controls.Add(this.label8);
            this.groupZ.Location = new System.Drawing.Point(13, 159);
            this.groupZ.Name = "groupZ";
            this.groupZ.Size = new Size(390, 82);
            this.groupZ.TabIndex = 1;
            this.groupZ.TabStop = false;
            this.groupZ.Text = "Z";
            this.lblZResolution.AutoSize = true;
            this.lblZResolution.Location = new System.Drawing.Point(158, 28);
            this.lblZResolution.Name = "lblZResolution";
            this.lblZResolution.Size = new Size(0, 12);
            this.lblZResolution.TabIndex = 40;
            this.txtZPrecision.EditValue = "0.0001";
            this.txtZPrecision.Location = new System.Drawing.Point(62, 22);
            this.txtZPrecision.Name = "txtZPrecision";
            this.txtZPrecision.Size = new Size(88, 21);
            this.txtZPrecision.TabIndex = 32;
            this.txtZPrecision.EditValueChanged += new EventHandler(this.txtZPrecision_EditValueChanged);
            this.txtZMaxValue.EditValue = "900719825474.099";
            this.txtZMaxValue.Location = new System.Drawing.Point(249, 54);
            this.txtZMaxValue.Name = "txtZMaxValue";
            this.txtZMaxValue.Properties.ReadOnly = true;
            this.txtZMaxValue.Size = new Size(131, 21);
            this.txtZMaxValue.TabIndex = 31;
            this.txtZMinValue.EditValue = "-100000";
            this.txtZMinValue.Location = new System.Drawing.Point(62, 54);
            this.txtZMinValue.Name = "txtZMinValue";
            this.txtZMinValue.Size = new Size(131, 21);
            this.txtZMinValue.TabIndex = 30;
            this.txtZMinValue.EditValueChanged += new EventHandler(this.txtZMinValue_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(14, 26);
            this.label6.Name = "label6";
            this.label6.Size = new Size(29, 12);
            this.label6.TabIndex = 29;
            this.label6.Text = "精度";
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(205, 58);
            this.label7.Name = "label7";
            this.label7.Size = new Size(41, 12);
            this.label7.TabIndex = 28;
            this.label7.Text = "最大值";
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(14, 58);
            this.label8.Name = "label8";
            this.label8.Size = new Size(41, 12);
            this.label8.TabIndex = 27;
            this.label8.Text = "最小值";
            this.groupM.Controls.Add(this.lblMResolution);
            this.groupM.Controls.Add(this.txtMPrecision);
            this.groupM.Controls.Add(this.txtMMaxValue);
            this.groupM.Controls.Add(this.txtMMinValue);
            this.groupM.Controls.Add(this.label9);
            this.groupM.Controls.Add(this.label10);
            this.groupM.Controls.Add(this.label11);
            this.groupM.Location = new System.Drawing.Point(13, 260);
            this.groupM.Name = "groupM";
            this.groupM.Size = new Size(390, 86);
            this.groupM.TabIndex = 2;
            this.groupM.TabStop = false;
            this.groupM.Text = "M";
            this.lblMResolution.AutoSize = true;
            this.lblMResolution.Location = new System.Drawing.Point(163, 17);
            this.lblMResolution.Name = "lblMResolution";
            this.lblMResolution.Size = new Size(0, 12);
            this.lblMResolution.TabIndex = 40;
            this.txtMPrecision.EditValue = "0.0001";
            this.txtMPrecision.Location = new System.Drawing.Point(68, 12);
            this.txtMPrecision.Name = "txtMPrecision";
            this.txtMPrecision.Size = new Size(88, 21);
            this.txtMPrecision.TabIndex = 29;
            this.txtMPrecision.EditValueChanged += new EventHandler(this.txtMPrecision_EditValueChanged);
            this.txtMMaxValue.EditValue = "900719825474.099";
            this.txtMMaxValue.Location = new System.Drawing.Point(249, 46);
            this.txtMMaxValue.Name = "txtMMaxValue";
            this.txtMMaxValue.Size = new Size(131, 21);
            this.txtMMaxValue.TabIndex = 28;
            this.txtMMinValue.EditValue = "-100000";
            this.txtMMinValue.Location = new System.Drawing.Point(68, 46);
            this.txtMMinValue.Name = "txtMMinValue";
            this.txtMMinValue.Size = new Size(131, 21);
            this.txtMMinValue.TabIndex = 27;
            this.txtMMinValue.EditValueChanged += new EventHandler(this.txtMMinValue_EditValueChanged);
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(20, 17);
            this.label9.Name = "label9";
            this.label9.Size = new Size(29, 12);
            this.label9.TabIndex = 26;
            this.label9.Text = "精度";
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(205, 46);
            this.label10.Name = "label10";
            this.label10.Size = new Size(41, 12);
            this.label10.TabIndex = 25;
            this.label10.Text = "最大值";
            this.label11.AutoSize = true;
            this.label11.Location = new System.Drawing.Point(20, 46);
            this.label11.Name = "label11";
            this.label11.Size = new Size(41, 12);
            this.label11.TabIndex = 24;
            this.label11.Text = "最小值";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.Controls.Add(this.groupM);
            base.Controls.Add(this.groupZ);
            base.Controls.Add(this.groupXY);
            base.Name = "NewDatasetCoordinateDomainPage";
            base.Size = new Size(417, 383);
            base.VisibleChanged += new EventHandler(this.NewDatasetCoordinateDomainPage_VisibleChanged);
            base.Load += new EventHandler(this.NewDatasetCoordinateDomainPage_Load);
            this.groupXY.ResumeLayout(false);
            this.groupXY.PerformLayout();
            this.textBoxMaxY.Properties.EndInit();
            this.textBoxMinY.Properties.EndInit();
            this.txtXYPrecision.Properties.EndInit();
            this.textBoxMaxX.Properties.EndInit();
            this.textBoxMinX.Properties.EndInit();
            this.groupZ.ResumeLayout(false);
            this.groupZ.PerformLayout();
            this.txtZPrecision.Properties.EndInit();
            this.txtZMaxValue.Properties.EndInit();
            this.txtZMinValue.Properties.EndInit();
            this.groupM.ResumeLayout(false);
            this.groupM.PerformLayout();
            this.txtMPrecision.Properties.EndInit();
            this.txtMMaxValue.Properties.EndInit();
            this.txtMMinValue.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private GroupBox groupM;
        private GroupBox groupXY;
        private GroupBox groupZ;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label lblMResolution;
        private Label lblXYResolution;
        private Label lblZResolution;
        private TextEdit textBoxMaxX;
        private TextEdit textBoxMaxY;
        private TextEdit textBoxMinX;
        private TextEdit textBoxMinY;
        private TextEdit txtMMaxValue;
        private TextEdit txtMMinValue;
        private TextEdit txtMPrecision;
        private TextEdit txtXYPrecision;
        private TextEdit txtZMaxValue;
        private TextEdit txtZMinValue;
        private TextEdit txtZPrecision;
    }
}