using System;
using System.ComponentModel;
using System.Drawing;
using System.Reflection;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using ESRI.ArcGIS.Geometry;
using Yutai.ArcGIS.Common.ControlExtend;
using Yutai.ArcGIS.Common.Helpers;

namespace Yutai.ArcGIS.Catalog.Geodatabase.UI
{
    partial class ProjCoordSys
    {
        protected override void Dispose(bool bool_1)
        {
            if (bool_1 && (this.container_0 != null))
            {
                this.container_0.Dispose();
            }
            base.Dispose(bool_1);
        }

       
        private void InitializeComponent()
        {
            this.groupBox4 = new GroupBox();
            this.cboLineUnitName = new ComboBoxEdit();
            this.txtValue = new TextEdit();
            this.label6 = new Label();
            this.label5 = new Label();
            this.groupBox1 = new GroupBox();
            this.cboProjectName = new ComboBoxEdit();
            this.paramlistView = new EditListView();
            this.lvcolumnHeader_0 = new LVColumnHeader();
            this.lvcolumnHeader_1 = new LVColumnHeader();
            this.label2 = new Label();
            this.label1 = new Label();
            this.textEditName = new TextEdit();
            this.groupBox3 = new GroupBox();
            this.btnModify = new SimpleButton();
            this.btnNew = new SimpleButton();
            this.btnSelect = new SimpleButton();
            this.textBoxGeoCoodSys = new MemoEdit();
            this.groupBox4.SuspendLayout();
            this.cboLineUnitName.Properties.BeginInit();
            this.txtValue.Properties.BeginInit();
            this.groupBox1.SuspendLayout();
            this.cboProjectName.Properties.BeginInit();
            this.textEditName.Properties.BeginInit();
            this.groupBox3.SuspendLayout();
            this.textBoxGeoCoodSys.Properties.BeginInit();
            base.SuspendLayout();
            this.groupBox4.Controls.Add(this.cboLineUnitName);
            this.groupBox4.Controls.Add(this.txtValue);
            this.groupBox4.Controls.Add(this.label6);
            this.groupBox4.Controls.Add(this.label5);
            this.groupBox4.Location = new System.Drawing.Point(8, 208);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(296, 88);
            this.groupBox4.TabIndex = 7;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "线性单位";
            this.cboLineUnitName.EditValue = "";
            this.cboLineUnitName.Location = new System.Drawing.Point(80, 24);
            this.cboLineUnitName.Name = "cboLineUnitName";
            this.cboLineUnitName.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboLineUnitName.Size = new Size(192, 21);
            this.cboLineUnitName.TabIndex = 10;
            this.cboLineUnitName.SelectedIndexChanged += new EventHandler(this.cboLineUnitName_SelectedIndexChanged);
            this.txtValue.EditValue = "1";
            this.txtValue.Location = new System.Drawing.Point(80, 56);
            this.txtValue.Name = "txtValue";
            this.txtValue.Size = new Size(192, 21);
            this.txtValue.TabIndex = 9;
            this.txtValue.EditValueChanged += new EventHandler(this.txtValue_EditValueChanged);
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(16, 56);
            this.label6.Name = "label6";
            this.label6.Size = new Size(60, 17);
            this.label6.TabIndex = 4;
            this.label6.Text = "单位(米):";
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(16, 26);
            this.label5.Name = "label5";
            this.label5.Size = new Size(35, 17);
            this.label5.TabIndex = 2;
            this.label5.Text = "名称:";
            this.groupBox1.Controls.Add(this.cboProjectName);
            this.groupBox1.Controls.Add(this.paramlistView);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Location = new System.Drawing.Point(8, 40);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(296, 160);
            this.groupBox1.TabIndex = 6;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "投影";
            this.cboProjectName.EditValue = "";
            this.cboProjectName.Location = new System.Drawing.Point(64, 24);
            this.cboProjectName.Name = "cboProjectName";
            this.cboProjectName.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboProjectName.Size = new Size(200, 21);
            this.cboProjectName.TabIndex = 3;
            this.cboProjectName.SelectedIndexChanged += new EventHandler(this.cboProjectName_SelectedIndexChanged);
            this.paramlistView.Columns.AddRange(new ColumnHeader[] { this.lvcolumnHeader_0, this.lvcolumnHeader_1 });
            this.paramlistView.ComboBoxBgColor = Color.LightBlue;
            this.paramlistView.ComboBoxFont = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.paramlistView.EditBgColor = Color.LightBlue;
            this.paramlistView.EditFont = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            this.paramlistView.FullRowSelect = true;
            this.paramlistView.GridLines = true;
            this.paramlistView.Location = new System.Drawing.Point(16, 56);
            this.paramlistView.Name = "paramlistView";
            this.paramlistView.Size = new Size(272, 96);
            this.paramlistView.TabIndex = 2;
            this.paramlistView.View = View.Details;
            this.paramlistView.ValueChanged += new Common.ControlExtend.ValueChangedHandler(this.method_5);
            this.lvcolumnHeader_0.ColumnStyle = ListViewColumnStyle.ReadOnly;
            this.lvcolumnHeader_0.Text = "参数";
            this.lvcolumnHeader_0.Width = 144;
            this.lvcolumnHeader_1.ColumnStyle = ListViewColumnStyle.EditBox;
            this.lvcolumnHeader_1.Text = "值";
            this.lvcolumnHeader_1.Width = 122;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(16, 27);
            this.label2.Name = "label2";
            this.label2.Size = new Size(35, 17);
            this.label2.TabIndex = 0;
            this.label2.Text = "名称:";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(8, 11);
            this.label1.Name = "label1";
            this.label1.Size = new Size(35, 17);
            this.label1.TabIndex = 5;
            this.label1.Text = "名称:";
            this.textEditName.EditValue = "";
            this.textEditName.Location = new System.Drawing.Point(48, 8);
            this.textEditName.Name = "textEditName";
            this.textEditName.Size = new Size(240, 21);
            this.textEditName.TabIndex = 4;
            this.groupBox3.Controls.Add(this.btnModify);
            this.groupBox3.Controls.Add(this.btnNew);
            this.groupBox3.Controls.Add(this.btnSelect);
            this.groupBox3.Controls.Add(this.textBoxGeoCoodSys);
            this.groupBox3.Location = new System.Drawing.Point(8, 304);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(296, 128);
            this.groupBox3.TabIndex = 8;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "地理坐标系";
            this.btnModify.Location = new System.Drawing.Point(232, 96);
            this.btnModify.Name = "btnModify";
            this.btnModify.Size = new Size(48, 24);
            this.btnModify.TabIndex = 14;
            this.btnModify.Text = "修改";
            this.btnModify.Click += new EventHandler(this.btnModify_Click);
            this.btnNew.Location = new System.Drawing.Point(232, 64);
            this.btnNew.Name = "btnNew";
            this.btnNew.Size = new Size(48, 24);
            this.btnNew.TabIndex = 13;
            this.btnNew.Text = "新建";
            this.btnNew.Click += new EventHandler(this.btnNew_Click);
            this.btnSelect.Location = new System.Drawing.Point(232, 32);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new Size(48, 24);
            this.btnSelect.TabIndex = 12;
            this.btnSelect.Text = "选择";
            this.btnSelect.Click += new EventHandler(this.btnSelect_Click);
            this.textBoxGeoCoodSys.EditValue = "";
            this.textBoxGeoCoodSys.Location = new System.Drawing.Point(16, 24);
            this.textBoxGeoCoodSys.Name = "textBoxGeoCoodSys";
            this.textBoxGeoCoodSys.Properties.ReadOnly = true;
            this.textBoxGeoCoodSys.Size = new Size(200, 96);
            this.textBoxGeoCoodSys.TabIndex = 4;
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.textEditName);
            base.Controls.Add(this.groupBox3);
            base.Name = "ProjCoordSys";
            base.Size = new Size(320, 480);
            base.Load += new EventHandler(this.ProjCoordSys_Load);
            this.groupBox4.ResumeLayout(false);
            this.cboLineUnitName.Properties.EndInit();
            this.txtValue.Properties.EndInit();
            this.groupBox1.ResumeLayout(false);
            this.cboProjectName.Properties.EndInit();
            this.textEditName.Properties.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.textBoxGeoCoodSys.Properties.EndInit();
            base.ResumeLayout(false);
        }

       
        private SimpleButton btnModify;
        private SimpleButton btnNew;
        private SimpleButton btnSelect;
        private ComboBoxEdit cboLineUnitName;
        private ComboBoxEdit cboProjectName;
        private GroupBox groupBox1;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private IGeographicCoordinateSystem igeographicCoordinateSystem_0;
        private IProjectedCoordinateSystem iprojectedCoordinateSystem_0;
        private IProjection iprojection_0;
        private IUnit iunit_0;
        private Label label1;
        private Label label2;
        private Label label5;
        private Label label6;
        private LVColumnHeader lvcolumnHeader_0;
        private LVColumnHeader lvcolumnHeader_1;
        private EditListView paramlistView;
        private MemoEdit textBoxGeoCoodSys;
        private TextEdit textEditName;
        private TextEdit txtValue;
    }
}